import { useLayoutEffect, useRef, type RefObject } from 'react';
interface Modal { element: HTMLElement; dismiss:()=>void; opener: Element|null }
const stack:Modal[]=[];
let outsideFocus:Element|null=null,bodyOverflow='';
export function rememberDialogOpener(target:Element){if(!stack.length){const control=target.closest('button,summary,input,select,textarea');if(control)outsideFocus=control;}}
export const activeEditorDialog=()=>stack.at(-1)?.element;
function focusables(element:HTMLElement){return [...element.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled):not([type=hidden]),select:not(:disabled),textarea:not(:disabled),summary,[tabindex]:not([tabindex="-1"]),a[href]')].filter(e=>e.getClientRects().length&&!e.closest('[inert]'));}
export function dialogFocus(event:FocusEvent){const top=stack.at(-1);if(!top){if(event.target instanceof Element&&event.target!==document.body&&!event.target.closest('.editor-dialog'))outsideFocus=event.target;return;}if(event.target instanceof Element&&!top.element.contains(event.target)&&!(top.element.id&&event.target.closest(`[data-popup-owner="${CSS.escape(top.element.id)}"]`)))(focusables(top.element)[0]??top.element).focus({preventScroll:true});}
export function dialogKey(event:KeyboardEvent){const top=stack.at(-1);if(!top)return false;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();top.dismiss();return true;}if((event.ctrlKey||event.metaKey)&&['s','o','n','z','y'].includes(event.key.toLowerCase())&&!(event.target instanceof Element&&event.target.closest('input,textarea,[contenteditable]')))event.preventDefault();if(event.key==='Tab'){const list=focusables(top.element),first=list[0],last=list.at(-1),current=document.activeElement;if(!first){event.preventDefault();top.element.focus({preventScroll:true});}else if(event.shiftKey&&(current===first||!top.element.contains(current))){event.preventDefault();last?.focus({preventScroll:true});}else if(!event.shiftKey&&(current===last||!top.element.contains(current))){event.preventDefault();first.focus({preventScroll:true});}}return false;}
export function dialogPointer(event:PointerEvent){const top=stack.at(-1);if(!top)return;const target=event.target;if(target instanceof Element&&target.hasAttribute('data-dialog-backdrop')&&target.contains(top.element)){event.preventDefault();top.dismiss();}}
/** Registration only; all keyboard/pointer/focus events use useEditorFocus's single boundary. */
export function useEditorDialog(ref:RefObject<HTMLElement|null>,dismiss:()=>void,initialFocus?:string,focusAfterClose?:()=>HTMLElement|SVGElement|null){const restore=useRef(focusAfterClose);restore.current=focusAfterClose;const latest=useRef(dismiss);latest.current=dismiss;useLayoutEffect(()=>{const element=ref.current;if(!element)return;const opener=document.activeElement===document.body||element.contains(document.activeElement)?outsideFocus:document.activeElement;const modal:Modal={element,dismiss:()=>latest.current(),opener};if(!stack.length){bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';}stack.push(modal);(initialFocus?element.querySelector<HTMLElement>(initialFocus):element.querySelector<HTMLElement>('[data-initial-focus],input:not([type=checkbox]):not([type=file]),textarea,select'))?.focus({preventScroll:true});if(!element.contains(document.activeElement))(focusables(element)[0]??element).focus({preventScroll:true});return()=>{const i=stack.indexOf(modal);if(i>=0)stack.splice(i,1);if(!stack.length)document.body.style.overflow=bodyOverflow;requestAnimationFrame(()=>{const next=stack.at(-1);if(next){if(!next.element.contains(document.activeElement)){const parentOpener=opener instanceof HTMLElement&&next.element.contains(opener)&&opener.getClientRects().length?opener:null;(parentOpener??focusables(next.element)[0]??next.element).focus({preventScroll:true});}return;}const override=restore.current?.();const usable=override??((opener instanceof HTMLElement||opener instanceof SVGElement)?opener.getClientRects().length&&!opener.closest('[inert]')?opener:opener.closest('details')?.querySelector<HTMLElement>('summary'):null);const visibleOpener=usable?.closest('details:not([open])')?.querySelector<HTMLElement>('summary')??usable;if(visibleOpener?.isConnected&&!visibleOpener.closest('[inert]'))visibleOpener.focus({preventScroll:true});if(document.activeElement!==visibleOpener)document.querySelector<SVGElement>('.active-viewport-editor .drawing-canvas,[data-testid=layout-canvas],[data-testid=drawing-canvas]')?.focus({preventScroll:true});});};},[ref,initialFocus]);}
