import { createSnapProvider } from '../snapping';
import { operationsFixture } from './fixtures/documentOperations';
import { describe, expect, it } from 'vitest';
import { applyCommand, applyCommandsAtomically } from '../domain/commands';
import { editorReducer, editorViewDocument, initialEditorState, isDocumentDirty } from '../store/editor';
import { renderItems } from '../renderer/selectors';
import { applicationReducer, type ApplicationState } from '../ai/workflow';
import { validateParserResult, aiTaskSchema } from '../ai/intent';
import { developmentMockProvider, OpenRouterIntentProvider } from '../../server/ai';
import { documentQueryIndex, resolveDocumentQuery, searchDocument, defaultExcludedGroups } from '../documentOperations/query';
import { applyDocumentPlan, isDocumentPlanStale, resolveDocumentPlan } from '../documentOperations/plan';
import { DOCUMENT_QUERY_LIMITS, type DocumentAction, type DocumentQuery } from '../documentOperations/schema';
import { normalizeQuery, semanticTokens } from '../documentOperations/aliases';
const size={width:1000,height:700};

const q=(query:DocumentQuery,d=operationsFixture(),selection:readonly string[]=[])=>resolveDocumentQuery(query,d,selection);
const semantic=(concepts:Extract<DocumentQuery,{kind:'semantic_concept'}>['concepts']):DocumentQuery=>({kind:'semantic_concept',concepts});
const compound:DocumentAction[]=[{type:'create_layer',name:'Архив'},{type:'move_entities_to_layer',query:{kind:'source_layer',name:'_ГП_ЗИС'},target:{kind:'created_layer',actionIndex:0}}];
function plan(actions:DocumentAction[]=compound,d=operationsFixture(),selection:string[]=[]) {return resolveDocumentPlan(actions,d,selection,'test','request');}
function preview(actions:DocumentAction[],d=operationsFixture()):ApplicationState {const state:ApplicationState={editor:initialEditorState(d),ai:{status:'idle'}};return applicationReducer(applicationReducer(state,{type:'ai-event',event:{type:'start',id:'r',text:'Запрос'}}),{type:'ai-event',event:{type:'result',id:'r',result:{actions}}});}

describe('local document queries',()=>{
  it('keeps source and current layers distinct, indexed, normalized exact queries',()=>{const d=operationsFixture();expect(documentQueryIndex(d)).toBe(documentQueryIndex(d));expect(q({kind:'source_layer',name:' _гп_зис '},d).entityIds).toEqual(['building']);expect(q({kind:'geoservice_layer',name:'ГП_здания и сооружения'},d).entityIds).toEqual(['building']);expect(q({kind:'source_layer',name:'ЗИС'},d).entityIds).toEqual([]);});
  it('indexes block names, names, source types including ATTRIB, and native types',()=>{const d=operationsFixture();expect(q({kind:'block_name',name:'volume'},d).entityIds).toHaveLength(2);expect(q({kind:'entity_name',name:'контур'},d).entityIds).toEqual(['building']);expect(q({kind:'source_type',sourceType:'MULTILEADER'},d).entityIds).toEqual(['mleader']);expect(q({kind:'source_type',sourceType:'ATTRIB'},d).entityIds).toContain(d.entities[0]!.id);expect(q({kind:'entity_type',entityType:'dimension'},d).entityIds).toEqual(['dimension']);});
  it('searches MLeader primary text, supplies nested evidence and selects owner IDs',()=>{const r=q({kind:'text_contains',text:'грунт',sourceType:'MULTILEADER'});expect(r.entityIds).toEqual(['mleader']);expect(r.evidence.get('mleader')?.[0]).toMatchObject({text:'Плодородный грунт, h=0.20 м'});});
  it('ATTRIB current edited text replaces stale value without changing template or sibling',()=>{const d=operationsFixture(),owner=d.entities[0]!;if(owner.type!=='block_instance')throw Error();const edited=applyCommand(d,{type:'update-block-attribute',entityId:owner.id,attributeIndex:0,tag:'NAME',patch:{value:'27.95'}});expect(q({kind:'block_attribute',tag:'name',value:'27.95'},edited).entityIds).toEqual([owner.id]);expect(q({kind:'text_contains',text:'27.89',sourceType:null},edited).entityIds).not.toContain(owner.id);expect(q({kind:'text_contains',text:'27.95',sourceType:null},edited).entityIds).toContain(owner.id);expect(edited.blocks).toBe(d.blocks);expect(edited.entities[1]).toBe(d.entities[1]);expect(searchDocument(edited,'27.95').rows[0]?.entityId).toBe(owner.id);});
  it('supports exact ATTRIB tag and rejects empty ATTRIB predicates',()=>{expect(q({kind:'block_attribute',tag:'NAME',value:null}).entityIds.length).toBeGreaterThan(0);expect(q({kind:'block_attribute',tag:null,value:null}).error).toBeTruthy();});
  it.each(['roads','slopes','annotations','dimensions','text','blocks','hatches','symbols','utilities'] as const)('resolves concept %s locally',concept=>{const r=q(semantic([concept]));if(['roads','slopes','annotations','dimensions','text','blocks'].includes(concept))expect(r.entityIds.length).toBeGreaterThan(0);else expect(r.entityIds).toEqual([]);});
  it('buildings expose strong aliases and weak mentions; weak groups excluded by default',()=>{const d=operationsFixture(),r=q(semantic(['buildings']),d);expect(r.groups.some(g=>g.tier==='STRONG'&&g.entityIds.includes('building'))).toBe(true);expect(r.groups.some(g=>g.tier==='WEAK'&&g.entityIds.includes('weak'))).toBe(true);const excluded=defaultExcludedGroups(r);expect(resolveDocumentQuery(r.query,d,[],excluded).entityIds).not.toContain('weak');expect(resolveDocumentQuery(r.query,d,[],excluded).entityIds).toContain('building');expect(plan([{type:'select_entities',query:r.query}],d).matchedEntityIds).not.toContain('weak');});
  it('Russian NFKC/case/ё normalization and separators',()=>{expect(normalizeQuery('  ЁЛКА  ')).toBe('елка');expect(semanticTokens('_ГП-ЗИС')).toEqual(['гп','зис']);const d=operationsFixture();expect(q(semantic(['buildings']),d).groups.some(g=>g.source.includes('_ГП_ЗИС'))).toBe(true);});
  it('captures current selection, empty selection and sorted fingerprint',()=>{expect(q({kind:'current_selection'},operationsFixture(),['road','building','road']).entityIds).toEqual(['road','building']);expect(q({kind:'current_selection'}).entityIds).toEqual([]);expect(q({kind:'current_selection'},operationsFixture(),['road','building']).selectionFingerprint).toBe('["building","road"]');});
  it('searches names/layers/block names/tags without provider and caps result rows',()=>{expect(searchDocument(operationsFixture(),'VOLUME').total).toBe(2);expect(searchDocument(operationsFixture(),'_ГП_ЗИС').rows[0]?.entityId).toBe('building');expect(searchDocument(operationsFixture(),'NAME').total).toBeGreaterThan(0);});
  it('rejects oversized results without a silently executable prefix',()=>{const d=operationsFixture(),e=d.entities.find(e=>e.id==='road')!;const large={...d,entities:Array.from({length:DOCUMENT_QUERY_LIMITS.results+1},(_,i)=>({...e,id:`e${i}`}))};const r=q({kind:'entity_type',entityType:'line'},large);expect(r.error).toContain('лимит');expect(r.entityIds).toEqual([]);expect(plan([{type:'select_entities',query:r.query}],large).error).toBeTruthy();});
});
describe('preview, execution, history and privacy',()=>{
  it('create layer + move is one atomic action preserving source, definitions, geometry',()=>{const d=operationsFixture(),p=plan(compound,d);expect(p.error).toBeNull();expect(d.layers.some(l=>l.name==='Архив')).toBe(false);const initial=initialEditorState(d),next=applyDocumentPlan(p,initial,size);expect(next.past).toHaveLength(1);expect(next.document.entities.find(e=>e.id==='building')).toMatchObject({layerId:p.commands[0]?.type==='create-layer'?p.commands[0].layer.id:'',source:{originalLayer:'_ГП_ЗИС'}});expect(next.document.blocks).toEqual(d.blocks);expect(next.document.vertices).toEqual(d.vertices);expect(editorReducer(next,{type:'undo'}).document).toBe(d);expect(editorReducer(editorReducer(next,{type:'undo'}),{type:'redo'}).document).toEqual(next.document);});
  it.each(['source','target'] as const)('locked %s blocks every mutation and leaves no created layer',kind=>{const d=operationsFixture(),locked={...d,layers:d.layers.map(l=>l.id==='buildings'?{...l,locked:true}:l)};const actions:DocumentAction[]=kind==='source'?compound:[{type:'move_entities_to_layer',query:{kind:'entity_type',entityType:'block_instance'},target:{kind:'existing_layer',name:'ГП_здания и сооружения'}}];const p=plan(actions,locked),initial=initialEditorState(locked),next=applyDocumentPlan(p,initial,size);expect(p.error).toContain('заблокирован');expect(next.document).toBe(locked);expect(next.past).toEqual([]);expect(next.document.layers.some(l=>l.name==='Архив')).toBe(false);});
  it('command kernel rolls back a failed move after create even without preflight',()=>{const d=operationsFixture(),p=plan(compound,d);expect(()=>applyCommandsAtomically(d,[p.commands[0]!,{type:'set-entities-layer',entityIds:['missing'],layerId:'missing'}])).toThrow();expect(d.layers.some(l=>l.name==='Архив')).toBe(false);});
  it('document/selection stale guards block Apply and refresh requires another Apply',()=>{let app=preview([{type:'select_entities',query:{kind:'current_selection'}}]);app=applicationReducer(app,{type:'select-entities',entityIds:['road']});expect(app.ai.status).toBe('document-stale');const stale=applicationReducer(app,{type:'document-apply',size});expect(stale.editor.selectedEntityIds).toEqual(['road']);app=applicationReducer(stale,{type:'document-refresh'});expect(app.ai.status).toBe('document-preview');expect(app.editor.past).toHaveLength(0);const p=plan(),editor=initialEditorState({...p.basedOnDocument,metadata:{...p.basedOnDocument.metadata,title:'Edited'}});expect(isDocumentPlanStale(p,editor)).toBe(true);expect(applyDocumentPlan(p,editor,size).document).toBe(editor.document);});
  it('highlight preview/select/fit have no mutation, history or dirty state',()=>{let app=preview([{type:'select_entities',query:{kind:'source_layer',name:'_ГП_ЗИС'}}]);const before=app.editor;expect(before.selectedEntityIds).toEqual([]);app=applicationReducer(app,{type:'document-fit-preview',size});expect(app.editor.document).toBe(before.document);expect(app.editor.selectedEntityIds).toEqual([]);app=applicationReducer(app,{type:'document-apply',size});expect(app.editor.selectedEntityIds).toEqual(['building']);expect(app.editor.document).toBe(before.document);expect(app.editor.past).toBe(before.past);expect(isDocumentDirty(app.editor)).toBe(false);});
  it('hide/show exact full layers use normal history, partial layer queries fail closed',()=>{const d=operationsFixture(),p=plan([{type:'set_layer_visibility',query:semantic(['roads','slopes']),visible:false}],d),next=applyDocumentPlan(p,initialEditorState(d),size);expect(next.past).toHaveLength(1);expect(next.document.layers.filter(l=>['roads','slopes'].includes(l.id)).every(l=>!l.visible)).toBe(true);expect(plan([{type:'set_layer_visibility',query:{kind:'entity_type',entityType:'dimension'},visible:false}],d).error).toContain('вне результата');});
  it('isolation is transient, excludes unrelated owners, restores exact visibility, no history/autosave',()=>{const d=operationsFixture(),hidden={...d,layers:d.layers.map(l=>l.id==='buildings'?{...l,visible:false}:l)},initial=initialEditorState(hidden),p=plan([{type:'isolate_result',query:{kind:'source_layer',name:'_ГП_ЗИС'}}],hidden),next=applyDocumentPlan(p,initial,size);expect(next.document).toBe(hidden);expect(next.past).toEqual([]);expect(renderItems(editorViewDocument(next)).map(i=>i.entity.id)).toEqual(['building']);const exited=editorReducer(next,{type:'exit-isolation'});expect(editorViewDocument(exited)).toBe(hidden);expect(exited.document.layers).toBe(hidden.layers);expect(isDocumentDirty(exited)).toBe(false);});
  it('strict runtime rejects IDs/code/deletion/mixed spatial tasks/forward layer refs/invented literals',()=>{for(const extra of [{entityIds:['building']},{commands:[]},{predicate:'return true'}])expect(()=>validateParserResult({actions:[{type:'select_entities',query:{kind:'source_layer',name:'_ГП_ЗИС'},...extra}]},'Выбери _ГП_ЗИС')).toThrow();expect(aiTaskSchema.safeParse({actions:[{type:'delete_entities',query:{kind:'current_selection'}}]}).success).toBe(false);expect(aiTaskSchema.safeParse({actions:[compound[1],compound[0]]}).success).toBe(false);expect(aiTaskSchema.safeParse({actions:[compound[0],{type:'create_rectangle',name:'Дом',width:2,height:3,placement:{type:'local_origin'}}]}).success).toBe(false);expect(()=>validateParserResult({actions:[{type:'select_entities',query:{kind:'block_name',name:'invented'}}]},'Выбери VOLUME')).toThrow();});
  it('real-provider transport includes only fixed instructions/schema and user text, never document IDs/catalog',async()=>{let payload:Record<string,unknown>={};const transport=async(_url:string|URL|Request,options?:RequestInit)=>{payload=JSON.parse(options!.body as string);return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({intent:{actions:[{type:'select_entities',query:semantic(['buildings'])}]},unsupported:false})}}]}),{status:200});};const result=await new OpenRouterIntentProvider('test-secret','model',transport).parseIntent({text:'Выбери все здания.',signal:new AbortController().signal});expect(result).toEqual({actions:[{type:'select_entities',query:semantic(['buildings'])}]});expect((payload.messages as {role:string;content:string}[]).filter(m=>m.role==='user')).toEqual([{role:'user',content:'Выбери все здания.'}]);expect(JSON.stringify(payload)).not.toContain('building"');expect(payload).not.toHaveProperty('document');});
});

it('isolated hidden owners remain manually selectable, label dependencies stay invisible/non-snappable',()=>{
  const d=operationsFixture(),hidden={...d,layers:d.layers.map(l=>l.id==='buildings'?{...l,visible:false}:l)},initial=initialEditorState(hidden),isolated=editorReducer(initial,{type:'isolate-entities',entityIds:['building'],label:'Building'});
  const clicked=editorReducer(isolated,{type:'select',entityId:'building'});expect(clicked.selectedEntityIds).toEqual(['building']);expect(editorReducer(clicked,{type:'exit-isolation'}).selectedEntityIds).toEqual([]);
  const withLabel={...d,entities:[...d.entities,{type:'label' as const,id:'label',name:'Linked',layerId:'notes',targetId:'building',template:'Name',dx:0,dy:0}]},labelView=editorViewDocument(editorReducer(initialEditorState(withLabel),{type:'isolate-entities',entityIds:['label'],label:'Annotation'}));
  expect(labelView.entities.some(e=>e.id==='building'&&e.visible===false)).toBe(true);expect(renderItems(labelView).map(i=>i.entity.id)).toEqual(['label']);expect(createSnapProvider(labelView).candidates).toEqual([]);
});
it('same-value ATTRIBs retain precise evidence while edited one loses its old match',()=>{
  const d=operationsFixture(),owner=d.entities[0]!;if(owner.type!=='block_instance')throw Error();const first=owner.attributePrimitives![0]!;
  const repeated={...d,entities:d.entities.map(e=>e.id===owner.id?{...owner,attributePrimitives:[first,{...first,source:{...first.source!,handle:'other'}}]}:e)};
  const changed=applyCommand(repeated,{type:'update-block-attribute',entityId:owner.id,tag:'NAME',attributeIndex:0,patch:{value:'27.95'}});
  const old=q({kind:'block_attribute',tag:'NAME',value:'27.89'},changed);expect(old.entityIds).toContain(owner.id);expect(old.evidence.get(owner.id)?.map(e=>e.attributeIndex)).toEqual([1]);expect(old.evidence.get(owner.id)?.[0]?.sourceHandle).toBe('other');expect(q({kind:'text_contains',text:'27.95',sourceType:null},changed).evidence.get(owner.id)?.[0]?.attributeIndex).toBe(0);
});

it('filtered text search finds nested ATTDEF and view-only Apply clears unrelated old editor errors',()=>{
  const d=operationsFixture();expect(q({kind:'text_contains',text:'Отметка',sourceType:'ATTDEF'},d).entityIds).toHaveLength(2);
  const initial={...initialEditorState(d),error:'Previous failure'},p=plan([{type:'select_entities',query:{kind:'source_layer',name:'_ГП_ЗИС'}}],d),next=applyDocumentPlan(p,initial,size);
  expect(next.error).toBeNull();expect(next.selectedEntityIds).toEqual(['building']);expect(next.document).toBe(d);expect(next.past).toEqual([]);
});

it('cancelled coordinate drafts block Apply transiently without making unchanged committed results stale',()=>{
  let app=preview([{type:'select_entities',query:{kind:'source_layer',name:'_ГП_ЗИС'}}]);app=applicationReducer(app,{type:'begin-transaction'});app=applicationReducer(app,{type:'transient',command:{type:'update-vertex',vertexId:'a',position:{x:2,y:3}}});
  expect(app.ai.status).toBe('document-preview');expect(applicationReducer(app,{type:'document-apply',size})).toBe(app);app=applicationReducer(app,{type:'cancel-transaction'});expect(app.ai.status).toBe('document-preview');app=applicationReducer(app,{type:'document-apply',size});expect(app.editor.selectedEntityIds).toEqual(['building']);
});

it('explicit mock document fixtures stay separate from the real natural-language adapter',async()=>{
  const text='Выбери все здания.',raw=await developmentMockProvider().parseIntent({text,signal:new AbortController().signal});expect(validateParserResult(raw,text)).toEqual({actions:[{type:'select_entities',query:{kind:'semantic_concept',concepts:['buildings']}}]});
});

it('visibility follows manual view policy and can hide a locked layer without editing its geometry',()=>{
  const d=operationsFixture(),locked={...d,layers:d.layers.map(l=>l.id==='roads'?{...l,locked:true}:l)},p=plan([{type:'set_layer_visibility',query:{kind:'geoservice_layer',name:'Дороги'},visible:false}],locked),next=applyDocumentPlan(p,initialEditorState(locked),size);
  expect(p.error).toBeNull();expect(next.document.layers.find(l=>l.id==='roads')).toMatchObject({locked:true,visible:false});expect(next.document.entities).toEqual(locked.entities);
});
