import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { createSampleDocument } from '../sample/document';
import type { GeoDocument, BlockInstanceEntity } from '../domain/model';
import type { VectorPrimitive, SourceProvenance } from '../vectors/types';
import { createHitStack, deepSelectionMetrics, nativeHit, NESTED_MOVE_MESSAGE, prioritizeHitOwners, resolveDeepSelection, topLevelBoundsCandidates } from '../editor/deepSelection';
import { vectorBoundsMetrics, vectorEntityBounds } from '../vectors/geometry';
import { createProvenanceIndex } from '../dxf/provenance';
import { editorReducer, initialEditorState, isDocumentDirty } from '../store/editor';
import { serializeDocument, deserializeDocument, documentFingerprint } from '../persistence/serialization';
import { validateDocument } from '../persistence/documentSchema';
import { importDxf } from '../dxf/import';
import { marqueeEntities } from '../editor/marquee';
const source=(originalType:string,handle='A'):SourceProvenance=>({kind:'dxf',sourceDocumentId:'source',originalType,originalLayer:'0',handle});
const primitiveStyle={layerId:'l',colorMode:'byblock' as const};
function fixture():GeoDocument {
  const sample=createSampleDocument();
  const primitives:VectorPrimitive[]=[{...primitiveStyle,kind:'path',points:[{x:0,y:0},{x:8,y:0}],closed:false,source:source('LINE','line')},{...primitiveStyle,kind:'text',position:{x:1,y:0},content:'ГРС газ',height:1,rotationDeg:0,source:source('TEXT','text')}];
  const instance=(i:number):BlockInstanceEntity=>({id:`b${i}`,name:'generic',type:'block_instance',layerId:'l',blockDefinitionId:'a',position:{x:i*12,y:0},rotationDeg:0,scaleX:1,scaleY:1,attributes:{Марка:'ГРС-1'},source:source('INSERT',String(i))});
  return {...sample,vertices:{},entities:Array.from({length:10},(_,i)=>instance(i)),layers:[{id:'l',name:'0',styleId:'s',order:0,visible:true,locked:false}],styles:[{id:'s',stroke:'#333333',fill:'none',lineWeight:1}],blocks:[{id:'a',sourceName:'BlockA',basePoint:{x:0,y:0},primitives}],sources:[{id:'source',filename:'synthetic.dxf',format:'DXF',dxfVersion:'AC1024',encoding:'utf-8',originalUnits:6}],viewport:{center:{x:0,y:0},pixelsPerUnit:10}};
}
const mixed=()=>{const b=readFileSync(new URL('./fixtures/dxf/mixed_proxy.dxf',import.meta.url));return importDxf(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'mixed.dxf');};
describe('deep selection is a transient read-only path',()=>{
  it('ordinary bounds query selects one canonical owner without a deep walk',()=>{const d=fixture(),before=deepSelectionMetrics();expect(topLevelBoundsCandidates(d,{x:2,y:0},.01)).toEqual(['b0']);expect(deepSelectionMetrics()).toEqual(before);});
  it('owner then painted TEXT and LINE cycle deterministically without changing 10 instances',()=>{const d=fixture(),original=serializeDocument(d),stack=createHitStack(d,['b0'],{x:2,y:0},.01);expect(stack.map(h=>h.selection?.sourceType??'owner')).toEqual(['owner','TEXT','LINE']);let state=initialEditorState(d);for(let i=0;i<7;i++){const index=i%stack.length;state=editorReducer(state,{type:'deep-select',candidate:stack[index]!,index,count:stack.length});expect(state.selectedEntityIds).toEqual(['b0']);expect(state.past).toEqual([]);}expect(serializeDocument(state.document)).toBe(original);expect(state.document.blocks).toBe(d.blocks);});
  it('nested text resolves Parent → Child → TEXT with composed rotation/scale and provenance',()=>{const d=fixture();d.blocks!.push({id:'parent',sourceName:'Parent',basePoint:{x:0,y:0},primitives:[{...primitiveStyle,kind:'block',blockDefinitionId:'a',position:{x:10,y:20},rotationDeg:90,scaleX:2,scaleY:3,source:source('INSERT','nested')}]});d.entities=[{...d.entities[0] as BlockInstanceEntity,blockDefinitionId:'parent'}];const hits=createHitStack(d,['b0'],{x:9,y:24},.01);expect(hits.map(h=>h.selection?.sourceType??'owner')).toEqual(['owner','INSERT','TEXT']);const selection=hits[2]!.selection!;expect(selection.blockPath).toEqual(['Parent','BlockA']);expect(selection.primitivePath).toEqual([0,1]);expect(resolveDeepSelection(d,selection)).toMatchObject({primitive:{content:'ГРС газ'},source:{handle:'text'}});});
  it('M / drag / deletion cannot mutate a deep selection; normal owner restores movement',()=>{const d=fixture(),candidate=createHitStack(d,['b0'],{x:2,y:0},.01)[1]!;let s=editorReducer(initialEditorState(d),{type:'deep-select',candidate,index:1,count:3});for(const action of [{type:'open-move-input' as const},{type:'begin-selection-move' as const,entityIds:['b0']},{type:'execute' as const,command:{type:'delete-entity' as const,entityId:'b0'}}]){const next=editorReducer(s,action);expect(next.error).toBe(NESTED_MOVE_MESSAGE);expect(next.document).toBe(d);expect(next.transactionBefore).toBeNull();}s=editorReducer(s,{type:'select',entityId:'b0'});expect(s.deepSelection).toBeNull();expect(editorReducer(s,{type:'begin-selection-move',entityIds:['b0']}).selectionMove).not.toBeNull();});
  it('hidden primitive layers and cycles are guarded; invalid saved paths do not resolve',()=>{const d=fixture();d.blocks![0]!.primitives[1]={...d.blocks![0]!.primitives[1]!,visible:false};expect(createHitStack(d,['b0'],{x:2,y:0},.01)).toHaveLength(2);expect(resolveDeepSelection(d,{ownerEntityId:'b0',blockPath:[],primitivePath:[99],sourceType:'TEXT'})).toBeNull();});
});
describe('foreground hit priority and shared bounds cache',()=>{
  it('line and block precede a filled hatch, while every overlapping owner remains in the stack',()=>{const d=fixture();d.vertices={v1:{id:'v1',x:0,y:0},v2:{id:'v2',x:8,y:0}};d.entities.push({id:'line',name:'Line',type:'line',layerId:'l',startVertexId:'v1',endVertexId:'v2'},{id:'hatch',name:'Hatch',type:'imported_graphic',layerId:'l',position:{x:0,y:0},source:source('HATCH'),primitives:[{...primitiveStyle,kind:'path',points:[{x:-10,y:-10},{x:10,y:-10},{x:10,y:10},{x:-10,y:10}],closed:true,fill:true}]});expect(nativeHit(d,d.entities[10]!,{x:2,y:0},.01)).toBe(true);expect(prioritizeHitOwners(d,['hatch','b0','line'])).toEqual(['line','b0','hatch']);const stack=createHitStack(d,['hatch','b0','line'],{x:2,y:0},.01);expect(stack.filter(h=>!h.selection).map(h=>h.ownerEntityId)).toEqual(['line','b0','hatch']);});
  it('definitions compute once and unchanged instances survive document edits and marquee',()=>{const d=fixture(),start=vectorBoundsMetrics();for(const e of d.entities)vectorEntityBounds(d,e);const warm=vectorBoundsMetrics();expect(warm.definitionComputations-start.definitionComputations).toBe(1);for(let i=0;i<20;i++){const next={...d,metadata:{...d.metadata,title:String(i)}};topLevelBoundsCandidates(next,{x:2,y:0},.1);marqueeEntities(next,d.viewport,{width:1000,height:700},{x:0,y:0},{x:1000,y:700});}expect(vectorBoundsMetrics()).toEqual(warm);});
  it('moving one instance transforms cached definition bounds without visiting primitives',()=>{const d=fixture();vectorEntityBounds(d,d.entities[0]!);const warm=vectorBoundsMetrics(),e=d.entities[0] as BlockInstanceEntity;expect(vectorEntityBounds({...d}, {...e,position:{x:10,y:20}})[0]).toEqual({x:10,y:20});expect(vectorBoundsMetrics().primitiveVisits).toBe(warm.primitiveVisits);expect(vectorBoundsMetrics().definitionComputations).toBe(warm.definitionComputations);});
  it('replacement child revision invalidates nested ancestor bounds',()=>{const d=fixture();d.blocks!.push({id:'p',sourceName:'Parent',basePoint:{x:0,y:0},primitives:[{...primitiveStyle,kind:'block',blockDefinitionId:'a',position:{x:0,y:0},rotationDeg:0,scaleX:1,scaleY:1}]});const e={...d.entities[0] as BlockInstanceEntity,blockDefinitionId:'p'};const initial=vectorEntityBounds(d,e),child={...d.blocks![0]!,primitives:[{...primitiveStyle,kind:'path' as const,points:[{x:0,y:0},{x:40,y:0}],closed:false}]};const updated={...d,blocks:[child,d.blocks![1]!]};expect(vectorEntityBounds(updated,e)).not.toEqual(initial);expect(vectorEntityBounds(updated,e)[1]?.x).toBe(40);});
});
describe('controlled imported semantic text',()=>{
  it('MLeader keeps line/arrow and text geometry with explicit searchable metadata',()=>{const {document:d}=mixed(),leader=d.entities.find(e=>e.source?.originalType==='MULTILEADER')!;expect(leader).toMatchObject({type:'imported_graphic',semanticContent:{primaryText:'Выноска'}});if(leader.type!=='imported_graphic')throw Error();expect(leader.primitives.some(p=>p.kind==='path')).toBe(true);expect(createProvenanceIndex(d).searchText('ВЫНОСКА').some(h=>h.ownerEntityId===leader.id&&h.sourceKind==='multileader')).toBe(true);expect(deserializeDocument(serializeDocument(d))).toEqual(d);});
  it('anonymous DXF dimension stays proxy, exposes displayed text/type/measurement where supplied',()=>{const b=readFileSync(new URL('./fixtures/dxf/mixed_proxy.dxf',import.meta.url),'utf8').replace('0\nDIMENSION\n','0\nDIMENSION\n42\n12.5\n70\n32\n');const d=importDxf(new TextEncoder().encode(b).buffer,'dimension.dxf').document;const dimension=d.entities.find(e=>e.source?.originalType==='DIMENSION')!;expect(dimension).toMatchObject({type:'imported_graphic',semanticContent:{measuredValue:12.5,dimensionType:32}});expect(createProvenanceIndex(d).searchText('12.5').some(h=>h.ownerEntityId===dimension.id)).toBe(true);});
  it('definition and ATTRIB text are projected as structured Russian hits without adding entities',()=>{const d=fixture(),index=createProvenanceIndex(d);expect(index.searchText('ГАЗ')).toHaveLength(10);expect(index.searchBlockAttributes('грс-1')).toHaveLength(10);expect(index.searchText('газ',{includeBlockDefinitions:false})).toEqual([]);expect(index.searchText('газ')[0]).toMatchObject({ownerEntityId:'b0',sourceKind:'block_text',path:['BlockA','TEXT'],primitivePath:[1],layer:'0'});expect(index.getEntitySemanticSummary('b0')).toMatchObject({blockName:'BlockA',primitiveCount:2,instanceCount:10});expect(d.entities).toHaveLength(10);});
  it('derived metadata exposes ATTDEF/source types/nested names and does not leak mutable references',()=>{const d=fixture();d.blocks![0]!.primitives.push({...primitiveStyle,kind:'text',position:{x:0,y:1},content:'Марка',attributeTag:'TAG',height:1,rotationDeg:0,source:source('ATTDEF')});const index=createProvenanceIndex(d),summary=index.getBlockDefinitionSemantics('a');expect(summary.attributeDefinitions).toEqual([{tag:'TAG',text:'Марка',path:['BlockA']}]);expect(summary.sourceTypes).toEqual(['LINE','TEXT','ATTDEF']);summary.textContent[0]!.text='mutated';expect(index.searchText('газ')[0]?.text).toBe('ГРС газ');const hits=index.searchText('газ');hits[0]!.path.push('bad');expect(index.searchText('газ')[0]!.path).not.toContain('bad');});
  it('canonical metadata rejects unsafe/raw content and invalid positions',()=>{const d=mixed().document,e=d.entities[0]!;expect(()=>validateDocument({...d,entities:[{...e,semanticContent:{rawDxf:'payload'}}]})).toThrow();expect(()=>validateDocument({...d,entities:[{...e,semanticContent:{textRuns:[{text:'x',position:{x:NaN,y:0}}]}}]})).toThrow();});
  it('native TEXT/MTEXT remain editable and source provenance survives edit/Move/layer/Save Open',()=>{const d=mixed().document,e=d.entities.find(e=>e.type==='text')!;let s=initialEditorState(d);s=editorReducer(s,{type:'execute',command:{type:'update-entity',entityId:e.id,patch:{content:'Газ новый'}}});s=editorReducer(s,{type:'execute',command:{type:'move-entities',entityIds:[e.id],delta:{x:2,y:3}}});s=editorReducer(s,{type:'execute',command:{type:'set-entity-layer',entityId:e.id,layerId:d.layers[0]!.id}});expect(deserializeDocument(serializeDocument(s.document))).toEqual(s.document);expect(createProvenanceIndex(s.document).searchText('НОВЫЙ')).toHaveLength(1);expect(s.document.entities.find(x=>x.id===e.id)?.source).toEqual(e.source);});
  it('exact component fingerprints retain dirty/Undo/Save semantics on immutable large definitions',()=>{const d=fixture(),before=documentFingerprint(d);let s=initialEditorState(d);s=editorReducer(s,{type:'execute',command:{type:'move-entities',entityIds:['b0'],delta:{x:1,y:2}}});expect(isDocumentDirty(s)).toBe(true);s=editorReducer(s,{type:'undo'});expect(isDocumentDirty(s)).toBe(false);expect(documentFingerprint(s.document)).toBe(before);});
});
