import {describe,expect,it} from 'vitest';
import {fitCurve,reconstructPaths} from '../image/reconstruct';
import {analysisToPerspective,rotatedSize,suggestDeskew} from '../image/deskew';
import {fullQuad,homography,pixelToModel,projectPixel} from '../image/transform';
import {extractGeometry} from '../image/extract';
import {DEFAULT_EXTRACTION,type PixelImage,type PixelPoint} from '../image/types';
const settings={detail:'medium' as const,join:true,minimum:3};
const straight=(a:PixelPoint,b:PixelPoint,count=100)=>Array.from({length:count+1},(_,i)=>({x:a.x+(b.x-a.x)*i/count,y:a.y+(b.y-a.y)*i/count}));
const curve=(start:number,end:number)=>Array.from({length:161},(_,i)=>({x:120+60*Math.cos(start+(end-start)*i/160),y:110+60*Math.sin(start+(end-start)*i/160)}));
function raster(paths:PixelPoint[][],width=320,height=240):PixelImage{const data=new Uint8ClampedArray(width*height*4).fill(255);for(const path of paths)for(const [i,p]of path.entries()){const previous=path[i-1]??p,count=Math.ceil(Math.hypot(p.x-previous.x,p.y-previous.y)*2);for(let n=0;n<=count;n++){const x=Math.round(previous.x+(p.x-previous.x)*n/(count||1)),y=Math.round(previous.y+(p.y-previous.y)*n/(count||1));for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(x+dx>=0&&y+dy>=0&&x+dx<width&&y+dy<height){const k=((y+dy)*width+x+dx)*4;data[k]=data[k+1]=data[k+2]=0;}}}return {width,height,data};}
describe('CAD primitive reconstruction',()=>{
 it('staircase and 0.5 degree wobble become one Line with measured residual',()=>{const raw=Array.from({length:181},(_,i)=>({x:20+i,y:40+Math.round(i*.02)+(i%7===0?.3:0)})),result=reconstructPaths([raw],settings);expect(result.candidates).toHaveLength(1);expect(result.candidates[0]?.type).toBe('line');expect(result.metrics.rawVertices).toBe(181);expect(result.metrics.finalVertices).toBe(2);expect(result.metrics.maxDeviationPx).toBeLessThan(1);});
 it('a genuine corner stays two shared Line primitives',()=>{const corner={x:150,y:40},path=[...straight({x:20,y:40},corner).slice(0,-1),...straight(corner,{x:150,y:190})],result=reconstructPaths([path],settings);expect(result.candidates).toHaveLength(2);expect(result.candidates.every(c=>c.type==='line')).toBe(true);const p=result.candidates.flatMap(c=>'points'in c?c.points:[]);expect(p.filter(p=>p.x===150&&p.y===40)).toHaveLength(2);});
 it.each(['T','X'] as const)('%s branch endpoints are not merged through',kind=>{const node={x:150,y:120},paths=[straight({x:20,y:120},node),straight(node,{x:280,y:120}),straight(node,{x:150,y:25}),...(kind==='X'?[straight(node,{x:150,y:220})]:[])],result=reconstructPaths(paths,settings);expect(result.candidates).toHaveLength(kind==='T'?3:4);expect(result.candidates.flatMap(c=>'points'in c?c.points:[]).filter(p=>p.x===node.x&&p.y===node.y)).toHaveLength(paths.length);});
 it('true arc fits circle model with endpoint constraints; arbitrary free curve is rejected',()=>{const points=curve(.15,2.3),result=fitCurve(points,false,.2);expect(result?.candidate.type).toBe('arc');expect(result?.deviations.every(d=>d<1e-7)).toBe(true);expect(fitCurve(Array.from({length:60},(_,i)=>({x:i,y:20*Math.sin(i*.15)})),false,.5)).toBeNull();});
 it('full circle is one Circle, not tiny segments',()=>{const result=reconstructPaths([curve(0,2*Math.PI)],settings);expect(result.candidates).toHaveLength(1);expect(result.candidates[0]?.type).toBe('circle');expect(result.metrics.finalVertices).toBe(0);});
 it('only compatible small scan gaps merge; close parallel strokes stay separate',()=>{const result=reconstructPaths([straight({x:20,y:40},{x:100,y:40}),straight({x:102,y:40},{x:200,y:40})],settings);expect(result.candidates).toHaveLength(1);const parallel=reconstructPaths([straight({x:20,y:40},{x:100,y:40}),straight({x:102,y:42},{x:200,y:42})],settings);expect(parallel.candidates).toHaveLength(2);});
 it('stroke thickness increases noise tolerance but calibrated MODEL cap limits fitting',()=>{const p=Array.from({length:101},(_,i)=>({x:20+i,y:40+Math.sin(i*.1)*1.5})),distances=new Float32Array(320*240).fill(3);expect(reconstructPaths([p],{...settings,distances,width:320}).candidates).toHaveLength(1);expect(reconstructPaths([p],{...settings,distances,width:320,modelTolerancePx:.4}).candidates.length).toBeGreaterThan(1);});
 it.each(['T','X'] as const)('raster %s retains one shared branch node',kind=>{const node={x:150,y:120},result=extractGeometry(raster([straight({x:20,y:120},{x:280,y:120}),straight({x:150,y:25},kind==='T'?node:{x:150,y:220})]),DEFAULT_EXTRACTION);const lines=result.candidates.filter(c=>c.type==='line');expect(lines).toHaveLength(kind==='T'?3:4);const endpoints=lines.flatMap(c=>'points'in c?c.points:[]),counts=new Map<string,number>();for(const p of endpoints){const k=`${p.x}:${p.y}`;counts.set(k,(counts.get(k)??0)+1);}expect([...counts.values()]).toContain(kind==='T'?3:4);});
 it('raster straight line and circular arc use native candidates',()=>{const line=extractGeometry(raster([straight({x:20,y:40},{x:280,y:51})]),DEFAULT_EXTRACTION);expect(line.candidates).toHaveLength(1);expect(line.candidates[0]?.type).toBe('line');const arc=extractGeometry(raster([curve(.2,2.6)]),DEFAULT_EXTRACTION);expect(arc.candidates.some(c=>c.type==='arc')).toBe(true);});
});
describe('distinct deskew transform',()=>{
 it('detects a 2.5 degree dominant line; ambiguous orientations have no suggestion',()=>{const a=2.5*Math.PI/180,line={id:'line',type:'line' as const,points:[{x:10,y:20},{x:210,y:20+200*Math.tan(a)}]};expect(suggestDeskew([line])?.skewDeg).toBeCloseTo(2.5,5);expect(suggestDeskew([line,{...line,id:'other',points:[{x:0,y:0},{x:200,y:-35}]}])).toBeNull();});
 it('perspective + deskew + scale + MODEL placement compose with known point',()=>{const width=400,height=300,rotation=-2.5,size=rotatedSize(width,height,rotation),quad=[{x:20,y:30},{x:450,y:10},{x:470,y:350},{x:0,y:330}] as ReturnType<typeof fullQuad>,p={x:120,y:85},a=rotation*Math.PI/180,analysis={x:size.width/2+(p.x-width/2)*Math.cos(a)-(p.y-height/2)*Math.sin(a),y:size.height/2+(p.x-width/2)*Math.sin(a)+(p.y-height/2)*Math.cos(a)},calibration={quad,perspectiveWidth:width,perspectiveHeight:height,analysisRotationDeg:rotation,rectifiedWidth:size.width,rectifiedHeight:size.height};expect(analysisToPerspective(analysis,calibration).x).toBeCloseTo(p.x,9);const source=projectPixel(homography(fullQuad(width,height),quad),analysisToPerspective(analysis,calibration));expect(source).toEqual(projectPixel(homography(fullQuad(width,height),quad),p));const world=pixelToModel(analysis,{position:{x:100,y:200},width:size.width*.02,height:size.height*.02,rotationDeg:30},calibration),x=(analysis.x-size.width/2)*.02,y=(size.height/2-analysis.y)*.02;expect(world.x).toBeCloseTo(100+x*Math.cos(Math.PI/6)-y*Math.sin(Math.PI/6),9);expect(world.y).toBeCloseTo(200+x*Math.sin(Math.PI/6)+y*Math.cos(Math.PI/6),9);});
});
