import { describe, expect, it } from 'vitest';
import { fullQuad, homography, metresPerPixel, pixelToModel, projectPixel, quadError, rectifyImage } from '../image/transform';
import { cleanupPaths, extractGeometry, fitCircle, simplify } from '../image/extract';
import { DEFAULT_EXTRACTION, type Candidate, type ImageCalibration } from '../image/types';
import { imagePlan, skewedCorners } from './fixtures/imagePlan';
import { vectorizationCommands } from '../image/apply';
import { createNewDocument } from '../domain/newDocument';
import { applyCommand } from '../domain/commands';
import { editorReducer, initialEditorState } from '../store/editor';
import { serializeDocument, deserializeDocument } from '../persistence/serialization';
import { createSnapProvider } from '../snapping';
import type { RasterUnderlayEntity } from '../domain/model';
describe('local image transforms', () => {
  it('projective corners and inverse interior agree for a skewed photo', () => { const from = fullQuad(480, 320), forward = homography(from, skewedCorners), inverse = homography(skewedCorners, from); from.forEach((p, i) => { const q = projectPixel(forward, p); expect(q.x).toBeCloseTo(skewedCorners[i]!.x, 8); expect(q.y).toBeCloseTo(skewedCorners[i]!.y, 8); }); for (const p of [{ x: 120, y: 80 }, { x: 250, y: 170 }]) { const q = projectPixel(inverse, projectPixel(forward, p)); expect(q.x).toBeCloseTo(p.x, 8); expect(q.y).toBeCloseTo(p.y, 8); } });
  it('crossed, mirrored, collapsed and out-of-bounds corners fail safely', () => { const q = fullQuad(100, 100); expect(quadError([q[0], q[2], q[1], q[3]], 100, 100)).toBeTruthy(); expect(quadError([q[0], q[3], q[2], q[1]], 100, 100)).toBeTruthy(); expect(quadError([q[0], q[0], q[2], q[3]], 100, 100)).toBeTruthy(); expect(quadError(fullQuad(101, 100), 100, 100)).toBeTruthy(); expect(() => homography([q[0], q[0], q[0], q[0]], q)).toThrow(); });
  it('identity rectification retains source and alpha without mutating it', () => { const source = imagePlan(); source.data[3] = 127; source.data[7] = 0; const before = source.data.slice(), result = rectifyImage(source, fullQuad(480, 320), 480, 320); expect(Buffer.from(result.data).equals(Buffer.from(before))).toBe(true); expect(Buffer.from(source.data).equals(Buffer.from(before))).toBe(true); });
  it('calibration rejects zero reference and maps pixel → MODEL with Y inversion and rotation', () => { expect(metresPerPixel({ x: 0, y: 0 }, { x: 400, y: 0 }, 10)).toBe(.025); expect(() => metresPerPixel({ x: 0, y: 0 }, { x: 0, y: 0 }, 10)).toThrow(); expect(() => metresPerPixel({ x: 0, y: 0 }, { x: 4, y: 0 }, -1)).toThrow(); expect(pixelToModel({ x: 100, y: 0 }, { position: { x: 5, y: 6 }, width: 10, height: 20, rotationDeg: 90 }, { rectifiedWidth: 100, rectifiedHeight: 200 })).toEqual({ x: -5, y: 11 }); });
});
describe('deterministic extraction', () => {
  it.each(['clean', 'rotated', 'circle', 'text'] as const)('%s fixture returns meaningful bounded geometry without OCR fabrication', kind => { const result = extractGeometry(imagePlan(kind), DEFAULT_EXTRACTION); expect(result.candidates.length).toBeGreaterThan(0); expect(result.candidates.length).toBeLessThan(20); if (kind === 'text') { expect(result.candidates.some(c => c.type === 'text')).toBe(true); expect(result.candidates.every(c => !('recognizedText' in c))).toBe(true); } else { expect(result.candidates.some(c => c.type === 'contour')).toBe(true); expect(result.candidates.some(c => c.type === 'line')).toBe(true); } if (kind === 'circle') expect(result.candidates.filter(c => c.type === 'circle')).toHaveLength(1); });
  it('rectifies skewed fixture before extracting contour', () => { const source = imagePlan('skewed'), fixed = rectifyImage(source, skewedCorners, 480, 320); expect(extractGeometry(fixed, DEFAULT_EXTRACTION).candidates.some(c => c.type === 'contour')).toBe(true); });
  it('noise removal reduces spurious geometry with deterministic repeatability', () => { const source = imagePlan('noisy'), low = extractGeometry(source, { ...DEFAULT_EXTRACTION, noise: 'low' }), high = extractGeometry(source, { ...DEFAULT_EXTRACTION, noise: 'high' }); expect(high.candidates.length).toBeLessThan(low.candidates.length); expect(high.candidates).toEqual(extractGeometry(source, { ...DEFAULT_EXTRACTION, noise: 'high' }).candidates); });
  it('RDP keeps an actual corner and removes collinear jaggies', () => { expect(simplify([{ x: 0, y: 0 }, { x: 5, y: .1 }, { x: 10, y: 0 }, { x: 10, y: 10 }], .5)).toEqual([{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }]); });
  it('joins collinear fragments, rejects duplicate reverse segment and retains junctions', () => { const a = [{ x: 0, y: 0 }, { x: 10, y: 0 }], b = [{ x: 10.5, y: 0 }, { x: 20, y: 0 }]; expect(cleanupPaths([a, b], DEFAULT_EXTRACTION)[0]!.points).toHaveLength(2); expect(cleanupPaths([a, [...a].reverse()], { ...DEFAULT_EXTRACTION, join: false })).toHaveLength(1); const junction = cleanupPaths([a, b, [{ x: 10, y: 0 }, { x: 10, y: 20 }]], DEFAULT_EXTRACTION); expect(junction).toHaveLength(3); });
  it('accepts a complete circle and rejects arcs, rectangle and noisy radial loops', () => { const circle = Array.from({ length: 100 }, (_, i) => ({ x: Math.cos(i / 100 * Math.PI * 2) * 20, y: Math.sin(i / 100 * Math.PI * 2) * 20 })); expect(fitCircle(circle)?.radius).toBeCloseTo(20); expect(fitCircle(circle.slice(0, 60))).toBeNull(); expect(fitCircle(circle.map((p, i) => ({ x: p.x * (i % 2 ? 1.3 : .8), y: p.y })))).toBeNull(); });
});
describe('canonical atomic Apply', () => {
  const calibration: ImageCalibration = { quad: fullQuad(480, 320), rectifiedWidth: 480, rectifiedHeight: 320, reference: { a: { x: 45, y: 45 }, b: { x: 225, y: 45 }, distanceMeters: 18 } };
  const raster: RasterUnderlayEntity = { id: 'raster', type: 'raster_underlay', assetId: 'local-asset', name: 'plan', position: { x: 0, y: 0 }, width: 48, height: 32, rotationDeg: 0, opacity: .6, locked: false, layerId: 'boundary' };
  function document() { const base = createNewDocument(); return applyCommand(base, { type: 'add-entity', entity: raster, vertices: [] }); }
  it('one Undo removes all accepted native geometry and new layer, raster remains; Redo persists provenance and snapping', () => { const d = document(), original = d.entities[0] as RasterUnderlayEntity, candidates = extractGeometry(imagePlan('circle'), DEFAULT_EXTRACTION).candidates; const commands = vectorizationCommands(d, original, original, calibration, candidates, new Set(candidates.map(c => c.id)), '__new', 'run-one'); let state = initialEditorState(d); state = editorReducer(state, { type: 'execute-batch', commands, expectedDocument: d }); expect(state.error).toBeNull(); expect(state.past).toHaveLength(1); expect(state.document.entities.some(e => e.type === 'circle')).toBe(true); expect(state.document.entities.filter(e => e.type !== 'raster_underlay').every(e => e.imageSource?.source === 'image-vectorization')).toBe(true); expect(createSnapProvider(state.document).candidates.length).toBeGreaterThan(4); const saved = deserializeDocument(serializeDocument(state.document)); expect(saved.entities).toEqual(state.document.entities); state = editorReducer(state, { type: 'undo' }); expect(state.document).toBe(d); state = editorReducer(state, { type: 'redo' }); expect(state.document.entities).toEqual(saved.entities); const result = state.document.entities.find(e => e.type === 'line')!; const moved = applyCommand(state.document, { type: 'move-entities', entityIds: ['raster'], delta: { x: 12, y: 3 } }); expect(moved.entities.find(e => e.id === result.id)).toEqual(result); expect(moved.vertices).toEqual(state.document.vertices); });
  it('exclusion, text/symbol hooks and stale/locked guards never fabricate geometry', () => { const d = document(), original = d.entities[0] as RasterUnderlayEntity; const candidates: Candidate[] = [{ id: 't', type: 'text', bounds: { x: 0, y: 0, width: 20, height: 10 } }, { id: 's', type: 'symbol', bounds: { x: 0, y: 0, width: 20, height: 10 } }]; expect(() => vectorizationCommands(d, original, original, calibration, candidates, new Set(['t', 's']), '__new', 'run')).toThrow('OCR'); expect(() => vectorizationCommands(d, { ...original }, original, calibration, [], new Set(), '__new', 'run')).toThrow('изменена'); });
  it('perspective metadata stays separate from source asset and relinking clears stale calibration', () => { const d = document(), original = d.entities[0] as RasterUnderlayEntity; const fixed = applyCommand(d, { type: 'update-underlay', entityId: original.id, patch: { imageCalibration: calibration } }); expect((deserializeDocument(serializeDocument(fixed)).entities[0] as RasterUnderlayEntity).imageCalibration).toEqual(calibration); expect(fixed.entities[0]).toMatchObject({ assetId: 'local-asset' }); expect((applyCommand(fixed, { type: 'update-underlay', entityId: original.id, patch: { assetId: 'new-local-asset' } }).entities[0] as RasterUnderlayEntity).imageCalibration).toBeUndefined(); });
});
