import {describe,expect,it} from 'vitest';
import {grayImage,adaptiveMask} from '../image/binary';
import {normalizeOcrText,preprocessOcr} from '../image/ocr';
import {renderSymbolSignature,matchSymbol,detectSymbols} from '../image/symbolRecognition';
import {requireSymbol} from '../symbols/registry';
import {isConfirmedRegion} from '../image/understanding';
import {cleanupPaths,extractGeometry} from '../image/extract';
import {DEFAULT_EXTRACTION,type Candidate,type PixelImage,type ImageCalibration} from '../image/types';
import {vectorizationCommands} from '../image/apply';
import {fullQuad} from '../image/transform';
import {createNewDocument} from '../domain/newDocument';
import {applyCommand} from '../domain/commands';
import type {RasterUnderlayEntity} from '../domain/model';
import {editorReducer,initialEditorState} from '../store/editor';
import {serializeDocument,deserializeDocument} from '../persistence/serialization';
import {searchDocument,resolveDocumentQuery} from '../documentOperations/query';
import {featureIndex} from '../semantics/features';
function blank(width=100,height=100):PixelImage{return {width,height,data:new Uint8ClampedArray(width*height*4).fill(255)};}
function ink(image:PixelImage,x:number,y:number){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const X=x+dx,Y=y+dy;if(X<0||Y<0||X>=image.width||Y>=image.height)continue;const i=(Y*image.width+X)*4;image.data[i]=image.data[i+1]=image.data[i+2]=20;}}
describe('image understanding safety and deterministic preprocessing',()=>{
 it('normalizes RU whitespace/punctuation without inventing corrections or dropping Ø',()=>{expect(normalizeOcrText(' \nГАЗ\tØ57\u0000 H=28.40 ')).toBe('ГАЗ Ø57 H=28.40');expect(normalizeOcrText('ГAЗ')).toBe('ГAЗ');});
 it('transparent dark pixels composite to white',()=>{const im=blank(2,2);im.data.fill(0);expect([...grayImage(im)]).toEqual([255,255,255,255]);});
 it('local illumination removes shadow gradient but preserves faded stroke',()=>{const w=160,h=80,gray=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++)gray[y*w+x]=100+Math.round(x*.8);for(let x=15;x<145;x++)gray[40*w+x]=gray[40*w+x]!-40;const mask=adaptiveMask(gray,w,h);expect(mask.slice(40*w+15,40*w+145).reduce((n,v)=>n+v,0)).toBeGreaterThan(120);expect(mask.reduce((n,v)=>n+v,0)).toBeLessThan(300);});
 it('rotates padded OCR crop, inverts dark paper and never mutates source',()=>{const im=blank(20,60);for(let y=10;y<50;y++)ink(im,10,y);const before=im.data.slice(),out=preprocessOcr(im,90);expect(out.width).toBeGreaterThan(out.height);expect(out.data.some((v,i)=>i%4!==3&&v===0)).toBe(true);expect(im.data).toEqual(before);const inverted={...im,data:im.data.map((v,i)=>i%4===3?255:255-v)};expect(preprocessOcr(inverted,90).data.some((v,i)=>i%4!==3&&v===0)).toBe(true);});
 it.each(['T','X'] as const)('%s junction reconstructs shared endpoints without Connector inference',kind=>{const im=blank();if(kind==='T'){for(let x=10;x<90;x++)ink(im,x,50);for(let y=10;y<=50;y++)ink(im,50,y);}else for(let i=10;i<90;i++){ink(im,i,i);ink(im,i,100-i);}const cs=extractGeometry(im,DEFAULT_EXTRACTION).candidates;expect(cs.filter(c=>'points'in c)).toHaveLength(kind==='T'?3:4);const ends=cs.flatMap(c=>'points'in c?[c.points[0]!,c.points.at(-1)!]:[]);const center=ends.filter(p=>Math.hypot(p.x-50,p.y-50)<3);expect(center).toHaveLength(kind==='T'?3:4);expect(new Set(center.map(p=>`${p.x},${p.y}`)).size).toBe(1);});
 it('joins only collinear scan gaps; preserves nearby corners and ambiguous branches',()=>{const a=[{x:0,y:0},{x:10,y:0}],b=[{x:11,y:0},{x:20,y:0}],corner=[{x:11,y:0},{x:11,y:20}];expect(cleanupPaths([a,b],DEFAULT_EXTRACTION)).toHaveLength(1);expect(cleanupPaths([a,corner],DEFAULT_EXTRACTION)).toHaveLength(2);expect(cleanupPaths([a,b,corner],DEFAULT_EXTRACTION)).toHaveLength(3);});
 it('vector-derived signatures tolerate rotation and minor dropout; ambiguous blank has no match',()=>{const valve=requireSymbol('gas-process-demo','valve');for(const rotation of [0,90,180,270]){const signature=renderSymbolSignature(valve,rotation);expect(matchSymbol(signature)?.template.symbol.id).toBe('valve');signature.mask=signature.mask.map((v,i)=>i%17===0?0:v);expect(matchSymbol(signature)?.template.symbol.id).toBe('valve');}expect(matchSymbol({mask:new Uint8Array(48*48),aspect:1,width:1,center:{x:0,y:0}})).toBeNull();});
 it('does not promote unconfirmed text or guessed symbol',()=>{const text:Candidate={id:'t',type:'text',bounds:{x:0,y:0,width:10,height:10},recognizedText:'ГАЗ',confidence:.99};expect(isConfirmedRegion(text)).toBe(false);expect(isConfirmedRegion({...text,confirmed:true})).toBe(true);expect(isConfirmedRegion({...text,confirmed:true,recognizedText:' '})).toBe(false);});
 it('unknown repeated outline creates review candidates without a library claim',()=>{const im=blank(240,100);for(const offset of [20,130]){for(let i=0;i<40;i++){ink(im,offset+i,20);ink(im,offset+i,60);ink(im,offset,20+i);ink(im,offset+40,20+i);ink(im,offset+i,20+i);ink(im,offset+i,60-i);}}const groups=detectSymbols(im,[]).candidates;expect(groups).toHaveLength(2);expect(groups.every(c=>!c.proposedSymbol&&!c.confirmed)).toBe(true);expect(groups[0]!.groupId).toBe(groups[1]!.groupId);});
});
describe('confirmed image result uses canonical atomic command boundary',()=>{
 const calibration:ImageCalibration={quad:fullQuad(480,320),rectifiedWidth:480,rectifiedHeight:320};
 const raster:RasterUnderlayEntity={id:'raster',type:'raster_underlay',name:'scan',assetId:'local-asset',position:{x:0,y:0},width:48,height:32,rotationDeg:0,opacity:.6,locked:false,layerId:'boundary'};
 const text:Candidate={id:'t',type:'text',bounds:{x:40,y:40,width:60,height:20},recognizedText:'ГАЗ',originalText:'ГAЗ',confidence:.42,confirmed:true,semanticConceptId:'gas_pipe',semanticConfirmed:true};
 const signature=renderSymbolSignature(requireSymbol('gas-process-demo','valve'),90);
 const symbol:Candidate={id:'s',type:'symbol',groupId:'repeated',bounds:{x:200,y:40,width:70,height:100},proposedSymbol:{libraryId:'gas-process-demo',symbolId:'valve',confirmed:true,matchClass:'possible',rotationDeg:-90,localWidth:signature.width,localCenter:{x:signature.center.x,y:-signature.center.y}}};
 function base(){return applyCommand(createNewDocument(),{type:'add-entity',entity:raster,vertices:[]});}
 it('corrected Text, rotated Symbol, category and provenance survive Search/serialization/one Undo',()=>{const d=base(),original=d.entities[0] as RasterUnderlayEntity,cs=vectorizationCommands(d,original,original,calibration,[text,symbol],new Set(['t','s']),'__new','run');let state=editorReducer(initialEditorState(d),{type:'execute-batch',commands:cs,expectedDocument:d});expect(state.error).toBeNull();expect(state.past).toHaveLength(1);const t=state.document.entities.find(e=>e.type==='text')!,s=state.document.entities.find(e=>e.type==='symbol')!;expect(t).toMatchObject({content:'ГАЗ',height:2,imageSource:{source:'image-ocr',originalText:'ГAЗ',confidence:.42}});expect(s).toMatchObject({rotationDeg:270,imageSource:{source:'image-symbol-match',candidateGroupId:'repeated',symbolId:'valve'}});expect(searchDocument(state.document,'ГАЗ').entityIds).toContain(t.id);expect(resolveDocumentQuery({kind:'semantic_concept',concepts:['gas_pipe']},state.document).groups.flatMap(g=>g.entityIds)).toContain(t.id);expect(deserializeDocument(serializeDocument(state.document))).toEqual(state.document);state=editorReducer(state,{type:'undo'});expect(state.document).toBe(d);state=editorReducer(state,{type:'redo'});expect(state.document.entities).toHaveLength(3);});
 it('known Symbol exposes standard features, moves/rotates independently of raster',()=>{const d=base(),original=d.entities[0] as RasterUnderlayEntity,cs=vectorizationCommands(d,original,original,calibration,[symbol],new Set(['s']),'boundary','run');let state=editorReducer(initialEditorState(d),{type:'execute-batch',commands:cs});expect(state.error).toBeNull();const s=state.document.entities.find(e=>e.type==='symbol')!;const features=featureIndex(state.document).summaries.get(s.id)!;expect(features.facts.some(f=>f.key==='symbolId'&&f.value==='valve')).toBe(true);const before=state.document;state=editorReducer(state,{type:'execute',command:{type:'move-entities',entityIds:[s.id],delta:{x:3,y:2}}});expect(state.error).toBeNull();expect(state.document.entities[0]).toEqual(before.entities[0]);expect(state.document.entities.find(e=>e.id===s.id)).not.toEqual(s);state=editorReducer(state,{type:'undo'});expect(state.document).toBe(before);});
 it('uses reviewed result transform without mutating source raster or its calibration',()=>{const d=base(),original=d.entities[0] as RasterUnderlayEntity,placed={...original,position:{x:100,y:200},width:96,height:64,rotationDeg:30},cs=vectorizationCommands(d,original,placed,calibration,[text],new Set(['t']),'boundary','run');const state=editorReducer(initialEditorState(d),{type:'execute-batch',commands:cs,expectedDocument:d});expect(state.error).toBeNull();expect(state.document.entities[0]).toBe(original);expect(cs.some(c=>c.type==='update-underlay')).toBe(false);expect(state.document.vertices).not.toEqual(d.vertices);});
 it('rejects unlocked invalid scaling and leaves document unchanged on failure',()=>{const d=base(),original=d.entities[0] as RasterUnderlayEntity;expect(()=>vectorizationCommands(d,original,{...original,height:16},calibration,[symbol],new Set(['s']),'boundary','run')).toThrow('равномерный');expect(d.entities).toHaveLength(1);});
});
