import { describe,it,expect } from 'vitest';
import { createNewDocument } from '../domain/newDocument';
import { hitOwners,normalHitStack,prioritizeHitOwners,resolveDeepSelection,deepSelectionMetrics } from '../editor/deepSelection';
import { viewportDocument } from '../layouts/context';
import { entityIntersectsViewport,paperDocument } from '../layouts/selection';
import { initialEditorState,editorReducer,isDocumentDirty } from '../store/editor';
import type { DxfViewport } from '../layouts/types';
import type { VectorPrimitive } from '../vectors/types';
function fixture(){const d=createNewDocument(),layerId=d.layers[0]!.id;d.vertices={a:{id:'a',x:0,y:0},b:{id:'b',x:10,y:0}};const path:VectorPrimitive={kind:'path',points:[{x:0,y:0},{x:10,y:0}],closed:false,layerId,colorMode:'bylayer'};d.blocks=[{id:'def',sourceName:'Valve',basePoint:{x:0,y:0},primitives:[path]}];d.entities=[{id:'hatch',type:'imported_graphic',name:'Background',layerId,position:{x:0,y:0},primitives:[{...path,points:[{x:-20,y:-20},{x:20,y:-20},{x:20,y:20},{x:-20,y:20}],closed:true,fill:true}],source:{kind:'dxf',sourceDocumentId:'src',originalType:'HATCH',originalLayer:'0'}},{id:'block',type:'block_instance',blockDefinitionId:'def',name:'Valve',layerId,position:{x:0,y:0},rotationDeg:0,scaleX:1,scaleY:1},{id:'line-b',type:'line',name:'Line',layerId,startVertexId:'a',endVertexId:'b'},{id:'line-a',type:'line',name:'Line',layerId,startVertexId:'a',endVertexId:'b'}];return d;}
const viewport=(frozenSourceLayerNames:string[]=[]):DxfViewport=>({id:'vp',number:2,centerPaper:{x:50,y:50},sizePaper:{width:20,height:20},modelCenter:{x:0,y:0},viewHeight:20,scale:1,twist:27,clip:{kind:'rectangle'},frozenSourceLayerNames});
describe('CAD local hit stack',()=>{
 it('editable native > block > HATCH, stable canonical ID tie independent from paint order',()=>{const d=fixture();const expected=['line-a','line-b','block','hatch'];expect(hitOwners(d,{x:5,y:0},.2,10)).toEqual(expected);const reversed={...d,entities:[...d.entities].reverse()};expect(hitOwners(reversed,{x:5,y:0},.2,10)).toEqual(expected);expect(prioritizeHitOwners(d,['hatch','block','line-b','line-a','line-a'])).toEqual(expected);});
 it('hidden objects excluded; locked geometry remains inspectable with stable selection priority',()=>{const d=fixture(),hidden={...d,entities:d.entities.map(e=>e.id==='line-a'?{...e,visible:false}:e)};expect(hitOwners(hidden,{x:5,y:0},.2,10)).not.toContain('line-a');const locked={...d,layers:d.layers.map(l=>({...l,locked:true}))};expect(hitOwners(locked,{x:5,y:0},.2,10)).toEqual(['line-a','line-b','block','hatch']);});
 it('native text and point targets outrank polygon fill and intersecting lines, including locked points',()=>{const d=fixture(),layerId=d.layers[0]!.id;d.entities.push({id:'text',type:'text',name:'Note',layerId,vertexId:'a',content:'CAD',fontSize:12,rotationDeg:0},{id:'point',type:'point',name:'P1',layerId,vertexId:'a'});expect(hitOwners(d,{x:0,y:0},.2,10).slice(0,3)).toEqual(['text','point','line-a']);const locked={...d,layers:d.layers.map(l=>({...l,locked:true}))};expect(hitOwners(locked,{x:0,y:0},.2,10).slice(0,3)).toEqual(['text','point','line-a']);});
 it('polygon interior cannot steal a block contour; polygon edge and standalone interior remain selectable',()=>{const d=fixture();d.vertices={...d.vertices,c:{id:'c',x:-20,y:-20},e:{id:'e',x:20,y:-20},f:{id:'f',x:20,y:20},g:{id:'g',x:-20,y:20}};d.entities.push({id:'boundary',type:'polygon',name:'Background boundary',layerId:d.layers[0]!.id,vertexIds:['c','e','f','g']});const ids=hitOwners(d,{x:5,y:0},.1,10);expect(ids).toEqual(['line-a','line-b','block','boundary','hatch']);expect(normalHitStack(d,ids,{x:5,y:0},.1).map(h=>h.ownerEntityId)).toEqual(ids);expect(hitOwners(d,{x:20,y:10},.1,10)[0]).toBe('boundary');expect(hitOwners(d,{x:10,y:10},.1,10)[0]).toBe('boundary');});
 it('thin block contours have the same screen pick band as native geometry and beat nested HATCH fills',()=>{const d=fixture(),layerId=d.layers[0]!.id;d.blocks!.push({id:'background-def',sourceName:'Background',basePoint:{x:0,y:0},primitives:[{kind:'path',points:[{x:-20,y:-20},{x:20,y:-20},{x:20,y:20},{x:-20,y:20}],closed:true,fill:true,layerId,colorMode:'bylayer',source:{kind:'dxf',sourceDocumentId:'src',originalType:'HATCH',originalLayer:'0'}}]});d.entities=d.entities.filter(e=>e.type==='block_instance');d.entities.push({...d.entities[0]!,id:'background-block',blockDefinitionId:'background-def'} as typeof d.entities[number]);expect(hitOwners(d,{x:5,y:.3},.7,10,true)).not.toContain('block');const ids=hitOwners(d,{x:5,y:.3},.7,10);expect(ids).toEqual(['block','background-block']);expect(normalHitStack(d,ids,{x:5,y:.3},.5).map(h=>h.ownerEntityId)).toEqual(ids);});
 it('Freeze excludes source geometry without changing global visibility',()=>{const d=fixture(),view=viewportDocument(d,viewport([d.layers[0]!.name]));expect(hitOwners(view,{x:5,y:0},.2,10)).toEqual([]);expect(d.layers[0]!.visible).toBe(true);});
 it('normal stack keeps meaningful block and visits only instance ATTRIB',()=>{const d=fixture(),block=d.entities[1]!;if(block.type!=='block_instance')throw Error();block.attributeCoordinateSpace='block-local';block.attributePrimitives=[{kind:'text',content:'V1',attributeTag:'TAG',position:{x:3,y:0},height:1,rotationDeg:0,layerId:block.layerId,colorMode:'byblock',source:{kind:'dxf',sourceDocumentId:'src',originalType:'ATTRIB',originalLayer:'0'}}];const n=deepSelectionMetrics().walks,stack=normalHitStack(d,['block'],{x:3.5,y:.5},.01);expect(stack.map(s=>s.selection?.sourceType??'Block')).toEqual(['ATTRIB','Block']);expect(resolveDeepSelection(d,stack[0]!.selection!)?.primitive).toMatchObject({content:'V1'});expect(deepSelectionMetrics().walks).toBe(n);});
 it('viewport clip rejects entirely outside geometry even with canonical identity intact',()=>{const d=fixture();const vp=viewport();expect(entityIntersectsViewport(d,d.entities[2]!,vp)).toBe(true);const outside={...d,vertices:{a:{id:'a',x:100,y:100},b:{id:'b',x:110,y:100}}};expect(entityIntersectsViewport(outside,outside.entities[2]!,vp)).toBe(false);});
 it('cycle selection is transient and never mutates source, history or dirty',()=>{const d=fixture(),state=initialEditorState(d),candidates=normalHitStack(d,hitOwners(d,{x:5,y:0},.2,10),{x:5,y:0},.2);const next=editorReducer(state,{type:'deep-select',candidate:candidates[1]!,index:1,count:candidates.length});expect(next.selectionId).toBe('line-b');expect(next.document).toBe(d);expect(next.past).toEqual(state.past);expect(isDocumentDirty(next)).toBe(false);});
 it('Paper derived ID cannot edit canonical MODEL or source primitive',()=>{const d=fixture(),layout={id:'paper',name:'Sheet',nameAvailable:true,sourceDocumentId:'src',paperSpaceOwner:'p',viewports:[viewport()],paperPrimitives:[{kind:'text' as const,content:'Sheet title',position:{x:30,y:30},height:2,rotationDeg:0,layerId:d.layers[0]!.id,colorMode:'bylayer' as const}]};d.dxfLayouts=[layout];const p=paperDocument(d,layout);expect(hitOwners(p,{x:30.5,y:30.5},.1,10)).toEqual(['paper-paper-0']);const selected=editorReducer(initialEditorState(d),{type:'select-entities',entityIds:[p.entities[0]!.id]});const blocked=editorReducer(selected,{type:'execute',command:{type:'delete-entity',entityId:'line-a'}});expect(blocked.document).toBe(d);expect(blocked.error).toContain('только для чтения');});
});
