import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const storage=new Map<string,string>();
beforeEach(()=>{vi.resetModules();storage.clear();vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});});
afterEach(()=>vi.unstubAllGlobals());
describe('browser preferences / credentials lifecycle',()=>{
 it('session key survives preference changes but is absent from browser storage and disappears on reload',async()=>{let store=await import('../preferences/store');store.setApiKey('session-only');store.updatePreferences({rightTab:'ai',gridStep:2});expect(store.getApiKey()).toBe('session-only');expect([...storage.values()].join('')).not.toContain('session-only');vi.resetModules();store=await import('../preferences/store');expect(store.getApiKey()).toBe('');expect(store.getPreferences().gridStep).toBe(2);});
 it('explicit remembered key restores separately; unchecking removes it immediately',async()=>{let store=await import('../preferences/store');store.setApiKey('device-only',true);expect(storage.get(store.PREFERENCES_KEY)).not.toContain('device-only');vi.resetModules();store=await import('../preferences/store');expect(store.getApiKey()).toBe('device-only');store.setApiKey('device-only',false);expect(storage.has(store.DEVICE_KEY)).toBe(false);vi.resetModules();expect((await import('../preferences/store')).getApiKey()).toBe('');});
 it('custom enabled/provider/models/timeout/retry restore into strict provider runtime',async()=>{let store=await import('../preferences/store');store.updatePreferences({aiCustomized:true,ai:{...store.defaultPreferences.ai,enabled:false,provider:'mock',primaryModel:'local/primary',fallbackModel:'local/fallback',timeoutMs:12000,retryCount:1}});vi.resetModules();store=await import('../preferences/store');expect(store.getPreferences().ai.timeoutMs).toBe(12000);const runtime=await import('../ai/settings');expect(()=>runtime.aiSettingsHeaders()).toThrow('AI отключён');store.updatePreferences({ai:{...store.getPreferences().ai,enabled:true}});expect(runtime.aiSettingsHeaders()).toMatchObject({'X-AI-Provider':'mock','X-AI-Primary-Model':'local/primary','X-AI-Fallback-Model':'local/fallback'});expect(runtime.aiRuntime()).toMatchObject({timeoutMs:12000,retryCount:1});store.adoptServerAiDefaults({provider:'openrouter',primaryModel:'server/other'});expect(store.getPreferences().ai.primaryModel).toBe('local/primary');});
 it('storage failure retains usable in-memory settings with an honest warning',async()=>{vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{throw new Error('quota');},removeItem:()=>{throw new Error('quota');}});const store=await import('../preferences/store');store.updatePreferences({rightTab:'search'});expect(store.getPreferences().rightTab).toBe('search');expect(store.getPreferenceStorageError()).toContain('не сохранены');store.setApiKey('memory-retained',true);expect(store.getApiKey()).toBe('memory-retained');expect(store.getPreferenceStorageError()).toContain('Ключ не сохранён');});
});
