import { describe, expect, it } from 'vitest';
import { connectorDocument,endpoint } from './fixtures/connectorDocument';
import { semanticFixture } from './fixtures/semanticLearning';
import { operationsFixture } from './fixtures/documentOperations';
import { BUILTIN_CONCEPTS, conceptsNamed, descendants } from '../semantics/concepts';
import { featureIndex } from '../semantics/features';
import { learnedMatches, proposeRule, rememberedKnowledge, removeConcept, ruleMatches } from '../semantics/learning';
import { emptyKnowledge, featureIdentity, type SemanticKnowledge, type SemanticConcept } from '../semantics/model';
import { validateSemanticKnowledge } from '../semantics/schema';
import { applyCommand } from '../domain/commands';
import { deserializeDocument, serializeDocument } from '../persistence/serialization';
import { editorReducer, initialEditorState, isDocumentDirty } from '../store/editor';
import { resolveDocumentQuery, searchDocument, defaultExcludedGroups } from '../documentOperations/query';
import { documentQuerySchema } from '../documentOperations/schema';
const pipe=BUILTIN_CONCEPTS.find(c=>c.id==='pipe')!,examples=['pipe-1','pipe-2'];
function teach(excluded:string[]=[],weak=false){const d=semanticFixture(),rule=proposeRule(d,examples,'pipe','rule').rule;return {...d,semantics:rememberedKnowledge(d,pipe,rule,new Set(excluded),new Set(weak?['EXACT','STRONG','WEAK']:['EXACT','STRONG']))};}
describe('explainable local induction',()=>{
  it('source layer beats global layer 0; mixed lengths do not become conditions',()=>{const p=proposeRule(semanticFixture(),examples,'pipe','r');expect(p.rule.conditions).toEqual([{key:'kind',value:'line'},{key:'sourceLayer',value:'_ИИ_ТРАССА_025'}]);expect([...p.rule.conditions,...p.rule.supporting].some(f=>['length','size','layer'].includes(f.key))).toBe(false);expect(p.warning).toBeNull();});
  it('Exact, Strong and Weak are deterministic with factual explanations',()=>{const d=semanticFixture(),r=proposeRule(d,examples,'pipe','r').rule,m=ruleMatches(d,r);expect(m.filter(x=>x.tier==='EXACT').map(x=>x.entityId)).toEqual(['pipe-1','pipe-2','pipe-4']);expect(m.filter(x=>x.tier==='STRONG').map(x=>x.entityId)).toEqual(['pipe-3']);expect(m.filter(x=>x.tier==='WEAK')).toHaveLength(8);expect(m.find(x=>x.entityId==='pipe-3')!.reasons.join(' ')).toContain('Исходный DXF-слой');expect(m.every(x=>!x.reasons.join(' ').includes('confidence'))).toBe(true);});
  it('broad identical kind/style/layer warns and only creates weak hints',()=>{const d=semanticFixture();d.entities=d.entities.map(e=>{const {source,style,...rest}=e;void source;void style;return rest;});const p=proposeRule(d,examples,'pipe','r');expect(p.warning).toBeTruthy();expect(ruleMatches(d,p.rule).every(m=>m.tier==='WEAK')).toBe(true);const learned={...d,semantics:rememberedKnowledge(d,pipe,p.rule,new Set(),new Set(['EXACT','STRONG']))};expect(learnedMatches(learned,'pipe').map(m=>m.entityId)).toEqual(examples);});
  it('explicit rejection wins and never changes geometry/provenance',()=>{const d=teach(['pipe-4']);expect(learnedMatches(d,'pipe').some(m=>m.entityId==='pipe-4')).toBe(false);expect(d.entities).toEqual(semanticFixture().entities);expect(d.semantics.annotations.find(a=>a.entityId==='pipe-4')).toMatchObject({polarity:'negative',source:'user-explicit'});});
  it('excluded positive example is not described as positive evidence',()=>{const d=teach(['pipe-1']);expect(d.semantics.rules[0]!.positiveExamples).toEqual(['pipe-2']);expect(learnedMatches(d,'pipe').some(m=>m.entityId==='pipe-1')).toBe(false);});
  it('reviewing and clearing an old exception restores a match',()=>{const d=teach(['pipe-4']),r=d.semantics.rules[0]!;const restored={...d,semantics:rememberedKnowledge(d,pipe,r,new Set(),new Set(['EXACT','STRONG']))};expect(learnedMatches(restored,'pipe').some(m=>m.entityId==='pipe-4')).toBe(true);});
  it('confirmed weak candidates become separate explicit confirmations',()=>{const d=teach([],true);expect(d.semantics.annotations.filter(a=>a.source==='rule-confirmed')).toHaveLength(8);expect(learnedMatches(d,'pipe').find(m=>m.entityId==='other-4')).toMatchObject({origin:'explicit',tier:'EXACT'});});
  it('disabling rule keeps only explicit examples; disabled tier stays excluded',()=>{const d=teach();d.semantics={...d.semantics,rules:d.semantics.rules.map(r=>({...r,enabled:false}))};expect(learnedMatches(d,'pipe').map(m=>m.entityId)).toEqual(examples);const strongOff=teach();strongOff.semantics.rules[0]!.enabledTiers=['EXACT'];expect(learnedMatches(strongOff,'pipe').some(m=>m.entityId==='pipe-3')).toBe(false);});
  it('invalid examples fail rather than produce a fabricated rule',()=>{expect(()=>proposeRule(semanticFixture(),[],'pipe','r')).toThrow();expect(()=>proposeRule(semanticFixture(),['missing'],'pipe','r')).toThrow();});
  it('block identity and ATTRIB schema reuse owner metadata without promoting nested primitives',()=>{const d=operationsFixture(),p=proposeRule(d,['mark-a','mark-b'],'well','r');expect(p.rule.conditions).toContainEqual({key:'blockDefinition',value:'volume'});expect(p.shared.some(s=>s.fact.key==='attributeKeys')).toBe(true);expect(ruleMatches(d,p.rule).filter(m=>m.tier!=='WEAK').map(m=>m.entityId)).toEqual(['mark-a','mark-b']);expect(featureIndex(d).summaries.size).toBe(d.entities.length);});
});
describe('normalized feature cache and topology',()=>{
  it('translation, pan, rotation, visibility and viewport context do not become identity',()=>{const d=semanticFixture(),index=featureIndex(d);expect(featureIndex({...d,semantics:emptyKnowledge()})).toBe(index);const moved={...d,vertices:Object.fromEntries(Object.entries(d.vertices).map(([id,v])=>[id,{...v,x:v.x+1e6,y:v.y-5e5}]))};expect([...featureIndex(moved).summaries.values()].map(s=>s.facts)).toEqual([...index.summaries.values()].map(s=>s.facts));expect(featureIndex({...d,viewport:{center:{x:1e8,y:1e8},pixelsPerUnit:1}})).toEqual(index);const hidden={...d,layers:d.layers.map(l=>({...l,visible:false}))};expect([...featureIndex(hidden).summaries.values()].map(s=>s.facts)).toEqual([...index.summaries.values()].map(s=>s.facts));});
  it('unchanged owners reuse summaries; one style edit invalidates one owner',()=>{const d=semanticFixture();featureIndex(d);const e=d.entities[0]!,updated={...d,entities:d.entities.map(x=>x===e?{...x,style:{...x.style,strokeColor:'#990000'}}:x)};expect(featureIndex(updated)).toMatchObject({derived:1,reused:11});});
  it('vertex edits invalidate only referenced owner and knowledge edits reuse index',()=>{const d=semanticFixture();featureIndex(d);const id='pipe-1-b',updated={...d,vertices:{...d.vertices,[id]:{...d.vertices[id]!,y:2}}};expect(featureIndex(updated)).toMatchObject({derived:1,reused:11});expect(featureIndex({...updated,semantics:emptyKnowledge()})).toBe(featureIndex(updated));});
  it('close coordinates do not imply connectivity; shared canonical endpoint does',()=>{const d=semanticFixture(),a=d.entities[0]!,b=d.entities[1]!;expect(featureIndex(d).summaries.get(a.id)!.facts).toContainEqual({key:'connections',value:'0'});if(b.type!=='line'||a.type!=='line')throw Error();const connected={...d,entities:d.entities.map(e=>e===b?{...b,startVertexId:a.endVertexId}:e)};expect(featureIndex(connected).summaries.get(a.id)!.facts).toContainEqual({key:'connectedKind',value:'line'});});
  it('small continuous noise is normalized; no feature contains absolute coordinates',()=>{const d=semanticFixture();const first=featureIndex(d).summaries.get('pipe-1')!;const noisy={...d,vertices:{...d.vertices,'pipe-1-b':{...d.vertices['pipe-1-b']!,y:1.300000001}}};expect(featureIndex(noisy).summaries.get('pipe-1')!.facts).toEqual(first.facts);expect(first.facts.some(f=>['x','y','z','entityId'].includes(f.key))).toBe(false);});
  it('canonical image geometry matches without any raster resource or pixels',()=>{const d=semanticFixture();d.entities=d.entities.map((e,i)=>i<4?{...e,imageSource:{source:'image-vectorization',sourceAssetId:'missing-local-asset',vectorizationRunId:'run',candidateType:'line'}}:e);const index=featureIndex(d);expect(index.summaries.get('pipe-1')!.facts).toContainEqual({key:'importKind',value:'image-vectorization'});expect(index.summaries.get('pipe-1')!.facts).toContainEqual({key:'imageCandidate',value:'line'});expect(proposeRule(d,examples,'pipe','r').rule.conditions).toHaveLength(2);});
});
describe('concepts, query and privacy boundary',()=>{
  it('aliases normalize Russian ё and case; child concepts inherit only declared parents',()=>{const d=teach();const custom:SemanticConcept={id:'custom',name:'Трубы продувки',aliases:['ПРОДУВКА','трубочки'],parentConceptId:'pipe'};d.semantics.concepts.push(custom);d.semantics.annotations.push({entityId:'other-4',conceptId:'custom',source:'user-explicit',polarity:'positive'});expect(conceptsNamed(d,'продувка')[0]!.id).toBe('custom');expect(descendants(d,'utilities')).toContain('custom');expect(learnedMatches(d,'pipe').some(m=>m.entityId==='other-4')).toBe(true);expect(resolveDocumentQuery({kind:'learned_concept',name:'Продувка'},d).entityIds).toEqual(['other-4']);});
  it('Search and AI share same local learned result, Weak defaults off',()=>{const d=teach(['pipe-4']),found=searchDocument(d,'трубы');expect(found.rows.map(r=>r.entityId).sort()).toEqual(['pipe-1','pipe-2','pipe-3']);expect(found.rows.every(r=>!!r.semantics)).toBe(true);expect(searchDocument(d,'трубы',undefined,true).total).toBe(11);const q=resolveDocumentQuery({kind:'semantic_concept',concepts:['pipe']},d);expect(q.groups.some(g=>g.tier==='WEAK')).toBe(true);expect(defaultExcludedGroups(q)).toHaveLength(1);});
  it('scope filters owners and unknown concepts fail closed',()=>{const d=teach();expect(searchDocument(d,'трубы',new Set(['pipe-2'])).rows.map(r=>r.entityId)).toEqual(['pipe-2']);expect(resolveDocumentQuery({kind:'learned_concept',name:'Неизвестная категория'},d).error).toContain('Сначала научите');});
  it('wire schema accepts static intent/custom name but forbids rules or entity IDs',()=>{expect(documentQuerySchema.parse({kind:'semantic_concept',concepts:['pipe']})).toMatchObject({kind:'semantic_concept'});expect(documentQuerySchema.parse({kind:'learned_concept',name:'Трубы продувки'})).toMatchObject({name:'Трубы продувки'});expect(()=>documentQuerySchema.parse({kind:'learned_concept',name:'Трубы продувки',entityIds:examples})).toThrow();expect(()=>documentQuerySchema.parse({kind:'semantic_concept',concepts:['pipe'],rules:[]})).toThrow();});
});
describe('canonical persistence and commands',()=>{
  it('atomic semantic command changes only knowledge; Undo/Redo restore entire knowledge',()=>{const d=semanticFixture(),knowledge=teach().semantics;let s=editorReducer(initialEditorState(d),{type:'execute',expectedDocument:d,command:{type:'set-semantic-knowledge',knowledge}});expect(s.error).toBeNull();expect(s.past).toHaveLength(1);expect(s.document.entities).toBe(d.entities);expect(s.document.vertices).toBe(d.vertices);expect(isDocumentDirty(s)).toBe(true);s=editorReducer(s,{type:'undo'});expect(s.document).toBe(d);s=editorReducer(s,{type:'redo'});expect(s.document.semantics).toEqual(knowledge);});
  it('JSON round trip preserves transparent rule, concepts and negatives',()=>{const d=teach(['pipe-4']);expect(deserializeDocument(serializeDocument(d))).toEqual(d);expect(deserializeDocument(serializeDocument(semanticFixture())).semantics).toBeUndefined();});
  it('delete cleans references; Undo restores them, rule identity survives edits',()=>{const d=teach(['pipe-4']);let s=editorReducer(initialEditorState(d),{type:'execute',command:{type:'delete-entity',entityId:'pipe-1'}});expect(s.document.semantics!.annotations.some(a=>a.entityId==='pipe-1')).toBe(false);expect(s.document.semantics!.rules[0]!.positiveExamples).toEqual(['pipe-2']);expect(()=>serializeDocument(s.document)).not.toThrow();s=editorReducer(s,{type:'undo'});expect(s.document).toBe(d);});
  it('no-op knowledge is history-free and stale commands fail',()=>{const d=teach();expect(applyCommand(d,{type:'set-semantic-knowledge',knowledge:d.semantics})).toBe(d);const s=editorReducer(initialEditorState(d),{type:'execute',expectedDocument:{...d},command:{type:'set-semantic-knowledge',knowledge:emptyKnowledge()}});expect(s.document).toBe(d);expect(s.past).toHaveLength(0);});
  it('knowledge does not auto-apply to an unrelated import',()=>{const a=teach(),b=semanticFixture();expect(learnedMatches(a,'pipe').length).toBeGreaterThan(0);expect(learnedMatches(b,'pipe')).toEqual([]);});
  it('category deletion removes metadata and preserves geometry; parents with children cannot be removed',()=>{const d=teach();expect(removeConcept(d,'pipe').rules).toEqual([]);d.semantics.concepts.push({id:'parent',name:'Parent',aliases:[]},{id:'child',name:'Child',aliases:[],parentConceptId:'parent'});expect(()=>removeConcept(d,'parent')).toThrow('дочерних');expect(d.entities).toHaveLength(12);});
  it.each(['cycle','alias','missing-owner','missing-concept','duplicate-rule','duplicate-fact'] as const)('rejects malformed %s knowledge atomically',kind=>{const d=teach(),k=structuredClone(d.semantics) as SemanticKnowledge;if(kind==='cycle')k.concepts[0]!.parentConceptId='pipe';if(kind==='alias')k.concepts.push({id:'x',name:'x',aliases:['трубы']});if(kind==='missing-owner')k.annotations[0]!.entityId='absent';if(kind==='missing-concept')k.rules[0]!.conceptId='absent';if(kind==='duplicate-rule')k.rules.push(k.rules[0]!);if(kind==='duplicate-fact')k.rules[0]!.conditions.push(k.rules[0]!.conditions[0]!);expect(()=>validateSemanticKnowledge({...d,semantics:k})).toThrow();expect(()=>applyCommand(d,{type:'set-semantic-knowledge',knowledge:k})).toThrow();});
  it('facts use collision-free key/value identity',()=>{expect(featureIdentity({key:'layer',value:'a:b'})).not.toBe(featureIdentity({key:'sourceLayer',value:'a:b'}));});
});

describe('symbols, incremental metadata and result bounds',()=>{
  it('library symbol identity and real port peers are metadata, not rendered geometry',()=>{const d=connectorDocument(),index=featureIndex(d);expect(index.summaries.get('valve')!.facts).toContainEqual({key:'symbolId',value:'shutoff-valve'});expect(index.summaries.get('connection')!.facts).toContainEqual({key:'connectedKind',value:'symbol:gas-process-demo/shutoff-valve'});expect(index.summaries.get('valve')!.facts).toContainEqual({key:'connectedKind',value:'connector'});});
  it('connector retarget refreshes topology and preserves unchanged owner summaries',()=>{const d=connectorDocument();featureIndex(d);const next=applyCommand(d,{type:'retarget-connector',entityId:'connection',endpoint:'end',target:endpoint('regulator','in')});expect(featureIndex(next)).toMatchObject({derived:1,reused:5});expect(featureIndex(next).summaries.get('connection')!.facts).toContainEqual({key:'connectedKind',value:'symbol:gas-process-demo/pressure-regulator'});expect(featureIndex(next).summaries.get('filter')!.facts).toContainEqual({key:'connections',value:'0'});});
  it('symbol properties affect only changed owner and movement does not change identity',()=>{const d=connectorDocument();featureIndex(d);const e=d.entities[0]!;if(e.type!=='symbol')throw Error();const next={...d,entities:d.entities.map(x=>x===e?{...e,position:{x:100,y:200},properties:{code:'A'}}:x)};expect(featureIndex(next)).toMatchObject({derived:1,reused:5});expect(featureIndex(next).summaries.get(e.id)!.facts).toContainEqual({key:'symbolProperty',value:'code=A'});});
  it('ATTRIB updates invalidate own tokens and preserve other owner cache',()=>{const d=operationsFixture();featureIndex(d);const e=d.entities.find(e=>e.id==='mark-a')!;if(e.type!=='block_instance')throw Error();const next={...d,entities:d.entities.map(x=>x===e?{...e,attributes:{NAME:'Новое значение'},attributePrimitives:[]}:x)};expect(featureIndex(next)).toMatchObject({derived:1,reused:7});expect(featureIndex(next).summaries.get(e.id)!.facts).toContainEqual({key:'textToken',value:'новое'});});
  it('layer/style edits and block transform changes recompute relevant facts',()=>{const d=semanticFixture();featureIndex(d);const layerId=d.entities[0]!.layerId,next={...d,layers:d.layers.map(l=>l.id===layerId?{...l,name:'Обновлённый слой'}:l)};expect(featureIndex(next).summaries.get('pipe-1')!.facts).toContainEqual({key:'layer',value:'Обновлённый слой'});const block=operationsFixture();featureIndex(block);const e=block.entities[0]!;if(e.type!=='block_instance')throw Error();const resized={...block,entities:block.entities.map(x=>x===e?{...e,scaleX:8,scaleY:8}:x)};expect(featureIndex(resized)).toMatchObject({derived:1,reused:7});expect(featureIndex(resized).summaries.get(e.id)!.facts).toContainEqual({key:'size',value:'8–16'});});
  it('different entity type on a matching source layer is only a weak hint',()=>{const d=semanticFixture(),first=d.entities[0]!;d.entities.push({id:'text-source',name:'text-source',type:'text',layerId:first.layerId,vertexId:'pipe-1-a',content:'Неизвестно',fontSize:12,source:first.source!});const rule=proposeRule(d,examples,'pipe','r').rule;expect(ruleMatches(d,rule).find(m=>m.entityId==='text-source')!.tier).toBe('WEAK');});
  it('Search returns all owner IDs while rendering only first 100 rows',()=>{const original=teach(),d={...original,entities:[...original.entities,...Array.from({length:120},(_,i)=>({...original.entities[0]!,id:`clone-${i}`,name:`clone-${i}`}))]};const found=searchDocument(d,'трубы');expect(found.total).toBe(124);expect(found.entityIds).toHaveLength(124);expect(found.rows).toHaveLength(100);});
  it('canonical knowledge never classifies derived Paper-owned search rows',()=>{const d=teach(),first=d.entities[0]!,merged={...d,entities:[...d.entities,{...first,id:'paper-derived'}]};expect(searchDocument(merged,'трубы',undefined,false,d).entityIds).not.toContain('paper-derived');});
});

it('three selected DXF polylines of different lengths propose peer polylines; text on same layer remains Weak',()=>{const d=semanticFixture();d.entities=d.entities.map((e,i)=>{if(i>=4||e.type!=='line')return e;const{type,startVertexId,endVertexId,...rest}=e;void type;return {...rest,type:'polyline' as const,vertexIds:[startVertexId,endVertexId] as [string,string]};});const e=d.entities[0]!;d.entities.push({id:'same-layer-text',name:'same-layer-text',type:'text',layerId:e.layerId,vertexId:'pipe-1-a',content:'Неизвестное назначение',fontSize:12,source:e.source!});const r=proposeRule(d,['pipe-1','pipe-2','pipe-3'],'pipe','poly-rule').rule;expect(r.conditions).toEqual([{key:'kind',value:'polyline'},{key:'sourceLayer',value:'_ИИ_ТРАССА_025'}]);expect(r.supporting.some(f=>f.key==='length')).toBe(false);expect(ruleMatches(d,r).filter(m=>m.tier==='EXACT').map(m=>m.entityId)).toEqual(['pipe-1','pipe-2','pipe-3','pipe-4']);expect(ruleMatches(d,r).find(m=>m.entityId==='same-layer-text')!.tier).toBe('WEAK');});
