import { describe, expect, it } from 'vitest';
import { spatialDocument } from './fixtures/spatialDocument';
import { moveDocument } from './fixtures/moveDocument';
import { resolveEntityReference, entityNameIndex, type EntityReferenceContext } from '../ai/entityReferences';
import { aiTaskSchema, validateParserResult, type AiAction, type EntityReference } from '../ai/intent';
import { resolveAiTaskPlan, taskCommands, taskPreviews } from '../ai/task';
import { spatialFrame, spatialRectangle, offsetPolygonSide, rectangleCorners } from '../geometry/spatialLayout';
import { bounds, worldToScreen } from '../geometry';
import { entityPoints, type GeoDocument } from '../domain/model';
import { initialEditorState, editorReducer, isDocumentDirty } from '../store/editor';
import { applicationReducer, mutationExecutionGate, type ApplicationState } from '../ai/workflow';
import { marqueeEntities } from '../editor/marquee';
import { createHorizontalReference } from '../geometry/georeferencing';
const named:EntityReference={kind:'named_entity',name:'Дом'};
const rectangle=(reference:EntityReference=named,direction='east'):AiAction=>({type:'create_rectangle',name:'Сарай',width:3,height:5,placement:{type:'relative_to_entity',reference,direction:direction as 'east',gapMeters:2}});
const array:AiAction={type:'create_rectangle_array',nameBase:'Грядка',count:4,width:1,height:4,reference:named,direction:'south',itemGap:.8};
const edge:AiAction={type:'create_line_along_polygon_edge',name:'Газовая труба',reference:{kind:'named_entity',name:'Участок'},side:'west',offsetMeters:1.5,offsetSide:'outside'};
function context(d=spatialDocument(),selectionEntityIds:readonly string[]=[]):EntityReferenceContext{return {baseDocument:d,projectedDocument:d,outputs:new Map(),choices:new Map(),selectionEntityIds};}
function plan(actions:AiAction[],d=spatialDocument(),options:Parameters<typeof resolveAiTaskPlan>[3]={}) {return resolveAiTaskPlan({actions},d,new Map(),options);}
function preview(actions:AiAction[],d=spatialDocument(),layer='boundary',selection:string[]=[]):ApplicationState {
  let app:ApplicationState={editor:{...initialEditorState(d),currentLayerId:layer,selectedEntityIds:selection},ai:{status:'idle'}};
  app=applicationReducer(app,{type:'ai-event',event:{type:'start',id:'spatial',text:'test'}});
  return applicationReducer(app,{type:'ai-event',event:{type:'result',id:'spatial',result:{actions}}});
}
function current(app:ApplicationState){if(app.ai.status!=='preview'&&app.ai.status!=='stale')throw Error('preview');return app.ai.plan;}
describe('local object references',()=>{
  it('canonical exact normalized names; no fuzzy selection',()=>{const d=spatialDocument();expect(resolveEntityReference({kind:'named_entity',name:'  дОм '},context(d))).toMatchObject({status:'resolved',entity:{id:'house'}});expect(resolveEntityReference({kind:'named_entity',name:'Дома'},context(d)).status).toBe('unresolved');expect(entityNameIndex(d.entities).get('дом')).toHaveLength(1);});
  it('duplicate chooser metadata and stale explicit choices',()=>{const d=spatialDocument();d.entities.push({...d.entities[0]!,id:'second'});const ctx=context(d);expect(resolveEntityReference(named,ctx)).toMatchObject({status:'unresolved',issues:[{name:'entity:дом',scope:'entity',candidates:[{entityType:'polygon',layer:'Здания',bounds:{minX:7,maxX:13}},{entityId:'second'}]}]});expect(resolveEntityReference(named,{...ctx,choices:new Map([['entity:дом','second']])})).toMatchObject({status:'resolved',entity:{id:'second'}});expect(resolveEntityReference(named,{...ctx,choices:new Map([['entity:дом','absent']])}).status).toBe('invalid');});
  it.each([0,1,2])('current selection %i',n=>expect(resolveEntityReference({kind:'current_selection'},context(spatialDocument(),['house','site'].slice(0,n))).status).toBe(n===1?'resolved':n===0?'unresolved':'invalid'));
  it('compatible polygon required for inside/edge',()=>{const d=spatialDocument();d.entities.push({id:'pt',type:'point',name:'P',layerId:'survey-points',vertexId:'p'});expect(resolveEntityReference({kind:'named_entity',name:'P'},context(d),true).status).toBe('unresolved');});
  it('one named choice shared across actions without a provider',()=>{const d=spatialDocument();d.entities.push({...d.entities[0]!,id:'second'});const app=preview([rectangle(),array],d);expect(current(app).resolution.status).toBe('unresolved');const chosen=applicationReducer(app,{type:'ai-choose',name:'entity:дом',entityId:'second'});expect(current(chosen).resolution.status).toBe('ready');expect(current(chosen).referenceEntityIds).toEqual(['second']);expect(chosen.editor.document).toBe(d);expect(chosen.editor.past).toHaveLength(0);});
});
describe('deterministic directions',()=>{
  it('absent georeference MODEL',()=>expect(spatialFrame(spatialDocument())).toMatchObject({name:'MODEL',stale:false}));
  function survey(){const d=spatialDocument();d.entities.push({type:'point',id:'ca',name:'A',layerId:'survey-points',vertexId:'p'},{type:'point',id:'cb',name:'B',layerId:'survey-points',vertexId:'q'});const ref=createHorizontalReference(d,[{pointEntityId:'ca',survey:{e:0,n:0}},{pointEntityId:'cb',survey:{e:0,n:20}}]);d.horizontalReference=ref;return d;}
  it('valid Survey rotation maps east to MODEL south; stale -> MODEL',()=>{const d=survey(),frame=spatialFrame(d);expect(frame.name).toBe('SURVEY');expect(frame.from({x:1,y:0}).y).toBeCloseTo(-1,10);const result=plan([rectangle()],d);expect(result.resolution.status).toBe('ready');const b=bounds(entityPoints(result.projectedDocument!.entities.at(-1)!,result.projectedDocument!.vertices))!;expect(b.maxY).toBeCloseTo(10,10);d.vertices.p!.x=1;expect(spatialFrame(d)).toMatchObject({name:'MODEL',stale:true});expect(plan([rectangle()],d).assumptions).toEqual(expect.arrayContaining([expect.objectContaining({message:expect.stringContaining('устарела')})]));});
  it.each([['east',15,12],['west',2,12],['north',8.5,19],['south',8.5,5],['north_east',15,19],['south_west',2,5]] as const)('%s nearest-extents gap', (direction,x,y)=>{const r=spatialRectangle(rectangleCorners({x:7,y:12},6,5),3,5,direction,spatialFrame(spatialDocument()),false,2);expect(r).toMatchObject({status:'ready',origin:{x,y},gap:2});});
  it.each(['center','north','west'] as const)('inside %s reuses AutoPlacement',anchor=>{const d=spatialDocument(),r=plan([{type:'create_rectangle',name:'Дом',width:6,height:5,placement:{type:'inside_entity',reference:{kind:'named_entity',name:'Участок'},anchor}}],d);expect(r.resolution.status).toBe('ready');const b=bounds(entityPoints(r.projectedDocument!.entities.at(-1)!,r.projectedDocument!.vertices))!;expect(b).toMatchObject(anchor==='north'?{minX:7,minY:24,maxY:29}:anchor==='west'?{minX:1,minY:12.5}:{minX:7,minY:12.5});});
  it('concave contour exact containment blocks a bounding-box-only fit',()=>{const p=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:6,y:10},{x:6,y:4},{x:4,y:4},{x:4,y:10},{x:0,y:10}];expect(spatialRectangle(p,4,4,'north',spatialFrame(spatialDocument()),true).status).toBe('invalid');});
  it('missing gap uses central sketch policy with visible assumption',()=>{const a=rectangle();if(a.type!=='create_rectangle'||a.placement.type!=='relative_to_entity')throw Error();delete a.placement.gapMeters;expect(plan([a]).assumptions).toEqual([expect.objectContaining({message:expect.stringContaining('Auto, эскизный')})]);});
});
describe('offset side and arrays',()=>{
  it.each([['west',-1.5,0,-1.5,30],['north',0,31.5,20,31.5],['east',21.5,0,21.5,30],['south',0,-1.5,20,-1.5]] as const)('%s side exact parallel offset',(side,x,y,X,Y)=>{const r=offsetPolygonSide(rectangleCorners({x:0,y:0},20,30),side,1.5,true,spatialFrame(spatialDocument()));expect(r.status).toBe('ready');if(r.status==='ready')expect(bounds(r.geometry)).toEqual({minX:x,minY:y,maxX:X,maxY:Y});});
  it('excessive inward offset rejects geometry outside the polygon',()=>expect(offsetPolygonSide(rectangleCorners({x:0,y:0},20,30),'west',21,false,spatialFrame(spatialDocument())).status).toBe('invalid'));
  it('inside and reversed orientation preserve meaning',()=>{const p=rectangleCorners({x:0,y:0},20,30).reverse();const r=offsetPolygonSide(p,'west',1.5,false,spatialFrame(spatialDocument()));if(r.status!=='ready')throw Error();expect(bounds(r.geometry)!.minX).toBe(1.5);});
  it('ambiguous separated west sides reject; collinear chain supported',()=>{const p=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10},{x:0,y:7},{x:3,y:7},{x:3,y:3},{x:0,y:3}];expect(offsetPolygonSide(p,'west',1,false,spatialFrame(spatialDocument())).status).toBe('invalid');const q=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10},{x:0,y:5}];const r=offsetPolygonSide(q,'west',1,true,spatialFrame(spatialDocument()));expect(r.status).toBe('ready');if(r.status==='ready')expect(r.geometry).toHaveLength(3);});
  it.each(['north','south','east','west'] as const)('four rectangles %s exact gaps and whole group centering',direction=>{const r=plan([{...array,direction} as AiAction]);expect(r.resolution.status).toBe('ready');expect(taskCommands(r)).toHaveLength(4);expect(taskPreviews(r)).toHaveLength(4);const d=r.projectedDocument!,created=d.entities.slice(-4),boxes=created.map(e=>bounds(entityPoints(e,d.vertices))!);expect(created.map(e=>e.name)).toEqual(['Грядка 1','Грядка 2','Грядка 3','Грядка 4']);for(let i=1;i<4;i++)expect(direction==='north'||direction==='south'?boxes[i]!.minX-boxes[i-1]!.maxX:boxes[i]!.minY-boxes[i-1]!.maxY).toBeCloseTo(.8,10);const b=bounds(created.flatMap(e=>entityPoints(e,d.vertices)))!;expect(direction==='north'||direction==='south'?(b.minX+b.maxX)/2:(b.minY+b.maxY)/2).toBeCloseTo(direction==='north'||direction==='south'?10:14.5,10);});
  it.each([0,51,1.5])('array count %i rejected',count=>expect(aiTaskSchema.safeParse({actions:[{...array,count}]}).success).toBe(false));
  it('50 allowed, expansion budget enforced across actions',()=>{expect(plan([{...array,count:50} as AiAction]).generatedCommandCount).toBe(50);expect(plan([1,2,3].map(i=>({...array,nameBase:`Грядка${i}`,count:50} as AiAction))).resolution.status).toBe('invalid');});
  it('prior result stable projected geometry and strict backward references',()=>{const site:AiAction={type:'create_rectangle',name:'Участок',width:20,height:30,placement:{type:'local_origin'}};expect(plan([site,rectangle({kind:'prior_action_result',actionIndex:0})]).resolution.status).toBe('ready');expect(aiTaskSchema.safeParse({actions:[rectangle({kind:'prior_action_result',actionIndex:0})]}).success).toBe(false);});
  it('new provider schema validates sizes and rejects additional runtime fields',()=>{expect(validateParserResult({actions:[array]},'Четыре грядки 1×4 м с промежутком 0,8')).toMatchObject({actions:[{count:4}]});expect(()=>validateParserResult({actions:[{...array,width:9}]},'Четыре грядки 1×4')).toThrow();expect(aiTaskSchema.safeParse({actions:[{...edge,layerId:'bad'}]}).success).toBe(false);});
});
describe('AI target layer and atomic history',()=>{
  const actions:AiAction[]=[{type:'create_points',points:[{name:'P1',x:1,y:1},{name:'P2',x:2,y:2}]},{type:'create_rectangle',name:'Дом',width:6,height:5,placement:{type:'center',x:50,y:50}},{type:'create_dimensions_for_boundary_edges',boundaryActionIndex:1},edge,array,{type:'create_polyline_from_named_points',pointNames:['P1','P2']}];
  it('all created points/polygons/polyline/dimensions share captured current layer, unchanged sources; switch local',()=>{const d=spatialDocument(),app=preview(actions,d,'annotations');expect(current(app).resolution.status).toBe('ready');for(const e of current(app).projectedDocument!.entities.slice(d.entities.length))expect(e.layerId).toBe('annotations');const switched=applicationReducer(app,{type:'ai-target-layer',layerId:'buildings'});expect(switched.editor).toBe(app.editor);expect(isDocumentDirty(switched.editor)).toBe(false);const applied=applicationReducer(switched,{type:'ai-apply'});expect(applied.editor.past).toHaveLength(1);expect(applied.editor.document.entities.slice(0,2)).toEqual(d.entities);expect(applied.editor.document.entities.slice(2).every(e=>e.layerId==='buildings')).toBe(true);expect(applicationReducer(applied,{type:'undo'}).editor.document).toBe(d);});
  it.each(['locked','visible'] as const)('captured invalid %s layer blocks, repaired by explicit switch',property=>{const d=spatialDocument();d.layers.find(l=>l.id==='annotations')![property]=property==='locked';const app=preview([array],d,'annotations');expect(current(app).resolution.status).toBe('invalid');expect(mutationExecutionGate(current(app),app.editor).status).toBe('blocked');expect(current(applicationReducer(app,{type:'ai-target-layer',layerId:'boundary'})).resolution.status).toBe('ready');});
  it('capture at start despite current layer changes during generation',()=>{const d=spatialDocument();let app:ApplicationState={editor:initialEditorState(d),ai:{status:'idle'}};app=applicationReducer(app,{type:'ai-event',event:{type:'start',id:'capture',text:'array'}});app=applicationReducer(app,{type:'select-layer',layerId:'buildings'});app=applicationReducer(app,{type:'ai-event',event:{type:'result',id:'capture',result:{actions:[array]}}});expect(current(app).targetLayerId).toBe('boundary');});
  it('selection changes invalidate preview and refresh captures current selection without LLM',()=>{const app=preview([rectangle({kind:'current_selection'})],spatialDocument(),'boundary',['house']);const next=applicationReducer(app,{type:'select',entityId:'site'});expect(next.ai.status).toBe('stale');expect(mutationExecutionGate(current(next),next.editor).status).toBe('refreshed');const refreshed=applicationReducer(next,{type:'ai-refresh'});expect(current(refreshed).selectionEntityIds).toEqual(['site']);expect(current(refreshed).referenceEntityIds).toEqual(['site']);});
});
describe('marquee selection pure and transient',()=>{
  const viewport={center:{x:0,y:0},pixelsPerUnit:10},size={width:1000,height:800};
  function select(d:GeoDocument,a:{x:number;y:number},b:{x:number;y:number}){return marqueeEntities(d,viewport,size,worldToScreen(a,viewport,size),worldToScreen(b,viewport,size));}
  it('Window includes point/path/polygon, rejects partial crossing line/polygon',()=>{const d=moveDocument();expect(select(d,{x:-6,y:8},{x:7,y:-4})).toEqual(expect.arrayContaining(['house','line','point']));expect(select(d,{x:-1,y:2},{x:3,y:-1})).not.toContain('house');expect(select(d,{x:-1,y:2},{x:3,y:-1})).not.toContain('line');});
  it('Crossing intersects line/polygon and filled containment',()=>{const d=moveDocument();expect(select(d,{x:3,y:2},{x:-1,y:-1})).toEqual(expect.arrayContaining(['house','line']));expect(select(d,{x:4,y:4},{x:2,y:2})).toContain('house');});
  it('annotation and rendered Dimension bounds selected, hidden excluded',()=>{const d=moveDocument();expect(select(d,{x:8,y:10},{x:16,y:4})).toContain('text');expect(select(d,{x:-5,y:9},{x:10,y:-5})).toEqual(expect.arrayContaining(['label','dim-0']));d.layers.find(l=>l.id==='annotations')!.visible=false;expect(select(d,{x:-20,y:20},{x:20,y:-20})).not.toContain('label');});
  it('Crossing rectangle contained inside Text bounds selects',()=>expect(select(moveDocument(),{x:10,y:7.5},{x:9.5,y:7.2})).toContain('text'));
  it('replace/add/toggle preserve ordered points, no history/dirty; cancel retains selection',()=>{const d=moveDocument();let s=editorReducer(initialEditorState(d),{type:'select',entityId:'control-b',toggle:true});s=editorReducer(s,{type:'finish-marquee',mode:'add',entityIds:['point','control-a','house']});expect(s.orderedPointIds).toEqual(['control-b','point','control-a']);s=editorReducer(s,{type:'finish-marquee',mode:'toggle',entityIds:['point','house','text']});expect(s.selectedEntityIds).toEqual(['control-b','control-a','text']);const prior=s;s=editorReducer(editorReducer(s,{type:'begin-marquee'}),{type:'cancel-marquee'});expect(s.selectedEntityIds).toBe(prior.selectedEntityIds);expect(s.document).toBe(d);expect(s.past).toHaveLength(0);expect(isDocumentDirty(s)).toBe(false);s=editorReducer(s,{type:'finish-marquee',mode:'replace',entityIds:['house']});expect(s.selectedEntityIds).toEqual(['house']);expect(s.orderedPointIds).toEqual([]);});
});
