import { describe, expect, it } from 'vitest';
import { analyzeTopology } from '../topology/analyze';
import { resolvedRoute, topologyCommands } from '../topology/apply';
import { analysisRequest } from '../topology/scope';
import { applyCommand, applyCommandsAtomically } from '../domain/commands';
import { connectorRoute, connectivityIndex } from '../connectors/model';
import { serializeDocument, deserializeDocument } from '../persistence/serialization';
import { editorReducer, initialEditorState, isDocumentDirty } from '../store/editor';
import { addPath, processFixtureDocument, topologyFixture } from './fixtures/topology';
import { proposeRule, rememberedKnowledge } from '../semantics/learning';
import { resolveDocumentQuery, searchDocument } from '../documentOperations/query';
import { emptyKnowledge } from '../semantics/model';
import type { RouteReview } from '../topology/types';
const scope={kind:'layer' as const,layerId:'buildings'},confirmed:RouteReview={status:'confirmed'};
describe('explainable topology A–H',()=>{
 it('A traces one complete route to two existing ports, no mutation',()=>{const d=topologyFixture(),before=JSON.stringify(d),g=analyzeTopology(d,scope);expect(g.routes).toHaveLength(1);expect(g.routes[0]!.classification).toBe('STRONG');expect(g.nodes.filter(n=>n.kind==='symbol_port')).toHaveLength(2);expect(JSON.stringify(d)).toBe(before);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).entity?.routing).toBe('direct');});
 it('B requires choosing between two nearby canonical ports',()=>{const d=topologyFixture('B'),g=analyzeTopology(d,scope),r=g.routes[0]!;expect(r.startOptions).toHaveLength(2);expect(r.classification).toBe('AMBIGUOUS');expect(resolvedRoute(d,g,r,confirmed).reason).toContain('Выберите порты');expect(resolvedRoute(d,g,r,{...confirmed,start:r.startOptions.find(p=>p.endpoint.portId==='out')!.endpoint}).entity).toBeDefined();});
 it('C true T proposes geometric junction, does not invent an engineering tee',()=>{const d=topologyFixture('C'),g=analyzeTopology(d,scope);expect(g.findings.filter(f=>f.kind==='junction')).toHaveLength(1);expect(g.findings.find(f=>f.kind==='junction')!.evidence[0]).toContain('Три');expect(g.routes[0]!.branched).toBe(true);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('Ветвление');expect(()=>topologyCommands(d,g,{'route-0':confirmed})).toThrow();});
 it('D X remains disconnected and ambiguous; crossing decision preserves original route; connected stays geometry',()=>{const d=topologyFixture('D'),g=analyzeTopology(d,scope),x=g.findings.find(f=>f.kind==='crossing')!;expect(x.classification).toBe('AMBIGUOUS');expect(g.findings.some(f=>f.kind==='junction')).toBe(false);expect(g.routes[0]!.points).toHaveLength(3);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('пересечения');const reviewed=analyzeTopology(d,scope,{crossings:{[x.id]:'crossing'}});expect(resolvedRoute(d,reviewed,reviewed.routes[0]!,confirmed).entity).toBeDefined();const connected=analyzeTopology(d,scope,{crossings:{[x.id]:'connected'}});expect(connected.routes[0]!.branched).toBe(true);expect(resolvedRoute(d,connected,connected.routes[0]!,confirmed).entity).toBeUndefined();});
 it('E small collinear gap requires explicit repair and separate route confirmation',()=>{const d=topologyFixture('E'),g=analyzeTopology(d,scope),gap=g.findings.find(f=>f.kind==='gap')!;expect(g.routes).toHaveLength(0);expect(gap.distance).toBeCloseTo(.04);expect(gap.classification).toBe('AMBIGUOUS');const repaired=analyzeTopology(d,scope,{gaps:{[gap.id]:true}});expect(repaired.routes).toHaveLength(1);expect(repaired.routes[0]!.classification).toBe('AMBIGUOUS');expect(resolvedRoute(d,repaired,repaired.routes[0]!,confirmed).entity).toBeDefined();expect(analyzeTopology(d,scope,{gaps:{[gap.id]:false}}).routes).toHaveLength(0);});
 it('F large gap is not repaired/proposed',()=>{const g=analyzeTopology(topologyFixture('F'),scope);expect(g.findings.filter(f=>f.kind==='gap')).toHaveLength(0);expect(g.routes).toHaveLength(0);expect(g.findings.filter(f=>f.kind==='free')).toHaveLength(2);});
 it('G incompatible process/instrument ports produce rejection',()=>{const d=topologyFixture('G'),g=analyzeTopology(d,scope);expect(g.routes[0]!.classification).toBe('REJECTED');expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('Несовместимые');});
 it('H complex polyline cannot be straightened or deleted',()=>{const d=topologyFixture('H'),before=serializeDocument(d),g=analyzeTopology(d,scope);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('не сохраняет форму');expect(()=>topologyCommands(d,g,{'route-0':confirmed})).toThrow();expect(serializeDocument(d)).toBe(before);});
});
describe('canonical integration and conservative scope',()=>{
 it('Apply and one Undo restore exactly; redo/reload provenance and symbol associativity',()=>{const d=processFixtureDocument(),g=analyzeTopology(d,scope),reviews=Object.fromEntries(g.routes.map(r=>[r.id,confirmed])),commands=topologyCommands(d,g,reviews);let state=initialEditorState(d);state=editorReducer(state,{type:'execute-batch',commands,expectedDocument:d});expect(state.document.entities.filter(e=>e.type==='connector')).toHaveLength(4);expect(state.document.entities.filter(e=>e.type==='line')).toHaveLength(0);expect(state.past).toHaveLength(1);expect(isDocumentDirty(state)).toBe(true);const applied=state.document;expect(connectivityIndex(applied).bySymbol.get('s2')).toHaveLength(2);const reopened=deserializeDocument(serializeDocument(applied));expect(reopened).toEqual(applied);const c=reopened.entities.find(e=>e.type==='connector')!;expect(c.topologySource?.sourceGeometryIds).toEqual(['path0']);const moved=applyCommand(reopened,{type:'set-symbol-position',entityId:'s0',position:{x:0,y:2}});expect(connectorRoute(moved,c)[0]!.y).toBe(2);expect(()=>applyCommand(reopened,{type:'delete-entity',entityId:'s0'})).toThrow('подключения');state=editorReducer(state,{type:'undo'});expect(state.document).toEqual(d);state=editorReducer(state,{type:'redo'});expect(state.document).toEqual(applied);});
 it('preview/cancel does not mutate dirty/history/autosave document',()=>{const d=topologyFixture(),state=initialEditorState(d);analyzeTopology(d,scope);expect(isDocumentDirty(state)).toBe(false);expect(state.past).toEqual([]);expect(state.document).toBe(d);});
 it('shared vertex confirms junction rather than fake probability',()=>{const d=topologyFixture('C');d.entities=d.entities.filter(e=>e.id!=='route'&&e.id!=='branch');addPath(d,'a',[{x:1,y:0},{x:4,y:0}],['v0','join']);addPath(d,'b',[{x:4,y:0},{x:7,y:0}],['join','v1']);addPath(d,'c',[{x:4,y:0},{x:4,y:3}],['join','v2']);expect(analyzeTopology(d,scope).findings.find(f=>f.kind==='junction')!.classification).toBe('CONFIRMED');});
 it('fragments trace one route and replace all owners together',()=>{const d=topologyFixture('E');d.vertices['right-v0']!.x=4;const g=analyzeTopology(d,scope),r=g.routes[0]!;expect(r.sourceGeometryIds).toHaveLength(2);expect(applyCommandsAtomically(d,topologyCommands(d,g,{[r.id]:confirmed})).entities.filter(e=>e.type==='connector')).toHaveLength(1);});
 it('large translated MODEL coordinates do not change topology',()=>{const d=topologyFixture();for(const v of Object.values(d.vertices)){v.x+=3e6;v.y+=6e6;}for(const e of d.entities)if(e.type==='symbol'){e.position.x+=3e6;e.position.y+=6e6;}expect(analyzeTopology(d,scope).routes[0]!.classification).toBe('STRONG');});
 it('rotated/scaled ports use canonical world transform',()=>{const d=topologyFixture();d.entities=d.entities.filter(e=>e.type==='symbol');for(const e of d.entities)if(e.type==='symbol'){e.rotationDeg=90;e.scale=2;e.position={x:0,y:e.id==='valve'?0:12};}addPath(d,'route',[{x:0,y:2},{x:0,y:10}]);const g=analyzeTopology(d,scope);expect(g.routes[0]!.classification).toBe('STRONG');expect(g.routes[0]!.endOptions[0]!.point.y).toBe(10);});
 it('occupied port cannot become reconstructed connector',()=>{const d=topologyFixture(),g=analyzeTopology(d,scope),applied=applyCommandsAtomically(d,topologyCommands(d,g,{'route-0':confirmed}));addPath(applied,'again',[{x:1,y:0},{x:7,y:0}]);const again=analyzeTopology(applied,scope);expect(again.routes[0]!.classification).toBe('REJECTED');expect(resolvedRoute(applied,again,again.routes[0]!,confirmed).entity).toBeUndefined();});
 it('label/shared dimension prevents source replacement',()=>{const d=topologyFixture();d.entities.push({id:'dim',name:'dim',type:'dimension',layerId:'dimensions',startVertexId:'route-v0',endVertexId:'route-v1',offset:1});const g=analyzeTopology(d,scope);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('общие вершины');});
 it('locks prevent destructive replacement',()=>{const d=topologyFixture();d.layers.find(l=>l.id==='buildings')!.locked=true;const g=analyzeTopology(d,scope);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('незаблокированный');});
 it('selected / layer / bounded / import group scopes never default to whole drawing',()=>{const d=topologyFixture();addPath(d,'far',[{x:100,y:0},{x:200,y:0}]);expect(()=>analyzeTopology(d,{kind:'selection',ids:[]})).toThrow('Не найдено');expect(analyzeTopology(d,{kind:'selection',ids:['route']}).diagnostics.geometryCount).toBe(1);expect(analyzeTopology(d,{kind:'area',bounds:{minX:0,minY:-1,maxX:10,maxY:1}}).diagnostics.geometryCount).toBe(1);d.entities.find(e=>e.id==='route')!.imageSource={source:'pdf-vector',sourceAssetId:'pdf',vectorizationRunId:'r1',candidateType:'line'};expect(analyzeTopology(d,{kind:'image-group',runId:'r1'}).diagnostics.geometryCount).toBe(1);expect(analysisRequest(d,scope,{}).document.blocks).toEqual([]);});
 it('explicit learned concept scope; weak OCR-only rule is excluded; semantic annotation survives replacement',()=>{const d=topologyFixture();d.semantics={...emptyKnowledge(),annotations:[{entityId:'route',conceptId:'pipe',source:'user-explicit',polarity:'positive'}]};const g=analyzeTopology(d,{kind:'concept',conceptId:'pipe'}),applied=applyCommandsAtomically(d,topologyCommands(d,g,{'route-0':confirmed}));expect(applied.semantics!.annotations).toHaveLength(1);expect(applied.semantics!.annotations[0]!.entityId).toBe(applied.entities.find(e=>e.type==='connector')!.id);const untagged={...d,semantics:{...d.semantics,annotations:[]}};expect(()=>analyzeTopology(untagged,{kind:'concept',conceptId:'pipe'})).toThrow('Не найдено');});
 it('no symbols still reports neutral local geometry',()=>{const d=topologyFixture('C');d.entities=d.entities.filter(e=>e.type!=='symbol');const g=analyzeTopology(d,scope);expect(g.routes).toHaveLength(0);expect(g.findings.some(f=>f.kind==='junction')).toBe(true);expect(g.warnings[0]).toContain('Нет подтверждённых символов');});
 it('non-collinear nearby ends never create gap repair',()=>{const d=topologyFixture('E');d.vertices['right-v1']!.y=2;expect(analyzeTopology(d,scope).findings.some(f=>f.kind==='gap')).toBe(false);});
 it('bounded sparse process geometry uses indexed pairs, not N squared',()=>{const d=topologyFixture();d.entities=[];d.vertices={};for(let i=0;i<1000;i++)addPath(d,`p${i}`,[{x:i*10,y:0},{x:i*10+2,y:0}]);const g=analyzeTopology(d,scope);expect(g.diagnostics.geometryCount).toBe(1000);expect(g.diagnostics.pairChecks).toBe(0);expect(g.edges).toHaveLength(1000);});
 it('unshared coincident polyline X vertices remain ambiguous until a crossing choice',()=>{const d=topologyFixture();d.entities=d.entities.filter(e=>e.type==='symbol');addPath(d,'a',[{x:1,y:0},{x:4,y:0},{x:7,y:0}]);addPath(d,'b',[{x:4,y:-3},{x:4,y:0},{x:4,y:3}]);const g=analyzeTopology(d,scope),x=g.findings.find(f=>f.kind==='crossing')!;expect(x.classification).toBe('AMBIGUOUS');expect(g.findings.some(f=>f.kind==='junction')).toBe(false);expect(g.routes).toHaveLength(1);expect(g.routes[0]!.classification).toBe('AMBIGUOUS');const reviewed=analyzeTopology(d,scope,{crossings:{[x.id]:'crossing'}});expect(resolvedRoute(d,reviewed,reviewed.routes[0]!,confirmed).entity).toBeDefined();});
 it('explicit incompatible categories never merge coincident endpoints',()=>{const d=topologyFixture('E');d.vertices['right-v0']!.x=4;d.semantics={...emptyKnowledge(),annotations:[{entityId:'left',conceptId:'pipe',polarity:'positive',source:'user-explicit'},{entityId:'right',conceptId:'cable',polarity:'positive',source:'user-explicit'}]};expect(analyzeTopology(d,scope).routes).toHaveLength(0);});
 it('collinear overlap cannot be destructively converted',()=>{const d=topologyFixture();addPath(d,'duplicate',[{x:3,y:0},{x:5,y:0}]);const g=analyzeTopology(d,scope);expect(g.findings.some(f=>f.classification==='REJECTED')).toBe(true);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).reason).toContain('Наложение');});
 it('multiple independent endpoints competing for one port are never bulk strong',()=>{const d=topologyFixture();addPath(d,'near',[{x:1,y:.001},{x:7,y:.001}]);const g=analyzeTopology(d,scope);expect(g.routes).toHaveLength(2);expect(g.routes.every(r=>r.classification==='AMBIGUOUS')).toBe(true);expect(()=>topologyCommands(d,g,Object.fromEntries(g.routes.map(r=>[r.id,confirmed])))).toThrow('конфликтуют');});
 it('same source visual style is preserved; differing segment styles prevent replacement',()=>{const d=topologyFixture();d.entities.find(e=>e.id==='route')!.style={strokeColor:'#123456',lineType:'dashed'};const g=analyzeTopology(d,scope);expect(resolvedRoute(d,g,g.routes[0]!,confirmed).entity?.style?.strokeColor).toBe('#123456');const split=topologyFixture('E');split.vertices['right-v0']!.x=4;split.entities.find(e=>e.id==='left')!.style={strokeColor:'#123456'};const sg=analyzeTopology(split,scope);expect(resolvedRoute(split,sg,sg.routes[0]!,confirmed).reason).toContain('разные стили');});
 it('source metric resolution survives underlay removal/resize',()=>{const d=topologyFixture();d.vertices['route-v0']!.x=1.04;d.entities.find(e=>e.id==='route')!.imageSource={source:'image-vectorization',sourceAssetId:'deleted-underlay',vectorizationRunId:'run',candidateType:'line',modelUnitsPerPixel:.01};const g=analyzeTopology(d,scope);expect(g.diagnostics.tolerances.port).toBe(.06);expect(g.routes).toHaveLength(1);});
 it('worker payload is scoped before cloning and has no Paper/definitions',()=>{const d=topologyFixture();for(let i=0;i<1000;i++)addPath(d,`far${i}`,[{x:100+i,y:100},{x:102+i,y:100}]);const input=analysisRequest(d,{kind:'selection',ids:['route']},{});expect(input.document.entities.filter(e=>e.type==='line')).toHaveLength(1);expect(Object.keys(input.document.vertices)).toHaveLength(2);expect(input.document.dxfLayouts).toEqual([]);});
 it('image-internal geometry is suppressed without deleting canonical sources',()=>{const d=topologyFixture();const symbol=d.entities.find(e=>e.id==='valve')!;symbol.imageSource={source:'image-symbol-match',sourceAssetId:'asset',vectorizationRunId:'run',candidateType:'symbol'};addPath(d,'internal',[{x:-.2,y:.1},{x:.2,y:.1}]);d.entities.find(e=>e.id==='internal')!.imageSource={source:'image-vectorization',sourceAssetId:'asset',vectorizationRunId:'run',candidateType:'line'};const before=serializeDocument(d),g=analyzeTopology(d,scope);expect(g.diagnostics.suppressed).toBe(1);expect(serializeDocument(d)).toBe(before);});

 it('reconstructed connectors reuse Teach/Search/local AI resolver and regular retarget index',()=>{const d=processFixtureDocument(),g=analyzeTopology(d,scope),applied=applyCommandsAtomically(d,topologyCommands(d,g,Object.fromEntries(g.routes.map(r=>[r.id,confirmed])))),c=applied.entities.find(e=>e.type==='connector')!,concept={id:'learned-links',name:'Связи скана',aliases:[]},rule=proposeRule(applied,[c.id],concept.id,'rule-links').rule,knowledge=rememberedKnowledge(applied,concept,rule,new Set(),new Set(['EXACT','STRONG'])),taught=applyCommand(applied,{type:'set-semantic-knowledge',knowledge});expect(searchDocument(taught,'Связи скана').entityIds).toContain(c.id);expect(resolveDocumentQuery({kind:'learned_concept',name:'Связи скана',scope:'document'},taught).entityIds).toContain(c.id);const retarget=applyCommand(taught,{type:'retarget-connector',entityId:c.id,endpoint:'start',target:{kind:'symbol_port',symbolEntityId:'s0',portId:'in'}});expect(connectivityIndex(retarget).byPort.has(JSON.stringify(['s0','in']))).toBe(true);const moved=applyCommand(retarget,{type:'update-entity',entityId:'s0',patch:{rotationDeg:90,scale:2}}),route=connectorRoute(moved,moved.entities.find(e=>e.id===c.id) as typeof c);expect(route[0]!.y).toBe(-2);});

 it('T review can confirm transient branch or reject only proposed junction without deleting branch',()=>{const d=topologyFixture('C'),g=analyzeTopology(d,scope),j=g.findings.find(f=>f.kind==='junction')!,accepted=analyzeTopology(d,scope,{junctions:{[j.id]:true}});expect(accepted.findings.find(f=>f.kind==='junction')!.classification).toBe('CONFIRMED');expect(resolvedRoute(d,accepted,accepted.routes[0]!,confirmed).entity).toBeUndefined();const rejected=analyzeTopology(d,scope,{junctions:{[j.id]:false}}),commands=topologyCommands(d,rejected,{'route-0':confirmed}),applied=applyCommandsAtomically(d,commands);expect(applied.entities.some(e=>e.id==='branch')).toBe(true);expect(applied.entities.filter(e=>e.type==='connector')).toHaveLength(1);});

 it('compatible parent/child network categories connect; siblings remain separate despite shared generic parent',()=>{const d=topologyFixture('E');d.vertices['right-v0']!.x=4;const annotations=[{entityId:'left',conceptId:'pipe',polarity:'positive' as const,source:'user-explicit' as const},{entityId:'right',conceptId:'gas_pipe',polarity:'positive' as const,source:'user-explicit' as const}];d.semantics={...emptyKnowledge(),annotations};expect(analyzeTopology(d,scope).routes).toHaveLength(1);const conflict={...d,semantics:{...d.semantics,annotations:[{...annotations[0]!,conceptId:'pipe'},{...annotations[1]!,conceptId:'cable'},{...annotations[0]!,conceptId:'utilities'},{...annotations[1]!,conceptId:'utilities'}]}};expect(analyzeTopology(conflict,scope).routes).toHaveLength(0);});
 it('nonzero-Z symbols are not attached to planar source geometry',()=>{const d=topologyFixture();for(const e of d.entities)if(e.type==='symbol')e.position.z=5;expect(analyzeTopology(d,scope).routes).toHaveLength(0);});

});
