import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {BlockDefinitions} from '../renderer/VectorView';
import {EntityView} from '../renderer/EntityView';
import { describe,it,expect,vi,afterEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { IDBFactory } from 'fake-indexeddb';
import { createNewDocument } from '../domain/newDocument';
import type { RasterUnderlayEntity } from '../domain/model';
import { importDxf } from '../dxf/import';
import { layerCounts,selectedLayerCounts,filterLayers } from '../layouts/layers';
import { currentViewEntityIds,viewportDocument } from '../layouts/context';
import { editorReducer,initialEditorState,editorViewDocument,isDocumentDirty } from '../store/editor';
import { validateDocument } from '../persistence/documentSchema';
import { serializeDocument,deserializeDocument } from '../persistence/serialization';
import { applyCommand } from '../domain/commands';
import { underlayCorners,underlayContains,resizeUnderlay } from '../assets/underlay';
import { imageHeader,assetRegistry,IMAGE_LIMITS } from '../assets/registry';
import { drawSelectionContours } from '../renderer/selectionContourDrawing';
import { selectionBounds, renderItems } from '../renderer/selectors';
import { hitOwners,createHitStack } from '../editor/deepSelection';
import { applyDocumentPlan,resolveDocumentPlan,isDocumentPlanStale } from '../documentOperations/plan';
import { applicationReducer } from '../ai/workflow';
import { searchDocument } from '../documentOperations/query';
import { projectedOwnerBounds } from '../view/geometry';
function layoutDoc(){const b=readFileSync('src/tests/fixtures/dxf/layouts.dxf');return importDxf(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'layouts.dxf').document;}
const size={width:800,height:600};
const underlay=():RasterUnderlayEntity=>({id:'image',type:'raster_underlay',name:'Plan image',layerId:'boundary',assetId:'asset-test',position:{x:0,y:0},width:20,height:10,rotationDeg:0,opacity:.4,locked:false});
const rasterDoc=()=>{const d=createNewDocument();d.entities=[underlay()];return d;};
function png(w:number,h:number){const b=new Uint8Array(32);b.set([137,80,78,71,13,10,26,10]);b.set([73,72,68,82],12);const v=new DataView(b.buffer);v.setUint32(16,w);v.setUint32(20,h);return b;}
function jpeg(){return new Uint8Array([255,216,255,192,0,8,8,0,10,0,20,1,255,217]);}
function webp(){const b=new Uint8Array(30);b.set(new TextEncoder().encode('RIFF'),0);b.set(new TextEncoder().encode('WEBPVP8X'),8);new DataView(b.buffer).setUint32(16,10,true);b[24]=19;b[27]=9;return b;}
afterEach(()=>vi.unstubAllGlobals());
describe('layer viewing operations',()=>{
 it('counts only top-level owners and caches the index',()=>{const d=layoutDoc();expect([...layerCounts(d).values()].reduce((a,b)=>a+b,0)).toBe(3);expect(layerCounts(d)).toBe(layerCounts({...d}));});
 it('empty panel filter never mutates visibility',()=>{const d=layoutDoc(),before=serializeDocument(d);expect(filterLayers(d.layers,layerCounts(d),new Map(),'','all',true)).toHaveLength(3);expect(serializeDocument(d)).toBe(before);});
 it('visible filter',()=>{const d=layoutDoc();d.layers[1]!.visible=false;expect(filterLayers(d.layers,layerCounts(d),new Map(),'','visible',false)).toHaveLength(3);});
 it('hidden filter',()=>{const d=layoutDoc();d.layers[1]!.visible=false;expect(filterLayers(d.layers,layerCounts(d),new Map(),'','hidden',false)).toHaveLength(1);});
 it('selected filter',()=>{const d=layoutDoc();expect(filterLayers(d.layers,layerCounts(d),selectedLayerCounts(d,[d.entities[0]!.id]),'','selected',false)).toHaveLength(1);});
 it('Cyrillic search is case insensitive',()=>{const d=layoutDoc();d.layers[0]!.name='_ГП_ЗИС';expect(filterLayers(d.layers,new Map(),new Map(),'гп_зис','all',false)).toHaveLength(1);});
 it('hide all is one history entry, including locked layers',()=>{let s=initialEditorState(layoutDoc());s.document.layers[0]!.locked=true;s=editorReducer(s,{type:'execute-batch',commands:s.document.layers.map(l=>({type:'set-layer-visibility',layerId:l.id,visible:false}))});expect(s.document.layers.every(l=>!l.visible)).toBe(true);expect(s.past).toHaveLength(1);});
 it('show all and undo restore visibility exactly',()=>{let s=initialEditorState(layoutDoc());s.document.layers[1]!.visible=false;const before=s.document;s=editorReducer(s,{type:'execute-batch',commands:s.document.layers.map(l=>({type:'set-layer-visibility',layerId:l.id,visible:true}))});expect(s.document.layers.every(l=>l.visible)).toBe(true);expect(editorReducer(s,{type:'undo'}).document).toBe(before);});
 it('selected layer isolation is view-only and preserves global hidden',()=>{const d=layoutDoc();d.layers[1]!.visible=false;const s=editorReducer(initialEditorState(d),{type:'isolate-layers',layerIds:[d.layers[1]!.id],label:'selected'});expect(editorViewDocument(s).layers.every(l=>!l.visible)).toBe(true);expect(s.document).toBe(d);expect(s.past).toHaveLength(0);});
 it('exit isolation restores exact document and visibility',()=>{const d=layoutDoc(),s=editorReducer(editorReducer(initialEditorState(d),{type:'isolate-layers',layerIds:[d.layers[1]!.id],label:'selected'}),{type:'exit-isolation'});expect(editorViewDocument(s)).toBe(d);expect(isDocumentDirty(s)).toBe(false);});
 it('panel filter does not dirty document or add history',()=>{const s=editorReducer(initialEditorState(layoutDoc()),{type:'layer-panel-filter',filter:'nonempty'});expect(isDocumentDirty(s)).toBe(false);expect(s.past).toHaveLength(0);});
});
describe('DXF layouts and current view',()=>{
 it('imports exact layout names and paper settings',()=>{const ls=layoutDoc().dxfLayouts!;expect(ls.map(l=>l.name)).toEqual(['A','B']);expect(ls[0]!.paper).toEqual({width:200,height:120,units:'mm'});});
 it('imports paper content separately from MODEL entities',()=>{const d=layoutDoc();expect(d.entities).toHaveLength(3);expect(d.dxfLayouts![0]!.paperPrimitives).toHaveLength(1);});
 it('imports multiple viewports',()=>{expect(layoutDoc().dxfLayouts!.map(l=>l.viewports.length)).toEqual([2,1]);});
 it('resolves frozen layer handles to source names',()=>{expect(layoutDoc().dxfLayouts![0]!.viewports[0]!.frozenSourceLayerNames).toEqual(['UTILITY']);});
 it('viewport A1 shows BUILDING and ROAD',()=>{const d=layoutDoc();expect(renderItems(viewportDocument(d,d.dxfLayouts![0]!.viewports[0]!)).map(i=>i.layer.name)).toEqual(['BUILDING','ROAD']);});
 it('viewport B shows BUILDING and UTILITY',()=>{const d=layoutDoc();expect(renderItems(viewportDocument(d,d.dxfLayouts![1]!.viewports[0]!)).map(i=>i.layer.name)).toEqual(['BUILDING','UTILITY']);});
 it('global hidden remains hidden in every viewport',()=>{const d=layoutDoc();d.layers[1]!.visible=false;expect(renderItems(viewportDocument(d,d.dxfLayouts![1]!.viewports[0]!)).map(i=>i.layer.name)).toEqual(['UTILITY']);});
 it('same layout has distinct freeze overrides per viewport',()=>{const d=layoutDoc(),l=d.dxfLayouts![0]!;expect(viewportDocument(d,l.viewports[0]!).layers.map(l=>l.visible)).not.toEqual(viewportDocument(d,l.viewports[1]!).layers.map(l=>l.visible));});
 it('layout switch creates no dirty/history/global visibility change',()=>{const d=layoutDoc(),s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});expect(s.document).toBe(d);expect(s.past).toHaveLength(0);expect(isDocumentDirty(s)).toBe(false);});
 it('viewport switch is view state only',()=>{const d=layoutDoc();let s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});s=editorReducer(s,{type:'dxf-viewport',viewportId:d.dxfLayouts![0]!.viewports[1]!.id});expect(s.dxfViewportId).toBe(d.dxfLayouts![0]!.viewports[1]!.id);expect(isDocumentDirty(s)).toBe(false);expect(s.past).toHaveLength(0);});
 it('layout auto-enters Plan and Model restores Axon camera',()=>{const d=layoutDoc(),axon=editorReducer(initialEditorState(d),{type:'view-mode',mode:'axonometric',orientation:'NW',size}),paper=editorReducer(axon,{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});expect(paper.viewMode).toBe('plan');const model=editorReducer(paper,{type:'dxf-layout',layoutId:null,size});expect(model.viewMode).toBe('axonometric');expect(model.viewport).toEqual(axon.viewport);});
 it('paper camera zoom and Fit never alter the MODEL camera or history',()=>{const d=layoutDoc();let s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});const model=s.viewport;s=editorReducer(s,{type:'layout-camera',viewport:{center:{x:100,y:60},pixelsPerUnit:3}});s=editorReducer(s,{type:'zoom',factor:2,anchor:{x:400,y:300},size});expect(s.layoutViewport!.pixelsPerUnit).toBe(6);expect(s.viewport).toBe(model);expect(s.document).toBe(d);expect(s.past).toHaveLength(0);expect(editorReducer(s,{type:'fit-view',size}).layoutViewport).toBeNull();});
 it('layout owner isolation still respects global hidden layers',()=>{const d=layoutDoc();d.layers[1]!.visible=false;const s=editorReducer(initialEditorState(d),{type:'isolate-entities',entityIds:[d.entities[0]!.id],label:'owner'});expect(renderItems(editorViewDocument(s))).toHaveLength(1);expect(renderItems(editorViewDocument(s,d,true))).toHaveLength(0);expect(currentViewEntityIds({...s,layoutId:d.dxfLayouts![0]!.id},editorViewDocument(s,d,true)).size).toBe(0);});
 it('current view respects clipping bounds',()=>{const d=layoutDoc();d.vertices[d.entities[0]!.type==='line'?d.entities[0].startVertexId:'']!.x=1000;d.vertices[d.entities[0]!.type==='line'?d.entities[0].endVertexId:'']!.x=1010;const s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});expect(currentViewEntityIds(s,d).has(d.entities[0]!.id)).toBe(false);});
 it('unsupported clipping is explicit and not treated as visible',()=>{const d=layoutDoc();d.dxfLayouts![0]!.viewports[0]!.unsupportedReason='unsupported';const s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size});expect(currentViewEntityIds(s,d).size).toBe(0);});
 it('nonzero twist converts DCS center using the inverse MODEL rotation',()=>{const text=readFileSync('src/tests/fixtures/dxf/layouts.dxf','utf8').replaceAll('12\n0\n22\n0\n','12\n10\n22\n0\n').replaceAll('51\n0\n','51\n90\n'),d=importDxf(new TextEncoder().encode(text).buffer,'twist.dxf').document,v=d.dxfLayouts![0]!.viewports[0]!;expect(v.modelCenter.x).toBeCloseTo(0);expect(v.modelCenter.y).toBeCloseTo(-10);});
 it('layout metadata roundtrips JSON',()=>{const d=layoutDoc();expect(deserializeDocument(serializeDocument(d)).dxfLayouts).toEqual(d.dxfLayouts);});
});
describe('AI search, selection and private scope',()=>{
 it('find leaves selection and camera unchanged',()=>{const d=layoutDoc(),s=editorReducer(initialEditorState(d),{type:'select',entityId:d.entities[1]!.id}),p=resolveDocumentPlan([{type:'find_entities',query:{kind:'entity_type',entityType:'line'}}],d,s.selectedEntityIds,'find','find');const result=applyDocumentPlan(p,s,size);expect(result.selectedEntityIds).toEqual(s.selectedEntityIds);expect(result.viewport).toBe(s.viewport);});
 it('find persists transient query results after Apply, without real selection',()=>{const d=layoutDoc(),p=resolveDocumentPlan([{type:'find_entities',query:{kind:'entity_type',entityType:'line'}}],d,[],'find','find');const result=applicationReducer({editor:initialEditorState(d),ai:{status:'document-preview',plan:p,notice:null}},{type:'document-apply',size});expect(result.editor.selectedEntityIds).toEqual([]);expect(result.ai).toMatchObject({status:'document-applied',resultPlan:{matchedEntityIds:p.matchedEntityIds}});});
 it('select uses real editor selection',()=>{const d=layoutDoc(),s=initialEditorState(d),p=resolveDocumentPlan([{type:'select_entities',query:{kind:'entity_type',entityType:'line'}}],d,[],'sel','select');const result=applyDocumentPlan(p,s,size);expect(result.selectedEntityIds).toEqual(d.entities.map(e=>e.id));expect(result.past).toHaveLength(0);});
 it('current-layout scope resolves locally',()=>{const d=layoutDoc(),s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size}),p=resolveDocumentPlan([{type:'select_entities',query:{kind:'entity_type',entityType:'line',scope:'current_view'}}],d,[],'scope','select',undefined,s);expect(p.matchedEntityIds).toHaveLength(2);expect(JSON.stringify(p.actions[0]!.intent)).not.toContain(d.entities[0]!.id);});
 it('unscoped query still searches whole document',()=>{const d=layoutDoc(),p=resolveDocumentPlan([{type:'select_entities',query:{kind:'entity_type',entityType:'line'}}],d,[],'all','select');expect(p.matchedEntityIds).toHaveLength(3);});
 it('viewport change makes a scoped preview stale',()=>{const d=layoutDoc(),s=editorReducer(initialEditorState(d),{type:'dxf-layout',layoutId:d.dxfLayouts![0]!.id,size}),p=resolveDocumentPlan([{type:'select_entities',query:{kind:'entity_type',entityType:'line',scope:'current_view'}}],d,[],'scope','select',undefined,s);expect(isDocumentPlanStale(p,editorReducer(s,{type:'dxf-viewport',viewportId:d.dxfLayouts![0]!.viewports[1]!.id}))).toBe(true);});
 it('local search can filter by current-view IDs',()=>{const d=layoutDoc();expect(searchDocument(d,'LINE',new Set([d.entities[0]!.id])).total).toBe(1);});
});
describe('raster domain and budgets',()=>{
 it.each([['PNG',png(20,10),'image/png'],['JPEG',jpeg(),'image/jpeg'],['WebP',webp(),'image/webp']])('reads %s dimensions before decode',(_,b,mime)=>expect(imageHeader(b as Uint8Array)).toEqual({mimeType:mime,width:20,height:10}));
 it('rejects excessive decoded pixels before decode',()=>expect(()=>imageHeader(png(10000,10000))).toThrow('лимит'));
 it('rejects excessive dimensions before decode',()=>expect(()=>imageHeader(png(100000,1))).toThrow('лимит'));
 it('rejects SVG and unknown image types',()=>expect(()=>imageHeader(new TextEncoder().encode('<svg/>'))).toThrow());
 it('rejects animated WebP',()=>{const b=webp();b[20]=2;expect(()=>imageHeader(b)).toThrow('Анимированный');});
 it('creates canonical raster with no vertex references in one history entry',()=>{const s=editorReducer(initialEditorState(createNewDocument()),{type:'execute',command:{type:'add-entity',entity:underlay(),vertices:[]}});expect(s.error).toBeNull();expect(s.document.entities[0]).toEqual(underlay());expect(s.past).toHaveLength(1);});
 it('validates raster entity with missing asset reference',()=>expect(validateDocument(rasterDoc()).entities[0]).toEqual(underlay()));
 it.each([-1,1.01,NaN])('rejects invalid opacity %s',opacity=>{const d=rasterDoc();d.entities[0]={...underlay(),opacity};expect(()=>validateDocument(d)).toThrow();});
 it('opacity transaction adds exactly one history action',()=>{let s=initialEditorState(rasterDoc());s=editorReducer(s,{type:'begin-transaction'});for(const opacity of [.2,.3,.4])s=editorReducer(s,{type:'transient',command:{type:'update-underlay',entityId:'image',patch:{opacity}}});expect(s.past).toHaveLength(0);s=editorReducer(s,{type:'commit-transaction'});expect(s.past).toHaveLength(1);expect((s.document.entities[0] as RasterUnderlayEntity).opacity).toBe(.4);});
 it('Plan move translates canonical center',()=>expect((applyCommand(rasterDoc(),{type:'move-entities',entityIds:['image'],delta:{x:5,y:2}}).entities[0] as RasterUnderlayEntity).position).toEqual({x:5,y:2}));
 it('relink updates persisted asset metadata together with its reference',()=>{const metadata={mimeType:'image/png' as const,originalName:'replacement.png',byteSize:200,widthPx:20,heightPx:10};const e=applyCommand(rasterDoc(),{type:'update-underlay',entityId:'image',patch:{assetId:'replacement',assetMetadata:metadata}}).entities[0];expect(e).toMatchObject({assetId:'replacement',assetMetadata:metadata});});
 it('rotation affects outline and hit testing',()=>{const e={...underlay(),rotationDeg:90};expect(underlayContains(e,{x:0,y:9})).toBe(true);expect(underlayContains(e,{x:9,y:0})).toBe(false);expect(underlayCorners(e)[0]!.x).toBeCloseTo(-5);});
 it('corner resize preserves aspect and opposite corner',()=>{const e=underlay(),patch=resizeUnderlay(e,1,{x:20,y:15}),next={...e,...patch};expect(next.width/next.height).toBe(2);expect(underlayCorners(next)[3]).toEqual(underlayCorners(e)[3]);});
 it('Shift resize allows nonuniform scale',()=>{const patch=resizeUnderlay(underlay(),1,{x:20,y:15},false);expect(patch.width/patch.height).toBe(1.5);});
 it('locked raster refuses move and accepts explicit unlock',()=>{const d=rasterDoc();d.entities[0]={...underlay(),locked:true};expect(()=>applyCommand(d,{type:'move-entities',entityIds:['image'],delta:{x:1,y:0}})).toThrow('заблокирован');expect((applyCommand(d,{type:'update-underlay',entityId:'image',patch:{locked:false}}).entities[0] as RasterUnderlayEntity).locked).toBe(false);});
 it('locked raster does not steal normal click',()=>{const d=rasterDoc();d.entities[0]={...underlay(),locked:true};expect(hitOwners(d,{x:0,y:0},1)).toEqual([]);});
 it('unlocked raster also yields normal clicks to CAD geometry',()=>{const d=rasterDoc();d.vertices={a:{id:'a',x:-10,y:0},b:{id:'b',x:10,y:0}};d.entities.unshift({id:'cad',name:'CAD',type:'line',layerId:'boundary',startVertexId:'a',endVertexId:'b'});expect(hitOwners(d,{x:0,y:0},1)[0]).toBe('cad');});
 it('JSON stores references without pixel/base64 data',()=>{const json=serializeDocument(rasterDoc());expect(json).toContain('asset-test');expect(json).not.toContain('base64');expect(deserializeDocument(json).entities[0]).toEqual(underlay());});
 it('Axon projects raster ground-plane bounds',()=>expect(projectedOwnerBounds(rasterDoc(),underlay(),{orientation:'NE',origin:{x:0,y:0,z:0}})).not.toBeNull());
 it('rejects excessive file bytes before decode',async()=>{vi.stubGlobal('createImageBitmap',vi.fn());await expect(assetRegistry.import({size:IMAGE_LIMITS.bytes+1} as File)).rejects.toThrow('40 MiB');expect(createImageBitmap).not.toHaveBeenCalled();});
 it('shared bitmap consumers release only the last reference and GC preserves undo assets',async()=>{vi.stubGlobal('indexedDB',new IDBFactory());const close=vi.fn();vi.stubGlobal('createImageBitmap',vi.fn(async()=>({width:20,height:10,close})));const bytes=png(20,10),a=await assetRegistry.import({size:bytes.length,name:'history.png',arrayBuffer:async()=>bytes.buffer} as File);assetRegistry.retain(a.assetId);assetRegistry.retain(a.assetId);assetRegistry.releaseBitmap(a.assetId);await Promise.resolve();expect(close).not.toHaveBeenCalled();assetRegistry.releaseBitmap(a.assetId);await Promise.resolve();expect(close).toHaveBeenCalledTimes(1);const before=rasterDoc();before.entities[0]={...underlay(),assetId:a.assetId};const deleted=applyCommand(before,{type:'delete-entity',entityId:'image'});await assetRegistry.collect([deleted,before]);expect(await assetRegistry.get(a.assetId)).toBeDefined();await assetRegistry.collect([]);expect(await assetRegistry.get(a.assetId)).toBeUndefined();});
 it('stores decoded EXIF orientation dimensions while validating raw pixel budgets',async()=>{vi.stubGlobal('indexedDB',new IDBFactory());vi.stubGlobal('createImageBitmap',vi.fn(async()=>({width:10,height:20,close:vi.fn()})));const bytes=jpeg(),a=await assetRegistry.import({size:bytes.length,name:'oriented.jpg',arrayBuffer:async()=>bytes.buffer} as File);expect(a).toMatchObject({widthPx:10,heightPx:20,mimeType:'image/jpeg'});assetRegistry.releaseBitmap(a.assetId);const b=await assetRegistry.bitmap(a.assetId);expect(b).toMatchObject({width:10,height:20});await assetRegistry.remove(a.assetId);});
 it('IndexedDB asset, shared references, decoded cache and explicit GC',async()=>{vi.stubGlobal('indexedDB',new IDBFactory());const close=vi.fn(),decoder=vi.fn(async()=>({width:20,height:10,close}));vi.stubGlobal('createImageBitmap',decoder);const bytes=png(20,10),file={size:bytes.length,name:'test.png',arrayBuffer:async()=>bytes.buffer} as File,a=await assetRegistry.import(file);expect((await assetRegistry.get(a.assetId))?.blob.size).toBe(bytes.length);await assetRegistry.bitmap(a.assetId);await assetRegistry.bitmap(a.assetId);expect(decoder).toHaveBeenCalledTimes(1);const d=rasterDoc();d.entities[0]={...underlay(),assetId:a.assetId};await assetRegistry.collect([d]);expect(await assetRegistry.get(a.assetId)).toBeDefined();await assetRegistry.collect([]);expect(await assetRegistry.get(a.assetId)).toBeUndefined();expect(close).toHaveBeenCalledTimes(1);expect(await assetRegistry.bitmap('missing')).toBeNull();});
});
describe('selection contours',()=>{
 function ctx(){return {clearRect:vi.fn(),save:vi.fn(),restore:vi.fn(),beginPath:vi.fn(),moveTo:vi.fn(),lineTo:vi.fn(),closePath:vi.fn(),stroke:vi.fn(),fill:vi.fn(),strokeText:vi.fn(),translate:vi.fn(),rotate:vi.fn()} as unknown as CanvasRenderingContext2D;}
 function blockDoc(){const d=createNewDocument(),l=d.layers[0]!.id;d.blocks=[{id:'b',sourceName:'B',basePoint:{x:0,y:0},primitives:[{kind:'path',layerId:l,colorMode:'bylayer',points:[{x:0,y:0},{x:10,y:0},{x:10,y:10}],closed:true}]}];d.entities=[{id:'b1',name:'B',layerId:l,type:'block_instance',blockDefinitionId:'b',position:{x:0,y:0},rotationDeg:0,scaleX:1,scaleY:1}];return d;}
 it('block owner highlights actual contour',()=>{const d=blockDoc(),c=ctx();drawSelectionContours(c,d,renderItems(d),d.viewport,size);expect(c.lineTo).toHaveBeenCalledTimes(2);expect(c.stroke).toHaveBeenCalledTimes(2);});
 it('multi-selection walks each owner without separate bounds',()=>{const d=blockDoc();d.entities.push({...d.entities[0]!,id:'b2'});const c=ctx();drawSelectionContours(c,d,renderItems(d),d.viewport,size);expect(c.stroke).toHaveBeenCalledTimes(4);});
 it('HATCH highlights edges without fill',()=>{const d=blockDoc();d.blocks![0]!.primitives[0]={...d.blocks![0]!.primitives[0]!,kind:'path',points:[{x:0,y:0},{x:10,y:0},{x:0,y:10}],closed:true,fill:true,fillGroup:'h'};const c=ctx();drawSelectionContours(c,d,renderItems(d),d.viewport,size);expect(c.fill).not.toHaveBeenCalled();expect(c.stroke).toHaveBeenCalled();});
 it('selection respects hidden nested geometry',()=>{const d=blockDoc();d.blocks![0]!.primitives[0]!.visible=false;const c=ctx();drawSelectionContours(c,d,renderItems(d),d.viewport,size);expect(c.stroke).not.toHaveBeenCalled();});
 it('combined group bounds include both owners, without individual primary boxes',()=>{const d=blockDoc();d.entities.push({...d.entities[0]!,id:'b2',position:{x:20,y:0}} as typeof d.entities[0]);expect(selectionBounds(d,['b1','b2'])).toEqual({minX:0,minY:0,maxX:30,maxY:10});});
 it('text uses glyph halo',()=>{const d=blockDoc();d.blocks![0]!.primitives=[{kind:'text',layerId:d.layers[0]!.id,colorMode:'bylayer',position:{x:0,y:0},content:'Здание',height:1,rotationDeg:0}];const c=ctx();drawSelectionContours(c,d,renderItems(d),d.viewport,size);expect(c.strokeText).toHaveBeenCalledTimes(2);});
 it('SVG block selection keeps base paint and leaves contours to the shared overlay',()=>{const d=blockDoc(),item=renderItems(d)[0]!,markup=renderToStaticMarkup(createElement('svg',null,createElement(BlockDefinitions,{document:d}),createElement(EntityView,{item,document:d,viewport:d.viewport,size,selected:true})));expect(markup).not.toContain('data-move-body');expect(markup).toContain(`color="${item.style.stroke}"`);expect(markup.match(/data-selected="true"/g)).toHaveLength(1);});
 it('SVG selected HATCH retains its original fill instead of painting selection fill',()=>{const d=blockDoc();d.blocks![0]!.primitives[0]={kind:'path',layerId:d.layers[0]!.id,colorMode:'byblock',points:[{x:0,y:0},{x:10,y:0},{x:0,y:10}],closed:true,fill:true};const item=renderItems(d)[0]!,selected=renderToStaticMarkup(createElement('svg',null,createElement(BlockDefinitions,{document:d}),createElement(EntityView,{item,document:d,viewport:d.viewport,size,selected:true}))),plain=renderToStaticMarkup(createElement('svg',null,createElement(BlockDefinitions,{document:d}),createElement(EntityView,{item,document:d,viewport:d.viewport,size,selected:false})));expect(selected).toContain('fill="currentColor"');expect(selected).toContain(`color="${item.style.stroke}"`);expect(plain).toContain(`color="${item.style.stroke}"`);expect(selected).not.toContain('fill="#277ec1"');});
 it('deep primitive resolution remains precise',()=>{const d=blockDoc();expect(createHitStack(d,['b1'],{x:5,y:0},1).some(c=>c.selection?.primitivePath.join('.')==='0')).toBe(true);});
});
