import {drawingMask} from './binary';
import {listLibraries} from '../symbols/registry';
import type {SymbolDefinition,SymbolPrimitive} from '../symbols/types';
import type {Candidate,PixelImage,PixelPoint,RegionCandidate} from './types';
const SIDE=48;
interface Signature {mask:Uint8Array;aspect:number;width:number;center:PixelPoint}
function points(p:SymbolPrimitive):PixelPoint[]{if(p.type==='line')return [p.start,p.end];if(p.type==='circle')return [{x:p.center.x-p.radius,y:p.center.y-p.radius},{x:p.center.x+p.radius,y:p.center.y+p.radius}];if(p.type==='rect')return [p.position,{x:p.position.x+p.width,y:p.position.y+p.height}];return p.points;}
export function renderSymbolSignature(symbol:SymbolDefinition,rotation=0):Signature{const r=rotation*Math.PI/180,rotate=(p:PixelPoint)=>({x:p.x*Math.cos(r)+p.y*Math.sin(r),y:p.x*Math.sin(r)-p.y*Math.cos(r)}),bounds=symbol.geometry.flatMap(p=>p.type==='circle'?Array.from({length:64},(_,i)=>rotate({x:p.center.x+Math.cos(i/64*Math.PI*2)*p.radius,y:p.center.y+Math.sin(i/64*Math.PI*2)*p.radius})):p.type==='rect'?[p.position,{x:p.position.x+p.width,y:p.position.y},{x:p.position.x+p.width,y:p.position.y+p.height},{x:p.position.x,y:p.position.y+p.height}].map(rotate):points(p).map(rotate));const x0=Math.min(...bounds.map(p=>p.x)),x1=Math.max(...bounds.map(p=>p.x)),y0=Math.min(...bounds.map(p=>p.y)),y1=Math.max(...bounds.map(p=>p.y)),w=x1-x0,h=y1-y0,scale=40/Math.max(w,h,.01),mask=new Uint8Array(SIDE*SIDE),center={x:(x0+x1)/2,y:(y0+y1)/2};const pixel=(p:PixelPoint)=>{const q=rotate(p);return {x:24+(q.x-center.x)*scale,y:24+(q.y-center.y)*scale};};const ink=(x:number,y:number)=>{for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const X=Math.round(x)+dx,Y=Math.round(y)+dy;if(X>=0&&Y>=0&&X<SIDE&&Y<SIDE)mask[Y*SIDE+X]=1;}};const line=(a:PixelPoint,b:PixelPoint)=>{a=pixel(a);b=pixel(b);const n=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)*2);for(let i=0;i<=n;i++)ink(a.x+(b.x-a.x)*i/(n||1),a.y+(b.y-a.y)*i/(n||1));};for(const p of symbol.geometry){if(p.type==='circle'){for(let i=0;i<256;i++){const a=i/256*Math.PI*2,b=(i+1)/256*Math.PI*2;line({x:p.center.x+Math.cos(a)*p.radius,y:p.center.y+Math.sin(a)*p.radius},{x:p.center.x+Math.cos(b)*p.radius,y:p.center.y+Math.sin(b)*p.radius});}}else{const ps=p.type==='rect'?[p.position,{x:p.position.x+p.width,y:p.position.y},{x:p.position.x+p.width,y:p.position.y+p.height},{x:p.position.x,y:p.position.y+p.height}]:points(p);for(let i=1;i<ps.length;i++)line(ps[i-1]!,ps[i]!);if(p.type==='polygon'||p.type==='rect')line(ps.at(-1)!,ps[0]!);}}return {mask,aspect:w/(h||.01),width:w,center};}
function similarity(a:Uint8Array,b:Uint8Array){let covered=0,total=0;for(const [source,target] of [[a,b],[b,a]])for(let i=0;i<source!.length;i++)if(source![i]){total++;const x=i%SIDE,y=Math.floor(i/SIDE);let hit=false;for(let dy=-2;dy<=2&&!hit;dy++)for(let dx=-2;dx<=2;dx++){const X=x+dx,Y=y+dy;if(X>=0&&Y>=0&&X<SIDE&&Y<SIDE&&target![Y*SIDE+X]){hit=true;break;}}if(hit)covered++;}return total?covered/total:0;}
/** Quarter-turn grouping preserves internal strokes without mirror equivalence. */
function rotatedSignature(signature:Signature,turns:number):Signature {
  let mask=signature.mask;
  for(let turn=0;turn<turns;turn++) {
    const next=new Uint8Array(mask.length);
    for(let y=0;y<SIDE;y++)for(let x=0;x<SIDE;x++)next[x*SIDE+(SIDE-1-y)]=mask[y*SIDE+x]!;
    mask=next;
  }
  return {...signature,mask,aspect:turns%2?1/signature.aspect:signature.aspect};
}
function sameRepeatedShape(a:Signature,b:Signature) {
  return [0,1,2,3].some(turn=>{const q=rotatedSignature(b,turn);return Math.abs(Math.log(a.aspect/q.aspect))<.16&&similarity(a.mask,q.mask)>.92;});
}
let templates: {libraryId:string;symbol:SymbolDefinition;rotation:number;signature:Signature}[]|null=null;
function libraryTemplates(){return templates??=listLibraries().flatMap(l=>l.symbols.flatMap(symbol=>Array.from({length:24},(_,i)=>({libraryId:l.id,symbol,rotation:i*15,signature:renderSymbolSignature(symbol,i*15)}))));}
export function rankSymbolMatches(signature:Signature){const best=new Map<string,{template:ReturnType<typeof libraryTemplates>[number];score:number}>();for(const template of libraryTemplates()){const penalty=Math.abs(Math.log(signature.aspect/template.signature.aspect));if(penalty>.35)continue;const score=similarity(signature.mask,template.signature.mask)-penalty*.18,key=template.libraryId+'\0'+template.symbol.id;if(score>(best.get(key)?.score??-1))best.set(key,{template,score});}return [...best.values()].sort((a,b)=>b.score-a.score);}
export function matchSymbol(signature:Signature){const ranked=rankSymbolMatches(signature),first=ranked[0],margin=first?first.score-(ranked[1]?.score??0):0;if(!first||first.score<.82||margin<.02)return null;return {...first,matchClass:first.score>=.93&&margin>=.05?'strong' as const:'possible' as const};}
/** Compact connected ink regions only; no proximity-based engineering topology. */
export function detectSymbols(image:PixelImage,textRegions:Candidate[],adaptive=false):{candidates:RegionCandidate[];timings:{grouping:number;matching:number}}{const start=performance.now(),mask=drawingMask(image,adaptive),seen=new Uint8Array(mask.length),regions:{bounds:RegionCandidate['bounds'];signature:Signature}[]=[];for(let i=0;i<mask.length;i++){if(!mask[i]||seen[i])continue;const queue=[i],pixels:number[]=[];seen[i]=1;let x0=image.width,y0=image.height,x1=0,y1=0;while(queue.length){const n=queue.pop()!,x=n%image.width,y=Math.floor(n/image.width);pixels.push(n);x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const X=x+dx,Y=y+dy,k=Y*image.width+X;if(X>=0&&Y>=0&&X<image.width&&Y<image.height&&mask[k]&&!seen[k]){seen[k]=1;queue.push(k);}}}const w=x1-x0+1,h=y1-y0+1;if(w<12||h<12||Math.max(w,h)>190||w/h<.2||w/h>5||pixels.length<30||pixels.length/(w*h)>.7)continue;const bounds={x:x0,y:y0,width:w,height:h};if(textRegions.some(c=>c.type==='text'&&'bounds'in c&&x0>=c.bounds.x-2&&y0>=c.bounds.y-2&&x1<=c.bounds.x+c.bounds.width+2&&y1<=c.bounds.y+c.bounds.height+2))continue;const tile=new Uint8Array(SIDE*SIDE),scale=40/Math.max(w,h);for(const n of pixels){const x=Math.round(24+((n%image.width)-x0-w/2)*scale),y=Math.round(24+(Math.floor(n/image.width)-y0-h/2)*scale);if(x>=0&&y>=0&&x<SIDE&&y<SIDE)tile[y*SIDE+x]=1;}regions.push({bounds,signature:{mask:tile,aspect:w/h,width:w,center:{x:w/2,y:h/2}}});if(regions.length>=300)break;}
const groups:{signature:Signature;items:typeof regions}[]=[];for(const r of regions){const g=groups.find(g=>sameRepeatedShape(g.signature,r.signature));if(g)g.items.push(r);else groups.push({signature:r.signature,items:[r]});}const grouping=performance.now()-start,matchingStart=performance.now(),candidates:RegionCandidate[]=[];for(const [i,g]of groups.entries()){const matched=matchSymbol(g.signature);if(g.items.length<2&&!matched)continue;const groupId=`symbol-group-${i+1}`;for(const [j,item]of g.items.entries()){const own=matchSymbol(item.signature),m=own;candidates.push({id:`${groupId}-${j+1}`,type:'symbol',bounds:item.bounds,groupId,confirmed:false,evidence:[`Повторений формы: ${g.items.length}`,...(m?['Сопоставлены общий контур и внутренние штрихи','Проверены пропорции и повороты']:['Недостаточно отличительных признаков для библиотеки'])],...(m?{proposedSymbol:{libraryId:m.template.libraryId,symbolId:m.template.symbol.id,confirmed:false,matchClass:m.matchClass,rotationDeg:-m.template.rotation,localWidth:m.template.signature.width,localCenter:{x:m.template.signature.center.x,y:-m.template.signature.center.y}}}:{})});}}return {candidates,timings:{grouping,matching:performance.now()-matchingStart}};}
