import {createWorker,PSM} from 'tesseract.js';
import {detectSymbols} from './symbolRecognition';
import {scaleCandidates} from './extract';
import {normalizeOcrText,OCR_REGION_LIMIT,preprocessOcr,sourceTextCrop} from './ocr';
import type {RecognitionRequest,RecognitionResult} from './understanding';
import type {RegionCandidate} from './types';
const scope=self as unknown as {onmessage:((e:MessageEvent<RecognitionRequest>)=>void)|null;postMessage:(data:unknown)=>void};
scope.onmessage=async({data:r})=>{const candidates=r.candidates.filter(c=>c.type!=='symbol').map(c=>{const next={...c};if(next.type==='text'){delete next.recognizedText;delete next.originalText;delete next.confidence;next.confirmed=false;next.semanticConfirmed=false;}return next;}),warnings:string[]=[],ocrExamples:RecognitionResult['ocrExamples']=[];let ocr=0,grouping=0,matching=0,cacheable=true;
try{scope.postMessage({stage:'Поиск повторяющихся символов'});const text=scaleCandidates(candidates,r.image.width/r.calibration.rectifiedWidth,r.image.height/r.calibration.rectifiedHeight);try{const symbols=detectSymbols(r.image,text,r.adaptive);candidates.push(...scaleCandidates(symbols.candidates,r.calibration.rectifiedWidth/r.image.width,r.calibration.rectifiedHeight/r.image.height));({grouping,matching}=symbols.timings);}catch{cacheable=false;warnings.push('Сопоставление символов не завершено. Геометрия сохранена.');}
const regions=candidates.filter((c):c is RegionCandidate=>c.type==='text'&&'bounds'in c).slice(0,OCR_REGION_LIMIT);if(candidates.filter(c=>c.type==='text').length>OCR_REGION_LIMIT)warnings.push(`Распознаны первые ${OCR_REGION_LIMIT} областей; остальные требуют отдельной обработки.`);
if(regions.length){const start=performance.now();let worker:import('tesseract.js').Worker|undefined;try{scope.postMessage({stage:'Загрузка локального OCR · русский + английский'});const runtime=await fetch(r.runtimeBase+'/runtime/worker.min.js');if(!runtime.ok||!runtime.headers.get('content-type')?.includes('javascript'))throw new Error('OCR runtime unavailable');let initializationTimer:ReturnType<typeof setTimeout>|undefined;
const engineError=new Promise<never>((_,reject)=>{initializationTimer=setTimeout(()=>reject(new Error('OCR initialization timeout')),15000);});
let rejectEngine:(error:unknown)=>void=()=>{};
const engineFailure=new Promise<never>((_,reject)=>{rejectEngine=reject;});
try{worker=await Promise.race([createWorker('rus+eng',1,{workerPath:r.runtimeBase+'/runtime/worker.min.js',corePath:r.runtimeBase+'/runtime',langPath:r.runtimeBase+'/lang',workerBlobURL:false,cacheMethod:'write',gzip:true,errorHandler:error=>rejectEngine(new Error(String(error)))}),engineError,engineFailure]);}finally{clearTimeout(initializationTimer);}
await worker.setParameters({tessedit_pageseg_mode:PSM.SINGLE_LINE,preserve_interword_spaces:'1'});for(const [i,region]of regions.entries()){scope.postMessage({stage:`Текст ${i+1} / ${regions.length}`});try{const crop=await sourceTextCrop(r.sourceBlob,r.calibration,region);let best:{text:string;confidence:number;angle:number}|null=null;for(const angle of r.quality==='accurate'?[0,-6,6]:[0]){const image=preprocessOcr(crop,region.rotationDeg??0,angle),canvas=new OffscreenCanvas(image.width,image.height);try{canvas.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(image.data),image.width,image.height),0,0);const blob=await canvas.convertToBlob({type:'image/png'}),bytes=new Uint8Array(await blob.arrayBuffer()),encoded=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')),result=await worker.recognize('data:image/png;base64,'+encoded),text=normalizeOcrText(result.data.text);if(text&&(!best||result.data.confidence>best.confidence))best={text,confidence:result.data.confidence,angle};}finally{canvas.width=canvas.height=0;}}if(best){region.recognizedText=best.text;region.originalText=best.text;region.confidence=Math.max(0,Math.min(1,best.confidence/100));region.rotationDeg=(region.rotationDeg??0)+best.angle;region.confirmed=false;ocrExamples.push({expectedRegion:region.id,text:best.text,confidence:best.confidence});}else warnings.push(`${region.id}: текст не распознан; можно ввести вручную.`);}catch{cacheable=false;warnings.push(`${region.id}: OCR не завершён; геометрия сохранена.`);}}}catch{cacheable=false;warnings.push('Локальный OCR/runtime или RU/EN ресурсы недоступны. Геометрия и символы остаются доступными.');}finally{await worker?.terminate();ocr=performance.now()-start;}}
scope.postMessage({result:{candidates,warnings,cacheable,timings:{ocr,grouping,matching},ocrExamples}});}catch{scope.postMessage({error:'Не удалось распознать изображение. Геометрия остаётся в preview.'});}};
