import type {Candidate,ImageCalibration,PixelImage,RegionCandidate} from './types';
export interface RecognitionRequest{image:PixelImage;candidates:Candidate[];calibration:ImageCalibration;sourceBlob:Blob;quality:'balanced'|'accurate';adaptive:boolean;runtimeBase:string}
export interface RecognitionResult{candidates:Candidate[];warnings:string[];cacheable:boolean;timings:{ocr:number;grouping:number;matching:number};ocrExamples:{expectedRegion:string;text:string;confidence:number}[]}
/** Local provider boundary. Future remote adapters require a separate explicit opt-in contract. */
export interface LocalImageRecognizer{readonly mode:'local';recognize(request:RecognitionRequest,signal:AbortSignal,stage:(label:string)=>void):Promise<RecognitionResult>}
export async function recognizeImage(request:RecognitionRequest,signal:AbortSignal,stage:(label:string)=>void):Promise<RecognitionResult>{if(import.meta.env.PROD&&'serviceWorker'in navigator){
 let timer:ReturnType<typeof setTimeout>|undefined;
 try{await Promise.race([navigator.serviceWorker.register(new URL(import.meta.env.BASE_URL+'ocr-offline.js',location.origin),{scope:import.meta.env.BASE_URL}).then(()=>navigator.serviceWorker.ready),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('Offline cache unavailable')),5000);})]);}
 catch{/* Local OCR remains usable when optional offline storage is unavailable. */}
 finally{clearTimeout(timer);}
}
return new Promise((resolve,reject)=>{if(signal.aborted){reject(new DOMException('Отменено','AbortError'));return;}const worker=new Worker(new URL('./understanding.worker.ts',import.meta.url),{type:'module'});const finish=()=>{clearTimeout(timer);signal.removeEventListener('abort',cancel);worker.terminate();};const cancel=()=>{finish();reject(new DOMException('Отменено','AbortError'));};const timer=setTimeout(()=>{finish();reject(new Error('Распознавание заняло более 120 секунд. Геометрия сохранена в preview; уменьшите число областей.'));},120000);signal.addEventListener('abort',cancel,{once:true});worker.onerror=()=>{finish();reject(new Error('Процесс распознавания недоступен. Геометрия остаётся доступной.'));};worker.onmessageerror=()=>{finish();reject(new Error('Не удалось прочитать результат распознавания.'));};worker.onmessage=({data}:MessageEvent<{stage?:string;error?:string;result?:RecognitionResult}>)=>{if(data.stage){stage(data.stage);return;}finish();if(data.result)resolve(data.result);else reject(new Error(data.error??'Распознавание не завершено.'));};try{const image={...request.image,data:request.image.data.slice()};worker.postMessage({...request,image},[image.data.buffer]);}catch{finish();reject(new Error('Недостаточно памяти для распознавания.'));}});}
export const isConfirmedRegion=(c:Candidate):c is RegionCandidate=>!('points'in c)&&c.type!=='circle'&&c.type!=='arc'&&(c.type==='text'?!!c.confirmed&&!!c.recognizedText?.trim():!!c.proposedSymbol?.confirmed);
