import type { Candidate, PixelPoint, RegionCandidate } from './types';
import { matchSymbol, rankSymbolMatches } from './symbolRecognition';
import { box, SpatialIndex } from '../topology/spatial';
export function candidateBox(c:Candidate){if('bounds'in c)return {minX:c.bounds.x,minY:c.bounds.y,maxX:c.bounds.x+c.bounds.width,maxY:c.bounds.y+c.bounds.height};if(c.type==='circle'||c.type==='arc')return {minX:c.center.x-c.radius,minY:c.center.y-c.radius,maxX:c.center.x+c.radius,maxY:c.center.y+c.radius};return c.points.reduce((b,p)=>({minX:Math.min(b.minX,p.x),minY:Math.min(b.minY,p.y),maxX:Math.max(b.maxX,p.x),maxY:Math.max(b.maxY,p.y)}),box(c.points[0]!));}
export const replacementGeometryIds=(candidates:Candidate[],region:RegionCandidate)=>{const b=candidateBox(region);return candidates.filter(c=>!('bounds'in c)).filter(c=>{const p=candidateBox(c);return p.minX>=b.minX-3&&p.minY>=b.minY-3&&p.maxX<=b.maxX+3&&p.maxY<=b.maxY+3;}).map(c=>c.id);};
/** Native vector signature comparison; never rasterizes the PDF page or infers ports. */
export function detectVectorSymbols(candidates:Candidate[]):RegionCandidate[]{
 const geometry=candidates.filter(c=>!('bounds'in c)),index=new SpatialIndex(geometry.map((c,i)=>({bounds:candidateBox(c),value:i}))),seen=new Set<number>(),result:RegionCandidate[]=[];
 for(let i=0;i<geometry.length;i++){if(seen.has(i))continue;const group:number[]=[],queue=[i];seen.add(i);while(queue.length){const k=queue.pop()!;group.push(k);for(const neighbor of index.query((()=>{const b=candidateBox(geometry[k]!);return {...b,minX:b.minX-.001,minY:b.minY-.001,maxX:b.maxX+.001,maxY:b.maxY+.001};})()))if(!seen.has(neighbor)){seen.add(neighbor);queue.push(neighbor);}}
 if(group.length>100)continue;const b=group.map(k=>candidateBox(geometry[k]!)).reduce((a,c)=>({minX:Math.min(a.minX,c.minX),minY:Math.min(a.minY,c.minY),maxX:Math.max(a.maxX,c.maxX),maxY:Math.max(a.maxY,c.maxY)})),w=b.maxX-b.minX,h=b.maxY-b.minY;if(w<2||h<2||Math.max(w,h)>400)continue;
 const mask=new Uint8Array(48*48),scale=40/Math.max(w,h),ink=(p:PixelPoint)=>{const x=Math.round(24+(p.x-(b.minX+b.maxX)/2)*scale),y=Math.round(24+(p.y-(b.minY+b.maxY)/2)*scale);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const X=x+dx,Y=y+dy;if(X>=0&&Y>=0&&X<48&&Y<48)mask[Y*48+X]=1;}},line=(a:PixelPoint,c:PixelPoint)=>{const n=Math.max(1,Math.ceil(Math.hypot(a.x-c.x,a.y-c.y)*scale*2));for(let j=0;j<=n;j++)ink({x:a.x+(c.x-a.x)*j/n,y:a.y+(c.y-a.y)*j/n});};
 for(const k of group){const c=geometry[k]!;if('points'in c){for(let j=1;j<c.points.length;j++)line(c.points[j-1]!,c.points[j]!);if(c.type==='contour')line(c.points.at(-1)!,c.points[0]!);}else if(c.type==='circle'||c.type==='arc'){const begin=c.type==='arc'?c.startAngle:0,sweep=c.type==='arc'?c.endAngle-c.startAngle:Math.PI*2;for(let j=0;j<256;j++)line({x:c.center.x+Math.cos(begin+j/256*sweep)*c.radius,y:c.center.y+Math.sin(begin+j/256*sweep)*c.radius},{x:c.center.x+Math.cos(begin+(j+1)/256*sweep)*c.radius,y:c.center.y+Math.sin(begin+(j+1)/256*sweep)*c.radius});}}
 const signature={mask,aspect:w/h,width:w,center:{x:0,y:0}},matched=matchSymbol(signature),ranked=matched?[]:rankSymbolMatches(signature);if(!matched&&(ranked[0]?.score??0)<.82)continue;
 if(!matched){result.push({id:`vector-symbol-${result.length+1}`,groupId:`vector-symbol-group-${result.length+1}`,type:'symbol',bounds:{x:b.minX,y:b.minY,width:w,height:h},confirmed:false,evidence:[`Несколько похожих обозначений: ${ranked.slice(0,2).map(r=>r.template.symbol.name).join(' / ')}. Выберите вручную.`]});continue;}
 result.push({id:`vector-symbol-${result.length+1}`,groupId:`vector-symbol-group-${result.length+1}`,type:'symbol',bounds:{x:b.minX,y:b.minY,width:w,height:h},confirmed:false,evidence:['Native векторный контур и внутренние штрихи совпадают с библиотекой. Требуется подтверждение.'],proposedSymbol:{libraryId:matched.template.libraryId,symbolId:matched.template.symbol.id,matchClass:matched.matchClass,confirmed:false,rotationDeg:-matched.template.rotation,localWidth:matched.template.signature.width,localCenter:{x:matched.template.signature.center.x,y:-matched.template.signature.center.y}}});
 }
 return result;
}
