import { editorCommand } from './helpers/editorCommands';
import { expect,test,type Page } from '@playwright/test';
import { readFile,writeFile } from 'node:fs/promises';
import { createNewDocument } from '../src/domain/newDocument';
import type { GeoDocument,WorldPoint,SymbolEntity } from '../src/domain/model';
import { connectorBenchmarkDocument,connectorDocument } from '../src/tests/fixtures/connectorDocument';
import { PROCESS_FIXTURES,PROCESS_REQUESTS } from '../src/process/fixtures';
import { readAutosaveDocument } from './helpers/autosave';
import { validateConnectivity } from '../src/connectors/model';
import { worldToScreen } from '../src/geometry';
import { createHorizontalReference } from '../src/geometry/georeferencing';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function setup(page:Page,d=createNewDocument()){await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));await page.route('**/api/ai/intent',r=>r.fulfill({json:PROCESS_FIXTURES.get(r.request().postDataJSON().text)??{status:'unsupported'}}));await page.addInitScript(d=>localStorage.setItem('geoservice.document.v2',JSON.stringify(d)),d);await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
const canvas=(page:Page)=>page.getByTestId('drawing-canvas');
async function camera(page:Page){const c=canvas(page);return {center:{x:Number(await c.getAttribute('data-center-x')),y:Number(await c.getAttribute('data-center-y'))},pixelsPerUnit:Number(await c.getAttribute('data-zoom'))};}
async function screen(page:Page,p:WorldPoint){const c=canvas(page),b=(await c.boundingBox())!,view=await camera(page),mode=await c.getAttribute('data-view-mode');const projection={orientation:(await c.getAttribute('data-orientation')) as 'NE',origin:{x:Number(await c.getAttribute('data-origin-x')),y:Number(await c.getAttribute('data-origin-y')),z:Number(await c.getAttribute('data-origin-z'))}};const q=worldToScreen(p,mode==='plan'?view:{...view,projection},b);return {x:b.x+q.x,y:b.y+q.y};}
async function clickPoint(page:Page,p:WorldPoint){const q=await screen(page,p);await page.mouse.click(q.x,q.y);}
async function saveOpen(page:Page){const download=page.waitForEvent('download');await editorCommand(page, 'Сохранить JSON');const path=(await(await download).path())!,saved=JSON.parse(await readFile(path,'utf8'));await editorCommand(page, 'Новый документ');await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(path);expect(await readAutosaveDocument(page)).toEqual(saved);return saved as GeoDocument;}
function terrain(){const d=createNewDocument();const points=[{x:0,y:0,z:0},{x:10,y:0,z:2},{x:10,y:10,z:4},{x:0,y:10,z:1}];d.vertices=Object.fromEntries(points.map((p,i)=>[`v${i}`,{id:`v${i}`,...p}]));d.entities=points.map((_,i)=>({type:'point',id:`p${i}`,name:`P${i+1}`,vertexId:`v${i}`,layerId:'boundary'}));d.entities.push({type:'polyline',id:'terrain',name:'Terrain',layerId:'boundary',vertexIds:['v0','v1','v2','v3']});return d;}
test('terrain XYZ, four presets, Fit Layer, independent cameras and safe drag',async({page})=>{const d=terrain();await setup(page,d);await page.getByRole('button',{name:'Увеличить',exact:true}).click();const plan=await camera(page),original=await readAutosaveDocument(page);await page.getByLabel('Вид',{exact:true}).selectOption('NE');await expect(page.getByTestId('axon-axes')).toBeVisible();await expect(page.getByTestId('north-arrow')).toHaveCount(0);await expect(page.getByTestId('axon-ground-grid')).toBeVisible();
  for(const preset of ['NE','NW','SE','SW']){await page.getByLabel('Вид',{exact:true}).selectOption(preset);await page.getByRole('button',{name:'Вписать схему в вид',exact:true}).click();await clickPoint(page,d.vertices.v2!);await expect(page.locator('[data-entity-id="p2"]')).toHaveAttribute('data-selected','true');const q=await screen(page,d.vertices.v2!);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+35,q.y-20);await page.mouse.up();await expect(page.getByTestId('editor-error')).toContainText('точные координаты X/Y/Z');expect(await readAutosaveDocument(page)).toEqual(original);}
  await page.getByRole('button',{name:'Выбрать слой Граница участка',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await page.getByLabel('Вид',{exact:true}).selectOption('plan');expect(await camera(page)).toEqual(plan);await page.screenshot({path:'/private/tmp/geoservice-axon-terrain-plan.png'});
});
test('AI six-stage scheme, numeric Z, connectivity, Undo/Redo, JSON and IndexedDB',async({page})=>{await setup(page);await page.getByLabel('Запрос',{exact:true}).fill(PROCESS_REQUESTS.A);await page.getByRole('button',{name:'Generate plan',exact:true}).click();await expect(page.getByTestId('process-preview')).toBeVisible();await page.getByTestId('process-preview').getByRole('button',{name:/^Apply /}).click();await page.getByRole('button',{name:'Вписать схему в вид',exact:true}).click();let d=await readAutosaveDocument(page);const symbols=d.entities.filter(e=>e.type==='symbol'),heights=[0,0,.5,1,1,2];const xy=symbols.map(e=>({id:e.id,x:e.position.x,y:e.position.y}));
  for(const [i,e] of symbols.entries()){await clickPoint(page,e.position);await page.getByLabel('MODEL Z',{exact:true}).fill(String(heights[i]));await page.getByLabel('MODEL Z',{exact:true}).press('Enter');}
  d=await readAutosaveDocument(page);validateConnectivity(d);const plan=await camera(page);await page.getByLabel('Вид',{exact:true}).selectOption('NE');await expect(page.getByTestId('connector-route')).toHaveCount(5);const filter=d.entities.find(e=>e.id===symbols[2]!.id)! as SymbolEntity;await clickPoint(page,filter.position);const before=await page.locator(`[data-entity-id="${filter.id}"] path`).first().getAttribute('d');await page.getByLabel('MODEL Z',{exact:true}).fill('3');await page.getByLabel('MODEL Z',{exact:true}).press('Enter');await expect(page.locator(`[data-entity-id="${filter.id}"] path`).first()).not.toHaveAttribute('d',before!);await page.getByRole('button',{name:'Отменить',exact:true}).click();await expect(page.getByLabel('MODEL Z',{exact:true})).toHaveValue('0.5');await page.getByRole('button',{name:'Повторить',exact:true}).click();await expect(page.getByLabel('MODEL Z',{exact:true})).toHaveValue('3');await page.getByRole('button',{name:'Отменить',exact:true}).click();await expect(page.getByLabel('MODEL Z',{exact:true})).toHaveValue('0.5');await frame(page);await page.screenshot({path:'/private/tmp/geoservice-axon-process.png'});await page.getByLabel('Вид',{exact:true}).selectOption('plan');expect(await camera(page)).toEqual(plan);expect((await readAutosaveDocument(page)).entities.filter(e=>e.type==='symbol').map(e=>({id:e.id,x:e.position.x,y:e.position.y}))).toEqual(xy);const saved=await saveOpen(page);expect(saved.entities.filter(e=>e.type==='symbol').map(e=>e.position.z)).toEqual(heights);await page.reload();expect(await readAutosaveDocument(page)).toEqual(saved);
});
test('georeference: MODEL Z and SURVEY/absolute H; datum never moves presentation',async({page})=>{const d=terrain(),s=connectorDocument(false).entities[0]! as SymbolEntity;s.position={x:20,y:0,z:2};d.entities.push(s);d.verticalReference={modelZero:0,absoluteAtModelZero:100};d.horizontalReference=createHorizontalReference(d,[{pointEntityId:'p0',survey:{e:6000000,n:4000000}},{pointEntityId:'p1',survey:{e:6000010,n:4000000}}]);await setup(page,d);await page.getByLabel('Вид',{exact:true}).selectOption('NE');await clickPoint(page,s.position);await expect(page.getByTestId('symbol-absolute-h')).toHaveText('102.000');await expect(page.getByLabel('MODEL Z',{exact:true})).toHaveValue('2');await expect(page.getByText('SURVEY E',{exact:true})).toBeVisible();const path=await page.locator(`[data-entity-id="${s.id}"] path`).first().getAttribute('d');
  await page.getByLabel('Абсолютная отметка нуля',{exact:true}).fill('200');await page.getByRole('button',{name:'Применить высотную привязку',exact:true}).click();await expect(page.getByTestId('symbol-absolute-h')).toHaveText('202.000');expect(await page.locator(`[data-entity-id="${s.id}"] path`).first().getAttribute('d')).toBe(path);
});
async function frame(page:Page){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function measure(page:Page,action:()=>Promise<unknown>){const start=performance.now();await action();await frame(page);return +(performance.now()-start).toFixed(1);}
async function benchmark(page:Page,document:GeoDocument){const report:Record<string,unknown>={};for(const mode of ['plan','NE']){const initial=await measure(page,()=>page.getByLabel('Вид',{exact:true}).selectOption(mode)),c=canvas(page),b=(await c.boundingBox())!;const fit=await measure(page,()=>page.getByRole('button',{name:'Вписать схему в вид',exact:true}).click());const pan=await measure(page,async()=>{await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down({button:'middle'});await page.mouse.move(b.x+b.width/2+25,b.y+b.height/2+15);await page.mouse.up({button:'middle'});});const zoom=await measure(page,()=>page.mouse.wheel(0,-100));const selection=await measure(page,()=>page.mouse.click(b.x+b.width/2,b.y+b.height/2));const populated=[...document.layers].sort((a,b)=>document.entities.filter(e=>e.layerId===b.id).length-document.entities.filter(e=>e.layerId===a.id).length)[0]!,layer=page.getByRole('button',{name:`Скрыть слой ${populated.name}`,exact:true});let toggle:number|null=null;if(await layer.count()){const name=(await layer.getAttribute('aria-label'))!.replace('Скрыть слой ','');toggle=await measure(page,async()=>{await layer.click();await page.getByRole('button',{name:`Показать слой ${name}`,exact:true}).click();});}const metrics=await page.evaluate(async()=>{const {canvasMetrics}=await import(String('/src/renderer/CanvasSceneRenderer.ts'));return canvasMetrics();});report[mode]={camera:await camera(page),initial,fit,pan,zoom,selection,layerToggle:toggle,toggledLayer:populated.name,canvasFrames:metrics.frames.slice(-8),svgNodes:await page.locator('svg.drawing-canvas *').count(),canvasOwners:await page.locator('canvas').evaluateAll(cs=>cs.reduce((n,c)=>n+JSON.parse((c as HTMLCanvasElement).dataset.drawnOwners??'[]').length,0))};}return report;}
test('performance 100 symbols / 150 connectors, preserved elevations',async({page})=>{const d=connectorBenchmarkDocument();d.entities=d.entities.map((e,i)=>e.type==='symbol'?{...e,position:{...e.position,z:(i%5)*.5}}:e);const started=performance.now();await setup(page,d);await frame(page);const initialRender=+(performance.now()-started).toFixed(1),initial=await readAutosaveDocument(page),result=await benchmark(page,initial);await writeFile('/private/tmp/geoservice-axon-network-benchmark.json',JSON.stringify({initialRender,result},null,2));expect(await readAutosaveDocument(page)).toEqual(initial);validateConnectivity(initial);});
test('DXF Canvas, projected selection/zoom/pan/layers, JSON and original Plan camera',async({page})=>{test.setTimeout(180000);await setup(page);const started=performance.now();await editorCommand(page, 'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE??'src/tests/fixtures/dxf/simple_ascii.dxf');await page.getByTestId('dxf-report').waitFor();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);await frame(page);const initialRender=+(performance.now()-started).toFixed(1),original=await readAutosaveDocument(page);const result=await benchmark(page,original);await writeFile(process.env.DXF_REFERENCE?'/private/tmp/geoservice-axon-dxf-reference-benchmark.json':'/private/tmp/geoservice-axon-dxf-benchmark.json',JSON.stringify({initialRender,entities:original.entities.length,blocks:original.blocks?.length,definitionPrimitives:original.blocks?.reduce((n,b)=>n+b.primitives.length,0),result},null,2));await expect(canvas(page)).toHaveAttribute('data-renderer','canvas');expect(await page.locator('canvas').count()).toBeGreaterThan(0);expect(await page.locator('svg.drawing-canvas *').count()).toBeLessThan(5000);
  const line=original.entities.find(e=>e.type==='line');if(line?.type==='line'){const a=original.vertices[line.startVertexId]!,b=original.vertices[line.endVertexId]!;await page.getByRole('button',{name:'Вписать схему в вид',exact:true}).click();await clickPoint(page,{x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:((a.z??0)+(b.z??0))/2});await expect(page.locator('[data-testid="canvas-selection-overlay"]')).toHaveCount(1);}
  await page.screenshot({path:'/private/tmp/geoservice-axon-dxf.png'});await page.getByLabel('Вид',{exact:true}).selectOption('plan');expect(await camera(page)).toEqual((result.plan as {camera:unknown}).camera);expect(await readAutosaveDocument(page)).toEqual(original);const saved=await saveOpen(page);expect(saved.vertices).toEqual(original.vertices);expect(saved.entities).toEqual(original.entities);expect(saved.blocks).toEqual(original.blocks);
});
