import { editorCommand } from './helpers/editorCommands';
import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { readAutosaveDocument } from './helpers/autosave';
import { connectorDocument, endpoint } from '../src/tests/fixtures/connectorDocument';
import { createNewDocument } from '../src/domain/newDocument';
import type { ConnectorEntity, GeoDocument, SymbolEntity } from '../src/domain/model';
import { connectorRoute, resolvePort, validateConnectivity } from '../src/connectors/model';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function load(page:Page,d:GeoDocument){await page.addInitScript(d=>localStorage.setItem('geoservice.document.v2',JSON.stringify(d)),d);await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
const drawing=(page:Page)=>readAutosaveDocument(page);
async function screen(page:Page,x:number,y:number){const c=page.getByTestId('drawing-canvas'),b=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y'));return{x:b.x+b.width/2+(x-cx)*z,y:b.y+b.height/2-(y-cy)*z};}
async function clickPort(page:Page,id:string,port:string){const p=resolvePort(await drawing(page),endpoint(id,port)).world,s=await screen(page,p.x,p.y);await page.mouse.move(s.x,s.y);await page.mouse.click(s.x,s.y);}
async function create(page:Page,a:string,b:string){await page.getByRole('button',{name:'Инструмент: Соединение',exact:true}).click();await clickPort(page,a,'out');await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();await clickPort(page,b,'in');await expect(page.getByTestId('connector-ghost')).toHaveCount(0);}
async function symbolClick(page:Page,id:string,shift=false){await page.locator(`[data-entity-id="${id}"] [data-symbol-hit]`).click({modifiers:shift?['Shift']:[]});}
async function relative(page:Page,x:number,y:number){await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill(String(x));await page.getByLabel('Перемещение ΔY',{exact:true}).fill(String(y));await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();}
async function clickConnection(page:Page){const d=await drawing(page),e=d.entities.find(e=>e.type==='connector')! as ConnectorEntity,route=connectorRoute(d,e),segments=route.slice(1).map((b,i)=>({a:route[i]!,b})).sort((s,t)=>Math.hypot(t.b.x-t.a.x,t.b.y-t.a.y)-Math.hypot(s.b.x-s.a.x,s.b.y-s.a.y)),segment=segments[0]!,p=await screen(page,(segment.a.x+segment.b.x)/2,(segment.a.y+segment.b.y)/2);await page.mouse.click(p.x,p.y);}
async function saveOpen(page:Page){const promise=page.waitForEvent('download');await editorCommand(page, 'Сохранить JSON');const path=(await(await promise).path())!,saved=JSON.parse(await readFile(path,'utf8'));await editorCommand(page, 'Новый документ');await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(path);await expect.poll(async()=>drawing(page)).toEqual(saved);validateConnectivity(saved);return saved as GeoDocument;}
test('tool Create, ghost/Escape, occupied and incompatible targets, one Undo/Redo',async({page})=>{
  const d=connectorDocument(false);await load(page,d);await page.getByRole('button',{name:'Выбрать слой Аннотации',exact:true}).click();await page.keyboard.press('c');await page.keyboard.press('o');await expect(page.getByRole('button',{name:'Инструмент: Соединение',exact:true})).toHaveAttribute('aria-pressed','true');
  await clickPort(page,'valve','out');const p=await screen(page,4,2);await page.mouse.move(p.x,p.y);await expect(page.getByTestId('connector-ghost')).toBeVisible();expect(await drawing(page)).toEqual(d);await page.keyboard.press('Escape');expect(await drawing(page)).toEqual(d);await expect(page.getByTestId('connector-ghost')).toHaveCount(0);
  await create(page,'valve','filter');await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(1);const created=await drawing(page);expect(created.entities.at(-1)).toMatchObject({layerId:'annotations',start:endpoint('valve','out'),end:endpoint('filter','in')});
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(created);
  await page.getByRole('button',{name:'Инструмент: Соединение',exact:true}).click();await clickPort(page,'valve','out');await expect(page.getByTestId('editor-error')).toContainText('Порт уже подключён');expect(await drawing(page)).toEqual(created);await clickPort(page,'regulator','out');await clickPort(page,'instrument','sense');await expect(page.getByTestId('editor-error')).toContainText('Несовместимые');expect(await drawing(page)).toEqual(created);await clickPort(page,'regulator','out');await expect(page.getByTestId('editor-error')).toContainText('самим собой');await page.keyboard.press('Escape');expect(await drawing(page)).toEqual(created);
});
test('Move / Rotate / Scale stay attached, group with connector never double moves, Save/Open and IndexedDB',async({page})=>{
  await load(page,connectorDocument());const route=page.getByTestId('connector-route'),before=await route.getAttribute('d');await symbolClick(page,'filter');await relative(page,2,3);await expect(route).not.toHaveAttribute('d',before!);let d=await drawing(page);expect(resolvePort(d,endpoint('filter','in')).world).toMatchObject({x:9,y:3});expect(d.entities.at(-1)).toMatchObject({end:endpoint('filter','in')});
  await page.getByLabel('Поворот (°)',{exact:true}).fill('90');await page.getByLabel('Поворот (°)',{exact:true}).press('Enter');d=await drawing(page);expect(resolvePort(d,endpoint('filter','in')).world).toMatchObject({x:10,y:2});await page.getByLabel('Масштаб символа',{exact:true}).fill('2');await page.getByLabel('Масштаб символа',{exact:true}).press('Enter');d=await drawing(page);expect(resolvePort(d,endpoint('filter','in')).world.y).toBeCloseTo(1);
  await symbolClick(page,'valve',true);const connection=d.entities.at(-1)! as ConnectorEntity,mid=connectorRoute(d,connection)[1]!,point=await screen(page,mid.x+.1,mid.y);await page.keyboard.down('Shift');await page.mouse.click(point.x,point.y);await page.keyboard.up('Shift');await expect(page.getByTestId('group-properties')).toContainText('3 объектов');const beforeGroup=await drawing(page);await relative(page,1,-2);const after=await drawing(page);for(const id of ['valve','filter']){const a=beforeGroup.entities.find(e=>e.id===id)! as SymbolEntity,b=after.entities.find(e=>e.id===id)! as SymbolEntity;expect(b.position).toEqual({x:a.position.x+1,y:a.position.y-2});}expect(after.entities.at(-1)).toEqual(beforeGroup.entities.at(-1));
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(beforeGroup);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(after);const saved=await saveOpen(page);await page.reload();await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(1);expect(await drawing(page)).toEqual(saved);
});
test('endpoint grip retarget, invalid drag/Escape, inspector start pick, lifetime and locks',async({page})=>{
  await load(page,connectorDocument());const d=await drawing(page);const mid=await screen(page,4,0);await page.mouse.click(mid.x,mid.y);await expect(page.locator('[data-connector-grip="end"]')).toBeVisible();const grip=page.locator('[data-connector-grip="end"]'),box=(await grip.boundingBox())!,target=await screen(page,15,0);await page.mouse.move(box.x+5,box.y+5);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:8});await expect(page.getByTestId('connector-ghost')).toHaveCount(1);expect(await drawing(page)).toEqual(d);await page.mouse.up();await expect(page.getByTestId('connector-end')).toContainText('regulator · in');const retargeted=await drawing(page);expect(retargeted.entities.slice(0,-1)).toEqual(d.entities.slice(0,-1));await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(retargeted);
  const invalidGrip=(await page.locator('[data-connector-grip="end"]').boundingBox())!,empty=await screen(page,12,3);await page.mouse.move(invalidGrip.x+5,invalidGrip.y+5);await page.mouse.down();await page.mouse.move(empty.x,empty.y,{steps:4});await page.mouse.up();expect(await drawing(page)).toEqual(retargeted);await expect(page.getByTestId('editor-error')).toContainText('совместимый свободный порт');
  await page.getByRole('button',{name:'Выбрать порт: начало',exact:true}).click();await clickPort(page,'instrument','sense');expect(await drawing(page)).toEqual(retargeted);await expect(page.getByTestId('editor-error')).toContainText('Несовместимые');await page.getByRole('button',{name:'Выбрать порт: начало',exact:true}).click();await page.keyboard.press('Escape');expect(await drawing(page)).toEqual(retargeted);
  await page.mouse.click((await screen(page,4,0)).x,(await screen(page,4,0)).y);await page.getByRole('button',{name:'Выбрать порт: начало',exact:true}).click();await clickPort(page,'filter','out');await expect(page.getByTestId('connector-start')).toContainText('filter · out');
  await symbolClick(page,'filter');await page.getByRole('button',{name:/Удалить объект/}).click();await expect(page.getByTestId('editor-error')).toContainText('Символ имеет 1 подключения');await page.getByRole('button',{name:'Заблокировать слой Аннотации',exact:true}).click();await clickConnection(page);await expect(page.getByLabel('Маршрутизация соединения',{exact:true})).toBeDisabled();await expect(page.locator('[data-connector-grip]')).toHaveCount(0);
  await page.getByRole('button',{name:'Разблокировать слой Аннотации',exact:true}).click();await page.getByLabel('Маршрутизация соединения',{exact:true}).selectOption('direct');await expect(page.getByTestId('connector-route')).toHaveCount(1);await page.getByRole('button',{name:'Скрыть слой Аннотации',exact:true}).click();await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(0);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(5);await page.getByRole('button',{name:'Показать слой Аннотации',exact:true}).click();await clickConnection(page);await page.keyboard.press('Delete');await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(0);await symbolClick(page,'filter');await page.keyboard.press('Delete');await expect(page.locator('[data-entity-id="filter"]')).toHaveCount(0);
});
test('manual gas chain from library follows Filter, rotated Regulator, three-symbol group and persists',async({page})=>{
  test.setTimeout(90000);await load(page,createNewDocument());await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();const names=['Блок оборудования','Запорный кран','Фильтр','Регулятор давления','Счётчик газа','Блок оборудования'];const ids:string[]=[];
  for(let i=0;i<names.length;i++){await page.getByRole('button',{name:'Символы',exact:true}).click();await page.getByRole('button',{name:`Вставить символ: ${names[i]}`,exact:true}).click();const p=await screen(page,-15+i*6,0);await page.mouse.click(p.x,p.y);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(i+1);ids.push((await drawing(page)).entities.at(-1)!.id);if(i===0)for(let j=0;j<25&&Number(await page.getByTestId('drawing-canvas').getAttribute('data-zoom'))>10;j++)await page.getByRole('button',{name:'Уменьшить',exact:true}).click();await page.getByLabel('Имя / Tag',{exact:true}).fill(['Input','К-1','Ф-1','РД-1','СГ-1','Output'][i]!);await page.getByLabel('Имя / Tag',{exact:true}).press('Enter');}
  await editorCommand(page, 'Вписать');await page.getByRole('button',{name:'Выбрать слой Аннотации',exact:true}).click();for(let i=0;i<5;i++)await create(page,ids[i]!,ids[i+1]!);await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(5);
  await symbolClick(page,ids[2]!);await relative(page,0,3);await symbolClick(page,ids[3]!);await page.keyboard.press('r');await expect(page.getByLabel('Поворот (°)',{exact:true})).toHaveValue('90');await symbolClick(page,ids[2]!,true);await symbolClick(page,ids[4]!,true);await expect(page.getByTestId('group-properties')).toContainText('3 объектов');const before=await drawing(page);await relative(page,2,1);const after=await drawing(page);validateConnectivity(after);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(before);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(after);await saveOpen(page);await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(5);await page.screenshot({path:'/private/tmp/geoservice-connectors-gas-chain.png'});
});
test('DXF Canvas coexists with native port connections without redraw on connector interaction or symbol move',async({page})=>{
  test.setTimeout(120000);await load(page,createNewDocument());await editorCommand(page, 'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE??'src/tests/fixtures/dxf/simple_ascii.dxf');await page.getByTestId('dxf-report').waitFor();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);
  const original=await drawing(page),originalOwners=original.entities,canvas=page.getByTestId('drawing-canvas'),cx=Number(await canvas.getAttribute('data-center-x')),cy=Number(await canvas.getAttribute('data-center-y'));
  await page.getByRole('button',{name:'Создать слой',exact:true}).click();const ids:string[]=[];
  for(const [i,name] of ['Запорный кран','Фильтр'].entries()){await page.getByRole('button',{name:'Символы',exact:true}).click();await page.getByRole('button',{name:`Вставить символ: ${name}`,exact:true}).click();const p=await screen(page,cx+i*8,cy);await page.mouse.click(p.x,p.y);ids.push((await drawing(page)).entities.at(-1)!.id);}
  await page.getByRole('button',{name:'Выбрать слой Новый слой',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await expect(page.getByTestId('dxf-canvas').first()).toBeVisible();
  const metrics=()=>page.evaluate(async()=>{const {canvasMetrics}=await import(String('/src/renderer/CanvasSceneRenderer.ts'));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return canvasMetrics();});
  const before=await metrics();await create(page,ids[0]!,ids[1]!);await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(1);const connection=(await drawing(page)).entities.at(-1)! as ConnectorEntity;
  await page.getByRole('button',{name:'Инструмент: Соединение',exact:true}).click();await clickPort(page,ids[0]!,'out');await page.keyboard.press('Escape');await clickConnection(page);await symbolClick(page,ids[1]!);await relative(page,1,2);const after=await metrics();expect(after.draws).toBe(before.draws);expect(after.compilations).toBe(before.compilations);
  const changed=await drawing(page);expect(changed.entities.filter(e=>e.source?.kind==='dxf')).toEqual(originalOwners);expect(changed.blocks).toEqual(original.blocks);expect(changed.entities.at(-1)).toEqual(connection);await saveOpen(page);await expect(page.getByTestId('dxf-canvas').first()).toBeVisible();await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(1);
});
