import { test, expect, type Page } from '@playwright/test';
import { operationsFixture } from '../src/tests/fixtures/documentOperations';
import { readAutosaveDocument } from './helpers/autosave';
import type { DocumentAction } from '../src/documentOperations/schema';
import type { GeoDocument } from '../src/domain/model';
const buildings={kind:'semantic_concept' as const,concepts:['buildings' as const]};
const fixtureTasks:Record<string,DocumentAction[]>={
  'Выбери все здания.':[{type:'select_entities',query:buildings}],
  'Создай слой Здания и перенеси туда все здания.':[{type:'create_layer',name:'Здания'},{type:'move_entities_to_layer',query:buildings,target:{kind:'created_layer',actionIndex:0}}],
  'Скрой дороги и откосы.':[{type:'set_layer_visibility',query:{kind:'semantic_concept',concepts:['roads','slopes']},visible:false}],
  'Выбери все блоки VOLUME.':[{type:'select_entities',query:{kind:'block_name',name:'VOLUME'}}],
  'Найди все надписи со словом грунт.':[{type:'find_entities',query:{kind:'text_contains',text:'грунт',sourceType:null}}],
  'Найди 27.95.':[{type:'find_entities',query:{kind:'text_contains',text:'27.95',sourceType:null}}],
  'Покажи только здания.':[{type:'isolate_result',query:buildings}],
  'Перенеси выбранные объекты в слой Архив.':[{type:'move_entities_to_layer',query:{kind:'current_selection'},target:{kind:'existing_layer',name:'Архив'}}],
  'Выбери всё с исходного слоя _ГП_ЗИС.':[{type:'select_entities',query:{kind:'source_layer',name:'_ГП_ЗИС'}}],
};
async function setup(page:Page){await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));await page.route('**/api/ai/intent',r=>{const request=r.request().postDataJSON();expect(Object.keys(request)).toEqual(['text']);return r.fulfill({json:{intent:{actions:fixtureTasks[request.text]},unsupported:false}});});await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
async function open(page:Page,d:GeoDocument){page.once('dialog',d=>d.accept());await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'scene.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await expect.poll(async()=>(await readAutosaveDocument(page)).entities.length).toBe(d.entities.length);}
async function generate(page:Page,text:string){await page.getByLabel('Запрос',{exact:true}).fill(text);await page.getByRole('button',{name:'Generate plan',exact:true}).click();await expect(page.getByTestId('document-operations-preview')).toBeVisible();}
const preview=(page:Page)=>page.getByTestId('document-operations-preview');
test('local search and AI document workflow: preview/isolation/history/ATTRIB/fit',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await setup(page);await open(page,operationsFixture());const before=await readAutosaveDocument(page);
  await generate(page,'Выбери все здания.');await expect(preview(page)).toContainText('STRONG');await expect(preview(page)).toContainText('WEAK');await expect(page.locator('[data-query-owner]')).not.toHaveCount(0);await expect(page.locator('[data-query-owner="weak"]')).toHaveCount(0);const weak=preview(page).getByRole('checkbox',{name:/Включить Текст:/}).first();await weak.check();await expect(page.locator('[data-query-owner="weak"]')).toHaveCount(1);await weak.uncheck();expect(await readAutosaveDocument(page)).toEqual(before);
  await preview(page).getByRole('button',{name:'Выбрать',exact:true}).click();await expect(page.getByTestId('editor-error')).toContainText('Выбрано:');expect(await readAutosaveDocument(page)).toEqual(before);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();
  // The source fixture has a layer named Здания; rename it in the imported test data to avoid deliberate duplicate-target rejection.
  const unique={...before,layers:before.layers.map(l=>l.name==='Здания'?{...l,name:'Исходные вставки'}:l)};await open(page,unique);
  await generate(page,'Создай слой Здания и перенеси туда все здания.');await expect(preview(page)).toContainText('Будет создан слой: Здания');await preview(page).getByRole('button',{name:'Применить',exact:true}).click();await expect.poll(async()=>(await readAutosaveDocument(page)).layers.some(l=>l.name==='Здания')).toBe(true);const moved=await readAutosaveDocument(page);const target=moved.layers.find(l=>l.name==='Здания')!;expect(moved.entities.find(e=>e.id==='building')).toMatchObject({layerId:target.id,source:{originalLayer:'_ГП_ЗИС'}});
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(unique);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(moved);
  await generate(page,'Скрой дороги и откосы.');await preview(page).getByRole('button',{name:'Применить',exact:true}).click();await expect.poll(async()=>(await readAutosaveDocument(page)).layers.find(l=>l.id==='roads')?.visible).toBe(false);
  await generate(page,'Найди все надписи со словом грунт.');await expect(preview(page)).toContainText('Найдено: 1');await preview(page).getByRole('button',{name:'Показать на схеме',exact:true}).click();await expect(page.locator('[data-query-owner="mleader"]')).toHaveCount(1);await preview(page).getByRole('button',{name:'Применить',exact:true}).click();
  const search=page.getByLabel('Поиск в документе',{exact:true});await search.fill('VOLUME');await expect(page.locator('.search-results .query-result')).toHaveCount(2);await search.fill('грунт');await expect(page.locator('.search-results')).toContainText('Плодородный грунт');await page.locator('.search-results').getByRole('button',{name:'Fit',exact:true}).click();
  await generate(page,'Выбери все блоки VOLUME.');await expect(preview(page)).toContainText('Найдено: 2');await preview(page).getByRole('button',{name:'Выбрать',exact:true}).click();
  // Edit the actual instance ATTRIB through the inspector, not through AI.
  const d=await readAutosaveDocument(page),owner=d.entities.find(e=>e.type==='block_instance'&&e.attributePrimitives?.some(p=>p.kind==='text'&&p.content==='27.89'))!;
  await search.fill('27.89');await page.locator('.search-results .query-result').getByRole('button',{name:'27.89',exact:true}).click();await page.locator('.search-results .query-result').getByRole('button',{name:'Fit',exact:true}).click();
  const point=await page.evaluate(async({d,id}:{d:GeoDocument;id:string})=>{const {blockAttributeMatrix,blockMatrix,multiply,transformPoint}=await import(String('/src/vectors/geometry.ts'));const e=d.entities.find(e=>e.id===id);if(e?.type!=='block_instance')throw Error();const b=d.blocks!.find(b=>b.id===e.blockDefinitionId)!,a=e.attributePrimitives!.find(p=>p.kind==='text'&&p.content==='27.89');if(a?.kind!=='text')throw Error();const m=multiply(blockAttributeMatrix(e,b),blockMatrix({position:a.position,rotationDeg:a.rotationDeg,scaleX:1,scaleY:1},{x:0,y:0})),p=transformPoint({x:a.height*.35,y:a.height*.45},m),svg=document.querySelector('.drawing-canvas')!,r=svg.getBoundingClientRect(),z=Number(svg.getAttribute('data-zoom'));return {x:r.x+r.width/2+(p.x-Number(svg.getAttribute('data-center-x')))*z,y:r.y+r.height/2-(p.y-Number(svg.getAttribute('data-center-y')))*z};},{d,id:owner.id});
  for(let i=0;i<12;i++){await page.keyboard.down('Alt');await page.mouse.click(point.x,point.y);await page.keyboard.up('Alt');if(await page.getByLabel('Значение атрибута',{exact:true}).count())break;}
  await page.getByLabel('Значение атрибута',{exact:true}).fill('27.95');await page.getByLabel('Значение атрибута',{exact:true}).press('Enter');await search.fill('27.95');await expect(page.locator('.search-results')).toContainText('27.95');await generate(page,'Найди 27.95.');await expect(preview(page)).toContainText('Найдено: 1');await expect(page.locator(`[data-query-owner="${owner.id}"]`)).toHaveCount(1);
  const beforeIsolation=await readAutosaveDocument(page);await generate(page,'Покажи только здания.');await preview(page).getByRole('button',{name:'Применить',exact:true}).click();await expect(page.getByRole('button',{name:'Выйти из изоляции',exact:true})).toBeVisible();expect(await readAutosaveDocument(page)).toEqual(beforeIsolation);await page.getByRole('button',{name:'Выйти из изоляции',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(beforeIsolation);
  await generate(page,'Выбери всё с исходного слоя _ГП_ЗИС.');await preview(page).getByRole('button',{name:'Выбрать',exact:true}).click();await expect(page.getByTestId('selected-id')).toHaveText('building');expect(errors).toEqual([]);
});
test('document edits and current selection changes stale the preview until explicit refresh',async({page})=>{
  await setup(page);const d=operationsFixture();d.layers.push({id:'archive',name:'Архив',visible:true,locked:false,order:999,styleId:d.layers[0]!.styleId});await open(page,d);
  await page.getByLabel('Поиск в документе',{exact:true}).fill('грунт');await page.locator('.search-results .query-result').getByRole('button',{name:'Плодородный грунт, h=0.20 м',exact:true}).click();await generate(page,'Перенеси выбранные объекты в слой Архив.');await page.getByLabel('Поиск в документе',{exact:true}).fill('_ГП_ЗИС');await page.locator('.search-results .query-result').getByRole('button',{name:'Контур',exact:true}).click();await expect(preview(page)).toHaveAttribute('data-status','document-stale');await expect(preview(page).getByRole('button',{name:'Применить',exact:true})).toBeDisabled();await preview(page).getByRole('button',{name:'Обновить preview',exact:true}).click();await preview(page).getByRole('button',{name:'Применить',exact:true}).click();await expect.poll(async()=>(await readAutosaveDocument(page)).entities.find(e=>e.id==='building')?.layerId).toBe('archive');
});
test('reference local/AI queries expose actual buildings/layers/VOLUME/MLeader and edited ATTRIB',async({page})=>{
  test.skip(!process.env.DXF_REFERENCE,'Reference DXF local opt-in');test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await setup(page);await page.getByRole('button',{name:'DXF',exact:true}).click();await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await page.getByTestId('dxf-report').waitFor();await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);
  await generate(page,'Выбери все здания.');await expect(preview(page)).toContainText('_ГП_ЗИС');await preview(page).getByRole('button',{name:'Показать на схеме',exact:true}).click();await page.screenshot({path:'/private/tmp/geoservice-document-buildings.png',fullPage:true});
  await generate(page,'Выбери всё с исходного слоя _ГП_ЗИС.');await expect(preview(page)).toContainText('Найдено: 7');await generate(page,'Выбери все блоки VOLUME.');await expect(preview(page)).toContainText('Найдено: 62');await generate(page,'Найди все надписи со словом грунт.');await expect(preview(page)).toContainText('Плодородный грунт');await expect(preview(page)).toContainText('multileader');
  await page.getByLabel('Поиск в документе',{exact:true}).fill('27.89');await expect(page.locator('.search-results')).toContainText('27.89');expect(errors).toEqual([]);
});
