import { editorCommand } from './helpers/editorCommands';
import { expect, test, type Page } from '@playwright/test';
import { readAutosaveDocument } from './helpers/autosave';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { GeoDocument } from '../src/domain/model';
import { createProvenanceIndex } from '../src/dxf/provenance';
import { readAutosaveRecord } from './helpers/autosave';
const fixture=(name:string)=>resolve(`src/tests/fixtures/dxf/${name}.dxf`);
const errors=new WeakMap<Page,string[]>();
// Import/schema and SVG fallback DOM contracts; Canvas import/reload acceptance lives in hybrid-renderer.spec.
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});await page.goto('/?dxfRenderer=svg');await expect(page.getByTestId('drawing-canvas')).toBeVisible();});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
const drawing=(page:Page):Promise<GeoDocument>=>readAutosaveDocument(page);
async function preview(page:Page,name:string){await editorCommand(page, 'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(fixture(name));await expect(page.getByTestId('dxf-report')).toBeVisible();}
async function apply(page:Page){page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);}
async function imported(page:Page,name:string){await preview(page,name);await apply(page);}
async function screen(page:Page,x:number,y:number){const c=page.getByTestId('drawing-canvas'),b=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y'));return{x:b.x+b.width/2+(x-cx)*z,y:b.y+b.height/2-(y-cy)*z};}
async function relative(page:Page,x:number,y:number){await editorCommand(page, 'Переместить выбор');await page.getByLabel('Перемещение ΔX',{exact:true}).fill(String(x));await page.getByLabel('Перемещение ΔY',{exact:true}).fill(String(y));await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();}
test('DXF preview leaves drawing untouched; Apply, Fit, select LINE, Move and Undo',async({page})=>{
  const original=await drawing(page);await preview(page,'simple_ascii');expect(await drawing(page)).toEqual(original);await expect(page.getByTestId('dxf-report')).toContainText('AC1024');await expect(page.getByTestId('dxf-report')).toContainText('LINE');await apply(page);const d=await drawing(page);expect(d.entities).toHaveLength(3);await editorCommand(page, 'Вписать');const p=await screen(page,2196010,464815);await page.mouse.click(p.x,p.y);await expect(page.getByTestId('selected-id')).toHaveText(d.entities.find(e=>e.type==='line')!.id);await relative(page,5,7);await expect.poll(async()=>Object.values((await drawing(page)).vertices)[0]?.x).toBe(2196005);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);
});
test('Cyrillic layer survives decoding, Fit Layer and Hide/Show',async({page})=>{
  await imported(page,'cp1251_cyrillic');await page.getByRole('button',{name:'Выбрать слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await page.getByRole('button',{name:'Скрыть слой _ГП_ЗИС',exact:true}).click();await expect(page.locator('[data-entity-id]')).toHaveCount(0);await page.getByRole('button',{name:'Показать слой _ГП_ЗИС',exact:true}).click();await expect(page.locator('[data-entity-id]')).toHaveCount(2);
});
test('one block instance moves; shared SVG defs and another instance remain unchanged',async({page})=>{
  await imported(page,'blocks_nested');const d=await drawing(page);expect(d.blocks).toHaveLength(2);await expect(page.locator('[data-entity-type="block_instance"]')).toHaveCount(3);const p=await screen(page,100,202);await page.mouse.click(p.x,p.y);await expect(page.getByTestId('selected-id')).toHaveText('dxf-entity-0');await expect(page.getByRole('heading',{name:'Блок',exact:true})).toBeVisible();await relative(page,3,4);const changed=await drawing(page);expect(changed.blocks).toEqual(d.blocks);expect(changed.entities[1]).toEqual(d.entities[1]);expect(changed.entities[0]).toMatchObject({position:{x:103,y:204,z:0}});await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);
});
test('an unselected large vector bounds does not steal clicks from geometry inside its empty area',async({page})=>{
  await imported(page,'arc_circle');const d=await drawing(page),circle=d.entities.find(e=>e.type==='circle')!;if(circle.type!=='circle')throw Error();const inner={...circle,id:'inner',name:'Inner'},outer={...circle,id:'outer',name:'Outer',center:{x:0,y:0},radius:40};const overlap={...d,entities:[inner,outer]};await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'overlap.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(overlap))});await expect(page.locator('[data-entity-id]')).toHaveCount(2);const p=await screen(page,18,0);await page.mouse.click(p.x,p.y);await expect(page.getByTestId('selected-id')).toHaveText('inner');await relative(page,2,3);expect((await drawing(page)).entities[0]).toMatchObject({center:{x:17,y:3}});
});
test('Save JSON, New, Open JSON preserves block definitions, sources and attributes',async({page})=>{
  await imported(page,'blocks_nested');const d=await drawing(page);const downloadPromise=page.waitForEvent('download');await editorCommand(page, 'Сохранить JSON');const file=(await (await downloadPromise).path())!;expect(JSON.parse(await readFile(file,'utf8'))).toEqual(d);await editorCommand(page, 'Новый документ');await expect(page.locator('[data-entity-id]')).toHaveCount(0);await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(file);await expect(page.locator('[data-entity-type="block_instance"]')).toHaveCount(3);expect(await drawing(page)).toEqual(d);
});
test('invalid DXF and Cancel preserve document; Escape terminates preview',async({page})=>{
  const d=await drawing(page);await editorCommand(page, 'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(fixture('malformed'));await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Открыть как новый документ',exact:true})).toBeDisabled();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Отмена',exact:true}).click();await preview(page,'simple_ascii');await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);expect(await drawing(page)).toEqual(d);
});
test('unknown units block Apply until explicit choice; Local frame preserves coordinate scale',async({page})=>{
  await preview(page,'unitless');await expect(page.getByRole('button',{name:'Открыть как новый документ',exact:true})).toBeDisabled();await page.getByLabel('Единицы DXF',{exact:true}).selectOption('mm');await page.getByLabel('Система DXF',{exact:true}).selectOption('local');await expect(page.getByRole('button',{name:'Открыть как новый документ',exact:true})).toBeEnabled();await apply(page);const d=await drawing(page);expect(d.modelFrame).toBe('local');expect(Object.values(d.vertices)[0]?.x).toBe(2196);
});
test('marquee selects native arc and circle, and group Move/Undo preserves their shape',async({page})=>{
  await imported(page,'arc_circle');const d=await drawing(page);const a=await screen(page,0,5.3),b=await screen(page,18.5,-3.5);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();await expect(page.getByTestId('group-properties')).toContainText('2 объектов');await relative(page,2,3);expect((await drawing(page)).entities[1]).toMatchObject({center:{x:17,y:3},radius:3});await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);
});
test('proxy renders HATCH, DIMENSION and MULTILEADER without HTML/external resource requests',async({page})=>{
  const outbound:string[]=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:5173/')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))outbound.push(r.url());});await preview(page,'mixed_proxy');await expect(page.getByTestId('dxf-report')).toContainText('ELLIPSE');await apply(page);await expect(page.locator('[data-entity-type="imported_graphic"]')).toHaveCount(3);await expect(page.locator('[data-entity-id="dxf-entity-1"] use')).toHaveCount(1);expect(outbound).toEqual([]);
});
test('declined dirty replacement retains document and ready DXF preview',async({page})=>{
  await page.getByRole('button',{name:'Создать слой',exact:true}).click();const d=await drawing(page);await preview(page,'simple_ascii');page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toBeVisible();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Отмена',exact:true}).click();
});
test('reference DXF autosave, reload, integrity and edit (opt-in local file)',async({page})=>{
  test.skip(!process.env.DXF_REFERENCE,'Local reference file is not a CI fixture');test.setTimeout(60000);
  await editorCommand(page, 'DXF');const start=await page.evaluate(()=>performance.now());await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await expect(page.getByTestId('dxf-report')).toBeVisible();const previewMs=await page.evaluate(t=>performance.now()-t,start);await expect(page.getByTestId('dxf-report')).toContainText('458');
  const applyStart=Date.now(),renderStart=await page.evaluate(()=>performance.now());await apply(page);await expect(page.locator('[data-entity-id]')).toHaveCount(446);await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));const firstRenderMs=await page.evaluate(t=>performance.now()-t,renderStart);await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально',{timeout:30000});const autosaveAfterApplyMs=Date.now()-applyStart;
  const initial=await readAutosaveRecord(page);expect(initial).not.toBeNull();const d=initial!.document;expect(d.entities).toHaveLength(458);expect(d.layers).toHaveLength(127);expect(d.blocks).toHaveLength(450);expect(d.modelFrame).toBeTruthy();expect(d.sources?.[0]?.filename).toContain('p10b8003-7.dxf');expect(d.entities.filter(entity=>entity.type==='imported_graphic').length).toBeGreaterThan(0);expect(d.entities.some(entity=>entity.type==='arc')).toBe(true);expect(d.blocks!.some(block=>block.primitives.some(primitive=>primitive.kind==='circle'))).toBe(true);expect(d.blocks!.some(block=>block.primitives.some(primitive=>primitive.kind==='arc'))).toBe(true);expect(d.entities.filter(entity=>entity.type==='block_instance')).toHaveLength(102);expect(d.entities.some(entity=>entity.source?.kind==='dxf')).toBe(true);
  const index=createProvenanceIndex(d);expect(index.getEntitiesBySourceLayer('_ГП_ЗИС').length).toBeGreaterThan(0);expect(index.getBlockInstancesBySourceName('VOLUME')).toHaveLength(62);
  const fitStart=await page.evaluate(()=>performance.now());await page.getByRole('button',{name:'Выбрать слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>r())));const fitMs=await page.evaluate(t=>performance.now()-t,fitStart);
  const restoreStart=Date.now();await page.reload();await expect(page.locator('[data-entity-id]')).toHaveCount(446);await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально');const reloadRestoreMs=Date.now()-restoreStart;const restored=await readAutosaveRecord(page);expect(restored!.document).toEqual(d);await page.getByRole('button',{name:'Выбрать слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();
  const editStart=Date.now();await page.getByRole('button',{name:'Создать слой',exact:true}).click();await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально',{timeout:30000});const autosaveEditMs=Date.now()-editStart;const edited=await readAutosaveRecord(page);expect(edited!.document.layers).toHaveLength(128);expect(edited!.document.entities).toEqual(d.entities);expect(edited!.document.blocks).toEqual(d.blocks);
  const secondRestoreStart=Date.now();await page.reload();await expect(page.locator('[data-entity-id]')).toHaveCount(446);const secondReloadRestoreMs=Date.now()-secondRestoreStart;const final=await readAutosaveRecord(page);expect(final!.document.layers).toHaveLength(128);expect(createProvenanceIndex(final!.document).getBlockInstancesBySourceName('VOLUME')).toHaveLength(62);await page.screenshot({path:'/private/tmp/geoservice-dxf-browser-reference.png'});const results={previewMs,firstRenderMs,fitMs,autosaveAfterApplyMs,reloadRestoreMs,autosaveEditMs,secondReloadRestoreMs,serializedBytes:initial!.approximateSerializedBytes,entityCount:initial!.entityCount,domPrimitives:await page.locator('svg.drawing-canvas path,svg.drawing-canvas circle').count(),instances:await page.locator('[data-entity-type="block_instance"]').count()};await writeFile('docs/audit-results/dxf-browser.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));
});
