import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { readAutosaveDocument } from './helpers/autosave';
import type { BlockInstanceEntity, GeoDocument } from '../src/domain/model';
import type { DeepSelection } from '../src/editor/deepSelection';
import type { SemanticTextHit } from '../src/dxf/provenance';
import type { VectorPrimitive } from '../src/vectors/types';
type TextPrimitive=Extract<VectorPrimitive,{kind:'text'}>;

const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});await page.goto('/?dxfRenderer=canvas');await expect(page.getByTestId('drawing-canvas')).toBeVisible();});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
const drawing=(page:Page)=>readAutosaveDocument(page);
async function apply(page:Page){page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);}
async function screenFor(page:Page,doc:GeoDocument,ownerId:string,handle:string){
  return page.evaluate(async({doc,ownerId,handle}:{doc:GeoDocument;ownerId:string;handle:string})=>{
    const [{blockAttributeMatrix,blockDefinition,blockMatrix,multiply,transformPoint},{createHitStack,hitOwners}]=await Promise.all([import(String('/src/vectors/geometry.ts')),import(String('/src/editor/deepSelection.ts'))]);
    const owner=doc.entities.find(e=>e.id===ownerId);if(owner?.type!=='block_instance')throw Error('ATTRIB owner missing');const definition=blockDefinition(doc,owner.blockDefinitionId),attribute=owner.attributePrimitives?.find(p=>p.kind==='text'&&p.source?.handle===handle);if(!definition||attribute?.kind!=='text')throw Error('ATTRIB geometry missing');
    const text=blockMatrix({position:attribute.position,rotationDeg:attribute.rotationDeg,scaleX:1,scaleY:1},{x:0,y:0}),matrix=multiply(blockAttributeMatrix(owner,definition),text),world=transformPoint({x:attribute.height*.35,y:attribute.height*.45},matrix),zoom=Number(document.querySelector('.drawing-canvas')?.getAttribute('data-zoom')),svg=document.querySelector('.drawing-canvas')!,r=svg.getBoundingClientRect(),cx=Number(svg.getAttribute('data-center-x')),cy=Number(svg.getAttribute('data-center-y'));
    return {x:r.x+r.width/2+(world.x-cx)*zoom,y:r.y+r.height/2-(world.y-cy)*zoom,world,owners:hitOwners(doc,world,7/zoom,zoom),stack:createHitStack(doc,[ownerId],world,5/zoom).map((h:{selection:DeepSelection|null})=>h.selection)};
  },{doc,ownerId,handle});
}
async function deepSelectAttribute(page:Page,x:number,y:number,ownerId:string,handle:string){
  await page.mouse.click(x,y);await expect(page.getByTestId('selected-id')).toHaveText(ownerId);
  for(let i=0;i<300;i++){await page.keyboard.down('Alt');await page.mouse.click(x,y);await page.keyboard.up('Alt');if((await page.getByTestId('deep-properties').count())&&(await page.getByTestId('deep-properties').textContent())?.includes(handle))break;}
  await expect(page.getByRole('heading',{name:'Атрибут блока',exact:true})).toBeVisible();await expect(page.getByTestId('deep-properties')).toContainText(handle);
}
test('real reference ATTRIB is edited per instance, moved in MODEL, searched and persisted',async({page})=>{
  test.skip(!process.env.DXF_REFERENCE,'Reference DXF is local opt-in');test.setTimeout(180000);
  await page.getByRole('button',{name:'DXF',exact:true}).click();await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await page.getByTestId('dxf-report').waitFor();await apply(page);await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально',{timeout:60000});
  const before=await drawing(page),instances=before.entities.filter((e):e is BlockInstanceEntity=>e.type==='block_instance'),target=instances.find(e=>before.blocks?.find(b=>b.id===e.blockDefinitionId)?.sourceName==='_ТОПО'&&e.attributePrimitives?.some(p=>p.kind==='text'&&p.content==='27.89'))??instances.find(e=>e.attributePrimitives?.some(p=>p.kind==='text'&&p.source?.originalType==='ATTRIB'&&p.content==='27.89'));
  if(!target){const samples=instances.flatMap(e=>e.attributePrimitives?.filter((p):p is TextPrimitive=>p.kind==='text').map(p=>({owner:before.blocks?.find(b=>b.id===e.blockDefinitionId)?.sourceName,handle:p.source?.handle,tag:p.attributeTag,content:p.content}))??[]).slice(0,8),tagHits=instances.flatMap(e=>Object.entries(e.attributes??{}).filter(([,value])=>value==='27.89').map(([tag])=>({owner:before.blocks?.find(b=>b.id===e.blockDefinitionId)?.sourceName,tag})));throw Error(`Reference ATTRIB text 27.89 not found: ${JSON.stringify({samples,tagHits,attributeInstances:instances.filter(e=>Object.keys(e.attributes??{}).length).length,attributeGeometry:instances.filter(e=>e.attributePrimitives?.length).length})}`);}const attribute=target.attributePrimitives!.find((p):p is TextPrimitive=>p.kind==='text'&&p.content==='27.89')!;expect(attribute.source).toMatchObject({originalType:'ATTRIB',blockName:'_ТОПО'});expect(attribute.attributeTag).toBeTruthy();const handle=attribute.source?.handle;if(!handle)throw Error('Reference ATTRIB source handle missing');const ownerName=before.blocks?.find(b=>b.id===target.blockDefinitionId)?.sourceName??target.name;
  const point=await screenFor(page,before,target.id,handle);expect(point.owners).toContain(target.id);expect(point.stack.some((s:DeepSelection|null)=>s?.attribute&&s.attributeTag===attribute.attributeTag&&s.primitivePath.length===1)).toBe(true);
  await deepSelectAttribute(page,point.x,point.y,target.id,handle);await expect(page.getByLabel('Значение атрибута',{exact:true})).toHaveValue('27.89');await expect(page.getByTestId('deep-properties')).toContainText(ownerName);
  const siblings=before.entities.filter((e):e is BlockInstanceEntity=>e.type==='block_instance'&&e.id!==target.id&&e.blockDefinitionId===target.blockDefinitionId).map(e=>[e.id,e.attributes,e.attributePrimitives]);
  await page.getByLabel('Значение атрибута',{exact:true}).fill('27.95');await page.getByLabel('Значение атрибута',{exact:true}).press('Enter');await expect.poll(async()=>{const d=await drawing(page),e=d.entities.find(e=>e.id===target.id);return e?.type==='block_instance'?e.attributePrimitives?.find(p=>p.kind==='text'&&p.source?.handle===handle)?.kind==='text'?(e.attributePrimitives.find(p=>p.kind==='text'&&p.source?.handle===handle) as TextPrimitive).content:null:null;}).toBe('27.95');
  let changed=await drawing(page);expect(changed.entities.find(e=>e.id===target.id)).toMatchObject({position:target.position,source:target.source});expect((changed.entities.find(e=>e.id===target.id) as BlockInstanceEntity).attributePrimitives?.find((p):p is TextPrimitive=>p.kind==='text'&&p.source?.handle===handle)).toMatchObject({content:'27.95',attributeTag:attribute.attributeTag,source:attribute.source});expect(changed.blocks).toEqual(before.blocks);expect(changed.entities.filter((e):e is BlockInstanceEntity=>e.type==='block_instance'&&e.id!==target.id&&e.blockDefinitionId===target.blockDefinitionId).map(e=>[e.id,e.attributes,e.attributePrimitives])).toEqual(siblings);
  const index=await page.evaluate(async({d,id,tag}:{d:GeoDocument;id:string;tag:string})=>{const {createProvenanceIndex}=await import(String('/src/dxf/provenance.ts'));const p=createProvenanceIndex(d);return {text:p.searchText('27.95').some((hit:SemanticTextHit)=>hit.ownerEntityId===id&&hit.tag===tag),attribute:p.searchBlockAttributes('27.95').some((hit:SemanticTextHit)=>hit.ownerEntityId===id&&hit.tag===tag),summary:p.getEntitySemanticSummary(id)?.texts.some((hit:SemanticTextHit)=>hit.text==='27.95'&&hit.tag===tag)};},{d:changed,id:target.id,tag:attribute.attributeTag!});expect(index).toEqual({text:true,attribute:true,summary:true});
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(before);await page.getByRole('button',{name:'Повторить',exact:true}).click();changed=await drawing(page);expect((changed.entities.find(e=>e.id===target.id) as BlockInstanceEntity).attributePrimitives?.find((p):p is TextPrimitive=>p.kind==='text'&&p.source?.handle===handle)).toMatchObject({content:'27.95'});
  const movedStart=await screenFor(page,changed,target.id,handle);await deepSelectAttribute(page,movedStart.x,movedStart.y,target.id,handle);await page.mouse.move(movedStart.x,movedStart.y);await page.mouse.down();await page.mouse.move(movedStart.x+42,movedStart.y-18,{steps:5});await page.mouse.up();await expect.poll(async()=>{const d=await drawing(page),e=d.entities.find(e=>e.id===target.id);return e?.type==='block_instance'?e.attributePrimitives?.find(p=>p.kind==='text'&&p.source?.handle===handle)?.kind==='text'?(e.attributePrimitives.find(p=>p.kind==='text'&&p.source?.handle===handle) as TextPrimitive).position:null:null;}).not.toEqual(attribute.position);
  const afterDrag=await drawing(page),dragged=afterDrag.entities.find((e):e is BlockInstanceEntity=>e.id===target.id&&e.type==='block_instance');expect(dragged).toBeTruthy();if(!dragged)throw Error();expect(dragged.position).toEqual(target.position);expect(dragged.attributePrimitives?.find((p):p is TextPrimitive=>p.kind==='text'&&p.source?.handle===handle)).toMatchObject({content:'27.95',source:{originalType:'ATTRIB',handle}});expect(afterDrag.blocks).toEqual(before.blocks);expect(afterDrag.entities.filter((e):e is BlockInstanceEntity=>e.type==='block_instance'&&e.id!==target.id&&e.blockDefinitionId===target.blockDefinitionId).map(e=>[e.id,e.attributes,e.attributePrimitives])).toEqual(siblings);
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(changed);await page.getByRole('button',{name:'Повторить',exact:true}).click();changed=await drawing(page);expect(changed.entities.find(e=>e.id===target.id)).toMatchObject({position:target.position});
  const ownerHit=await screenFor(page,changed,target.id,handle);await page.mouse.click(ownerHit.x,ownerHit.y);await expect(page.getByTestId('selected-id')).toHaveText(target.id);await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('1');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('2');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();const moved=await drawing(page),movedOwner=moved.entities.find(e=>e.id===target.id)!;expect(movedOwner.type).toBe('block_instance');if(movedOwner.type!=='block_instance')throw Error();expect(movedOwner.position.x).toBeCloseTo(target.position.x+1,5);expect(movedOwner.position.y).toBeCloseTo(target.position.y+2,5);expect(movedOwner.attributePrimitives).toEqual((changed.entities.find(e=>e.id===target.id) as Extract<typeof target,{type:'block_instance'}>).attributePrimitives);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Сохранить JSON',exact:true}).click();const file=(await(await download).path())!;expect(JSON.parse(await readFile(file,'utf8'))).toEqual(moved);await page.reload();await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально',{timeout:60000});const restored=await drawing(page);expect(restored).toEqual(moved);const verified=await page.evaluate(async({d,id}:{d:GeoDocument;id:string})=>{const {createProvenanceIndex}=await import(String('/src/dxf/provenance.ts'));return createProvenanceIndex(d).searchText('27.95').some((hit:SemanticTextHit)=>hit.ownerEntityId===id);},{d:restored,id:target.id});expect(verified).toBe(true);
  expect(errors.get(page)).toEqual([]);
});
