import { editorCommand , openRightTab } from './helpers/editorCommands';
import { test, expect, type Page } from '@playwright/test';
import { createNewDocument } from '../src/domain/newDocument';
import { readAutosaveDocument, autosaveSnapshot } from './helpers/autosave';
function scene() { const d = createNewDocument(); d.metadata.id = 'view-hardening'; d.vertices = { a: { id: 'a', x: 0, y: 0 }, b: { id: 'b', x: 10, y: 5 } }; d.entities = [{ id: 'line', name: 'Shared MODEL line', type: 'line', layerId: 'boundary', startVertexId: 'a', endVertexId: 'b' }]; d.sources = [{ id: 'src', filename: 'fixture.dxf', format: 'DXF', dxfVersion: 'AC1027', encoding: 'utf-8', originalUnits: 6 }]; d.dxfLayouts = [{ id: 'paper', sourceDocumentId: 'src', name: '*Paper_Space', nameAvailable: false, paperSpaceOwner: 'p', paperPrimitives: [{ kind: 'text', content: 'Paper Title', position: { x: 20, y: 20 }, height: 2, rotationDeg: 0, layerId: 'boundary', colorMode: 'bylayer' }], viewports: [{ id: 'vp1', number: 2, centerPaper: { x: 100, y: 100 }, sizePaper: { width: 80, height: 60 }, modelCenter: { x: 0, y: 0 }, viewHeight: 60, scale: 1, twist: 27, clip: { kind: 'rectangle' }, frozenSourceLayerNames: [] }, { id: 'vp2', number: 3, centerPaper: { x: 200, y: 100 }, sizePaper: { width: 80, height: 60 }, modelCenter: { x: 0, y: 0 }, viewHeight: 60, scale: 1, twist: 0, clip: { kind: 'rectangle' }, frozenSourceLayerNames: [] }] }]; return d; }
async function setup(page: Page) { const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error')
    errors.push(m.text()); }); await page.goto('/'); await page.getByTestId('drawing-canvas').waitFor(); await page.getByLabel('Файл GeoDocument', { exact: true }).setInputFiles({ name: 'view.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(scene())) }); await readAutosaveDocument(page); return errors; }
async function pan(page: Page, testid = 'drawing-canvas') { const canvas = page.getByTestId(testid), before = await canvas.getAttribute('data-center-x'), b = (await canvas.boundingBox())!; await page.keyboard.down('Space'); await page.mouse.move(b.x + b.width * .5, b.y + b.height * .45); await page.mouse.down(); await page.mouse.move(b.x + b.width * .5 + 50, b.y + b.height * .45 + 20, { steps: 5 }); await page.mouse.up(); await page.keyboard.up('Space'); await expect(canvas).not.toHaveAttribute('data-center-x', before!); }
async function openViews(page: Page) { const d = page.getByTestId('dxf-views'); if (await d.getAttribute('open') === null)
    await d.locator('>summary').click(); return d; }
test('shared popup dismissal, peers, nested content and Escape priority', async ({ page }) => { await page.setViewportSize({ width: 1024, height: 900 }); const errors = await setup(page); const more = page.locator('.toolbar-menu').filter({ hasText: 'Ещё' }); await more.locator('>summary').click(); await expect(more).toHaveAttribute('open', ''); await page.getByTestId('drawing-canvas').click({ position: { x: 30, y: 30 } }); await expect(more).not.toHaveAttribute('open', ''); const layer = page.locator('[data-layer-id="boundary"] .layer-menu'); await layer.locator('summary').click(); await openRightTab(page,'search');await page.getByLabel('Поиск в документе', { exact: true }).click(); await expect(layer).not.toHaveAttribute('open', ''); await more.locator('>summary').click(); const views = await openViews(page); await expect(more).not.toHaveAttribute('open', ''); await views.getByTestId('dxf-paper-node').locator('details>summary').click(); await expect(views).toHaveAttribute('open', ''); await page.keyboard.press('Escape'); await expect(views).not.toHaveAttribute('open', ''); await expect(page.getByRole('button', { name: 'Инструмент: Выбор', exact: true })).toHaveAttribute('aria-pressed', 'true'); await page.getByRole('button', { name: 'Символы', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Библиотека символов' })).toBeVisible(); await page.locator('[data-dialog-backdrop]').click({ position: { x: 2, y: 2 } }); await expect(page.getByRole('dialog', { name: 'Библиотека символов' })).toHaveCount(0); expect(errors).toEqual([]); });
test('pointer select returns canvas focus, keyboard select stays usable; text Space stays text', async ({ page }) => { const errors = await setup(page); const view = page.getByLabel('Вид', { exact: true }); await view.selectOption('NE'); await view.selectOption('plan'); await view.dispatchEvent('pointerdown'); await view.selectOption('plan'); await expect(page.getByTestId('drawing-canvas')).toBeFocused(); await pan(page); await expect(view).toHaveValue('plan'); await openRightTab(page,'search'); const search = page.getByLabel('Поиск в документе', { exact: true }); await search.fill('Дом'); await search.press('Space'); await expect(search).toHaveValue('Дом '); await openRightTab(page,'ai'); const prompt = page.getByLabel('Запрос', { exact: true }); await prompt.fill('План'); await prompt.press('Space'); await expect(prompt).toHaveValue('План '); await page.getByTestId('drawing-canvas').click({ position: { x: 30, y: 30 } }); await pan(page); await view.focus(); await view.press('ArrowDown'); await view.press('Enter'); await expect(view).toBeFocused(); expect(errors).toEqual([]); });
test('working angle/align/ORTHO/North preserve document; independent Axon, Fit and Space', async ({ page }) => { const errors = await setup(page), snapshot = await autosaveSnapshot(page); await page.locator('.view-orientation>summary').click(); await page.getByLabel('Поворот вида, °', { exact: true }).fill('27');await page.getByLabel('Поворот вида, °',{exact:true}).press('Enter'); await page.getByTestId('drawing-canvas').click({ position: { x: 20, y: 20 } }); await page.getByRole('button', { name: 'Вписать схему в вид', exact: true }).click(); await expect(page.getByTestId('drawing-canvas')).toHaveAttribute('data-view-angle', '27'); await expect(page.getByTestId('north-arrow')).not.toHaveAttribute('data-screen-x', '0'); await pan(page); await page.getByLabel('Вид', { exact: true }).selectOption('NE'); await pan(page); await page.getByLabel('Вид', { exact: true }).selectOption('plan'); await expect(page.getByTestId('drawing-canvas')).toHaveAttribute('data-view-angle', '27'); expect(await autosaveSnapshot(page)).toEqual(snapshot); await page.locator('.view-orientation>summary').click(); await page.getByRole('button', { name: 'Север вверх', exact: true }).click(); await expect(page.getByTestId('drawing-canvas')).toHaveAttribute('data-view-angle', '0'); expect(errors).toEqual([]); });
test('active MODEL viewport canonical line creation, Rotate, Undo, exit and Space sheet pan', async ({ page }) => { const errors = await setup(page), before = await readAutosaveDocument(page); await page.getByLabel('DXF контекст', { exact: true }).selectOption('paper'); await pan(page, 'layout-canvas'); const views = await openViews(page), node = views.getByTestId('dxf-paper-node'); await node.locator('details>summary').click(); await node.getByRole('button', { name: 'Редактировать модель · Viewport 1', exact: true }).click(); await expect(page.locator('.layout-note')).toContainText('Редактирование модели'); await expect(page.locator('.active-viewport-editor')).toBeVisible(); const sheetCamera = await page.getByTestId('layout-canvas').getAttribute('data-center-x'); await pan(page); await expect(page.getByTestId('layout-canvas')).toHaveAttribute('data-center-x', sheetCamera!); await editorCommand(page, 'Инструмент: Линия'); const box = (await page.locator('[data-viewport-id="vp1"]>svg').boundingBox())!; await page.mouse.click(box.x + box.width * .4, box.y + box.height * .4); await page.mouse.click(box.x + box.width * .6, box.y + box.height * .6); let d = await readAutosaveDocument(page); expect(d.entities).toHaveLength(before.entities.length + 1); expect(d.dxfLayouts).toEqual(before.dxfLayouts); const added = d.entities.at(-1)!; await page.getByLabel('Угол поворота выделения', { exact: true }).fill('30'); await page.getByRole('button', { name: 'Применить поворот', exact: true }).click(); d = await readAutosaveDocument(page); expect(d.vertices).not.toEqual(before.vertices); await editorCommand(page, 'Отменить'); await editorCommand(page, 'Отменить'); expect((await readAutosaveDocument(page)).entities).toEqual(before.entities); await page.getByRole('button', { name: 'Выйти в лист', exact: true }).click(); await expect(page.locator('.active-viewport-editor')).toHaveCount(0); await pan(page, 'layout-canvas'); await page.getByLabel('DXF контекст', { exact: true }).selectOption('model'); expect((await readAutosaveDocument(page)).entities.some(e => e.id === added.id)).toBe(false); expect(errors).toEqual([]); });
for (const width of [1920, 1600, 1440, 1366, 1280, 1024])
    test(`compact semantic toolbar, search and import ${width}`, async ({ page }) => { await page.setViewportSize({ width, height: 800 }); const errors = await setup(page); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await expect(page.getByRole('button', { name: 'Символы', exact: true })).toBeVisible(); for (const name of ['Файл / данные', 'Правка', 'Линия', 'Инженерия'])
        await expect(page.locator('.toolbar-menu>summary').filter({ hasText: name })).toBeVisible(); await expect(page.getByLabel('Сетка', { exact: true })).toBeVisible(); await expect(page.getByLabel('DXF renderer', { exact: true })).toHaveCount(0); await editorCommand(page, 'DXF'); const modal = page.getByRole('dialog'); const b = await modal.boundingBox(); expect(b!.y + b!.height).toBeLessThanOrEqual(800); await expect(page.getByRole('button', { name: 'Выбрать файл', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Открыть как новый документ', exact: true })).toBeVisible(); expect(errors).toEqual([]); });
test('reference hierarchy/scopes/readonly explication fresh import', async ({ page }) => { test.skip(!process.env.DXF_REFERENCE); test.setTimeout(120000); const errors = await setup(page); await editorCommand(page, 'DXF'); await page.getByLabel('Файл DXF', { exact: true }).setInputFiles(process.env.DXF_REFERENCE!); await page.getByTestId('dxf-report').waitFor(); await expect(page.getByTestId('dxf-report')).not.toContainText('Paper Space skipped'); await page.getByRole('button', { name: 'Открыть как новый документ', exact: true }).click(); const before = await readAutosaveDocument(page); let views = await openViews(page); await expect(views.getByTestId('dxf-paper-node')).toHaveCount(5); await expect(views.getByText('Имя исходного листа отсутствует в DXF',{exact:true})).toHaveCount(5); for (let i = 0; i < 5; i++) {
    const node = views.getByTestId('dxf-paper-node').nth(i);
    await node.locator('details>summary').click();
    await expect(node.getByTestId('dxf-viewport-node')).toHaveCount([2, 2, 3, 6, 2][i]!);
} await views.getByRole('button', { name: 'Выбрать все объекты Model', exact: true }).click(); await expect(page.locator('.scope-summary')).toContainText('MODEL: 458'); views = await openViews(page); await views.getByRole('button', { name: 'Paper Space *Paper_Space289', exact: true }).click(); await expect(page.getByTestId('layout-viewport')).toHaveCount(6); await openRightTab(page,'search');await page.getByLabel('Категория поиска', { exact: true }).selectOption('tables'); await openRightTab(page,'search');await page.getByLabel('Поиск в документе', { exact: true }).fill('ЭКСПЛИКАЦИЯ'); const table = page.locator('.table-result').filter({ hasText: 'ЭКСПЛИКАЦИЯ' }); await expect(table).toHaveCount(1); await table.locator('>summary').click(); await expect(table).toContainText('Определение без экземпляра'); await expect(table).toContainText('Блок-здание технологическое'); await expect(table).toContainText('*T35'); expect(await readAutosaveDocument(page)).toEqual(before); expect(errors).toEqual([]); });
test('Escape closes popup, then cancels drawing draft, then tool on separate keys', async ({ page }) => { const errors = await setup(page); await editorCommand(page, 'Инструмент: Линия'); await page.getByTestId('drawing-canvas').click({ position: { x: 150, y: 150 } }); await page.locator('.current-style>summary').click(); await page.keyboard.press('Escape'); await expect(page.locator('.drawing-preview')).toBeVisible(); await page.getByTestId('drawing-canvas').focus(); await page.keyboard.press('Escape'); await expect(page.locator('.drawing-preview')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Инструмент: Линия', exact: true, includeHidden: true })).toHaveAttribute('aria-pressed', 'true'); await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'Инструмент: Выбор', exact: true })).toHaveAttribute('aria-pressed', 'true'); expect(errors).toEqual([]); });

test('nested palette item executes before dismissal; wheel closes unrelated popup',async({page})=>{const errors=await setup(page);const before=await readAutosaveDocument(page);await page.getByRole('button',{name:'Символы',exact:true}).click();await page.getByRole('button',{name:'Вставить символ: Фильтр',exact:true}).click();await expect(page.getByRole('dialog',{name:'Библиотека символов'})).toHaveCount(0);await expect(page.getByTestId('drawing-canvas')).toBeFocused();await page.getByTestId('drawing-canvas').click({position:{x:300,y:300}});const after=await readAutosaveDocument(page);expect(after.entities).toHaveLength(before.entities.length+1);expect(after.entities.at(-1)?.type).toBe('symbol');await page.locator('.current-style>summary').click();const b=(await page.getByTestId('drawing-canvas').boundingBox())!;await page.mouse.move(b.x+100,b.y+100);await page.mouse.wheel(0,-30);await expect(page.locator('.current-style')).not.toHaveAttribute('open','');expect(errors).toEqual([]);});
test('pointer canvas control completes focus before immediate Space pan', async ({ page }) => {
  const errors = await setup(page), canvas = page.getByTestId('drawing-canvas');
  await page.getByRole('button', { name: 'Увеличить', exact: true }).click();
  expect(await canvas.evaluate(e => document.activeElement === e)).toBe(true);
  await pan(page); expect(errors).toEqual([]);
});
test('mixed Paper selection allows global layer visibility without changing viewport Freeze', async ({ page }) => {
  await setup(page); await page.getByLabel('DXF контекст', { exact: true }).selectOption('paper');
  const before = await readAutosaveDocument(page), layer = before.layers.find(l => l.id === 'boundary')!;
  const views = await openViews(page); await views.getByRole('button', { name: 'Всё видимое на листе', exact: true }).click();
  await expect(page.locator('.scope-summary')).toContainText('Paper');
  await page.getByRole('button', { name: `Скрыть слой ${layer.name}`, exact: true }).click();
  const hidden = await readAutosaveDocument(page); expect(hidden.layers.find(l => l.id === layer.id)!.visible).toBe(false); expect(hidden.dxfLayouts).toEqual(before.dxfLayouts);
  await editorCommand(page, 'Отменить'); expect((await readAutosaveDocument(page)).layers).toEqual(before.layers);
});
test('native text Undo does not undo document history; canvas Undo resumes after pointer focus', async ({ page }) => {
  const errors = await setup(page), canvas = page.getByTestId('drawing-canvas');
  await editorCommand(page, 'Инструмент: Линия'); await canvas.click({ position: { x: 200, y: 150 } }); await canvas.click({ position: { x: 300, y: 200 } });
  const before = await readAutosaveDocument(page);
  for (const [tab,input] of [['search',page.getByLabel('Поиск в документе', { exact: true })], ['ai',page.getByLabel('Запрос', { exact: true })]]as const) {
    await openRightTab(page,tab);await input.fill('draft'); await input.pressSequentially(' text'); await input.press(process.platform === 'darwin' ? 'Meta+z' : 'Control+z');
    await expect(input).not.toHaveValue('draft text'); expect(await readAutosaveDocument(page)).toEqual(before); await expect(input).toBeFocused();
  }
  await canvas.click({ position: { x: 60, y: 50 } }); await page.keyboard.press('Control+z'); expect((await readAutosaveDocument(page)).entities).toHaveLength(before.entities.length - 1); expect(errors).toEqual([]);
});
test('Escape cancels active viewport marquee before exiting the viewport', async ({ page }) => {
  await setup(page); await page.getByLabel('DXF контекст', { exact: true }).selectOption('paper');
  const views = await openViews(page); await views.getByTestId('dxf-paper-node').locator('details>summary').click();
  await views.getByRole('button', { name: 'Редактировать модель · Viewport 1', exact: true }).click();
  const box = (await page.locator('.active-viewport-editor').boundingBox())!;
  await page.mouse.move(box.x + box.width * .2, box.y + box.height * .2); await page.mouse.down(); await page.mouse.move(box.x + box.width * .35, box.y + box.height * .35, { steps: 3 });
  await expect(page.getByTestId('marquee-selection')).toBeVisible(); await page.keyboard.press('Escape');
  await expect(page.getByTestId('marquee-selection')).toHaveCount(0); await expect(page.locator('.active-viewport-editor')).toBeVisible();
  await page.mouse.up(); await page.keyboard.press('Escape'); await expect(page.locator('.active-viewport-editor')).toHaveCount(0);
});
test('active viewport text form stays inside its visible clip and supports pointer Cancel and Submit', async ({ page }) => {
  await setup(page); const before = await readAutosaveDocument(page);
  await page.getByLabel('DXF контекст', { exact: true }).selectOption('paper'); const views = await openViews(page); await views.getByTestId('dxf-paper-node').locator('details>summary').click(); await views.getByRole('button', { name: 'Редактировать модель · Viewport 1', exact: true }).click();
  await editorCommand(page, 'Инструмент: Текст'); const box = (await page.locator('.active-viewport-editor').boundingBox())!;
  await page.mouse.click(box.x + box.width - 20, box.y + box.height - 20); const form = page.locator('.text-entry'), entry = (await form.boundingBox())!;
  expect(entry.x + entry.width).toBeLessThanOrEqual(box.x + box.width); expect(entry.y + entry.height).toBeLessThanOrEqual(box.y + box.height);
  await form.getByRole('button', { name: 'Отмена', exact: true }).click(); await expect(form).toHaveCount(0); expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);
  await editorCommand(page, 'Инструмент: Текст'); await page.mouse.click(box.x + box.width - 20, box.y + box.height - 20); await page.getByLabel('Текст аннотации', { exact: true }).fill('Viewport text'); await form.getByRole('button', { name: 'Готово', exact: true }).click(); const after = await readAutosaveDocument(page); expect(after.entities).toHaveLength(before.entities.length + 1); expect(after.entities.at(-1)).toMatchObject({ type: 'text', content: 'Viewport text' }); expect(after.dxfLayouts).toEqual(before.dxfLayouts); await editorCommand(page, 'Отменить'); expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);
});
