import {expect,test,type Page} from '@playwright/test';
import {createNewDocument} from '../src/domain/newDocument';
import {editorCommand} from './helpers/editorCommands';
import {readAutosaveDocument} from './helpers/autosave';
async function setup(page:Page){await page.addInitScript(d=>{if(!sessionStorage.getItem('hardening-seed')){localStorage.setItem('geoservice.document.v2',JSON.stringify(d));sessionStorage.setItem('hardening-seed','yes');}},createNewDocument());await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
async function image(page:Page,kind:string){const png=await page.evaluate(async kind=>{const {reconstructionFixture}=await import(String('/src/tests/fixtures/reconstruction.ts'));const image=reconstructionFixture(kind as 'straight'),canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d')!.putImageData(new ImageData(image.data,image.width,image.height),0,0);return canvas.toDataURL().split(',')[1];},kind);await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles({name:kind+'.png',mimeType:'image/png',buffer:Buffer.from(png!,'base64')});await expect(page.getByTestId('underlay-properties')).toBeVisible();await editorCommand(page,'Векторизация изображения');}
async function extract(page:Page){await page.getByRole('button',{name:'4. Извлечение',exact:true}).click();await page.getByRole('button',{name:'Извлечь геометрию',exact:true}).click();await expect(page.getByRole('button',{name:'Распознать текст и символы',exact:true})).toBeEnabled();}
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))list.push(m.text());});});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
for(const [kind,type,count]of [['straight','line',1],['corner','line',2],['T','line',3],['X','line',4],['arc','arc',1],['circle','circle',1]] as const)test(`raster ${kind}: reconstructed ${type}, atomic Apply and source unchanged`,async({page})=>{await setup(page);await image(page,kind);const before=await readAutosaveDocument(page);await extract(page);await expect(page.locator(`[data-candidate-type="${type}"]`)).toHaveCount(count);await page.getByRole('button',{name:/Применить геометрию/}).click();const applied=await readAutosaveDocument(page);expect(applied.entities.filter(e=>e.type===type)).toHaveLength(count);expect(applied.entities.find(e=>e.type==='raster_underlay')).toEqual(before.entities.find(e=>e.type==='raster_underlay'));if(kind==='T'||kind==='X'){const owners=applied.entities.filter(e=>e.type==='line'),ids=owners.flatMap(e=>e.type==='line'?[e.startVertexId,e.endVertexId]:[]);expect([...new Set(ids)].some(id=>ids.filter(x=>x===id).length===count)).toBe(true);}await editorCommand(page,'Отменить');expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);});
test('deskew: reliable 2.5° suggestion requires confirmation, numeric fine rotation is distinct',async({page})=>{await setup(page);await image(page,'deskew');const before=await readAutosaveDocument(page);await page.getByRole('button',{name:'2. Перспектива',exact:true}).click();await page.getByRole('button',{name:'Оценить наклон',exact:true}).click();await expect(page.getByRole('button',{name:'Выровнять',exact:true})).toBeVisible();const detected=await page.getByLabel('Поворот анализа, °',{exact:true}).inputValue();expect(detected).toBe('0');await page.getByRole('button',{name:'Выровнять',exact:true}).click();expect(Number(await page.getByLabel('Поворот анализа, °',{exact:true}).inputValue())).toBeCloseTo(-2.5,0);await page.getByRole('button',{name:'+0.1°',exact:true}).click();await extract(page);await expect(page.locator('[data-candidate-type="line"]')).toHaveCount(1);await page.getByRole('button',{name:'Отмена',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(before);});
for(const route of ['vector','scan','mixed']as const)test(`PDF ${route}: local routing, native content and Cancel/Apply`,async({page})=>{await setup(page);const external:string[]=[];page.context().on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());});const before=await readAutosaveDocument(page);await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles(`e2e/fixtures/pdf/${route}.pdf`);await expect(page.getByTestId('pdf-route')).toContainText(route==='scan'?'PDF-скан':route==='mixed'?'Смешанный PDF':'Векторный PDF');if(route==='vector'){await page.getByLabel('Страница PDF',{exact:true}).selectOption('2');await expect(page.locator('.pdf-candidate-list input:not([type=checkbox])')).toHaveValue('SECOND PAGE');await page.getByLabel('Страница PDF',{exact:true}).selectOption('1');await expect(page.locator('.pdf-candidate-list input:not([type=checkbox])')).toHaveValue('ГАЗ V-101 H=28.40');}if(route==='scan'){await page.getByRole('button',{name:'Добавить скан и открыть анализ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Векторизация изображения',exact:true})).toBeVisible();await page.getByRole('button',{name:'Отмена',exact:true}).click();expect((await readAutosaveDocument(page)).entities.filter(e=>e.type==='raster_underlay')).toHaveLength(1);}else {const row=page.locator('.pdf-candidate-list>div').filter({has:page.locator('input:not([type=checkbox])')});await row.locator('input[type=checkbox]').check();await page.getByRole('button',{name:/Применить PDF/}).click();const d=await readAutosaveDocument(page);expect(d.entities.some(e=>e.type==='line')).toBe(true);expect(d.entities.some(e=>e.type==='text'&&e.content==='ГАЗ V-101 H=28.40'&&e.imageSource?.source==='pdf-vector')).toBe(true);expect(d.entities.some(e=>e.type==='raster_underlay')).toBe(false);await editorCommand(page,'Отменить');expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);}expect(external).toEqual([]);});
test('Settings persistence, session versus explicit device key, narrow dialog and unchanged GeoDocument',async({page})=>{await setup(page);const before=await readAutosaveDocument(page);await editorCommand(page,'Настройки');let d=page.getByRole('dialog',{name:'Настройки',exact:true});await d.getByRole('tab',{name:'AI',exact:true}).click();await page.getByLabel('Основная AI модель',{exact:true}).fill('qwen/local-test');await page.getByLabel('Резервная AI модель',{exact:true}).fill('qwen/local-fallback');await page.getByLabel('AI timeout',{exact:true}).fill('12');await page.getByLabel('Повторы AI',{exact:true}).selectOption('1');await page.getByLabel('AI API key',{exact:true}).fill('session-test-only');await d.getByRole('tab',{name:'Редактор',exact:true}).click();await page.getByLabel('SNAP по умолчанию',{exact:true}).uncheck();await page.getByLabel('Шаг сетки по умолчанию',{exact:true}).fill('2.5');await d.getByRole('button',{name:'Готово',exact:true}).click();await page.reload();await editorCommand(page,'Настройки');d=page.getByRole('dialog',{name:'Настройки',exact:true});await d.getByRole('tab',{name:'AI',exact:true}).click();await expect(page.getByLabel('Основная AI модель',{exact:true})).toHaveValue('qwen/local-test');await expect(page.getByLabel('Резервная AI модель',{exact:true})).toHaveValue('qwen/local-fallback');await expect(page.getByLabel('AI timeout',{exact:true})).toHaveValue('12');await expect(page.getByLabel('Повторы AI',{exact:true})).toHaveValue('1');await expect(page.getByLabel('AI API key',{exact:true})).toHaveValue('');await page.getByLabel('AI API key',{exact:true}).fill('remember-test-only');await page.getByLabel('Запомнить ключ на этом устройстве',{exact:true}).check();await page.reload();await editorCommand(page,'Настройки');d=page.getByRole('dialog',{name:'Настройки',exact:true});await d.getByRole('tab',{name:'AI',exact:true}).click();await expect(page.getByLabel('AI API key',{exact:true})).toHaveValue('remember-test-only');await page.getByLabel('Запомнить ключ на этом устройстве',{exact:true}).uncheck();expect(await page.evaluate(()=>localStorage.getItem('geoservice.ai-device-key.v1'))).toBeNull();await d.getByRole('tab',{name:'Редактор',exact:true}).click();await expect(page.getByLabel('SNAP по умолчанию',{exact:true})).not.toBeChecked();await expect(page.getByLabel('Шаг сетки по умолчанию',{exact:true})).toHaveValue('2.5');await page.setViewportSize({width:390,height:650});expect(await d.evaluate(e=>e.scrollWidth<=e.clientWidth&&e.getBoundingClientRect().right<=innerWidth)).toBe(true);await page.keyboard.press('Escape');expect(await readAutosaveDocument(page)).toEqual(before);});
test('one right tab, preserved Search/AI drafts, Cmd+F focus and immediate orientation interactions',async({page})=>{await setup(page);await expect(page.getByRole('complementary',{name:'Свойства объекта'})).toBeVisible();await expect(page.locator('.document-search')).toBeHidden();await expect(page.locator('.ai-panel')).toBeHidden();await page.keyboard.press('Control+f');const search=page.getByLabel('Поиск в документе',{exact:true});await expect(search).toBeFocused();await search.fill('draft query');await page.getByRole('tab',{name:'AI',exact:true}).click();await page.getByLabel('Запрос',{exact:true}).fill('draft prompt');await page.getByRole('tab',{name:'Поиск',exact:true}).click();await expect(search).toHaveValue('draft query');await page.getByRole('tab',{name:'AI',exact:true}).click();await expect(page.getByLabel('Запрос',{exact:true})).toHaveValue('draft prompt');await page.getByTestId('drawing-canvas').focus();await page.locator('.view-orientation>summary').click();await page.getByRole('button',{name:'Повернуть вид 90°',exact:true}).click();await page.locator('.view-orientation>summary').click();await expect(page.getByLabel('Поворот вида, °',{exact:true})).toHaveValue('90');await page.getByLabel('Поворот вида, °',{exact:true}).fill('12.5');await page.getByLabel('Поворот вида, °',{exact:true}).press('Enter');await expect(page.locator('.view-orientation>summary')).toContainText('12.5°');await page.getByRole('button',{name:'Выровнять горизонтально по 2 точкам',exact:true}).click();await expect(page.locator('.view-orientation')).not.toHaveAttribute('open','');await expect(page.locator('.canvas-help')).toContainText('Укажите две точки');await page.keyboard.press('Escape');await expect(page.locator('.canvas-help')).not.toContainText('Укажите две точки');});

test('changing AI settings cancels pending parse; invalid key draft stays inside Settings',async({page})=>{
 await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));
 let release=()=>{};const pending=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/ai/intent',async r=>{await pending;await r.fulfill({json:{actions:[{type:'create_rectangle',name:'Old request',width:1,height:1,placement:{type:'local_origin'}}]}}).catch(()=>{});});
 await setup(page);const before=await readAutosaveDocument(page);
 await page.getByRole('button',{name:'AI Assistant',exact:true}).click();await expect(page.getByRole('button',{name:'Generate plan',exact:true})).toBeEnabled();
 const requested=page.waitForRequest('**/api/ai/intent');await page.getByLabel('Запрос',{exact:true}).fill('Нарисуй прямоугольник 1x1 м');await page.getByRole('button',{name:'Generate plan',exact:true}).click();await requested;
 await page.getByRole('tab',{name:'Поиск',exact:true}).click();await page.getByRole('tab',{name:'AI',exact:true}).click();await expect(page.locator('.ai-panel')).toContainText('Разбираем запрос');
 await page.getByRole('button',{name:'Настройки AI',exact:true}).click();await page.getByLabel('AI включён',{exact:true}).uncheck();release();
 await page.getByLabel('AI API key',{exact:true}).fill('invalid key');await page.getByLabel('Запомнить ключ на этом устройстве',{exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:'Ключ должен'})).toBeVisible();await expect(page.getByLabel('Запомнить ключ на этом устройстве',{exact:true})).not.toBeChecked();
 await expect(page.getByRole('button',{name:'Проверить подключение',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Готово',exact:true}).click();
 await expect(page.getByTestId('ai-plan')).toHaveCount(0);await expect(page.locator('.ai-panel')).not.toContainText('Разбираем запрос');await expect(page.getByRole('button',{name:'Generate plan',exact:true})).toBeDisabled();expect(await readAutosaveDocument(page)).toEqual(before);
});
