import { expect, test, type Page } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import { createNewDocument } from '../src/domain/newDocument';
import type { GeoDocument } from '../src/domain/model';
import type { SourceProvenance } from '../src/vectors/types';
import { readAutosaveDocument } from './helpers/autosave';
const X=6190000,Y=2196000;
const source=(originalType:string):SourceProvenance=>({kind:'dxf',sourceDocumentId:'source',originalType,originalLayer:'0'});
function scene():GeoDocument {
  const d=createNewDocument(),l=d.layers[0]!.id,s={layerId:l,colorMode:'byblock' as const};d.layers[0]!.name='0';
  d.sources=[{id:'source',filename:'hybrid.dxf',format:'DXF',dxfVersion:'AC1024',encoding:'utf-8',originalUnits:6}];
  d.blocks=[{id:'child',sourceName:'Child',basePoint:{x:0,y:0},primitives:[{...s,kind:'path',points:[{x:0,y:0},{x:10,y:0}],closed:false},{...s,kind:'text',position:{x:2,y:0},content:'NESTED TEXT',height:1,rotationDeg:0}]},
    {id:'parent',sourceName:'Parent',basePoint:{x:0,y:0},primitives:[{...s,kind:'block',blockDefinitionId:'child',position:{x:X,y:Y},rotationDeg:0,scaleX:1,scaleY:1},
      {...s,kind:'path',points:[{x:X-12,y:Y-12},{x:X+35,y:Y+15}],closed:false}]}];
  d.vertices={a:{id:'a',x:X-15,y:Y-15},b:{id:'b',x:X+15,y:Y-15},c:{id:'c',x:X+15,y:Y-20},t:{id:'t',x:X-15,y:Y+10}};
  d.entities=[{id:'owner',name:'Owner',type:'block_instance',layerId:l,blockDefinitionId:'parent',position:{x:0,y:0},rotationDeg:0,scaleX:1,scaleY:1,source:source('INSERT')},
    {id:'line',name:'LINE',type:'line',layerId:l,startVertexId:'a',endVertexId:'b',source:source('LINE')},
    {id:'poly',name:'POLY',type:'polygon',layerId:l,vertexIds:['a','b','c'],source:source('LWPOLYLINE')},
    {id:'arc',name:'ARC',type:'arc',layerId:l,center:{x:X+20,y:Y+8},radius:3,startAngle:0,endAngle:Math.PI,source:source('ARC')},
    {id:'circle',name:'CIRCLE',type:'circle',layerId:l,center:{x:X+30,y:Y-5},radius:3,source:source('CIRCLE')},
    {id:'text',name:'MTEXT',type:'text',layerId:l,vertexId:'t',content:'Газ\nвход',height:2,rotationDeg:25,fontSize:12,source:source('MTEXT')},
    {id:'hatch',name:'HATCH',type:'imported_graphic',layerId:l,position:{x:X+16,y:Y-8},source:source('HATCH'),primitives:[{...s,kind:'path',points:[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}],closed:true,fill:true,fillGroup:'hole',fillOpacity:.5},{...s,kind:'path',points:[{x:1,y:1},{x:3,y:1},{x:3,y:3},{x:1,y:3}],closed:true,fill:true,fillGroup:'hole',fillOpacity:.5}]}];
  return d;
}
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const e:string[]=[];errors.set(page,e);page.on('pageerror',x=>e.push(x.message));page.on('console',x=>{if(x.type()==='error')e.push(x.text());});await page.goto('/?dxfRenderer=canvas');});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
const frame=(page:Page)=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function open(page:Page,d:GeoDocument){await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'scene.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await expect(page.getByTestId('dxf-canvas')).toHaveCount(1);await expect.poll(()=>page.getByTestId('dxf-canvas').getAttribute('data-drawn-owners')).not.toBeNull();await frame(page);}
async function screen(page:Page,x:number,y:number){const s=page.getByTestId('drawing-canvas'),b=(await s.boundingBox())!,z=Number(await s.getAttribute('data-zoom')),cx=Number(await s.getAttribute('data-center-x')),cy=Number(await s.getAttribute('data-center-y'));return {x:b.x+b.width/2+(x-cx)*z,y:b.y+b.height/2-(y-cy)*z};}
async function click(page:Page,x:number,y:number,alt=false){const p=await screen(page,x,y);if(alt)await page.keyboard.down('Alt');await page.mouse.click(p.x,p.y);if(alt)await page.keyboard.up('Alt');await frame(page);}
async function stats(page:Page){return page.evaluate(async()=>{const {canvasMetrics}=await import(String('/src/renderer/CanvasSceneRenderer.ts')) as typeof import('../src/renderer/CanvasSceneRenderer');return canvasMetrics();});}
async function drawn(page:Page):Promise<string[]>{return JSON.parse((await page.getByTestId('dxf-canvas').getAttribute('data-drawn-owners'))!);}
async function zoom(page:Page,factor:number,anchor?:{x:number;y:number}){const p=(await page.getByTestId('drawing-canvas').boundingBox())!;await page.mouse.move(anchor?.x??p.x+p.width/2,anchor?.y??p.y+p.height/2);const dpr=await page.evaluate(()=>devicePixelRatio);/* Chrome CDP wheel delivery uses physical delta in emulated Retina contexts. */const delta=-Math.log(factor)/.002*dpr,n=Math.ceil(Math.abs(delta)/180);for(let i=0;i<n;i++){await page.mouse.wheel(0,delta/n);await frame(page);}}

test('Canvas bulk is absent from SVG; normal selection, hover and nested Alt work with overlay-only invalidation',async({page})=>{
  await open(page,scene());await expect(page.locator('defs path,defs text,svg use,[data-entity-id]')).toHaveCount(0);
  const before=await stats(page);await click(page,X+3,Y+.4);await expect(page.getByTestId('selected-id')).toHaveText('owner');await expect(page.getByTestId('canvas-selection-overlay')).toHaveCount(1);expect((await stats(page)).draws).toBe(before.draws);expect((await stats(page)).compilations).toBe(before.compilations);
  const p=await screen(page,X+4,Y);await page.mouse.move(p.x,p.y);await frame(page);expect(await page.getByTestId('drawing-canvas').evaluate(e=>(e as SVGSVGElement).style.cursor)).toBe('pointer');
  for(let i=0;i<3;i++)await click(page,X+3,Y+.4,true);
  await expect(page.getByTestId('deep-properties')).toContainText('Parent → Child → TEXT');await expect(page.getByTestId('deep-selection-highlight')).toBeVisible();await expect(page.locator('defs path,defs text,svg use')).toHaveCount(0);expect((await stats(page)).draws).toBe(before.draws);
});
test('Canvas Move preview leaves autosave untouched, commits once and Undo restores exact canonical document',async({page})=>{
  const d=scene();await open(page,d);await click(page,X+3,Y+.4);const a=await screen(page,X+3,Y+.4),b=await screen(page,X+5,Y+1.4),before=await stats(page);
  await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:5});await frame(page);expect(await readAutosaveDocument(page)).toEqual(d);expect((await stats(page)).draws).toBeGreaterThan(before.draws);expect((await stats(page)).compilations).toBe(before.compilations);await page.mouse.up();
  await expect.poll(async()=>{const e=(await readAutosaveDocument(page)).entities.find(e=>e.id==='owner');return e?.type==='block_instance'?e.position.x:NaN;}).toBeCloseTo(2,4);const moved=(await readAutosaveDocument(page)).entities.find(e=>e.id==='owner')!;if(moved.type!=='block_instance')throw Error();expect(moved.position.y).toBeCloseTo(1,4);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(d);
});
test('marquee, relative/absolute Move, layer visibility and Fit Layer need no owner DOM',async({page})=>{
  const d=scene();await open(page,d);const s=page.getByTestId('drawing-canvas'),initial={zoom:await s.getAttribute('data-zoom'),x:await s.getAttribute('data-center-x'),y:await s.getAttribute('data-center-y')},r=(await s.boundingBox())!;
  await page.mouse.move(r.x+3,r.y+3);await page.mouse.down();await page.mouse.move(r.x+r.width-3,r.y+r.height-3,{steps:4});await page.mouse.up();await expect(page.locator('[data-selected="true"]')).toHaveCount(d.entities.length);
  await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('1');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('2');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();const moved=await readAutosaveDocument(page);expect(moved.vertices.a!.x).toBe(d.vertices.a!.x+1);expect(moved.vertices.a!.y).toBe(d.vertices.a!.y+2);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(d);
  await page.getByRole('button',{name:'X/Y Абсолютно',exact:true}).click();await page.getByLabel('Базовая точка',{exact:true}).selectOption('bottom-left');await page.getByLabel('Перемещение MODEL X',{exact:true}).fill(String(X));await page.getByLabel('Перемещение MODEL Y',{exact:true}).fill(String(Y));await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();const absolute=await readAutosaveDocument(page);/* The rotated text extends left of vertex a by height*sin(25°). */expect(absolute.vertices.a!.x).toBeCloseTo(X+2*Math.sin(25*Math.PI/180),5);expect(absolute.vertices.c!.y).toBe(Y);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(d);
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'Скрыть слой 0',exact:true}).click();await expect(page.getByTestId('dxf-canvas')).toHaveCount(0);await page.getByRole('button',{name:'Показать слой 0',exact:true}).click();await expect(page.getByTestId('dxf-canvas')).toHaveCount(1);await page.getByRole('button',{name:'Выбрать слой 0',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();expect(await s.getAttribute('data-zoom')).toBe(initial.zoom);expect(await s.getAttribute('data-center-x')).toBe(initial.x);expect(await s.getAttribute('data-center-y')).toBe(initial.y);
});
test('same document A/B removes inactive bulk, preserves camera, text editing, JSON and IndexedDB reload',async({page})=>{
  const d=scene();await open(page,d);const s=page.getByTestId('drawing-canvas'),z=await s.getAttribute('data-zoom');await page.getByLabel('DXF renderer',{exact:true}).selectOption('svg');await expect(page.getByTestId('dxf-canvas')).toHaveCount(0);await expect(page.locator('[data-entity-id]')).toHaveCount(d.entities.length);expect(await s.getAttribute('data-zoom')).toBe(z);await page.getByLabel('DXF renderer',{exact:true}).selectOption('canvas');await expect(page.locator('[data-entity-id],defs path,defs text')).toHaveCount(0);await click(page,X-14,Y+11);await expect(page.getByTestId('selected-id')).toHaveText('text');
  await page.getByLabel('Текст',{exact:true}).fill('Новый газ');await page.getByLabel('Текст',{exact:true}).blur();const p=await screen(page,X-14,Y+11);await page.mouse.dblclick(p.x,p.y);await expect(page.getByLabel('Редактировать текст',{exact:true})).toBeVisible();await page.getByLabel('Редактировать текст',{exact:true}).fill('Газ сохранён');await page.getByRole('button',{name:'Готово',exact:true}).click();const changed=await readAutosaveDocument(page);expect(changed.entities.find(e=>e.id==='text')).toMatchObject({content:'Газ сохранён'});
  const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Сохранить JSON',exact:true}).click();const file=(await(await dl).path())!;expect(JSON.parse(await readFile(file,'utf8'))).toEqual(changed);await open(page,d);await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(file);expect(await readAutosaveDocument(page)).toEqual(changed);await page.reload();await expect(page.getByTestId('dxf-canvas')).toHaveCount(1);expect(await readAutosaveDocument(page)).toEqual(changed);await expect(page.locator('defs path,defs text,[data-entity-id]')).toHaveCount(0);
});
test('Canvas proxies paint HATCH, MULTILEADER and anonymous DXF dimensions with semantic inspection',async({page})=>{
  await page.getByRole('button',{name:'DXF',exact:true}).click();await page.getByLabel('Файл DXF',{exact:true}).setInputFiles('src/tests/fixtures/dxf/mixed_proxy.dxf');await page.getByTestId('dxf-report').waitFor();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await page.getByRole('dialog',{name:'Открыть DXF',exact:true}).waitFor({state:'hidden'});const d=await readAutosaveDocument(page);
  for(const sourceType of ['HATCH','MULTILEADER','DIMENSION']){
    const owner=d.entities.find(e=>e.source?.originalType===sourceType)!;await open(page,{...d,entities:[owner]});expect(await drawn(page)).toContain(owner.id);await expect(page.locator('defs path,defs text,svg use,[data-entity-id]')).toHaveCount(0);expect(await page.getByTestId('dxf-canvas').evaluate(c=>{const a=c as HTMLCanvasElement,p=a.getContext('2d')!.getImageData(0,0,a.width,a.height).data;return p.some((v,i)=>i%4===3&&v>0);})).toBe(true);
    if(sourceType==='MULTILEADER')await click(page,4.5,6.5);if(sourceType==='DIMENSION')await click(page,5.5,-1.5);
    if(sourceType!=='HATCH')await expect(page.getByTestId('imported-semantic-content')).toContainText(sourceType==='MULTILEADER'?'Выноска':'10');
    await page.keyboard.press('Escape');await page.getByLabel('DXF renderer',{exact:true}).selectOption('svg');await expect(page.getByTestId('dxf-canvas')).toHaveCount(0);await expect(page.locator(`[data-entity-id="${owner.id}"]`)).toBeVisible();await page.getByLabel('DXF renderer',{exact:true}).selectOption('canvas');await expect(page.locator('defs path,defs text,svg use,[data-entity-id]')).toHaveCount(0);expect(await readAutosaveDocument(page)).toEqual({...d,entities:[owner]});
  }
});
for(const dpr of [1,2])test(`DPR ${dpr}: camera-relative geometry remains painted at 63/100 px/m and after pan`,async({browser})=>{
  const context=await browser.newContext({deviceScaleFactor:dpr,viewport:{width:1440,height:900}}),page=await context.newPage();const e:string[]=[];page.on('pageerror',x=>e.push(x.message));await page.goto('/?dxfRenderer=canvas');const d=scene();await open(page,d);const s=page.getByTestId('drawing-canvas'),r=(await s.boundingBox())!;
  expect(await page.getByTestId('dxf-canvas').evaluate(c=>({width:(c as HTMLCanvasElement).width,height:(c as HTMLCanvasElement).height}))).toEqual({width:Math.round(r.width*dpr),height:Math.round(r.height*dpr)});
  for(const z of [63,100]){const current=Number(await s.getAttribute('data-zoom'));await zoom(page,z/current);expect(Number(await s.getAttribute('data-zoom'))).toBeCloseTo(z,4);expect(await drawn(page)).toContain('owner');const ink=await page.getByTestId('dxf-canvas').evaluate(c=>{const canvas=c as HTMLCanvasElement,p=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;let ink=0;for(let i=3;i<p.length;i+=4)if(p[i])ink++;return ink;});expect(ink).toBeGreaterThan(50);}
  await page.keyboard.down('Space');await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+60,r.y+r.height/2+30,{steps:5});await page.mouse.up();await page.keyboard.up('Space');await frame(page);expect(await drawn(page)).toContain('owner');await page.getByRole('button',{name:'Вписать',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(d);expect(e).toEqual([]);await context.close();
});
test('real reference Canvas acceptance: Fit/zoom/select/Alt/marquee/Move/layers/proxies/index/Save/Open/reload',async({page})=>{
  test.skip(!process.env.DXF_REFERENCE,'Reference DXF is local opt-in');test.setTimeout(120000);
  await page.getByRole('button',{name:'DXF',exact:true}).click();await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await page.getByTestId('dxf-report').waitFor();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await page.getByRole('dialog',{name:'Открыть DXF',exact:true}).waitFor({state:'hidden'});await frame(page);const d=await readAutosaveDocument(page);expect(d.entities).toHaveLength(458);await expect(page.locator('defs path,defs text,svg use,[data-entity-id]')).toHaveCount(0);
  const probe=await page.evaluate(async d=>{
    const [{createProvenanceIndex},{resolveDeepSelection,hitOwners,createHitStack},{blockMatrix,multiply,transformPoint}]=await Promise.all([import(String('/src/dxf/provenance.ts')),import(String('/src/editor/deepSelection.ts')),import(String('/src/vectors/geometry.ts'))]);
    const s=window.document.querySelector('.drawing-canvas')!,r=s.getBoundingClientRect(),z=Number(s.getAttribute('data-zoom')),cx=Number(s.getAttribute('data-center-x')),cy=Number(s.getAttribute('data-center-y'));
    const entities=d.entities.filter(e=>e.type==='block_instance'&&d.layers.find(l=>l.id===e.layerId)?.visible).sort((a,b)=>(a.type==='block_instance'?d.blocks?.find(x=>x.id===a.blockDefinitionId)?.primitives.length??0:0)-(b.type==='block_instance'?d.blocks?.find(x=>x.id===b.blockDefinitionId)?.primitives.length??0:0));
    for(const e of entities)for(const text of createProvenanceIndex(d).getEntitySemanticSummary(e.id).texts){const resolved=resolveDeepSelection(d,{ownerEntityId:e.id,primitivePath:text.primitivePath,blockPath:[],sourceType:'TEXT'});if(!resolved||resolved.primitive.kind!=='text')continue;const p=resolved.primitive,world=transformPoint({x:p.height*.5,y:p.height*.4},multiply(resolved.matrix,blockMatrix({position:p.position,rotationDeg:p.rotationDeg,scaleX:1,scaleY:1},{x:0,y:0})));const point={x:r.x+r.width/2+(world.x-cx)*z,y:r.y+r.height/2-(world.y-cy)*z},owners=hitOwners(d,world,7/z,z);if(point.x>r.x+10&&point.x<r.right-10&&point.y>r.y+10&&point.y<r.bottom-10&&owners[0]===e.id&&createHitStack(d,owners,world,5/z).slice(1,12).some((h:import('../src/editor/deepSelection').HitCandidate)=>h.selection?.ownerEntityId===e.id&&h.selection.primitivePath.join('.')===text.primitivePath.join('.')))return {...point,owner:e.id,text:p.content};}return null;
  },d);expect(probe).not.toBeNull();await page.mouse.click(probe!.x,probe!.y);await expect(page.getByTestId('selected-id')).toHaveText(probe!.owner);for(let i=0;i<15;i++){await page.keyboard.down('Alt');await page.mouse.click(probe!.x,probe!.y);await page.keyboard.up('Alt');if((await page.getByTestId('deep-properties').count())&&(await page.getByTestId('deep-properties').textContent())?.includes(probe!.text))break;}await expect(page.getByTestId('deep-properties')).toContainText(probe!.text);await expect(page.getByTestId('deep-selection-highlight')).toBeVisible();await page.keyboard.press('Escape');
  await zoom(page,2);await zoom(page,.5);const r=(await page.getByTestId('drawing-canvas').boundingBox())!;await page.keyboard.down('Space');await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+40,r.y+r.height/2+20,{steps:4});await page.mouse.up();await page.keyboard.up('Space');await page.getByRole('button',{name:'Вписать',exact:true}).click();
  for(const target of [63,100]){const s=page.getByTestId('drawing-canvas');await zoom(page,target/Number(await s.getAttribute('data-zoom')),probe!);expect(Number(await s.getAttribute('data-zoom'))).toBeCloseTo(target,4);expect((await drawn(page)).length).toBeGreaterThan(0);expect(await page.getByTestId('dxf-canvas').evaluate(c=>{const a=c as HTMLCanvasElement,p=a.getContext('2d')!.getImageData(0,0,a.width,a.height).data;let n=0;for(let i=3;i<p.length;i+=4)if(p[i])n++;return n;})).toBeGreaterThan(20);await page.getByRole('button',{name:'Вписать',exact:true}).click();}
  await page.mouse.move(r.x+r.width-3,r.y+3);await page.mouse.down();await page.mouse.move(r.x+3,r.y+r.height-3,{steps:4});await page.mouse.up();expect(await page.locator('[data-selected="true"]').count()).toBeGreaterThan(0);await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('1');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('2');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(d);await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Скрыть слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Показать слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Выбрать слой _ГП_ЗИС',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await page.getByRole('button',{name:'Вписать',exact:true}).click();
  const semantic=await page.evaluate(async d=>{const {createProvenanceIndex}=await import(String('/src/dxf/provenance.ts'));return createProvenanceIndex(d).searchText('Плодородный');},d);expect(semantic.length).toBeGreaterThan(0);
  const leader=d.entities.find(e=>e.source?.handle==='58829')!;await open(page,{...d,entities:[leader]});if(leader.type!=='imported_graphic')throw Error();const text=leader.primitives.find(p=>p.kind==='text')!;if(text.kind!=='text')throw Error();await click(page,leader.position.x+text.position.x+text.height*.5,leader.position.y+text.position.y+text.height*.4);await expect(page.getByTestId('imported-semantic-content')).toContainText('Плодородный грунт');
  await open(page,d);const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Сохранить JSON',exact:true}).click();const file=(await(await dl).path())!;expect(JSON.parse(await readFile(file,'utf8'))).toEqual(d);await page.getByRole('button',{name:'Новый документ',exact:true}).click();await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(file);expect(await readAutosaveDocument(page)).toEqual(d);await page.reload();await expect(page.getByTestId('dxf-canvas')).toHaveCount(1);expect(await readAutosaveDocument(page)).toEqual(d);await expect(page.locator('defs path,defs text,svg use,[data-entity-id]')).toHaveCount(0);await page.screenshot({path:'/private/tmp/geoservice-hybrid-reference.png'});
  await writeFile('docs/audit-results/hybrid-reference-acceptance.json',JSON.stringify({entities:458,blocks:d.blocks?.length,canvasCount:await page.getByTestId('dxf-canvas').count(),svgBulkNodes:0,deepOwner:probe!.owner,textSearchHits:semantic.length,consoleErrors:errors.get(page)},null,2)+'\n');
});
