import { expect, test, type Page } from '@playwright/test';
import { createNewDocument } from '../src/domain/newDocument';
import { skewedCorners, type ImageFixture } from '../src/tests/fixtures/imagePlan';
import type { RasterUnderlayEntity } from '../src/domain/model';
import { editorCommand } from './helpers/editorCommands';
import { readAutosaveDocument } from './helpers/autosave';
const errors = new WeakMap<Page, string[]>();
test.beforeEach(({ page }) => { const messages: string[] = []; errors.set(page, messages); page.on('pageerror', e => messages.push(e.message)); page.on('console', m => { if (m.type() === 'error') messages.push(m.text()); }); });
test.afterEach(({ page }) => expect(errors.get(page)).toEqual([]));
async function setup(page: Page) { await page.addInitScript(d => localStorage.setItem('geoservice.document.v2', JSON.stringify(d)), createNewDocument()); await page.goto('/'); await expect(page.getByTestId('drawing-canvas')).toBeVisible(); }
async function addImage(page: Page, kind: ImageFixture = 'clean') {
  const data = await page.evaluate(async kind => { const { imagePlan } = await import(String('/src/tests/fixtures/imagePlan.ts')); const image = imagePlan(kind), c = document.createElement('canvas'); c.width = image.width; c.height = image.height; c.getContext('2d')!.putImageData(new ImageData(image.data, image.width, image.height), 0, 0); return c.toDataURL('image/png').split(',')[1]!; }, kind);
  await page.getByLabel('Импорт подложки', { exact: true }).setInputFiles({ name: `${kind}.png`, mimeType: 'image/png', buffer: Buffer.from(data, 'base64') }); await expect(page.getByTestId('underlay-properties')).toBeVisible(); await expect(page.getByTestId('missing-raster')).toHaveCount(0);
}
async function workflow(page: Page) { await editorCommand(page, 'Векторизация изображения'); await expect(page.getByRole('dialog', { name: 'Векторизация изображения' })).toBeVisible(); }
async function extract(page: Page) { await page.getByRole('button', { name: '4. Извлечение', exact: true }).click(); await page.getByRole('button', { name: 'Извлечь геометрию', exact: true }).click(); await expect(page.getByTestId('image-count-contour')).toBeVisible(); await expect(page.getByTestId('image-progress')).toHaveCount(0); }
async function calibrate(page: Page) { await page.getByRole('button', { name: '3. Масштаб', exact: true }).click(); await page.getByRole('button', { name: 'Выбрать точку A', exact: true }).click(); const svg = page.getByLabel('Предпросмотр векторизации', { exact: true }), box = (await svg.boundingBox())!; await page.mouse.click(box.x + box.width * .1, box.y + box.height * .2); await page.mouse.click(box.x + box.width * .5, box.y + box.height * .2); await page.getByLabel('Реальная длина, м', { exact: true }).fill('19.2'); expect(Number((await page.getByTestId('image-scale').innerText()).split(' ')[0])).toBeCloseTo(.1,3); }
test('clean image → calibrated editable/snappable geometry, one Undo, independent raster, reload', async ({ page }) => {
  await setup(page); await addImage(page); const before = await readAutosaveDocument(page); await workflow(page); await calibrate(page); await extract(page);
  await expect(page.getByTestId('image-count-line')).toHaveText('2'); await expect(page.getByTestId('image-count-contour')).toHaveText('1'); await expect(page.getByTestId('image-count-polyline')).toHaveText('1');
  expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);
  await page.getByLabel('Слой векторизации', { exact: true }).selectOption('__new'); await page.getByRole('button', { name: 'Применить геометрию (4)', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect.poll(async () => (await readAutosaveDocument(page)).entities.length).toBe(5); const applied = await readAutosaveDocument(page), geometry = applied.entities.filter(e => e.type !== 'raster_underlay');
  expect(geometry.map(e => e.type).sort()).toEqual(['line', 'line', 'polygon', 'polyline']); expect(geometry.every(e => e.imageSource?.source === 'image-vectorization')).toBe(true);
  expect(await page.evaluate(async () => { const { loadAutosave } = await import(String('/src/persistence/autosave.ts')), { createSnapProvider } = await import(String('/src/snapping/index.ts')); const saved = await loadAutosave(); return createSnapProvider(saved!.document).candidates.length; })).toBeGreaterThan(8);
  await editorCommand(page, 'Отменить'); await expect.poll(async () => (await readAutosaveDocument(page)).entities.length).toBe(1); await editorCommand(page, 'Повторить'); await expect.poll(async () => (await readAutosaveDocument(page)).entities.length).toBe(5);
  await page.reload(); await expect(page.getByTestId('missing-raster')).toHaveCount(0); const restored = await readAutosaveDocument(page); expect(restored.entities).toEqual(applied.entities);
  const line = geometry.find(e => e.type === 'line')!; await page.getByLabel('Поиск в документе', { exact: true }).fill(line.name); await page.locator('.search-results').getByRole('button', { name: line.name, exact: true }).click(); await expect(page.getByTestId('selected-id')).toHaveText(line.id); await editorCommand(page, 'Переместить выбор'); await page.getByLabel('Перемещение ΔX', { exact: true }).fill('2'); await page.getByLabel('Перемещение ΔY', { exact: true }).fill('3'); await page.getByRole('button', { name: 'Применить перемещение', exact: true }).click(); const moved = await readAutosaveDocument(page); expect(moved.vertices).not.toEqual(applied.vertices); expect(moved.entities.find(e => e.type === 'raster_underlay')).toEqual(restored.entities.find(e => e.type === 'raster_underlay'));
});
test('four corner correction validates crossing, previews and maps result without source mutation; cancel is transient', async ({ page }) => {
  await setup(page); await addImage(page, 'skewed'); const before = await readAutosaveDocument(page); await workflow(page); await page.getByRole('button', { name: '2. Перспектива', exact: true }).click();
  const names = ['Верхний левый', 'Верхний правый', 'Нижний правый', 'Нижний левый']; for (let i = 0; i < 4; i++) for (const axis of ['x', 'y'] as const) await page.getByLabel(`${names[i]} ${axis.toUpperCase()}`, { exact: true }).fill(String(skewedCorners[i]![axis])); await page.getByLabel('Пропорция чертежа', { exact: true }).fill('1.5');
  await page.getByLabel('Верхний левый X', { exact: true }).fill('460'); await expect(page.getByRole('alert')).toContainText('пересекаются'); await expect(page.getByRole('button', { name: 'Применить коррекцию', exact: true })).toBeDisabled(); await page.getByLabel('Верхний левый X', { exact: true }).fill('35');
  const corner = page.getByTestId('perspective-corner-0'); await corner.focus(); await page.keyboard.press('ArrowRight'); await expect(page.getByLabel('Верхний левый X', { exact: true })).toHaveValue('36'); await page.keyboard.press('ArrowLeft'); await page.getByRole('button', { name: 'Применить коррекцию', exact: true }).click(); await page.getByLabel('Масштаб вручную, м/px', { exact: true }).fill('0.1'); await extract(page); await expect(page.getByTestId('image-count-contour')).toHaveText('1');
  const contour = page.locator('[data-candidate-type="contour"]'), bounds = await contour.evaluate(e => (() => {const b=(e as SVGGraphicsElement).getBBox();return {x:b.x,y:b.y,width:b.width,height:b.height};})()); expect(bounds.width).toBeGreaterThan(120); expect(bounds.height).toBeGreaterThan(90);
  await page.getByRole('button', { name: /Применить геометрию/ }).click(); await expect.poll(async () => (await readAutosaveDocument(page)).entities.length).toBeGreaterThan(1); const applied = await readAutosaveDocument(page), raster = applied.entities.find(e => e.type === 'raster_underlay') as RasterUnderlayEntity; expect(raster).toEqual(before.entities[0]); expect(raster.assetId).toBe((before.entities[0] as RasterUnderlayEntity).assetId);
  await page.reload(); await expect(page.getByTestId('missing-raster')).toHaveCount(0); await workflow(page); await page.getByRole('button', { name: '2. Перспектива', exact: true }).click(); await page.getByRole('button', { name: 'Сбросить перспективу', exact: true }).click(); await page.getByRole('button', { name: 'Отмена', exact: true }).click(); expect((await readAutosaveDocument(page)).entities).toEqual(applied.entities);
});
test('noisy scan: stronger cleanup, category/individual exclusion, before-after and clear all', async ({ page }) => {
  await setup(page); await addImage(page, 'noisy'); await workflow(page); await page.getByRole('button', { name: '4. Извлечение', exact: true }).click(); await page.getByLabel('Удаление шума', { exact: true }).selectOption('low'); await extract(page); const low = await page.locator('[data-candidate-id]').count(); await page.getByRole('button', { name: '4. Извлечение', exact: true }).click(); await page.getByLabel('Удаление шума', { exact: true }).selectOption('high'); await extract(page); expect(await page.locator('[data-candidate-id]').count()).toBeLessThan(low);
  const first = page.locator('[data-candidate-type="line"]').first(); const point=await first.evaluate(e=>{const line=e as SVGPolylineElement,p=line.points.getItem(0),q=line.points.getItem(1),screen=new DOMPoint((p.x+q.x)/2,(p.y+q.y)/2).matrixTransform(line.getScreenCTM()!);return {x:screen.x,y:screen.y};}); await page.mouse.click(point.x,point.y); await page.getByRole('button', { name: 'Исключить кандидат', exact: true }).click(); await expect(first).toHaveClass(/excluded/); await page.getByLabel('Показать: Контуры', { exact: true }).uncheck(); await expect(page.locator('[data-candidate-type="contour"]')).toHaveCount(0); await page.getByLabel('Только изображение', { exact: true }).check(); await expect(page.locator('[data-candidate-id]')).toHaveCount(0); await page.getByLabel('Только изображение', { exact: true }).uncheck(); await page.getByRole('button', { name: 'Очистить выбор', exact: true }).click(); await expect(page.getByRole('button', { name: 'Применить геометрию (0)', exact: true })).toBeDisabled(); await page.getByRole('button', { name: 'Выбрать все', exact: true }).click(); await expect(page.getByRole('button', { name: /Применить геометрию/ })).toBeEnabled(); await page.getByRole('button', { name: 'Отмена', exact: true }).click(); expect((await readAutosaveDocument(page)).entities).toHaveLength(1);
});
test('local-only privacy: no OpenRouter/AI intent/image request, text regions are not fabricated entities', async ({ page }) => {
  const external: string[] = [], ai: string[] = []; page.on('request', r => { if (/^https?:/.test(r.url()) && new URL(r.url()).hostname !== '127.0.0.1') external.push(r.url()); if (r.url().includes('/api/ai/intent')) ai.push(r.url()); });
  await setup(page); await addImage(page, 'text'); await workflow(page); await extract(page); await expect(page.getByTestId('image-count-text')).toHaveText('1'); await expect(page.getByRole('button', { name: 'Применить геометрию (0)', exact: true })).toBeDisabled(); await page.getByRole('button', { name: 'Отмена', exact: true }).click(); expect((await readAutosaveDocument(page)).entities).toHaveLength(1); expect(external).toEqual([]); expect(ai).toEqual([]);
  const canvas = page.getByTestId('drawing-canvas'), box = (await canvas.boundingBox())!, center = await canvas.getAttribute('data-center-x'); await page.mouse.click(box.x + box.width * .5, box.y + box.height * .5); await page.keyboard.down('Space'); await page.mouse.move(box.x + box.width * .5, box.y + box.height * .5); await page.mouse.down(); await page.mouse.move(box.x + box.width * .5 + 60, box.y + box.height * .5 + 30); await page.mouse.up(); await page.keyboard.up('Space'); await expect(canvas).not.toHaveAttribute('data-center-x', center!);
});
test('AI settings use current provider abstraction and session-only key; privacy stays prompt only', async ({ page }) => {
  let calls = 0; await page.route('**/api/ai/intent', async route => { calls++; expect(Object.keys(route.request().postDataJSON())).toEqual(['text']); expect(route.request().headers()['x-ai-api-key']).toBe('test-local-key'); expect(route.request().headers()['x-ai-primary-model']).toBe('qwen/test'); await route.fulfill({ json: { result: { actions: [{ type: 'create_rectangle', name: 'Тест', width: 1, height: 1, sizeSource: null, placement: { type: 'local_origin' } }] } } }); });
  await setup(page); await page.getByText('Настройки AI', { exact: true }).click(); await page.getByLabel('AI API key', { exact: true }).fill('test-local-key'); await page.getByLabel('Основная AI модель', { exact: true }).fill('qwen/test'); await page.getByRole('button', { name: 'Проверить подключение', exact: true }).click(); await expect(page.locator('.ai-mode')).toContainText('online'); expect(calls).toBe(1); await page.getByLabel('AI включён', { exact: true }).uncheck(); await expect(page.getByRole('button', { name: 'Generate plan', exact: true })).toBeDisabled();
  expect(JSON.stringify(await readAutosaveDocument(page))).not.toContain('test-local-key'); expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain('test-local-key'); await page.reload(); await page.getByText('Настройки AI', { exact: true }).click(); await expect(page.getByLabel('AI API key', { exact: true })).toHaveValue('');
});
test('zero reference is rejected; Escape cancels a hung worker before closing the workflow', async ({ page }) => {
  await page.addInitScript(() => { window.Worker = class extends Worker { imageJob:boolean; constructor(url:string|URL,options?:WorkerOptions){super(url,options);this.imageJob=String(url).includes('/image/worker.ts');} postMessage(message:unknown,transfer:Transferable[]|StructuredSerializeOptions=[]) { if(!this.imageJob)super.postMessage(message,Array.isArray(transfer)?transfer:transfer.transfer??[]); } }; });
  await setup(page); await addImage(page); const before = await readAutosaveDocument(page); await workflow(page); await page.getByRole('button', { name: '3. Масштаб', exact: true }).click(); await page.getByRole('button', { name: 'Выбрать точку A', exact: true }).click(); const svg = page.getByLabel('Предпросмотр векторизации', { exact: true }), box = (await svg.boundingBox())!; await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2); await expect(page.getByRole('alert')).toContainText('Две разные точки'); await page.getByRole('button', { name: 'Сбросить точки', exact: true }).click(); await page.getByRole('button', { name: '4. Извлечение', exact: true }).click(); await page.getByRole('button', { name: 'Извлечь геометрию', exact: true }).click(); await expect(page.getByTestId('image-progress')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.getByTestId('image-progress')).toHaveCount(0); await expect(page.getByRole('dialog')).toBeVisible(); expect((await readAutosaveDocument(page)).entities).toEqual(before.entities); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('worker crash is explained without partial Apply or unhandled console errors', async ({ page }) => {
  await page.addInitScript(() => { window.Worker = class extends Worker { imageJob:boolean;constructor(url:string|URL,options?:WorkerOptions){super(url,options);this.imageJob=String(url).includes('/image/worker.ts');} postMessage(message:unknown,transfer:Transferable[]|StructuredSerializeOptions=[]) { if(this.imageJob)setTimeout(() => this.onerror?.call(this, new ErrorEvent('error')), 20);else super.postMessage(message,Array.isArray(transfer)?transfer:transfer.transfer??[]); } }; });
  await setup(page); await addImage(page); await workflow(page); await page.getByRole('button', { name: '4. Извлечение', exact: true }).click(); await page.getByRole('button', { name: 'Извлечь геометрию', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Рабочий процесс'); await expect(page.getByTestId('image-progress')).toHaveCount(0); await page.getByRole('button', { name: '5. Проверка', exact: true }).click(); await expect(page.getByRole('button', { name: 'Применить геометрию (0)', exact: true })).toBeDisabled(); expect((await readAutosaveDocument(page)).entities).toHaveLength(1);
});
