import { test,expect,type Page } from '@playwright/test';
import { createNewDocument } from '../src/domain/newDocument';
import { editorCommand , openRightTab } from './helpers/editorCommands';
import { readAutosaveDocument } from './helpers/autosave';
function scene(){const d=createNewDocument(),layerId=d.layers[0]!.id;d.sources=[{id:'src',filename:'polish.dxf',format:'DXF' as const,dxfVersion:'AC1027',encoding:'utf-8',originalUnits:6}];d.vertices={a:{id:'a',x:0,y:0},b:{id:'b',x:10,y:0}};d.blocks=[{id:'def',sourceName:'Valve',basePoint:{x:0,y:0},primitives:[{kind:'path' as const,points:[{x:0,y:0},{x:10,y:0}],closed:false,layerId,colorMode:'bylayer' as const},{kind:'path' as const,points:[{x:8,y:-5},{x:8,y:5}],closed:false,layerId,colorMode:'bylayer' as const}]}];d.entities=[{id:'hatch',type:'imported_graphic',name:'Background',layerId,position:{x:0,y:0},source:{kind:'dxf',sourceDocumentId:'src',originalType:'HATCH',originalLayer:'0'},primitives:[{kind:'path',points:[{x:-20,y:-20},{x:20,y:-20},{x:20,y:20},{x:-20,y:20}],closed:true,fill:true,layerId,colorMode:'bylayer'}]},{id:'block',type:'block_instance',name:'Valve',layerId,blockDefinitionId:'def',position:{x:0,y:0},rotationDeg:0,scaleX:1,scaleY:1,attributeCoordinateSpace:'block-local',attributes:{TAG:'V1'},attributePrimitives:[{kind:'text',content:'V1',attributeTag:'TAG',position:{x:5,y:0},height:1,rotationDeg:0,layerId,colorMode:'byblock',source:{kind:'dxf',sourceDocumentId:'src',originalType:'ATTRIB',originalLayer:'0'}}]},{id:'line-b',type:'line',name:'B',layerId,startVertexId:'a',endVertexId:'b'},{id:'line-a',type:'line',name:'A',layerId,startVertexId:'a',endVertexId:'b'}];d.dxfLayouts=[{id:'paper',name:'Sheet',nameAvailable:true,sourceDocumentId:'src',paperSpaceOwner:'p',paperPrimitives:[{kind:'text',content:'Paper title',position:{x:20,y:20},height:3,rotationDeg:0,layerId,colorMode:'bylayer'}],viewports:[{id:'vp',number:2,centerPaper:{x:80,y:70},sizePaper:{width:40,height:40},modelCenter:{x:5,y:0},viewHeight:20,scale:2,twist:27,clip:{kind:'rectangle'},frozenSourceLayerNames:[]}]}];return d;}
async function setup(page:Page){await page.goto('/');await page.getByTestId('drawing-canvas').waitFor();await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'polish.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(scene()))});return readAutosaveDocument(page);}
async function point(page:Page,x:number,y:number,id='drawing-canvas'){const c=page.getByTestId(id),b=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y')),a=Number(await c.getAttribute('data-view-angle')??0)*Math.PI/180,dx=x-cx,dy=y-cy;return {x:b.x+b.width/2+(dx*Math.cos(a)-dy*Math.sin(a))*z,y:b.y+b.height/2-(dx*Math.sin(a)+dy*Math.cos(a))*z};}
async function click(page:Page,x:number,y:number){const p=await point(page,x,y);await page.mouse.click(p.x,p.y);}
const frames=(page:Page)=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
test('ranked click, Tab backwards, geometry/properties/source and overlay-only invalidation',async({page})=>{const before=await setup(page);const base=await page.evaluate(()=>({...((globalThis as unknown as {__geoCanvasCounters:{draws:number;compilations:number}}).__geoCanvasCounters)}));await click(page,5,0);await expect(page.getByTestId('selected-id')).toHaveText('line-a');await expect(page.getByTestId('property-source')).not.toHaveAttribute('open','');await expect(page.getByRole('term').filter({hasText:/^Длина$/})).toBeVisible();await page.keyboard.press('Tab');await expect(page.getByTestId('selected-id')).toHaveText('line-b');await expect(page.getByTestId('selection-cycle')).toContainText('2 / 7');await page.keyboard.press('Shift+Tab');await expect(page.getByTestId('selected-id')).toHaveText('line-a');await page.keyboard.press('Tab');await page.keyboard.press('Tab');await expect(page.getByLabel('Значение атрибута',{exact:true})).toHaveValue('V1');await page.keyboard.press('Tab');await expect(page.getByTestId('deep-properties')).toContainText('только просмотр');await page.getByRole('button',{name:'Выбрать блок',exact:true}).click();await expect(page.locator('.object-breadcrumb')).toContainText('DXF блок');await expect(page.getByText('Элементов',{exact:true})).toBeVisible();const p=await point(page,2,0);await page.mouse.move(p.x,p.y);await frames(page);const after=await page.evaluate(()=>((globalThis as unknown as {__geoCanvasCounters:{draws:number;compilations:number}}).__geoCanvasCounters));expect(after.draws).toBe(base.draws);expect(after.compilations).toBe(base.compilations);expect(await readAutosaveDocument(page)).toEqual(before);await page.keyboard.press('Escape');await page.keyboard.press('Tab');await expect(page.getByTestId('selected-id')).toHaveCount(0);});
test('wide DXF contour click selects, while dragging from an unpainted gap starts a clean marquee',async({page})=>{
  const before=await setup(page),p=await point(page,8,2),start={x:p.x+4,y:p.y};
  await page.mouse.click(start.x,start.y);await expect(page.getByTestId('selected-id')).toHaveText('block');
  await page.keyboard.press('Escape');await page.mouse.move(start.x,start.y);await page.mouse.down();
  await page.mouse.move(start.x+40,start.y+40,{steps:4});await expect(page.getByTestId('marquee-selection')).toBeVisible();
  await page.mouse.up();expect(await readAutosaveDocument(page)).toEqual(before);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();
});
test('block ATTRIB editor updates only instance, undo and locked state',async({page})=>{const before=await setup(page);await click(page,8,2);await expect(page.getByTestId('deep-properties')).toBeVisible();await page.getByRole('button',{name:'Выбрать блок',exact:true}).click();await expect(page.getByTestId('selected-id')).toHaveText('block');await expect(page.getByLabel('Атрибут TAG',{exact:true})).toHaveValue('V1');await page.getByLabel('Атрибут TAG',{exact:true}).fill('V2');await page.getByLabel('Атрибут TAG',{exact:true}).press('Enter');const after=await readAutosaveDocument(page);expect(after.blocks).toEqual(before.blocks);expect(after.entities.find(e=>e.id==='block')).toMatchObject({attributes:{TAG:'V2'}});await editorCommand(page,'Отменить');expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);await page.getByRole('button',{name:`Заблокировать слой ${before.layers[0]!.name}`,exact:true}).click();await expect(page.getByLabel('Атрибут TAG',{exact:true})).toBeDisabled();});
test('rotated selection, Paper object inspection, active viewport canonical edit and clip',async({page})=>{const before=await setup(page);await page.locator('.view-orientation>summary').click();await page.getByLabel('Поворот вида, °',{exact:true}).fill('27');await page.getByLabel('Поворот вида, °',{exact:true}).press('Enter');await click(page,5,0);await expect(page.getByTestId('selected-id')).toHaveText('line-a');await page.getByLabel('DXF контекст',{exact:true}).selectOption('paper');const p=await point(page,21,21,'layout-canvas');await page.mouse.click(p.x,p.y);await expect(page.getByTestId('group-properties')).toContainText('Только чтение: 1');await expect(page.locator('.object-breadcrumb')).toContainText('Paper Space');const views=page.getByTestId('dxf-views');await views.locator('>summary').click();await views.getByTestId('dxf-paper-node').locator('details>summary').click();await views.getByRole('button',{name:'Редактировать модель · Viewport 1',exact:true}).click();await click(page,5,0);await expect(page.getByTestId('selected-id')).toHaveText('line-a');await page.keyboard.press('Tab');await expect(page.getByTestId('selected-id')).toHaveText('line-b');await editorCommand(page,'Переместить выбор');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('1');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('0');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();expect((await readAutosaveDocument(page)).vertices.a!.x).toBe(1);await editorCommand(page,'Отменить');expect((await readAutosaveDocument(page)).dxfLayouts).toEqual(before.dxfLayouts);await page.getByRole('button',{name:'Выйти в лист',exact:true}).click();await expect(page.locator('.active-viewport-editor')).toHaveCount(0);});
test('compact mixed properties, dock tabs retain drafts, collapse increases canvas; CloseButton keyboard',async({page})=>{await setup(page);await page.setViewportSize({width:1280,height:800});await frames(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(1280);await page.getByTestId('dxf-views').locator('>summary').click();await page.getByRole('button',{name:'Выбрать все объекты Model',exact:true}).click();await expect(page.getByTestId('group-properties')).toContainText('Выбрано: 4');await expect(page.getByTestId('group-properties')).toContainText('Общий слой');await openRightTab(page,'search');await page.getByLabel('Поиск в документе',{exact:true}).fill('draft');await page.getByRole('tablist',{name:'Панели редактора'}).getByRole('tab',{name:'Поиск',exact:true}).click();await expect(page.getByLabel('Поиск в документе',{exact:true})).toHaveValue('draft');await page.getByRole('tablist',{name:'Панели редактора'}).getByRole('tab',{name:'Свойства',exact:true}).click();const old=(await page.getByTestId('drawing-canvas').boundingBox())!.width;await page.getByRole('button',{name:'Свернуть панели',exact:true}).click();await expect.poll(async()=> (await page.getByTestId('drawing-canvas').boundingBox())!.width).toBeGreaterThan(old);await page.getByRole('button',{name:'Развернуть панели',exact:true}).click();await editorCommand(page,'Символы');const close=page.getByRole('button',{name:'Закрыть символы',exact:true});expect(await close.locator('svg').count()).toBe(1);await close.focus();await close.press('Enter');await expect(page.getByRole('dialog',{name:'Библиотека символов'})).toHaveCount(0);});

for(const context of ['model','rotated','paper','viewport']as const)test(`primitive-first hover/click and explicit parent: ${context}`,async({page})=>{
 await setup(page);const d=scene();d.dxfLayouts![0]!.paperPrimitives.push({kind:'block',blockDefinitionId:'def',position:{x:40,y:20},rotationDeg:0,scaleX:1,scaleY:1,layerId:d.layers[0]!.id,colorMode:'bylayer'});await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'nested.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});const before=await readAutosaveDocument(page);
 if(context==='rotated'){await page.locator('.view-orientation>summary').click();await page.getByLabel('Поворот вида, °',{exact:true}).fill('27');await page.getByLabel('Поворот вида, °',{exact:true}).press('Enter');}
 if(context==='paper'||context==='viewport'){await page.getByLabel('DXF контекст',{exact:true}).selectOption('paper');if(context==='viewport'){const views=page.getByTestId('dxf-views');await views.locator('>summary').click();await views.getByTestId('dxf-paper-node').locator('details>summary').click();await views.getByRole('button',{name:'Редактировать модель · Viewport 1',exact:true}).click();}}
 const p=await point(page,context==='paper'?48:8,context==='paper'?22:2,context==='paper'?'layout-canvas':'drawing-canvas');await page.mouse.move(p.x,p.y);await frames(page);const leaf=page.getByTestId('deep-selection-highlight');await expect(leaf).toHaveCount(1);await expect(leaf.locator('polyline,path,line')).toHaveCount(1);await expect(page.getByTestId('hover-contour')).toHaveCount(0);await page.mouse.click(p.x,p.y);await expect(page.getByTestId('deep-properties')).toContainText('только просмотр');await page.getByRole('button',{name:'Выбрать блок',exact:true}).click();await expect(page.getByTestId('deep-properties')).toHaveCount(0);
 await page.mouse.click(p.x,p.y);await expect(page.getByTestId('deep-properties')).toBeVisible();await page.keyboard.down('Control');await page.mouse.click(p.x,p.y);await page.keyboard.up('Control');await expect(page.getByTestId('deep-properties')).toHaveCount(0);expect(await readAutosaveDocument(page)).toEqual(before);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();
});
