import { editorCommand , openRightTab } from './helpers/editorCommands';
import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { readAutosaveDocument } from './helpers/autosave';
import { createNewDocument } from '../src/domain/newDocument';
import type { GeoDocument, SymbolEntity } from '../src/domain/model';
import { PROCESS_FIXTURES, PROCESS_REQUESTS, chainAction } from '../src/process/fixtures';
import { validateConnectivity, connectorRoute } from '../src/connectors/model';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function setup(page:Page,d=createNewDocument(),real=false){
  if(!real){await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));await page.route('**/api/ai/intent',r=>{const body=r.request().postDataJSON();expect(Object.keys(body)).toEqual(['text']);return r.fulfill({json:PROCESS_FIXTURES.get(body.text)??{status:'unsupported'}});});}
  await page.addInitScript(d=>localStorage.setItem('geoservice.document.v2',JSON.stringify(d)),d);await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();
}
const drawing=(page:Page)=>readAutosaveDocument(page);
async function plan(page:Page,text:string){await openRightTab(page,'ai');await page.getByLabel('Запрос',{exact:true}).fill(text);await page.getByRole('button',{name:'Generate plan',exact:true}).click();await expect(page.getByTestId('process-preview')).toBeVisible({timeout:35000});}
async function apply(page:Page){await page.getByTestId('process-preview').getByRole('button',{name:/^Apply /}).click();await expect(page.getByTestId('process-preview')).toHaveCount(0);}
async function saveOpen(page:Page){const event=page.waitForEvent('download');await editorCommand(page, 'Сохранить JSON');const path=(await(await event).path())!,saved=JSON.parse(await readFile(path,'utf8'));await editorCommand(page, 'Новый документ');await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(path);expect(await drawing(page)).toEqual(saved);validateConnectivity(saved);return saved as GeoDocument;}
async function chooseSymbol(page:Page,id:string){await page.getByRole('button',{name:'Инструмент: Выбор',exact:true}).click();await page.locator(`[data-entity-id="${id}"] [data-symbol-hit]`).click();}
test('chain6 + 5 ghosts, target layer, one Undo/Redo, insert, occupied/free append, Move/Rotate, JSON and IndexedDB',async({page})=>{
  await setup(page);await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();const before=await drawing(page);
  await plan(page,PROCESS_REQUESTS.A);expect(await drawing(page)).toEqual(before);await expect(page.getByTestId('symbol-ghost')).toHaveCount(6);await expect(page.getByTestId('process-connector-ghost')).toHaveCount(5);await page.getByLabel('Слой новых объектов',{exact:true}).selectOption('annotations');await apply(page);let d=await drawing(page);expect(d.entities).toHaveLength(11);expect(d.entities.every(e=>e.layerId==='annotations')).toBe(true);validateConnectivity(d);
  await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(before);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(d);
  await plan(page,PROCESS_REQUESTS.insert);await expect(page.getByTestId('symbol-ghost')).toHaveCount(1);await expect(page.getByTestId('process-connector-ghost')).toHaveCount(2);await apply(page);const inserted=await drawing(page);expect(inserted.entities).toHaveLength(13);expect(inserted.entities.filter(e=>e.type==='connector')).toHaveLength(6);validateConnectivity(inserted);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);
  await plan(page,PROCESS_REQUESTS.append);await expect(page.getByTestId('process-preview')).toContainText('Порт уже подключён');await expect(page.getByTestId('process-preview').getByRole('button',{name:/Apply/})).toBeDisabled();expect(await drawing(page)).toEqual(d);
  await page.getByRole('button',{name:'Cancel',exact:true}).click();const edge=d.entities.find(e=>e.type==='connector'&&d.entities.find(s=>s.id===e.end.symbolEntityId)?.name==='ВЫХ-1')!;const route=connectorRoute(d,edge as Parameters<typeof connectorRoute>[1]),a=route[0]!,b=route.at(-1)!;
  const c=page.getByTestId('drawing-canvas'),box=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y'));await page.mouse.click(box.x+box.width/2+((a.x+b.x)/2-cx)*z,box.y+box.height/2-((a.y+b.y)/2-cy)*z);await page.keyboard.press('Delete');
  await expect(page.locator('[data-entity-type="connector"]')).toHaveCount(4);await chooseSymbol(page,d.entities.find(e=>e.name==='ВЫХ-1')!.id);await page.keyboard.press('Delete');await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(5);await plan(page,PROCESS_REQUESTS.append);await apply(page);d=await drawing(page);expect(d.entities.filter(e=>e.type==='symbol')).toHaveLength(6);validateConnectivity(d);
  const valve=d.entities.find(e=>e.name==='К-2')! as SymbolEntity;await chooseSymbol(page,valve.id);await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('1');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('3');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();await page.getByLabel('Поворот (°)',{exact:true}).fill('90');await page.getByLabel('Поворот (°)',{exact:true}).press('Enter');validateConnectivity(await drawing(page));const saved=await saveOpen(page);await page.reload();expect(await drawing(page)).toEqual(saved);await page.screenshot({path:'/private/tmp/geoservice-ai-process-chain.png'});
});
test('current selection reference; selection change stale; local refresh; definition chooser',async({page})=>{
  const d=createNewDocument();d.entities=[{id:'existing-filter',type:'symbol',name:'Ф-1',layerId:'buildings',libraryId:'gas-process-demo',symbolId:'filter',rotationDeg:0,scale:1,position:{x:0,y:0}}];await setup(page,d);await chooseSymbol(page,'existing-filter');await plan(page,PROCESS_REQUESTS.C);await expect(page.getByTestId('symbol-ghost')).toHaveCount(2);await page.keyboard.press('Escape');await expect(page.getByTestId('process-preview')).toHaveAttribute('data-status','process-stale');await chooseSymbol(page,'existing-filter');await openRightTab(page,'ai');await page.getByRole('button',{name:'Пересчитать план',exact:true}).click();await apply(page);validateConnectivity(await drawing(page));
  const text='Создай клапан и фильтр.';PROCESS_FIXTURES.set(text,{actions:[chainAction(['valve','filter'])]});await plan(page,text);await expect(page.getByTestId('process-preview').getByRole('button',{name:/Apply/})).toBeDisabled();await page.getByLabel(/Разрешить definition:/).selectOption('shutoff-valve');await expect(page.getByTestId('symbol-ghost')).toHaveCount(2);await apply(page);
});
test('DXF coexistence: current named layer, preview and Apply do not compile/redraw Canvas base',async({page})=>{
  test.setTimeout(120000);await setup(page);await editorCommand(page, 'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE??'src/tests/fixtures/dxf/simple_ascii.dxf');await page.getByTestId('dxf-report').waitFor();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);
  const original=await drawing(page);await page.getByRole('button',{name:'Создать слой',exact:true}).click();await page.getByRole('button',{name:'Выбрать слой Новый слой',exact:true}).click();await page.getByLabel('Название слоя',{exact:true}).fill('Технологическая схема');await page.getByLabel('Название слоя',{exact:true}).press('Enter');
  const metrics=()=>page.evaluate(async()=>{const {canvasMetrics}=await import(String('/src/renderer/CanvasSceneRenderer.ts'));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return canvasMetrics();});const before=await metrics();await plan(page,PROCESS_REQUESTS.A);await expect(page.getByTestId('symbol-ghost')).toHaveCount(6);await apply(page);const after=await metrics();expect(after.draws).toBe(before.draws);expect(after.compilations).toBe(before.compilations);const result=await drawing(page);expect(result.entities.filter(e=>e.source?.kind==='dxf')).toEqual(original.entities);expect(result.blocks).toEqual(original.blocks);validateConnectivity(result);await saveOpen(page);
});
test('REAL provider in browser: selected filter resolves append preview locally',async({page})=>{
  test.skip(process.env.AI_PROCESS_REAL_BROWSER!=='1');test.setTimeout(60000);const d=createNewDocument();d.entities=[{id:'private-filter-id',type:'symbol',name:'Ф-17',layerId:'buildings',libraryId:'gas-process-demo',symbolId:'filter',rotationDeg:0,scale:1,position:{x:0,y:0}}];await setup(page,d,true);await chooseSymbol(page,'private-filter-id');const request=page.waitForRequest('**/api/ai/intent');await plan(page,PROCESS_REQUESTS.C);expect((await request).postDataJSON()).toEqual({text:PROCESS_REQUESTS.C});await expect(page.getByTestId('symbol-ghost')).toHaveCount(2);await expect(page.getByTestId('process-connector-ghost')).toHaveCount(2);expect(await drawing(page)).toEqual(d);await apply(page);validateConnectivity(await drawing(page));
});
for(const count of [10,30,50])test(`bounded chain ${count}: full ghost, local Fit, atomic Apply and Undo`,async({page})=>{
  await setup(page);const text=`Тестовая цепочка ${count} фильтров`;PROCESS_FIXTURES.set(text,{actions:[chainAction(Array(count).fill('filter'))]});await plan(page,text);await expect(page.getByTestId('symbol-ghost')).toHaveCount(count);await expect(page.getByTestId('process-connector-ghost')).toHaveCount(count-1);await page.getByRole('button',{name:'Вписать preview',exact:true}).click();await apply(page);const d=await drawing(page);expect(d.entities).toHaveLength(2*count-1);validateConnectivity(d);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect((await drawing(page)).entities).toEqual([]);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(d);
});
