import {test,expect} from '@playwright/test';
import {editorCommand,openRightTab} from './helpers/editorCommands';
import {readAutosaveDocument} from './helpers/autosave';
import {ORIGINAL_SPATIAL_REQUEST} from '../src/tests/fixtures/spatialConstraints';
test.skip(process.env.RC_REAL_AI!=='1','Explicit opt-in only: real configured provider, never a mock.');
test('REAL golden Apply/Undo and local orientation clarification preserve prompt-only transport',async({page})=>{
 test.setTimeout(150000);const errors:string[]=[],payloads:unknown[]=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(r.url().endsWith('/api/ai/intent'))payloads.push(r.postDataJSON());});
 await page.goto('/');await editorCommand(page,'Новый документ');await openRightTab(page,'ai');
 const before=await readAutosaveDocument(page);
 await page.getByLabel('Запрос',{exact:true}).fill(ORIGINAL_SPATIAL_REQUEST);
 await page.getByRole('button',{name:'Generate plan',exact:true}).click();
 await expect(page.getByTestId('ai-plan')).toHaveAttribute('data-status','preview',{timeout:65000});
 await expect(page.getByTestId('ai-ghost')).toHaveCount(8);await expect(page.getByTestId('ai-assumptions')).toBeVisible();
 expect(await readAutosaveDocument(page)).toEqual(before);
 await page.getByRole('button',{name:'Apply 8 changes',exact:true}).click();
 const applied=await readAutosaveDocument(page),point=applied.entities.find(e=>e.type==='point');
 if(!point||point.type!=='point')throw Error('Missing valve point');
 expect(applied.vertices[point.vertexId]).toMatchObject({x:17,y:3});expect(applied.entities.filter(e=>e.type==='dimension')).toHaveLength(4);
 await editorCommand(page,'Отменить');expect(await readAutosaveDocument(page)).toEqual(before);
 const prompt='Создай Участок 20 на 30 метров, Дом 5 на 6 метров на севере участка. Ориентацию Дома уточни у меня, не выбирай её автоматически.';
 await page.getByLabel('Запрос',{exact:true}).fill(prompt);await page.getByRole('button',{name:'Generate plan',exact:true}).click();
 await expect(page.getByTestId('ai-local-clarification')).toBeVisible({timeout:65000});
 const question=page.getByTestId('ai-local-clarification').locator('select');await question.selectOption('MODEL');
 await expect(page.getByTestId('ai-local-clarification')).toHaveCount(0);await expect(page.getByTestId('ai-plan')).toContainText(prompt);
 await expect(page.getByRole('button',{name:'Apply 2 changes',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(before);
 expect(payloads).toEqual([{text:ORIGINAL_SPATIAL_REQUEST},{text:prompt}]);expect(errors).toEqual([]);
});
