import { test, expect, type Page } from '@playwright/test';
import { semanticFixture } from '../src/tests/fixtures/semanticLearning';
import { operationsFixture } from '../src/tests/fixtures/documentOperations';
import type { GeoDocument } from '../src/domain/model';
import { editorCommand } from './helpers/editorCommands';
import { readAutosaveDocument } from './helpers/autosave';
const modal=(page:Page)=>page.getByRole('dialog',{name:'Научить GeoService',exact:true});
async function open(page:Page,d:GeoDocument){page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'semantic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await expect.poll(async()=>(await readAutosaveDocument(page)).metadata.title).toBe(d.metadata.title);}
async function setup(page:Page,d=semanticFixture()){
  await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));
  await page.route('**/api/ai/intent',r=>{const body=r.request().postDataJSON();expect(Object.keys(body)).toEqual(['text']);expect(body.text).toBe('выдели все трубы');return r.fulfill({json:{intent:{actions:[{type:'select_entities',query:{kind:'semantic_concept',concepts:['pipe'],scope:'document'}}]},unsupported:false}});});
  await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();await open(page,d);
}
async function selectExample(page:Page,name='pipe-1'){await page.getByLabel('Поиск в документе',{exact:true}).fill(name);await page.locator('.search-results .query-result').getByRole('button',{name,exact:true}).click();}
async function propose(page:Page,name='Трубы'){await editorCommand(page,'Научить GeoService');await modal(page).getByLabel('Название смысловой категории',{exact:true}).fill(name);await modal(page).getByRole('button',{name:'Предложить правило',exact:true}).click();await expect(modal(page).getByTestId('semantic-count-EXACT')).toBeVisible();}
async function save(page:Page){await modal(page).getByRole('button',{name:'Запомнить',exact:true}).click();await expect(modal(page)).toHaveCount(0);await expect.poll(async()=>!!(await readAutosaveDocument(page)).semantics).toBe(true);}

test('teach review/exclude is preview first; one Undo/Redo, local Search/AI, reload/JSON',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await selectExample(page);const before=await readAutosaveDocument(page);await propose(page);
  await expect(modal(page).getByTestId('semantic-count-EXACT')).toHaveText('3');await expect(modal(page).getByTestId('semantic-count-STRONG')).toHaveText('1');await expect(modal(page).getByLabel('Принять WEAK',{exact:true})).not.toBeChecked();await expect(page.locator('[data-query-owner="other-4"]')).toHaveCount(0);expect(await readAutosaveDocument(page)).toEqual(before);
  await modal(page).getByRole('button',{name:'Fit EXACT',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(before);await modal(page).getByRole('button',{name:'Выбрать EXACT',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(before);await modal(page).getByRole('button',{name:'Показать EXACT',exact:true}).click();await modal(page).getByRole('button',{name:'Показать объект pipe-4',exact:true}).click();await expect(page.locator('[data-query-owner]')).toHaveCount(1);await modal(page).getByRole('button',{name:'Fit объекта pipe-4',exact:true}).click();await modal(page).getByLabel('Включить объект pipe-4',{exact:true}).uncheck();await save(page);const taught=await readAutosaveDocument(page);expect(taught.entities).toEqual(before.entities);expect(taught.semantics!.annotations.find(a=>a.entityId==='pipe-4')).toMatchObject({polarity:'negative'});
  await editorCommand(page,'Отменить');expect(await readAutosaveDocument(page)).toEqual(before);await editorCommand(page,'Повторить');expect((await readAutosaveDocument(page)).semantics).toEqual(taught.semantics);
  await page.getByLabel('Поиск в документе',{exact:true}).fill('трубы');await expect(page.locator('.search-results .query-result')).toHaveCount(3);await expect(page.locator('.search-results')).toContainText('STRONG');await page.getByRole('button',{name:'Выбрать результаты',exact:true}).click();await expect(page.getByRole('complementary',{name:'Свойства объекта'}).locator('.panel-heading')).toContainText('3 объектов');await page.getByRole('button',{name:'Показать только результаты',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(taught);await page.getByRole('button',{name:'Выйти из изоляции',exact:true}).click();
  await page.getByLabel('Запрос',{exact:true}).fill('выдели все трубы');await page.getByRole('button',{name:'Generate plan',exact:true}).click();const preview=page.getByTestId('document-operations-preview');await expect(preview).toContainText('Найдено: 3');await expect(preview).toContainText('Правило');await preview.getByRole('button',{name:'Выбрать',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(taught);
  const download=page.waitForEvent('download');await editorCommand(page,'Сохранить JSON');const file=await download;await file.saveAs('/private/tmp/geoservice-semantic-roundtrip.json');await page.reload();await expect(page.getByTestId('drawing-canvas')).toBeVisible();await page.getByLabel('Поиск в документе',{exact:true}).fill('трубы');await expect(page.locator('.search-results .query-result')).toHaveCount(3);await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles('/private/tmp/geoservice-semantic-roundtrip.json');expect((await readAutosaveDocument(page)).semantics).toEqual(taught.semantics);expect(errors).toEqual([]);
});

test('cancel and Escape leave no knowledge/history; focus supports immediate Space pan',async({page})=>{
  await setup(page);await selectExample(page);const before=await readAutosaveDocument(page);await propose(page);await modal(page).getByLabel('Принять WEAK',{exact:true}).check();await modal(page).getByRole('button',{name:'Отмена',exact:true}).click();expect(await readAutosaveDocument(page)).toEqual(before);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();await propose(page);await page.keyboard.press('Escape');await expect(modal(page)).toHaveCount(0);await expect(page.getByTestId('selected-id')).toHaveText('pipe-1');await expect(page.getByTestId('drawing-canvas')).toBeFocused();const canvas=page.getByTestId('drawing-canvas'),center=await canvas.getAttribute('data-center-x'),r=(await canvas.boundingBox())!;await page.keyboard.down('Space');await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+50,r.y+r.height/2+20);await page.mouse.up();await page.keyboard.up('Space');await expect(canvas).not.toHaveAttribute('data-center-x',center!);expect(await readAutosaveDocument(page)).toEqual(before);
});

test('custom category aliases, parent, management refine/disable/delete and Properties labels',async({page})=>{
  await setup(page);await selectExample(page);await propose(page,'Трубы продувки');await modal(page).getByLabel('Синонимы категории',{exact:true}).fill('продувка');await modal(page).getByLabel('Родитель категории',{exact:true}).selectOption('pipe');await save(page);await page.getByLabel('Поиск в документе',{exact:true}).fill('продувка');await expect(page.locator('.search-results .query-result')).toHaveCount(4);
  await editorCommand(page,'Смысл / категории');await modal(page).getByRole('button',{name:'Проверить / изменить правило',exact:true}).click();await modal(page).getByText('Уточнить признаки',{exact:true}).click();const color=modal(page).getByLabel(/^Роль признака Цвет:/);await color.selectOption('off');await color.selectOption('supporting');await save(page);
  await editorCommand(page,'Смысл / категории');await modal(page).getByRole('button',{name:'Отключить правило',exact:true}).click();await expect(page.locator('.search-results .query-result')).toHaveCount(1);await editorCommand(page,'Отменить');await expect(page.locator('.search-results .query-result')).toHaveCount(4);
  await selectExample(page);await page.getByTestId('semantic-properties').getByText(/^Смысл ·/).click();await expect(page.getByTestId('semantic-properties')).toContainText('Трубы продувки');await page.getByLabel('Категория объекта',{exact:true}).selectOption('well');await page.getByRole('button',{name:'Добавить значение',exact:true}).click();await expect(page.getByTestId('semantic-properties')).toContainText('Колодец');await page.getByRole('button',{name:'Убрать явную метку',exact:true}).last().click();
  const customId=(await readAutosaveDocument(page)).semantics!.concepts.find(c=>c.name==='Трубы продувки')!.id;await page.getByLabel('Категория объекта',{exact:true}).selectOption(customId);await editorCommand(page,'Смысл / категории');await modal(page).getByRole('button',{name:'Удалить категорию Трубы продувки',exact:true}).click();await expect(page.getByLabel('Категория объекта',{exact:true})).toHaveValue('pipe');await page.getByLabel('Поиск в документе',{exact:true}).fill('продувка');await expect(page.locator('.search-results .query-result')).toHaveCount(0);await editorCommand(page,'Отменить');await expect(page.locator('.search-results .query-result')).toHaveCount(4);
});

test('image-derived canonical geometry teaches without loading raster and survives reload',async({page})=>{
  const d=semanticFixture();d.metadata.title='Image semantic fixture';d.entities=d.entities.map((e,i)=>i<4?{...e,imageSource:{source:'image-vectorization',sourceAssetId:'unavailable',vectorizationRunId:'run',candidateType:'line'}}:e);await setup(page,d);await selectExample(page);await propose(page,'Тест изображения');await save(page);const before=await readAutosaveDocument(page);await page.reload();await expect(page.getByTestId('drawing-canvas')).toBeVisible();await page.getByLabel('Поиск в документе',{exact:true}).fill('Тест изображения');await expect(page.locator('.search-results .query-result')).toHaveCount(4);expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);
});

test('broad layer zero remains Weak; explicit examples can be saved without accepting whole drawing',async({page})=>{
  const d=semanticFixture();d.metadata.title='Broad layer fixture';d.entities=d.entities.map(e=>{const{source,style,...rest}=e;void source;void style;return rest;});await setup(page,d);await selectExample(page);await propose(page);await expect(modal(page)).toContainText('Нет отличительного общего признака');await expect(modal(page).getByTestId('semantic-count-WEAK')).toHaveText('12');await save(page);await page.getByLabel('Поиск в документе',{exact:true}).fill('трубы');await expect(page.locator('.search-results .query-result')).toHaveCount(1);await page.getByLabel('Включить слабые смысловые подсказки',{exact:true}).check();await expect(page.locator('.search-results .query-result')).toHaveCount(12);
});

test('BlockDefinition and own ATTRIB are evidence; nested content remains owned by instances',async({page})=>{
  const d=operationsFixture();d.metadata.title='Block semantic fixture';await setup(page,d);await selectExample(page,'mark-a');await propose(page,'Колодец');await expect(modal(page)).toContainText('Определение блока: VOLUME');await expect(modal(page).getByTestId('semantic-count-EXACT')).toHaveText('2');await expect(modal(page).getByTestId('semantic-count-STRONG')).toHaveText('0');await save(page);await page.getByLabel('Поиск в документе',{exact:true}).fill('колодец');await expect(page.locator('.search-results .query-result')).toHaveCount(2);
});

test('reference DXF neutral VOLUME category, viewport identity, no mutation during Fit and measured browser acceptance',async({page})=>{
  test.skip(!process.env.DXF_REFERENCE,'Reference DXF local opt-in');test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await editorCommand(page,'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await page.getByTestId('dxf-report').waitFor();await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Открыть DXF',exact:true})).toHaveCount(0);const d=await readAutosaveDocument(page);
  await page.getByLabel('Поиск в документе',{exact:true}).fill('VOLUME');await expect(page.locator('.search-results .query-result')).toHaveCount(62);await page.locator('.search-results .query-result').first().getByRole('button').first().click();const id=await page.getByTestId('selected-id').textContent();await page.evaluate(()=>{(window as unknown as {semanticLongTasks:{start:number;duration:number}[]}).semanticLongTasks=[];new PerformanceObserver(list=>{(window as unknown as {semanticLongTasks:{start:number;duration:number}[]}).semanticLongTasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})));}).observe({type:'longtask',buffered:false});});
  const stages:{name:string;start:number;end:number}[]=[];const measured=async(name:string,action:()=>Promise<void>)=>{const start=await page.evaluate(()=>performance.now());await action();const end=await page.evaluate(()=>new Promise<number>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(performance.now())))));stages.push({name,start,end});};
  const started=Date.now();await measured('propose',()=>propose(page,'Тестовая группа VOLUME'));const counts={exact:Number(await modal(page).getByTestId('semantic-count-EXACT').textContent()),strong:Number(await modal(page).getByTestId('semantic-count-STRONG').textContent()),weak:Number(await modal(page).getByTestId('semantic-count-WEAK').textContent())};expect(counts.exact+counts.strong).toBe(62);await measured('fit',()=>modal(page).getByRole('button',{name:'Fit EXACT',exact:true}).click());expect(await readAutosaveDocument(page)).toEqual(d);await page.screenshot({path:'/private/tmp/geoservice-semantic-reference-teach.png',fullPage:true});await measured('confirm/autosave',async()=>{await modal(page).getByRole('button',{name:'Запомнить',exact:true}).click();await expect(modal(page)).toHaveCount(0);await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально');});const taught=await readAutosaveDocument(page);await measured('search',async()=>{await page.getByLabel('Поиск в документе',{exact:true}).fill('Тестовая группа VOLUME');await expect(page.locator('.search-results .query-result')).toHaveCount(62);await expect(page.locator('.semantic-search-explanation')).toHaveCount(62);});const searchMs=Date.now()-started;await measured('select',async()=>{await page.getByRole('button',{name:'Выбрать результаты',exact:true}).click();await expect(page.getByRole('complementary',{name:'Свойства объекта'}).locator('.panel-heading')).toContainText('62 объектов');});const selectionMs=Date.now()-started;
  const layout=taught.dxfLayouts!.find(l=>l.viewports.some(v=>!v.unsupportedReason))!,vp=layout.viewports.find(v=>!v.unsupportedReason)!;await page.getByLabel('DXF контекст',{exact:true}).selectOption(layout.id);await page.getByLabel('DXF viewport',{exact:true}).selectOption(vp.id);await page.getByTestId('dxf-views').locator(':scope>summary').click();const node=page.getByTestId('dxf-paper-node').filter({has:page.getByRole('button',{name:`Paper Space ${layout.name}`,exact:true})});await node.locator('details>summary').click();await node.getByRole('button',{name:'Редактировать модель · Viewport 1',exact:true}).click();await expect(page.locator('.active-viewport-editor')).toBeVisible();await page.getByLabel('Область поиска',{exact:true}).selectOption('model');await expect(page.locator('.search-results .query-result')).toHaveCount(62);expect(await readAutosaveDocument(page)).toEqual(taught);
  const longTasks=await page.evaluate(()=>(window as unknown as {semanticLongTasks:{start:number;duration:number}[]}).semanticLongTasks);const appLongTasks=longTasks.filter(t=>stages.some(s=>t.start>=s.start&&t.start<s.end));await test.info().attach('semantic-reference',{body:JSON.stringify({example:id,counts,searchAndReviewWallMs:searchMs,selectAndReviewWallMs:selectionMs,stages:stages.map(s=>({name:s.name,wallMs:s.end-s.start,longTasks:appLongTasks.filter(t=>t.start>=s.start&&t.start<s.end).map(t=>t.duration)})),appLongTasks:appLongTasks.map(t=>t.duration),allObservedLongTasks:longTasks.map(t=>t.duration),note:'App stages exclude transport of full document through E2E/DevTools autosave helpers; timing includes two frames and UI debounce.'},null,2),contentType:'application/json'});expect(errors).toEqual([]);
});
