import { expect, test, type Page } from '@playwright/test';
import { spatialDocument } from '../src/tests/fixtures/spatialDocument';
import { createNewDocument } from '../src/domain/newDocument';
import { entityPoints, type GeoDocument } from '../src/domain/model';
import { bounds } from '../src/geometry';
import type { AiAction } from '../src/ai/intent';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function load(page:Page,d:GeoDocument){await page.addInitScript(d=>localStorage.setItem('geoservice.document.v2',JSON.stringify(d)),d);await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
async function drawing(page:Page):Promise<GeoDocument>{return page.evaluate(()=>JSON.parse(localStorage.getItem('geoservice.document.v2')!));}
async function screen(page:Page,x:number,y:number){const c=page.getByTestId('drawing-canvas');await c.scrollIntoViewIfNeeded();const b=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y'));return{x:b.x+b.width/2+(x-cx)*z,y:b.y+b.height/2-(y-cy)*z};}
async function marquee(page:Page,a:{x:number;y:number},b:{x:number;y:number},modifier?:string){const s=await screen(page,a.x,a.y),e=await screen(page,b.x,b.y);if(modifier)await page.keyboard.down(modifier);await page.mouse.move(s.x,s.y);await page.mouse.down();await page.mouse.move(e.x,e.y,{steps:8});await expect(page.getByTestId('marquee-selection')).toHaveAttribute('data-mode',a.x<b.x?'window':'crossing');await page.mouse.up();if(modifier)await page.keyboard.up(modifier);}
function group(){const d=createNewDocument();d.viewport={center:{x:8,y:5},pixelsPerUnit:30};d.vertices={};d.entities=[];for(let i=0;i<5;i++){const x=i*3,a=`a${i}`,b=`b${i}`;d.vertices[a]={id:a,x,y:4};d.vertices[b]={id:b,x:x+2,y:4};d.entities.push({id:`line${i}`,type:'line',name:`Линия ${i}`,layerId:'boundary',startVertexId:a,endVertexId:b});}return d;}
async function translated(page:Page,d:GeoDocument,dx:number,dy:number){await expect.poll(async()=>(await drawing(page)).vertices.a0!.x).toBeCloseTo(dx,5);const after=await drawing(page);for(const v of Object.values(d.vertices)){expect(after.vertices[v.id]!.x).toBeCloseTo(v.x+dx,5);expect(after.vertices[v.id]!.y).toBeCloseTo(v.y+dy,5);}}
test('Window five entities, group drag, one Undo; Crossing partial lines',async({page})=>{const d=group();await load(page,d);await marquee(page,{x:-1,y:6},{x:15,y:2});await expect(page.getByTestId('group-properties')).toContainText('5 объектов');expect(await drawing(page)).toEqual(d);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();const s=await screen(page,1,4),e=await screen(page,6,2);await page.mouse.move(s.x,s.y);await page.mouse.down();await page.mouse.move(e.x,e.y,{steps:10});await page.mouse.up();await translated(page,d,5,-2);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await marquee(page,{x:1,y:5},{x:-1,y:3});await expect(page.getByTestId('editor-error')).toContainText('Линия 0');});
test('Window rejects partial, modifiers and numeric group Properties/M exact delta',async({page})=>{const d=group();await load(page,d);await marquee(page,{x:-1,y:5},{x:1,y:3});await expect(page.getByTestId('editor-error')).toContainText('Готов');await marquee(page,{x:-1,y:6},{x:6,y:2});await expect(page.getByTestId('group-properties')).toContainText('2 объектов');await marquee(page,{x:5.5,y:6},{x:8.5,y:2},'Shift');await expect(page.getByTestId('group-properties')).toContainText('3 объектов');await marquee(page,{x:5.5,y:6},{x:8.5,y:2},'Control');await expect(page.getByTestId('group-properties')).toContainText('2 объектов');await marquee(page,{x:5.5,y:6},{x:8.5,y:2},'Shift');await page.keyboard.press('m');await expect(page.getByLabel('Перемещение ΔX',{exact:true})).toBeFocused();await page.getByLabel('Перемещение ΔX',{exact:true}).fill('5');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('-2');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();const a=await drawing(page);for(let i=0;i<5;i++){expect(a.vertices[`a${i}`]!.x).toBe(d.vertices[`a${i}`]!.x+(i<3?5:0));expect(a.vertices[`a${i}`]!.y).toBe(i<3?2:4);}await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);});
test('marquee Esc retains selection; movement below threshold stays click, no dirty/history',async({page})=>{const d=group();await load(page,d);await marquee(page,{x:-1,y:6},{x:6,y:2});const s=await screen(page,-1,7),e=await screen(page,15,1);await page.mouse.move(s.x,s.y);await page.mouse.down();await page.mouse.move(e.x,e.y,{steps:8});await page.keyboard.press('Escape');await page.mouse.up();await expect(page.getByTestId('group-properties')).toContainText('2 объектов');await expect(page.getByTestId('marquee-selection')).toHaveCount(0);await page.mouse.move(s.x,s.y);await page.mouse.down();await page.mouse.move(s.x+2,s.y+1);await page.mouse.up();await expect(page.getByTestId('group-properties')).toHaveCount(0);expect(await drawing(page)).toEqual(d);});
const rectangle:AiAction={type:'create_rectangle',name:'Сарай',width:3,height:5,placement:{type:'relative_to_entity',reference:{kind:'named_entity',name:'Дом'},direction:'east',gapMeters:2}};
const edge:AiAction={type:'create_line_along_polygon_edge',name:'Газовая труба',reference:{kind:'named_entity',name:'Участок'},side:'west',offsetMeters:1.5,offsetSide:'outside'};
const array:AiAction={type:'create_rectangle_array',nameBase:'Грядка',count:4,width:1,height:4,reference:{kind:'named_entity',name:'Дом'},direction:'south',itemGap:.8};
async function ai(page:Page,action:AiAction,d=spatialDocument()){let calls=0;await page.route('**/api/ai/config',r=>r.fulfill({json:{mode:'mock'}}));await page.route('**/api/ai/intent',r=>{calls++;expect(Object.keys(r.request().postDataJSON())).toEqual(['text']);return r.fulfill({json:{actions:[action]}});});await load(page,d);return()=>calls;}
async function generate(page:Page,text:string){await page.getByRole('textbox',{name:'Запрос',exact:true}).fill(text);await page.getByRole('button',{name:'Generate plan',exact:true}).click();await expect(page.getByTestId('ai-plan')).toBeVisible();}
test('AI existing rectangle preview exact gap, highlight and no source mutation',async({page})=>{const d=spatialDocument();await ai(page,rectangle,d);await generate(page,'Поставь сарай 3×5 в 2 м восточнее дома');await expect(page.getByTestId('ai-ghost')).toHaveCount(1);await expect(page.getByTestId('ai-reference-highlight')).toHaveCount(1);await expect(page.getByTestId('ai-assumptions')).toContainText('2.000 м');expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Apply',exact:true}).click();const after=await drawing(page);expect(bounds(entityPoints(after.entities.at(-1)!,after.vertices))).toEqual({minX:15,minY:12,maxX:18,maxY:17});expect(after.entities.slice(0,2)).toEqual(d.entities);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);});
test('AI west line exact parallel offset',async({page})=>{await ai(page,edge);await generate(page,'Газовая труба вдоль западной границы участка с отступом 1,5 м');await expect(page.getByTestId('ai-ghost')).toHaveCount(1);await page.getByRole('button',{name:'Apply',exact:true}).click();const d=await drawing(page);expect(bounds(entityPoints(d.entities.at(-1)!,d.vertices))).toEqual({minX:-1.5,maxX:-1.5,minY:0,maxY:30});});
test('AI array, capture layer, local target switch, exact gaps, atomic Undo',async({page})=>{const before=spatialDocument();const calls=await ai(page,array,before);await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await generate(page,'Размести четыре грядки 1×4 южнее дома с промежутком 0,8 м');await expect(page.getByLabel('Слой новых объектов')).toHaveValue('buildings');await expect(page.getByTestId('ai-ghost')).toHaveCount(4);await page.getByLabel('Слой новых объектов').selectOption('annotations');await expect(page.getByTestId('ai-ghost')).toHaveCount(4);expect(calls()).toBe(1);expect(await drawing(page)).toEqual(before);await page.getByRole('button',{name:'Apply 4 changes',exact:true}).click();const after=await drawing(page),created=after.entities.slice(2);expect(created.map(e=>e.name)).toEqual(['Грядка 1','Грядка 2','Грядка 3','Грядка 4']);expect(created.every(e=>e.layerId==='annotations')).toBe(true);const boxes=created.map(e=>bounds(entityPoints(e,after.vertices))!);for(let i=1;i<4;i++)expect(boxes[i]!.minX-boxes[i-1]!.maxX).toBeCloseTo(.8,10);expect((boxes[0]!.minX+boxes[3]!.maxX)/2).toBe(10);expect(after.entities.slice(0,2)).toEqual(before.entities);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(before);});
test('AI duplicate object chooser local, once for normalized name',async({page})=>{const d=spatialDocument();d.entities.push({...d.entities[0]!,id:'house2'});const calls=await ai(page,rectangle,d);await generate(page,'Поставь сарай 3×5 в 2 м восточнее дома');await expect(page.getByLabel('Разрешить entity:дом')).toHaveCount(1);await expect(page.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await page.getByLabel('Разрешить entity:дом').selectOption('house2');await expect(page.getByTestId('ai-ghost')).toHaveCount(1);await expect(page.getByRole('button',{name:'Apply',exact:true})).toBeEnabled();expect(calls()).toBe(1);expect(await drawing(page)).toEqual(d);});
test('AI current selection local reference, change selection invalidates plan',async({page})=>{await ai(page,{...rectangle,placement:{type:'relative_to_entity',reference:{kind:'current_selection'},direction:'east'}});const p=await screen(page,10,14);await page.mouse.click(p.x,p.y);await generate(page,'Поставь сарай 3×5 справа от выбранного объекта');await expect(page.getByTestId('ai-ghost')).toHaveCount(1);await page.getByRole('button',{name:'Вписать',exact:true}).click();const s=await screen(page,2,12);await page.mouse.click(s.x,s.y);await expect(page.getByTestId('ai-plan')).toHaveAttribute('data-status','stale');await expect(page.getByRole('button',{name:'Apply',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Пересчитать план',exact:true}).click();await expect(page.getByTestId('ai-ghost')).toHaveCount(1);});
