import { editorCommand } from './helpers/editorCommands';
import { expect, test, type Page } from '@playwright/test';
import { readAutosaveDocument } from './helpers/autosave';
import { readFile } from 'node:fs/promises';
import { createNewDocument } from '../src/domain/newDocument';
import { spatialDocument } from '../src/tests/fixtures/spatialDocument';
import { symbolDocument } from '../src/tests/fixtures/symbolDocument';
import type { GeoDocument, SymbolEntity } from '../src/domain/model';
import { selectionModelAnchor } from '../src/domain/exactMove';
import { symbolWorldBounds } from '../src/symbols/transforms';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});
test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function load(page:Page,d:GeoDocument){await page.addInitScript(d=>localStorage.setItem('geoservice.document.v2',JSON.stringify(d)),d);await page.goto('/');await expect(page.getByTestId('drawing-canvas')).toBeVisible();}
async function drawing(page:Page):Promise<GeoDocument>{return readAutosaveDocument(page);}
async function screen(page:Page,x:number,y:number){const c=page.getByTestId('drawing-canvas');await c.scrollIntoViewIfNeeded();const b=(await c.boundingBox())!,z=Number(await c.getAttribute('data-zoom')),cx=Number(await c.getAttribute('data-center-x')),cy=Number(await c.getAttribute('data-center-y'));return{x:b.x+b.width/2+(x-cx)*z,y:b.y+b.height/2-(y-cy)*z};}
async function choose(page:Page,name:string){await page.getByRole('button',{name:'Символы',exact:true}).click();await page.getByRole('button',{name:`Вставить символ: ${name}`,exact:true}).click();}
async function place(page:Page,name:string,x:number,y:number,rotate=false){await choose(page,name);const p=await screen(page,x,y);await page.mouse.move(p.x,p.y);await expect(page.getByTestId('symbol-ghost')).toBeVisible();if(rotate)await page.keyboard.press('r');await page.mouse.click(p.x,p.y);await expect(page.getByTestId('symbol-ghost')).toHaveCount(0);}
async function absolute(page:Page,x:number,y:number,anchor='center'){await page.getByRole('button',{name:'Переместить… · M',exact:true}).click();await page.getByRole('button',{name:'X/Y Абсолютно',exact:true}).click();await page.getByLabel('Базовая точка',{exact:true}).selectOption(anchor);await page.getByLabel('Перемещение MODEL X',{exact:true}).fill(String(x));await page.getByLabel('Перемещение MODEL Y',{exact:true}).fill(String(y));await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();}
async function marquee(page:Page,x:number,y:number,X:number,Y:number){const a=await screen(page,x,y),b=await screen(page,X,Y);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();}
test('Polygon center exact (50,25), group lower-left (100,200), one Undo/Redo and no-op',async({page})=>{
  const d=spatialDocument();d.vertices.sa={id:'sa',x:15,y:12};d.vertices.sb={id:'sb',x:18,y:12};d.vertices.sc={id:'sc',x:18,y:17};d.vertices.sd={id:'sd',x:15,y:17};d.entities.push({type:'polygon',id:'shed',name:'Сарай',layerId:'buildings',vertexIds:['sa','sb','sc','sd']});await load(page,d);
  const p=await screen(page,10,14);await page.mouse.click(p.x,p.y);await page.keyboard.press('m');await expect(page.getByLabel('Перемещение ΔX',{exact:true})).toBeFocused();await expect(page.getByLabel('Перемещение ΔX',{exact:true})).toHaveValue('0');await page.getByTestId('drawing-canvas').press('m');await expect(page.getByLabel('Перемещение ΔX',{exact:true})).toBeFocused();await page.getByRole('button',{name:'X/Y Абсолютно',exact:true}).click();await page.getByLabel('Перемещение MODEL X',{exact:true}).fill('50');await page.getByLabel('Перемещение MODEL Y',{exact:true}).fill('25');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();
  await expect.poll(async()=>selectionModelAnchor(await drawing(page),['house'])).toEqual({x:50,y:25});await expect(page.getByRole('button',{name:'Применить перемещение',exact:true})).toBeDisabled();
  const moved=await drawing(page);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(moved);await page.getByRole('button',{name:'Отменить',exact:true}).click();
  const s=await screen(page,16,14);await page.keyboard.down('Shift');await page.mouse.click(s.x,s.y);await page.keyboard.up('Shift');await expect(page.getByTestId('group-properties')).toContainText('2 объектов');
  await page.getByLabel('Базовая точка',{exact:true}).selectOption('bottom-left');await page.getByLabel('Перемещение MODEL X',{exact:true}).fill('100');await page.getByLabel('Перемещение MODEL Y',{exact:true}).fill('200');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();
  await expect.poll(async()=>selectionModelAnchor(await drawing(page),['house','shed'],'bottom-left')).toEqual({x:100,y:200});const group=await drawing(page);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(group);
});
test('layer Fit includes hidden/locked content without document, history or dirty changes; empty disabled',async({page})=>{
  const d=symbolDocument();d.layers.find(l=>l.id==='buildings')!.visible=false;d.layers.find(l=>l.id==='buildings')!.locked=true;await load(page,d);const c=page.getByTestId('drawing-canvas'),previous=await c.getAttribute('data-center-x');
  await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await expect(c).not.toHaveAttribute('data-center-x',previous!);await expect(c).toHaveAttribute('data-center-x','10.5');expect(await drawing(page)).toEqual(d);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();await expect(page.getByLabel('Есть несохранённые изменения')).toHaveCount(0);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(0);
  await page.getByRole('button',{name:'Создать слой',exact:true}).click();await expect(page.getByRole('button',{name:'Вписать слой',exact:true})).toBeDisabled();
});
test('palette local alias/category search and Escape cancel with no insertion',async({page})=>{
  const d=createNewDocument();await load(page,d);await page.getByRole('button',{name:'Символы',exact:true}).click();await page.getByLabel('Поиск символов',{exact:true}).fill('редуктор');await expect(page.getByRole('button',{name:'Вставить символ: Регулятор давления',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/Вставить символ:/})).toHaveCount(1);await page.getByLabel('Поиск символов',{exact:true}).fill('');await page.getByLabel('Категория символов',{exact:true}).selectOption('КИП');await expect(page.getByRole('button',{name:/Вставить символ:/})).toHaveCount(3);await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Библиотека символов',exact:true})).toHaveCount(0);
  await choose(page,'Запорный кран');const p=await screen(page,0,0);await page.mouse.move(p.x,p.y);await expect(page.getByTestId('symbol-ghost')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByTestId('symbol-ghost')).toHaveCount(0);expect(await drawing(page)).toEqual(d);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();
});
test('insert valve/filter/regulator on current layer, R ghost, marquee Absolute (100,200), rotation/scale, Save/Open',async({page})=>{
  await load(page,createNewDocument());await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await place(page,'Запорный кран',-6,0);for(let i=0;i<14&&Number(await page.getByTestId('drawing-canvas').getAttribute('data-zoom'))>25;i++)await page.getByRole('button',{name:'Уменьшить',exact:true}).click();await place(page,'Фильтр',0,0,true);await place(page,'Регулятор давления',6,0);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(3);
  let d=await drawing(page);expect(d.entities.every(e=>e.layerId==='buildings')).toBe(true);expect(d.entities[1]).toMatchObject({rotationDeg:90});await marquee(page,-8,2,8,-2);await expect(page.getByTestId('group-properties')).toContainText('3 объектов');await absolute(page,100,200,'bottom-left');await expect.poll(async()=>selectionModelAnchor(await drawing(page),d.entities.map(e=>e.id),'bottom-left')).toEqual({x:100,y:200});
  const moved=await drawing(page);await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Повторить',exact:true}).click();expect(await drawing(page)).toEqual(moved);
  await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await page.getByRole('button',{name:'Вписать слой',exact:true}).click();await page.locator(`[data-entity-id="${d.entities[0]!.id}"] [data-symbol-hit]`).click();await expect(page.getByTestId('passive-ports')).toBeVisible();const port=page.locator('[data-port-id="out"]'),oldX=await port.getAttribute('cx');
  await page.getByLabel('Поворот (°)',{exact:true}).fill('90');await page.getByLabel('Поворот (°)',{exact:true}).press('Enter');await expect(port).not.toHaveAttribute('cx',oldX!);await page.getByLabel('Масштаб символа',{exact:true}).fill('2');await page.getByLabel('Масштаб символа',{exact:true}).press('Enter');await page.getByLabel('Имя / Tag',{exact:true}).fill('К-1');await page.getByLabel('Имя / Tag',{exact:true}).press('Enter');
  d=await drawing(page);expect(d.entities[0]).toMatchObject({rotationDeg:90,scale:2,name:'К-1'});expect(symbolWorldBounds(d.entities[0] as SymbolEntity).maxY-symbolWorldBounds(d.entities[0] as SymbolEntity).minY).toBeCloseTo(4);
  const downloadPromise=page.waitForEvent('download');await editorCommand(page, 'Сохранить JSON');const path=(await (await downloadPromise).path())!,saved=JSON.parse(await readFile(path,'utf8'));expect(saved).toEqual(d);expect(saved.entities[0].geometry).toBeUndefined();await editorCommand(page, 'Новый документ');await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles(path);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(3);expect(await drawing(page)).toEqual(d);
  await page.screenshot({path:'test-results/symbol-library.png'});
});
test('symbol label follows exact MODEL (50,30), selected R undo and dependent lock blocks movement',async({page})=>{
  await load(page,symbolDocument());await page.locator('[data-entity-id="valve"] [data-symbol-hit]').click();await page.keyboard.press('r');await expect(page.getByLabel('Поворот (°)',{exact:true})).toHaveValue('90');await page.getByRole('button',{name:'Отменить',exact:true}).click();await expect(page.getByLabel('Поворот (°)',{exact:true})).toHaveValue('0');await page.getByRole('button',{name:'Добавить подпись',exact:true}).click();const before=await drawing(page),label=before.entities.at(-1)!;expect(label).toMatchObject({type:'label',targetId:'valve',template:'{name}'});
  await page.locator('[data-entity-id="valve"] [data-symbol-hit]').click();await absolute(page,50,30);await expect.poll(async()=>(await drawing(page)).entities.find(e=>e.id==='valve')).toMatchObject({position:{x:50,y:30}});const after=await drawing(page);expect(after.entities.at(-1)).toEqual(label);await editorCommand(page, 'Вписать');await expect(page.locator(`[data-entity-id="${label.id}"] text`)).toHaveText('valve');
  await page.getByRole('button',{name:'Заблокировать слой Аннотации',exact:true}).click();await page.locator('[data-entity-id="valve"] [data-symbol-hit]').click();await expect(page.getByRole('form',{name:'Перемещение выбора'}).getByText(/Перемещение затронет связанный объект на заблокированном/)).toBeVisible();await expect(page.getByRole('button',{name:'Применить перемещение',exact:true})).toBeDisabled();
});
test('locked or hidden current layer blocks Symbol insertion without creating a dedicated layer',async({page})=>{
  const d=createNewDocument();await load(page,d);await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await page.getByRole('button',{name:'Заблокировать слой Здания',exact:true}).click();await choose(page,'Запорный кран');const p=await screen(page,0,0);await page.mouse.click(p.x,p.y);await expect(page.getByTestId('editor-error')).toContainText('Текущий слой скрыт или заблокирован');await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Разблокировать слой Здания',exact:true}).click();await page.getByRole('button',{name:'Скрыть слой Здания',exact:true}).click();await choose(page,'Фильтр');await page.mouse.click(p.x,p.y);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(0);expect((await drawing(page)).layers.map(l=>l.id)).toEqual(d.layers.map(l=>l.id));
});
test('CROSSING selects partial Symbol, Shift group and Relative Δ, own layer lock blocks',async({page})=>{
  const d=symbolDocument();d.entities=d.entities.filter(e=>e.type==='symbol');d.vertices={};await load(page,d);await marquee(page,8,9,9.5,7);await expect(page.locator('[data-entity-id="valve"]')).toHaveAttribute('data-selected','false');await marquee(page,9.5,9,8,7);await expect(page.locator('[data-entity-id="valve"]')).toHaveAttribute('data-selected','true');await page.locator('[data-entity-id="filter"] [data-symbol-hit]').click({modifiers:['Shift']});await expect(page.getByTestId('group-properties')).toContainText('2 объектов');await page.keyboard.press('m');await page.getByLabel('Перемещение ΔX',{exact:true}).fill('5');await page.getByLabel('Перемещение ΔY',{exact:true}).fill('-2');await page.getByRole('button',{name:'Применить перемещение',exact:true}).click();await expect.poll(async()=>(await drawing(page)).entities.find(e=>e.id==='valve')).toMatchObject({position:{x:15,y:6}});expect((await drawing(page)).entities.find(e=>e.id==='filter')).toMatchObject({position:{x:20,y:6}});await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await drawing(page)).toEqual(d);await page.getByRole('button',{name:'Заблокировать слой Здания',exact:true}).click();await expect(page.getByRole('button',{name:'Применить перемещение',exact:true})).toBeDisabled();
});
test('Symbol insertion reuses Vertex/Grid snap without attaching vertices or passive ports',async({page})=>{
  const d=symbolDocument();await load(page,d);await page.getByRole('button',{name:'Выбрать слой Здания',exact:true}).click();await choose(page,'Запорный кран');const a=await screen(page,0,0);await page.mouse.move(a.x+3,a.y+2);await expect(page.getByTestId('snap-indicator')).toHaveAttribute('data-snap-type','vertex');await page.mouse.click(a.x+3,a.y+2);await expect.poll(async()=>(await drawing(page)).entities.at(-1)).toMatchObject({position:{x:0,y:0}});
  await page.getByText('Типы привязок',{exact:true}).click();await page.getByLabel('Vertex',{exact:true}).uncheck();await page.getByLabel('Midpoint',{exact:true}).uncheck();await page.getByLabel('Grid',{exact:true}).check();await page.getByText('Типы привязок',{exact:true}).click();await choose(page,'Фильтр');const p=await screen(page,3.1,2.1);await page.mouse.move(p.x,p.y);await expect(page.getByTestId('snap-indicator')).toHaveAttribute('data-snap-type','grid');await page.mouse.click(p.x,p.y);await expect.poll(async()=>(await drawing(page)).entities.at(-1)).toMatchObject({position:{x:3,y:2}});expect((await drawing(page)).vertices).toEqual(d.vertices);
});
test('unknown symbol definition Open shows semantic error, retains drawing and has no console error',async({page})=>{
  const d=symbolDocument();await load(page,d);for(const patch of [{libraryId:'missing-pack'},{symbolId:'missing-symbol'}]){
    const symbol=d.entities.find(e=>e.type==='symbol')!;await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles({name:'unknown.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...d,entities:[{...symbol,...patch}]}))});
    await expect(page.getByRole('alert')).toContainText('Неизвестное обозначение');expect(await drawing(page)).toEqual(d);await expect(page.locator('[data-entity-type="symbol"]')).toHaveCount(3);await expect(page.getByRole('button',{name:'Отменить',exact:true})).toBeDisabled();
  }
});
