import { expect, test, type Page } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { createNewDocument } from '../src/domain/newDocument';
import { topologyFixture, processFixtureDocument } from '../src/tests/fixtures/topology';
import type { RouteCandidate } from '../src/topology/types';
import type { GeoDocument } from '../src/domain/model';
import { editorCommand, openRightTab } from './helpers/editorCommands';
import { readAutosaveDocument } from './helpers/autosave';
async function seed(page:Page,d:GeoDocument){await page.addInitScript(d=>{if(!sessionStorage.getItem('topology-seeded')){localStorage.setItem('geoservice.document.v2',JSON.stringify(d));sessionStorage.setItem('topology-seeded','1');}},d);await page.goto('/');await expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально');}
async function open(page:Page,source='layer'){await editorCommand(page,'Восстановить связи');await page.getByLabel('Область восстановления',{exact:true}).selectOption(source);if(source==='layer')await page.getByLabel('Слой восстановления',{exact:true}).selectOption('buildings');await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByTestId('topology-counts')).toBeVisible();}
const diagnostics=async(page:Page)=>JSON.parse((await page.getByTestId('topology-diagnostics').textContent())!);
async function accept(page:Page,count:number){await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await expect(page.getByRole('button',{name:`Применить связи (${count})`,exact:true})).toBeEnabled();await page.getByRole('button',{name:`Применить связи (${count})`,exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(async()=>(await readAutosaveDocument(page)).entities.filter(e=>e.type==='connector').length).toBe(count);}
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
test('manual CAD: safe bulk, Reject/leave, lightweight canvas overlay, Cancel, Apply one Undo, reload/Search/Properties',async({page})=>{
 const d=processFixtureDocument();await seed(page,d);await open(page);expect((await diagnostics(page)).geometryCount).toBe(4);await expect(page.getByTestId('topology-counts')).toContainText('Связи: 4');await page.getByTestId('route-0').hover();await expect(page.getByTestId('topology-overlay')).toHaveCount(1);await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await page.getByTestId('route-0').getByRole('button',{name:'Отклонить',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (3)',exact:true})).toBeEnabled();await page.getByTestId('route-0').getByRole('button',{name:'Оставить геометрией',exact:true}).click();await page.getByRole('button',{name:'Отмена',exact:true}).click();expect((await readAutosaveDocument(page)).entities).toEqual(d.entities);
 await open(page);await accept(page,4);const applied=await readAutosaveDocument(page);expect(applied.entities.some(e=>e.type==='line')).toBe(false);expect(applied.entities.filter(e=>e.type==='connector').every(e=>e.topologySource?.resolution==='user-confirmed')).toBe(true);
 await editorCommand(page,'Отменить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(d.entities);await editorCommand(page,'Повторить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(applied.entities);await page.reload();await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(applied.entities);
 await openRightTab(page,'search');await page.getByLabel('Поиск в документе',{exact:true}).fill('Восстановленная связь');await expect(page.locator('.search-results .query-result')).toHaveCount(4);await page.locator('.search-results .query-result').first().getByRole('button',{name:'Восстановленная связь',exact:true}).click();await openRightTab(page,'properties');await expect(page.getByTestId('connector-start')).toContainText('Input');await page.getByTestId('property-source').locator('summary').click();await expect(page.getByTestId('property-source')).toContainText('Восстановлено из схемы');
});
test('ambiguous port choice is explicit; bulk does not accept it',async({page})=>{await seed(page,topologyFixture('B'));await open(page);await expect(page.getByTestId('route-0')).toContainText('AMBIGUOUS');await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (0)',exact:true})).toBeDisabled();await page.getByLabel('Порт start route-0',{exact:true}).selectOption(JSON.stringify(['valve','out']));await page.getByTestId('route-0').getByRole('button',{name:'Подтвердить',exact:true}).click();await page.getByRole('button',{name:'Применить связи (1)',exact:true}).click();await expect.poll(async()=>(await readAutosaveDocument(page)).entities.filter(e=>e.type==='connector').length).toBe(1);});
test('X choice: connected branch retains geometry; crossing enables faithful ordinary connector',async({page})=>{const d=topologyFixture('D');await seed(page,d);await open(page);await expect(page.getByTestId('finding-crossing')).toHaveCount(1);await page.getByRole('button',{name:'Соединено',exact:true}).click();await expect(page.getByTestId('finding-junction')).toHaveCount(1);await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (0)',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Просто пересекаются',exact:true}).click();await expect(page.getByTestId('finding-junction')).toHaveCount(0);await accept(page,1);const applied=await readAutosaveDocument(page);expect(applied.entities.some(e=>e.id==='cross')).toBe(true);await editorCommand(page,'Отменить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(d.entities);});
test('small gap requires repair plus route confirmation, never bulk ambiguous; complex route cannot Apply',async({page})=>{await seed(page,topologyFixture('E'));await open(page);await expect(page.getByTestId('route-0')).toHaveCount(0);await page.getByRole('button',{name:'Соединить разрыв',exact:true}).click();await expect(page.getByTestId('route-0')).toContainText('AMBIGUOUS');await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (0)',exact:true})).toBeDisabled();await page.getByTestId('route-0').getByRole('button',{name:'Подтвердить',exact:true}).click();await page.getByRole('button',{name:'Применить связи (1)',exact:true}).click();await expect.poll(async()=>(await readAutosaveDocument(page)).entities.filter(e=>e.type==='connector').length).toBe(1);});
test('default selected scope empty/worker failure/cancel are human and preserve document',async({page})=>{const d=topologyFixture();await seed(page,d);await editorCommand(page,'Восстановить связи');await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Не найдено линий');await page.getByRole('button',{name:'Отмена',exact:true}).click();expect((await readAutosaveDocument(page)).entities).toEqual(d.entities);await page.route('**/src/topology/analysis.worker.ts*',r=>r.abort());await editorCommand(page,'Восстановить связи');await page.getByLabel('Область восстановления',{exact:true}).selectOption('layer');await page.getByLabel('Слой восстановления',{exact:true}).selectOption('buildings');await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Локальный процесс анализа');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect((await readAutosaveDocument(page)).entities).toEqual(d.entities);});
test('synthetic raster Input Valve Filter Regulator Output: real local extraction/recognition/review/topology/Apply/Undo, zero external',async({page})=>{
 test.setTimeout(150000);await seed(page,createNewDocument());const external:string[]=[],ai:string[]=[];page.context().on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());if(r.url().includes('/api/ai/intent'))ai.push(r.url());});
 const png=await page.evaluate(async()=>{const {topologyImageFixture}=await import(String('/src/tests/fixtures/topologyImage.ts'));return topologyImageFixture().toDataURL().split(',')[1];});await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles({name:'topology-process.png',mimeType:'image/png',buffer:Buffer.from(png!,'base64')});await expect(page.getByTestId('underlay-properties')).toBeVisible();await editorCommand(page,'Векторизация изображения');await page.getByRole('button',{name:'4. Извлечение',exact:true}).click();await page.getByRole('button',{name:'Извлечь геометрию',exact:true}).click();await expect(page.getByTestId('image-progress')).toHaveCount(0);await page.getByRole('button',{name:'Распознать текст и символы',exact:true}).click();await expect(page.getByRole('button',{name:'Распознать текст и символы',exact:true})).toBeEnabled({timeout:120000});
 await test.info().attach('raster-recognition',{body:await page.locator('.recognition-group').allTextContents().then(v=>JSON.stringify(v)),contentType:'application/json'});await expect(page.locator('.recognition-group')).toHaveCount(4);const unknown=page.locator('.recognition-group').filter({hasText:'Неизвестный повторяющийся символ'});await unknown.getByRole('combobox').selectOption('gas-process-demo/filter');for(const button of await page.getByRole('button',{name:/Подтвердить группу/}).all())await button.click();await page.getByRole('button',{name:/Применить результат/}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(async()=>(await readAutosaveDocument(page)).entities.filter(e=>e.type==='symbol').length).toBe(5);
 const before=await readAutosaveDocument(page);await open(page,'image-group');const metrics=await diagnostics(page);await test.info().attach('raster-topology',{body:JSON.stringify(metrics),contentType:'application/json'});await expect(page.getByTestId('topology-counts')).toContainText('Связи: 4');await accept(page,4);const applied=await readAutosaveDocument(page);writeFileSync('docs/audit-results/topology-raster.json',JSON.stringify({symbols:5,geometry:before.entities.filter(e=>e.type==='line'||e.type==='polyline').length,graph:metrics,connectors:4,externalRequests:external.length,aiRequests:ai.length},null,2)+'\n');await editorCommand(page,'Отменить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(before.entities);expect(applied.entities.filter(e=>e.type==='symbol')).toHaveLength(5);expect(external).toEqual([]);expect(ai).toEqual([]);
});
test('equivalent native vector PDF: native signature recognition, no raster entity, topology and one Undo',async({page})=>{
 await seed(page,createNewDocument());await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles('e2e/fixtures/pdf/topology-process.pdf');await expect(page.getByTestId('pdf-route')).toContainText('Векторный PDF');await page.getByLabel('Масштаб PDF, м/pt',{exact:true}).fill('0.025');await page.getByRole('button',{name:'Распознать символы из векторов',exact:true}).click();await test.info().attach('pdf-symbols',{body:JSON.stringify(await page.locator('.recognition-group').allTextContents()),contentType:'application/json'});await expect(page.locator('.recognition-group')).toHaveCount(5);const unknown=page.locator('.recognition-group').filter({hasText:'Неизвестный повторяющийся символ'});await unknown.getByRole('combobox').selectOption('gas-process-demo/filter');for(const button of await page.getByRole('button',{name:/Подтвердить группу/}).all())await button.click();await page.getByRole('button',{name:/Применить PDF/}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(async()=>(await readAutosaveDocument(page)).entities.filter(e=>e.type==='symbol').length).toBe(5);const before=await readAutosaveDocument(page);expect(before.entities.some(e=>e.type==='raster_underlay')).toBe(false);const external:string[]=[];page.context().on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());});await open(page,'image-group');const metrics=await diagnostics(page);await expect(page.getByTestId('topology-counts')).toContainText('Связи: 4');await accept(page,4);writeFileSync('docs/audit-results/topology-pdf.json',JSON.stringify({symbols:5,geometry:before.entities.filter(e=>e.type==='line'||e.type==='polyline').length,graph:metrics,connectors:4,rasterEntities:0,externalTopologyRequests:external.length},null,2)+'\n');await editorCommand(page,'Отменить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(before.entities);expect(external).toEqual([]);
});
test('private DXF: bounded canonical geometry experiment, neutral counts, no nested expansion or document mutation',async({page})=>{
 test.skip(!process.env.DXF_REFERENCE,'Private DXF requires an explicit local path');test.setTimeout(120000);await page.goto('/');await editorCommand(page,'DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles(process.env.DXF_REFERENCE!);await expect(page.getByRole('button',{name:'Открыть как новый документ',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const before=await readAutosaveDocument(page),canonical=before.entities.filter(e=>e.type==='line'||e.type==='polyline');expect(canonical.length).toBeGreaterThan(0);const first=canonical[0]!,ids=first.type==='line'?[first.startVertexId,first.endVertexId]:first.type==='polyline'?first.vertexIds:[],points=ids.map(id=>before.vertices[id]!),minX=Math.min(...points.map(p=>p.x))-1,minY=Math.min(...points.map(p=>p.y))-1,maxX=Math.max(...points.map(p=>p.x))+1,maxY=Math.max(...points.map(p=>p.y))+1;
 await editorCommand(page,'Восстановить связи');await page.getByLabel('Область восстановления',{exact:true}).selectOption('area');for(const [key,value]of Object.entries({minX,minY,maxX,maxY}))await page.getByLabel(`Область ${key}`,{exact:true}).fill(String(value));await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByTestId('topology-counts')).toBeVisible();const metrics=await diagnostics(page),counts=await page.getByTestId('topology-counts').innerText();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const base=await page.evaluate(()=>({...((globalThis as unknown as {__geoCanvasCounters:{draws:number;compilations:number}}).__geoCanvasCounters)}));await page.getByTestId('finding-free').first().getByRole('button',{name:'AMBIGUOUS',exact:true}).click();await expect(page.getByTestId('topology-overlay')).toHaveCount(1);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const after=await page.evaluate(()=>((globalThis as unknown as {__geoCanvasCounters:{draws:number;compilations:number}}).__geoCanvasCounters));expect(after.draws).toBe(base.draws);expect(after.compilations).toBe(base.compilations);writeFileSync('docs/audit-results/topology-dxf.json',JSON.stringify({canonicalOwners:before.entities.length,scopedGeometry:metrics.geometryCount,counts,diagnostics:Object.fromEntries(Object.entries(metrics).filter(([key])=>key!=='tolerances')),nestedExpansion:false,engineeringInterpretation:false},null,2)+'\n');await page.getByRole('button',{name:'Отмена',exact:true}).click();expect((await readAutosaveDocument(page)).entities).toEqual(before.entities);
});

test('unsupported complex route and changed scope preserve ordinary geometry',async({page})=>{const d=topologyFixture('H');await seed(page,d);await open(page);await expect(page.getByTestId('route-0')).toContainText('не сохраняет форму');await page.getByTestId('route-0').getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (0)',exact:true})).toBeDisabled();await page.getByLabel('Слой восстановления',{exact:true}).selectOption('annotations');await expect(page.getByTestId('topology-counts')).toHaveCount(0);await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Не найдено линий');await page.getByRole('button',{name:'Отмена',exact:true}).click();expect((await readAutosaveDocument(page)).entities).toEqual(d.entities);});
test('local worker phase timings, scoped cloning, Apply and main-thread long-task measurement',async({page})=>{
 await seed(page,processFixtureDocument());
 const measurements=await page.evaluate(async()=>{const {processFixtureDocument,addPath}=await import(String('/src/tests/fixtures/topology.ts')), {reconstructTopology}=await import(String('/src/topology/client.ts')), {topologyCommands}=await import(String('/src/topology/apply.ts')), {applyCommandsAtomically}=await import(String('/src/domain/commands.ts'));const d=processFixtureDocument(),scope={kind:'layer' as const,layerId:'buildings'};await reconstructTopology(d,scope,{},new AbortController().signal);topologyCommands(d,await reconstructTopology(d,scope,{},new AbortController().signal),{'route-0':{status:'confirmed'}});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const longTasks:number[]=[],observer=new PerformanceObserver(list=>longTasks.push(...list.getEntries().map(e=>e.duration)));observer.observe({type:'longtask'});const samples=[];for(let i=0;i<20;i++){const start=performance.now(),graph=await reconstructTopology(d,scope,{},new AbortController().signal),elapsed=performance.now()-start,applyStart=performance.now(),commands=topologyCommands(d,graph,Object.fromEntries(graph.routes.map((r:RouteCandidate)=>[r.id,{status:'confirmed' as const}])));applyCommandsAtomically(d,commands);samples.push({phases:graph.diagnostics.timings,elapsed,apply:performance.now()-applyStart});}const large=processFixtureDocument();for(let i=0;i<1000;i++)addPath(large,`far${i}`,[{x:100+i*10,y:100},{x:102+i*10,y:100}]);const scoped=await reconstructTopology(large,{kind:'selection',ids:['path0','path1','path2','path3']},{},new AbortController().signal);await new Promise(r=>setTimeout(r,100));observer.disconnect();return {samples,longTasks,scopedGeometry:scoped.diagnostics.geometryCount,documentGeometry:1004};});
 writeFileSync('docs/audit-results/topology-performance.json',JSON.stringify(measurements,null,2)+'\n');expect(measurements.scopedGeometry).toBe(4);expect(measurements.longTasks.filter(t=>t>50)).toEqual([]);
});

test('proposed T junction confirmation and rejection affect conversion; branch remains ordinary geometry',async({page})=>{const d=topologyFixture('C');await seed(page,d);await open(page);await page.getByRole('button',{name:'Подтвердить узел',exact:true}).click();await expect(page.getByTestId('finding-junction')).toContainText('CONFIRMED');await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await expect(page.getByRole('button',{name:'Применить связи (0)',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Отклонить узел',exact:true}).click();await expect(page.getByTestId('finding-junction')).toContainText('REJECTED');await accept(page,1);expect((await readAutosaveDocument(page)).entities.some(e=>e.id==='branch')).toBe(true);await editorCommand(page,'Отменить');await expect.poll(async()=>(await readAutosaveDocument(page)).entities).toEqual(d.entities);});
