import { Dialog } from './Dialog';
import { useEffect, useRef, useState } from 'react';
import type { DxfOptions, DxfPlan, TypeReport } from '../dxf/types';
import type { DxfEncoding } from '../dxf/encoding';
function Breakdown({rows}:{rows:Record<string,TypeReport>}) {return <table><thead><tr><th>DXF</th><th>Всего</th><th>Converted</th><th>Simplified</th><th>Proxy</th><th>Unsupported</th></tr></thead><tbody>{Object.entries(rows).map(([type,r])=><tr key={type}><td>{type}</td><td>{r.total}</td><td>{r.converted}</td><td>{r.simplified}</td><td>{r.proxy}</td><td>{r.unsupported}</td></tr>)}</tbody></table>;}
export function DxfDialog({onClose,onApply}:{onClose:()=>void;onApply:(plan:DxfPlan)=>void}) {
  const [file,setFile]=useState<File|null>(null),[options,setOptions]=useState<DxfOptions>({frame:'projected',encoding:'auto'}),[plan,setPlan]=useState<DxfPlan|null>(null),[error,setError]=useState(''),[phase,setPhase]=useState(''),fileInput=useRef<HTMLInputElement>(null),worker=useRef<Worker|null>(null),request=useRef(0),completedOptions=useRef<DxfOptions|null>(null);
  useEffect(()=>{
    const id=++request.current;if(!file)return;let active=true;setPlan(null);setError('');setPhase('Чтение файла');
    const w=new Worker(new URL('../dxf/worker.ts',import.meta.url),{type:'module'});worker.current=w;
    w.onmessage=(e:MessageEvent<{phase?:string;plan?:DxfPlan;error?:string}>)=>{if(!active||id!==request.current)return;if(e.data.phase)setPhase(e.data.phase);if(e.data.plan){completedOptions.current=options;setPlan(e.data.plan);setPhase('');}if(e.data.error){setError(e.data.error);setPhase('');}};
    w.onerror=()=>{if(active){setError('DXF Worker failed');setPhase('');}};
    void(async()=>{try{if(file.size>32*1024*1024)throw new Error('DXF превышает лимит 32 МБ');const buffer=await file.arrayBuffer();if(active)w.postMessage({buffer,filename:file.name,options},[buffer]);}catch(e){if(active){setError(e instanceof Error?e.message:'Ошибка чтения');setPhase('');}}})();
    return()=>{active=false;w.terminate();worker.current=null;};
  },[file,options]);
  const totals=Object.values(plan?.report.types??{}).reduce((a,r)=>({converted:a.converted+r.converted,simplified:a.simplified+r.simplified,proxy:a.proxy+r.proxy,unsupported:a.unsupported+r.unsupported}),{converted:0,simplified:0,proxy:0,unsupported:0});
  const report=plan?.report,canApply=!!plan&&completedOptions.current===options&&!phase&&!report?.requiresUnitsChoice&&!report?.requiresEncodingChoice;
  return <Dialog title="Открыть DXF" subtitle="Файл обрабатывается в этом браузере и открывается как новый документ." size="lg" className="dxf-dialog" closeLabel="Закрыть DXF" onClose={onClose} footer={<><button onClick={onClose}>Отмена</button><button className="primary-button" disabled={!canApply} onClick={()=>{if(plan)onApply(plan);}}>Открыть как новый документ</button></>}>
    <div className="dxf-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f?.name.toLowerCase().endsWith('.dxf'))setFile(f);else setError('Выберите файл DXF');}}><span>Перетащите DXF сюда или</span><button onClick={()=>fileInput.current?.click()}>Выбрать файл</button><input ref={fileInput} style={{display:'none'}} type="file" accept=".dxf" aria-label="Файл DXF" onChange={e=>{setFile(e.target.files?.[0]??null);}} />{file&&<strong>{file.name} · {(file.size/1024/1024).toFixed(2)} МБ</strong>}</div>
    <h3>Параметры</h3><div className="dxf-options"><label>Кодировка<select aria-label="Кодировка DXF" value={options.encoding} onChange={e=>setOptions({...options,encoding:e.target.value as DxfEncoding})}><option value="auto">Auto · header + UTF-8 validation</option><option value="utf-8">UTF-8</option><option value="windows-1251">Windows-1251</option></select></label>
    <label>Исходные единицы<select aria-label="Единицы DXF" value={options.units??''} onChange={e=>{const units=e.target.value as 'mm'|'cm'|'m'|'';const next={...options};if(units)next.units=units;else delete next.units;setOptions(next);}}><option value="">INSUNITS</option><option value="mm">Миллиметры</option><option value="cm">Сантиметры</option><option value="m">Метры</option></select></label>
    <label>Координаты<select aria-label="Система DXF" value={options.frame} onChange={e=>setOptions({...options,frame:e.target.value as 'local'|'projected'})}><option value="projected">Projected / Survey · direct E=X, N=Y</option><option value="local">Local · без привязки</option></select></label></div>
    {phase&&<p role="status">{phase}…</p>}{error&&<p role="alert">{error}</p>}
    {report&&<div data-testid="dxf-report"><dl className="dxf-summary"><dt>Файл</dt><dd>{report.filename}</dd><dt>Версия</dt><dd>{report.version}</dd><dt>Encoding</dt><dd>{report.encoding} · declared {report.declaredCodepage||'unknown'}</dd><dt>Units / factor to metres</dt><dd>{report.originalUnits===6?'meters':`INSUNITS ${report.originalUnits}`} · ×{report.factor}</dd><dt>Слои</dt><dd>{report.layerCount}</dd><dt>Объекты MODEL</dt><dd>{report.modelSpaceCount}</dd><dt>Блоки / экземпляры</dt><dd>{report.blockCount} / {report.blockInstances}</dd><dt>Converted / simplified / proxy / unsupported</dt><dd>{totals.converted} / {totals.simplified} / {totals.proxy} / {totals.unsupported}</dd><dt>Paper Space</dt><dd>{plan?.document.dxfLayouts?.length??0} контейнеров · {plan?.document.dxfLayouts?.reduce((n,l)=>n+l.paperPrimitives.length,0)??0} примитивов</dd><dt>MODEL viewport</dt><dd>{plan?.document.dxfLayouts?.reduce((n,l)=>n+l.viewports.length,0)??0}</dd><dt>Предупреждения</dt><dd>{report.warnings.length}</dd></dl>
      {report.requiresUnitsChoice&&<p role="alert">Выберите исходные единицы; координаты не будут угадываться.</p>}{report.requiresEncodingChoice&&<p role="alert">Подтвердите кодировку перед открытием.</p>}
      <details><summary>Подробный отчёт</summary><p>Исходные записи ENTITIES вне MODEL: {report.paperSpaceCount}, включая VIEWPORT. Содержимое Paper Space-блоков учтено отдельно.</p><details><summary>Отчёт по типам Model Space</summary><Breakdown rows={report.types}/></details><details><summary>Геометрия внутри definitions</summary><Breakdown rows={report.blockTypes}/></details><details><summary>Предупреждения ({report.warnings.length})</summary><ul>{report.warnings.map(w=><li key={w}>{w}</li>)}</ul></details><details><summary>Время обработки</summary><p>{Object.entries(report.timings).map(([phase,ms])=>`${phase}: ${ms.toFixed(1)} ms`).join(' · ')}</p><p>Normalized primitives: {report.normalizedPrimitives}</p></details></details>
    </div>}
  </Dialog>;
}
