import {useEffect,useRef,useMemo} from 'react';
import type {GeoDocument} from '../domain/model';
import {conceptsNamed,conceptsFor} from '../semantics/concepts';
import {listLibraries,requireSymbol} from '../symbols/registry';
import type {Candidate,RegionCandidate} from '../image/types';
import {renderSymbolSignature} from '../image/symbolRecognition';
import {isConfirmedRegion} from '../image/understanding';
interface Props{document:GeoDocument;candidates:Candidate[];included:ReadonlySet<string>;selected:string|null;onPick:(id:string)=>void;onFit:(c:Candidate)=>void;onUpdate:(id:string,patch:Partial<Omit<RegionCandidate,'proposedSymbol'>>&{proposedSymbol?:RegionCandidate['proposedSymbol']|undefined})=>void;onAccept:(ids:string[],accept:boolean)=>void;onGeometry:(id:string,accept:boolean)=>void}
export function ImageUnderstandingReview({document,candidates,included,selected,onPick,onFit,onUpdate,onAccept,onGeometry}:Props){const root=useRef<HTMLDivElement>(null);useEffect(()=>{if(!selected)return;const row=root.current?.querySelector<HTMLElement>(`[data-review-id="${CSS.escape(selected)}"]`);const details=row?.closest('details');if(details)details.open=true;row?.scrollIntoView({block:'nearest'});},[selected]);const texts=candidates.filter((c):c is RegionCandidate=>c.type==='text'&&'bounds'in c),symbols=candidates.filter((c):c is RegionCandidate=>c.type==='symbol'&&'bounds'in c),groups=useMemo(()=>[...new Set(symbols.map(c=>c.groupId??c.id))].map(id=>({id,items:symbols.filter(c=>(c.groupId??c.id)===id)})),[symbols]);const concepts=conceptsFor(document);const suggestion=(c:RegionCandidate)=>{const name=c.type==='text'?c.recognizedText:c.proposedSymbol?requireSymbol(c.proposedSymbol.libraryId,c.proposedSymbol.symbolId).name:'';return name?conceptsNamed(document,name)[0]:undefined;};const suggested=[...texts,...symbols].filter(c=>suggestion(c));return <div ref={root} className="image-understanding-review">
 <section><h3>Геометрия · {candidates.filter(c=>'points'in c||c.type==='circle').length}</h3><details><summary>Проверить объекты по одному</summary>{candidates.filter(c=>'points'in c||c.type==='circle').slice(0,100).map(c=><div data-review-id={c.id} key={c.id} className={selected===c.id?'recognition-row active':'recognition-row'}><button onClick={()=>onPick(c.id)}>{c.type} · {c.id}</button><button aria-label={`Fit ${c.id}`} onClick={()=>onFit(c)}>Fit</button><label><input type="checkbox" checked={included.has(c.id)} onChange={e=>onGeometry(c.id,e.target.checked)}/>Принять</label></div>)}</details></section>
 <section><h3>Текст · {texts.filter(c=>c.recognizedText).length} распознано · {texts.filter(c=>!c.confirmed).length} требуют проверки</h3><p>Результат OCR может ошибаться. Исправьте текст и подтвердите перед Apply.</p><button disabled={!texts.some(c=>c.recognizedText&&(c.confidence??0)>=.8)} onClick={()=>onAccept(texts.filter(c=>c.recognizedText&&(c.confidence??0)>=.8).map(c=>c.id),true)}>Подтвердить читаемый текст</button>{texts.slice(0,40).map(c=><div data-review-id={c.id} key={c.id} className={`recognition-row${selected===c.id?' active':''}`}><button aria-label={`Показать текст ${c.id}`} onClick={()=>onPick(c.id)}>{c.id} · {(c.confidence??0)<.8?'Требует проверки':'Распознано'}</button><button aria-label={`Fit ${c.id}`} onClick={()=>onFit(c)}>Fit</button><label>Текст<input aria-label={`Текст ${c.id}`} maxLength={10000} value={c.recognizedText??''} onChange={e=>onUpdate(c.id,{recognizedText:e.target.value,confirmed:false})}/></label><label>Ориентация<select aria-label={`Ориентация текста ${c.id}`} value={c.rotationDeg??0} onChange={e=>onUpdate(c.id,{rotationDeg:Number(e.target.value),confirmed:false})}>{[...new Set([0,90,-90,180,c.rotationDeg??0])].map(v=><option key={v} value={v}>{v}°</option>)}</select></label><label><input aria-label={`Подтвердить текст ${c.id}`} type="checkbox" disabled={!c.recognizedText?.trim()} checked={!!c.confirmed&&included.has(c.id)} onChange={e=>onAccept([c.id],e.target.checked)}/>Текст проверен</label></div>)}</section>
 <section><h3>Символы · {groups.length} групп</h3>{groups.map(g=>{const first=g.items[0]!,p=first.proposedSymbol;return <section key={g.id} className="recognition-group"><h4>{p?`Похоже на: ${requireSymbol(p.libraryId,p.symbolId).name}`:'Неизвестный повторяющийся символ'} · {g.items.length}</h4><small>{p?.matchClass==='strong'?'Сильный кандидат':p?'Возможный кандидат':'Нет надёжного соответствия'}</small>{first.evidence?.map(e=><p key={e}>{e}</p>)}<label>Назначить обозначение<select aria-label={`Символ группы ${g.id}`} value={p?`${p.libraryId}/${p.symbolId}`:''} onChange={e=>{const [libraryId,symbolId]=e.target.value.split('/');const signature=libraryId&&symbolId?renderSymbolSignature(requireSymbol(libraryId,symbolId)):null;g.items.forEach(c=>onUpdate(c.id,{proposedSymbol:libraryId&&symbolId&&signature?{libraryId,symbolId,confirmed:false,rotationDeg:0,localWidth:signature.width,localCenter:{x:signature.center.x,y:-signature.center.y}}:undefined}));}}><option value="">Не назначен · оставить геометрией</option>{listLibraries().flatMap(l=>l.symbols.map(s=><option key={`${l.id}/${s.id}`} value={`${l.id}/${s.id}`}>{s.name}</option>))}</select></label><button disabled={!p} onClick={()=>onAccept(g.items.map(c=>c.id),true)}>Подтвердить группу {g.id}</button><button onClick={()=>onAccept(g.items.map(c=>c.id),false)}>Оставить геометрией</button><details><summary>Проверить экземпляры</summary>{g.items.map(c=><div data-review-id={c.id} className={`recognition-row${selected===c.id?' active':''}`} key={c.id}><button onClick={()=>onPick(c.id)}>{c.id}</button><button aria-label={`Fit ${c.id}`} onClick={()=>onFit(c)}>Fit</button><label><input type="checkbox" aria-label={`Подтвердить символ ${c.id}`} disabled={!c.proposedSymbol} checked={!!c.proposedSymbol?.confirmed&&included.has(c.id)} onChange={e=>onAccept([c.id],e.target.checked)}/>Подтверждён</label></div>)}</details></section>;})}</section>
 <section><h3>Смысл · {suggested.length} предложений</h3><p>Категория относится только к подтверждённому тексту или символу. Соседние линии не получают инженерного значения.</p>{suggested.map(c=>{const concept=suggestion(c)!;return <label key={c.id}><input type="checkbox" aria-label={`Добавить категорию ${c.id}`} disabled={!isConfirmedRegion(c)||!included.has(c.id)} checked={!!c.semanticConfirmed} onChange={e=>onUpdate(c.id,{semanticConceptId:concept.id,semanticConfirmed:e.target.checked})}/>{concept.name} · {c.id} · совпало собственное название/alias</label>;})}<details><summary>Назначить другую категорию вручную</summary>{[...texts,...symbols].filter(isConfirmedRegion).map(c=><label key={c.id}>{c.id}<select aria-label={`Категория кандидата ${c.id}`} value={c.semanticConfirmed?c.semanticConceptId??'':''} onChange={e=>onUpdate(c.id,{semanticConceptId:e.target.value,semanticConfirmed:!!e.target.value})}><option value="">Без метки</option>{concepts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}</details><small>После Apply: выделите результат → Научить GeoService. Используется то же хранилище знаний документа.</small></section>
 </div>;}
