import '../image/vectorization.css';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { GeoDocument, RasterUnderlayEntity } from '../domain/model';
import type { DocumentCommand } from '../domain/commands';
import { useRasterAsset } from '../assets/useRasterAsset';
import { focusEditor } from '../editor/focus';
import { CloseButton } from './IconButton';
import { prepareImage, processImage, type WorkerResult } from '../image/client';
import { DEFAULT_EXTRACTION, type Candidate, type ExtractionOptions, type ImageCalibration, type ImageQuad, type PixelImage, type PixelPoint } from '../image/types';
import { distancePx, fullQuad, metresPerPixel, quadError, rectifiedSize } from '../image/transform';
import { isGeometry, vectorizationCommands } from '../image/apply';
const stages = ['Изображение', 'Перспектива', 'Масштаб', 'Извлечение', 'Проверка'];
const categories = ['line', 'polyline', 'contour', 'circle', 'text', 'symbol'] as const;
const labels: Record<Candidate['type'], string> = { line: 'Линии', polyline: 'Полилинии', contour: 'Контуры', circle: 'Окружности', text: 'Области текста', symbol: 'Области символов' };
const cornerNames = ['Верхний левый', 'Верхний правый', 'Нижний правый', 'Нижний левый'];
function PixelCanvas({ image, opacity = 1 }: { image: PixelImage; opacity?: number }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = ref.current; if (!canvas) return; canvas.width = image.width; canvas.height = image.height; canvas.getContext('2d')?.putImageData(new ImageData(new Uint8ClampedArray(image.data), image.width, image.height), 0, 0); return () => { canvas.width = canvas.height = 0; }; }, [image]);
  return <canvas ref={ref} style={{ width: '100%', height: '100%', opacity }} />;
}
function CandidateShape({ candidate, selected, excluded }: { candidate: Candidate; selected: boolean; excluded: boolean }) {
  const common = { className: `image-candidate candidate-${candidate.type}${selected ? ' selected' : ''}${excluded ? ' excluded' : ''}`, vectorEffect: 'non-scaling-stroke' as const, 'data-candidate-id': candidate.id, 'data-candidate-type': candidate.type };
  if (candidate.type === 'circle') return <circle {...common} cx={candidate.center.x} cy={candidate.center.y} r={candidate.radius} />;
  if ('points' in candidate) { const points = candidate.points.map(p => `${p.x},${p.y}`).join(' '); return candidate.type === 'contour' ? <polygon {...common} points={points} /> : <polyline {...common} points={points} />; }
  return <rect {...common} x={candidate.bounds.x} y={candidate.bounds.y} width={candidate.bounds.width} height={candidate.bounds.height} />;
}
interface Props { document: GeoDocument; currentLayerId: string; selectionId: string | null; onClose: () => void; onApply: (commands: DocumentCommand[], expectedDocument: GeoDocument) => void }
export function ImageVectorizationDialog(props: Props) {
  const rasters = props.document.entities.filter((e): e is RasterUnderlayEntity => e.type === 'raster_underlay');
  const [id, setId] = useState(rasters.find(e => e.id === props.selectionId)?.id ?? rasters[0]?.id ?? '');
  const raster = rasters.find(e => e.id === id);
  return raster ? <ImageWorkflow key={raster.id} {...props} raster={raster} rasters={rasters} onRaster={setId} /> : <div className="modal-backdrop"><div className="import-dialog" role="dialog" aria-modal="true" aria-label="Векторизация изображения" data-shortcut-suppressed><div className="import-heading"><h2>Векторизация изображения</h2><CloseButton label="Закрыть векторизацию" onClick={props.onClose} autoFocus /></div><p>Сначала добавьте PNG, JPEG или статический WebP через «Файл / данные → Подложка». Изображение останется обычной подложкой.</p><button className="primary-button" onClick={props.onClose}>Вернуться к импорту</button></div></div>;
}
function ImageWorkflow({ document, raster, rasters, currentLayerId, onClose, onApply, onRaster }: Props & { raster: RasterUnderlayEntity; rasters: RasterUnderlayEntity[]; onRaster: (id: string) => void }) {
  const [basedOnDocument] = useState(document);
  const asset = useRasterAsset(raster.assetId), originalWidth = raster.assetMetadata?.widthPx ?? asset.bitmap?.width ?? 1, originalHeight = raster.assetMetadata?.heightPx ?? asset.bitmap?.height ?? 1;
  const [step, setStep] = useState(0), [quad, setQuad] = useState<ImageQuad | null>(raster.imageCalibration?.quad ?? null), [aspect, setAspect] = useState<number | null>(null);
  const [a, setA] = useState<PixelPoint | null>(raster.imageCalibration?.reference?.a ?? null), [b, setB] = useState<PixelPoint | null>(raster.imageCalibration?.reference?.b ?? null), [realDistance, setRealDistance] = useState(raster.imageCalibration?.reference?.distanceMeters ?? 10), [picking, setPicking] = useState<'a' | 'b' | null>(null);
  const [position, setPosition] = useState(raster.position), [rotation, setRotation] = useState(raster.rotationDeg), [manualScale, setManualScale] = useState<number | null>(null);
  const [options, setOptions] = useState(DEFAULT_EXTRACTION), [preview, setPreview] = useState<WorkerResult | null>(null), [result, setResult] = useState<WorkerResult['result'] | null>(null), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const [included, setIncluded] = useState<Set<string>>(new Set()), [visible, setVisible] = useState<Set<Candidate['type']>>(new Set(categories)), [selected, setSelected] = useState<string | null>(null), [opacity, setOpacity] = useState(.7), [before, setBefore] = useState(false), [targetLayer, setTargetLayer] = useState(currentLayerId), [runId, setRunId] = useState('');
  const dialog = useRef<HTMLDivElement>(null), drag = useRef<number | null>(null), job = useRef<AbortController | null>(null);
  const source = useMemo(() => { if (!asset.bitmap) return null; try { return { image: prepareImage(asset.bitmap), error: '' }; } catch { return { image: null, error: 'Недостаточно памяти для предпросмотра изображения.' }; } }, [asset.bitmap]);
  const q = useMemo(() => quad ?? fullQuad(originalWidth, originalHeight), [quad, originalWidth, originalHeight]), invalidQuad = quadError(q, originalWidth, originalHeight), size = rectifiedSize(q);
  const calibration = useMemo<ImageCalibration>(() => ({ quad: q, rectifiedWidth: raster.imageCalibration && q === raster.imageCalibration.quad && aspect === null ? raster.imageCalibration.rectifiedWidth : size.width, rectifiedHeight: aspect ? Math.max(2, Math.round(size.width / aspect)) : raster.imageCalibration && q === raster.imageCalibration.quad ? raster.imageCalibration.rectifiedHeight : size.height }), [q, size.width, size.height, aspect, raster.imageCalibration]);
  const invalid = invalidQuad || (calibration.rectifiedWidth>16384||calibration.rectifiedHeight>16384||calibration.rectifiedWidth*calibration.rectifiedHeight>70_000_000?'Исправленное изображение превышает допустимые размеры. Проверьте пропорцию.':null);
  const scaleError = a && b ? (() => { try { metresPerPixel(a, b, realDistance); return ''; } catch (e) { return String((e as Error).message); } })() : '';
  const scale = a && b && !scaleError ? metresPerPixel(a, b, realDistance) : manualScale ?? raster.width / (raster.imageCalibration?.rectifiedWidth ?? originalWidth);
  const placed = { ...raster, position, rotationDeg: rotation, width: calibration.rectifiedWidth * scale, height: calibration.rectifiedHeight * scale };
  const placementError = ![scale,position.x,position.y,rotation,placed.width,placed.height].every(Number.isFinite)||scale<=0||placed.width>1e9||placed.height>1e9 ? 'Введите допустимые положение и положительный масштаб.' : '';
  const candidates = result?.candidates ?? [], accepted = candidates.filter(c => included.has(c.id) && isGeometry(c)).length;
  const cancelJob = useCallback(() => { job.current?.abort(); job.current = null; setBusy(''); }, []);
  useEffect(() => { dialog.current?.querySelector<HTMLElement>('button')?.focus({ preventScroll: true }); return () => { job.current?.abort(); setTimeout(focusEditor, 0); }; }, []);
  useEffect(() => {
    if (!source?.image || invalid || calibration.rectifiedWidth * calibration.rectifiedHeight > 70_000_000) return;
    const controller = new AbortController(), timer = setTimeout(() => {
      void processImage(source.image!, { width: originalWidth, height: originalHeight }, calibration, undefined, controller.signal).then(value => { if (!controller.signal.aborted) setPreview(value); }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Ошибка коррекции.'); });
    }, 80);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [source, originalWidth, originalHeight, calibration, invalid]);
  const changeQuad = (next: ImageQuad) => { cancelJob(); setQuad(next); setResult(null); setSelected(null); setA(null); setB(null); setError(''); };
  const changeOptions = (patch: Partial<ExtractionOptions>) => { cancelJob(); setOptions({ ...options, ...patch }); setResult(null); setSelected(null); };
  const pointFromEvent = (svg: SVGSVGElement, clientX: number, clientY: number, width: number, height: number) => { const inverse = svg.getScreenCTM()?.inverse(); if (!inverse) return { x: 0, y: 0 }; const p = new DOMPoint(clientX, clientY).matrixTransform(inverse); return { x: Math.max(0, Math.min(width, p.x)), y: Math.max(0, Math.min(height, p.y)) }; };
  const extract = async () => {
    if (!source?.image || invalid) return; cancelJob(); const controller = new AbortController(); job.current = controller; setBusy('Подготовка изображения'); setError(''); setResult(null);
    try { const value = await processImage(source.image, { width: originalWidth, height: originalHeight }, calibration, options, controller.signal, setBusy); if (controller.signal.aborted) return;
      setResult(value.result ?? null); setPreview(value); setIncluded(new Set(value.result?.candidates.filter(isGeometry).map(c => c.id))); setSelected(null); setRunId(crypto.randomUUID()); setStep(4);
    } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Обработка не завершена.'); }
    finally { if (job.current === controller) { job.current = null; setBusy(''); } }
  };
  const apply = () => { try { if(document!==basedOnDocument)throw new Error('Документ изменился. Откройте обработку заново.'); const metadata: ImageCalibration = { ...calibration, ...(a && b ? { reference: { a, b, distanceMeters: realDistance } } : {}) }; onApply(vectorizationCommands(document, raster, placed, metadata, candidates, included, targetLayer, runId), document); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось применить.'); } };
  const toggle = (id: string, checked: boolean) => setIncluded(previous => { const next = new Set(previous); if (checked) next.add(id); else next.delete(id); return next; });
  const shownImage = preview?.image ?? source?.image;
  const modalClose = () => { cancelJob(); onClose(); };
  return <div className="modal-backdrop"><div ref={dialog} className="import-dialog image-vectorization-dialog" role="dialog" aria-modal="true" aria-labelledby="image-vectorization-title" data-shortcut-suppressed onKeyDown={event => {
    if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); if (busy) cancelJob(); else modalClose(); }
    if (event.key === 'Tab') { const elements = [...dialog.current!.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]')], first = elements[0], last = elements.at(-1); if (event.shiftKey && window.document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && window.document.activeElement === last) { event.preventDefault(); first?.focus(); } }
  }}>
    <div className="import-heading"><div><h2 id="image-vectorization-title">Векторизация изображения</h2><p>Обработка выполняется локально · изображение не отправляется в AI</p></div><CloseButton label="Закрыть векторизацию" onClick={modalClose} /></div>
    <nav className="image-stages" aria-label="Этапы обработки">{stages.map((label, i) => <button key={label} className={step === i ? 'active' : ''} aria-current={step === i ? 'step' : undefined} disabled={!!busy} onClick={() => setStep(i)}>{i + 1}. {label}</button>)}</nav>
    <div className="image-workflow-body">
      <aside className="image-workflow-controls">
        {step === 0 && <><label>Подложка<select aria-label="Изображение для векторизации" value={raster.id} onChange={e => onRaster(e.target.value)}>{rasters.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><p>{originalWidth} × {originalHeight} px · {raster.assetMetadata?.originalName}</p><p>Исходный файл сохраняется. Перспектива, масштаб и кандидаты до Apply — временный предпросмотр.</p><p>Добавить другой файл: «Файл / данные → Подложка».</p></>}
        {step === 1 && <><h3>Четыре угла чертежа</h3><p>Перетащите пронумерованные углы по часовой стрелке. Ниже показан исправленный вид.</p>{q.map((p, i) => <fieldset key={i}><legend>{i + 1}. {cornerNames[i]}</legend>{(['x', 'y'] as const).map(axis => <label key={axis}>{axis.toUpperCase()}<input aria-label={`${cornerNames[i]} ${axis.toUpperCase()}`} type="number" step="1" value={Math.round(p[axis] * 100) / 100} onChange={e => { const next = q.map(p => ({ ...p })) as ImageQuad; next[i]![axis] = Number(e.target.value); changeQuad(next); }} /></label>)}</fieldset>)}
          <label>Пропорция ширина / высота (если известна)<input aria-label="Пропорция чертежа" type="number" step="any" value={aspect ?? ''} min="0.01" onChange={e => { setAspect(e.target.value && e.target.valueAsNumber > 0 ? e.target.valueAsNumber : null); setResult(null); setSelected(null); setA(null); setB(null); }} placeholder="По длинам сторон" /></label><small>Четыре угла не определяют реальную пропорцию. Для точного масштаба фото укажите известную пропорцию.</small>
          <div className="summary-actions"><button onClick={() => { changeQuad(fullQuad(originalWidth, originalHeight)); setAspect(null); }}>Сбросить перспективу</button><button disabled={!!invalid} onClick={() => setStep(2)}>Применить коррекцию</button></div></>}
        {step === 2 && <><h3>Известное расстояние</h3><div className="summary-actions"><button aria-pressed={picking === 'a'} onClick={() => setPicking('a')}>Выбрать точку A</button><button aria-pressed={picking === 'b'} onClick={() => setPicking('b')}>Выбрать точку B</button></div><p>{picking ? `Укажите точку ${picking.toUpperCase()} на исправленном изображении.` : 'Две точки на изображении → реальная длина в метрах.'}</p><label>Реальная длина, м<input aria-label="Реальная длина, м" type="number" step="any" min="0.000001" value={realDistance} onChange={e => setRealDistance(Number(e.target.value))} /></label><dl className="property-facts"><dt>На изображении</dt><dd>{a && b ? `${distancePx(a, b).toFixed(2)} px` : 'Выберите A и B'}</dd><dt>Масштаб</dt><dd data-testid="image-scale">{scale > 0 ? `${scale.toFixed(6)} м/px` : '—'}</dd><dt>Размер</dt><dd>{placed.width.toFixed(3)} × {placed.height.toFixed(3)} м</dd></dl>
          <button onClick={() => { setA(null); setB(null); setPicking(null); }}>Сбросить точки</button><label>Масштаб вручную, м/px<input aria-label="Масштаб вручную, м/px" type="number" step="any" value={manualScale ?? raster.width / (raster.imageCalibration?.rectifiedWidth ?? originalWidth)} disabled={!!a && !!b} onChange={e => setManualScale(Number(e.target.value))} /></label>
          <h3>Положение в MODEL</h3>{(['x', 'y'] as const).map(axis => <label key={axis}>MODEL {axis.toUpperCase()}<input aria-label={`Изображение MODEL ${axis.toUpperCase()}`} type="number" step="any" value={position[axis]} onChange={e => setPosition({ ...position, [axis]: Number(e.target.value) })} /></label>)}<label>Поворот, °<input aria-label="Поворот изображения" type="number" step="any" value={rotation} onChange={e => setRotation(Number(e.target.value))} /></label><small>Положение подложки не изменяет SURVEY-привязку документа.</small></>}
        {step === 3 && <><h3>Извлечение геометрии</h3><label>Детализация<select aria-label="Детализация изображения" value={options.detail} onChange={e => changeOptions({ detail: e.target.value as ExtractionOptions['detail'] })}><option value="low">Низкая</option><option value="medium">Средняя</option><option value="high">Высокая</option></select></label><label>Удаление шума<select aria-label="Удаление шума" value={options.noise} onChange={e => changeOptions({ noise: e.target.value as ExtractionOptions['noise'] })}><option value="low">Низкое</option><option value="medium">Среднее</option><option value="high">Высокое</option></select></label><label><input type="checkbox" checked={options.join} onChange={e => changeOptions({ join: e.target.checked })} />Соединять близкие концы</label><p>Линии, связные цепочки, замкнутые контуры и уверенные окружности. Области текста — без OCR.</p><button className="primary-button" disabled={!!busy || !!invalid || !source?.image} onClick={() => void extract()}>Извлечь геометрию</button>{busy && <button onClick={cancelJob}>Отменить обработку</button>}</>}
        {step === 4 && <><h3>Проверка кандидатов</h3><div className="summary-actions"><button disabled={!result} onClick={() => setIncluded(new Set(candidates.filter(isGeometry).map(c => c.id)))}>Выбрать все</button><button onClick={() => setIncluded(new Set())}>Очистить выбор</button></div>{categories.filter(type => type !== 'symbol' || candidates.some(c => c.type === type)).map(type => <div className="image-category" key={type}><strong>{labels[type]}: <span data-testid={`image-count-${type}`}>{candidates.filter(c => c.type === type).length}</span></strong><label><input aria-label={`Показать: ${labels[type]}`} type="checkbox" checked={visible.has(type)} onChange={e => setVisible(previous => { const next = new Set(previous); if (e.target.checked) next.add(type); else next.delete(type); return next; })} />Видны</label>{type === 'text' || type === 'symbol' ? <small>Только область · без распознавания</small> : <label><input aria-label={`Принять: ${labels[type]}`} type="checkbox" checked={candidates.filter(c => c.type === type).length > 0 && candidates.filter(c => c.type === type).every(c => included.has(c.id))} onChange={e => setIncluded(previous => { const next = new Set(previous); candidates.filter(c => c.type === type).forEach(c => e.target.checked ? next.add(c.id) : next.delete(c.id)); return next; })} />Принять</label>}</div>)}
          <label>Непрозрачность изображения<input aria-label="Изображение в предпросмотре, %" type="range" min="0" max="100" value={opacity * 100} onChange={e => setOpacity(Number(e.target.value) / 100)} /></label><label><input aria-label="Только изображение" type="checkbox" checked={before} onChange={e => setBefore(e.target.checked)} />Только изображение · до / после</label>
          {selected && <div className="image-selected"><strong>{labels[candidates.find(c => c.id === selected)!.type]} · {selected}</strong><button disabled={!isGeometry(candidates.find(c => c.id === selected)!)} onClick={() => toggle(selected, !included.has(selected))}>{included.has(selected) ? 'Исключить кандидат' : 'Вернуть кандидат'}</button></div>}
          <label>Слой результата<select aria-label="Слой векторизации" value={targetLayer} onChange={e => setTargetLayer(e.target.value)}><option value="__new">Создать: Векторизация изображения</option>{document.layers.map(l => <option key={l.id} value={l.id} disabled={l.locked || !l.visible}>{l.name}{l.locked ? ' · заблокирован' : !l.visible ? ' · скрыт' : ''}</option>)}</select></label><small>Текстовые области и символы не создают сущности. Результат не зависит от дальнейшего перемещения изображения.</small>
        </>}
      </aside>
      <div className={`image-preview-area${step === 1 ? ' perspective' : ''}`}>
        {source?.image && step === 1 && <figure><figcaption>Исходное изображение · углы 1 → 2 → 3 → 4</figcaption><div className="image-preview" style={{ aspectRatio: originalWidth / originalHeight }}><PixelCanvas image={source.image} /><svg viewBox={`0 0 ${originalWidth} ${originalHeight}`} aria-label="Углы перспективы" onPointerMove={e => { if (drag.current === null) return; const next = q.map(p => ({ ...p })) as ImageQuad; next[drag.current] = pointFromEvent(e.currentTarget, e.clientX, e.clientY, originalWidth, originalHeight); changeQuad(next); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><polygon className="image-quad" points={q.map(p => `${p.x},${p.y}`).join(' ')} vectorEffect="non-scaling-stroke" />{q.map((p, i) => <g key={i}><circle data-testid={`perspective-corner-${i}`} tabIndex={0} role="slider" aria-label={cornerNames[i]} aria-valuetext={`${p.x.toFixed(1)}, ${p.y.toFixed(1)}`} cx={p.x} cy={p.y} r={Math.max(originalWidth, originalHeight) / 55} onPointerDown={e => { e.preventDefault(); drag.current = i; e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId); }} onKeyDown={e => { const movement: Record<string, PixelPoint> = { ArrowLeft: { x: -1, y: 0 }, ArrowRight: { x: 1, y: 0 }, ArrowUp: { x: 0, y: -1 }, ArrowDown: { x: 0, y: 1 } }; const d = movement[e.key]; if (!d) return; e.preventDefault(); const next = q.map(p => ({ ...p })) as ImageQuad; next[i] = { x: Math.max(0, Math.min(originalWidth, p.x + d.x)), y: Math.max(0, Math.min(originalHeight, p.y + d.y)) }; changeQuad(next); }} /><text x={p.x} y={p.y} fontSize={Math.max(originalWidth, originalHeight) / 45} textAnchor="middle" dominantBaseline="middle" pointerEvents="none">{i + 1}</text></g>)}</svg></div></figure>}
        {shownImage && <figure><figcaption>{step === 1 ? 'Исправленный предпросмотр' : 'Изображение и кандидаты'}</figcaption><div className="image-preview" data-testid="image-review-preview" style={{ aspectRatio: calibration.rectifiedWidth / calibration.rectifiedHeight }}><PixelCanvas image={shownImage} opacity={step === 4 ? opacity : 1} /><svg viewBox={`0 0 ${calibration.rectifiedWidth} ${calibration.rectifiedHeight}`} aria-label="Предпросмотр векторизации" onPointerDown={e => { if (!picking || step !== 2) return; const p = pointFromEvent(e.currentTarget, e.clientX, e.clientY, calibration.rectifiedWidth, calibration.rectifiedHeight); if (picking === 'a') { setA(p); setPicking('b'); } else { setB(p); setPicking(null); } }}>
          {step === 2 && a && <circle className="image-reference" cx={a.x} cy={a.y} r={calibration.rectifiedWidth / 80} />} {step === 2 && b && <circle className="image-reference" cx={b.x} cy={b.y} r={calibration.rectifiedWidth / 80} />} {step===2&&a&&<text x={a.x+calibration.rectifiedWidth/55} y={a.y} fontSize={calibration.rectifiedWidth/35}>A</text>}{step===2&&b&&<text x={b.x+calibration.rectifiedWidth/55} y={b.y} fontSize={calibration.rectifiedWidth/35}>B</text>} {step === 2 && a && b && <line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="image-reference" vectorEffect="non-scaling-stroke" />}
          {step === 4 && !before && candidates.filter(c => visible.has(c.type)).map(c => <g key={c.id} tabIndex={0} role="button" aria-label={`${labels[c.type]} ${c.id}`} aria-pressed={selected === c.id} onPointerDown={() => setSelected(c.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setSelected(c.id); } if (e.key === 'Delete') { e.preventDefault(); toggle(c.id, false); } }}><title>{labels[c.type]} · {included.has(c.id) ? 'принят' : 'исключён / только просмотр'}</title><CandidateShape candidate={c} selected={selected === c.id} excluded={!included.has(c.id)} /></g>)}
        </svg></div></figure>}
        {!source?.image && <p role="status">{source?.error || (asset.loaded ? 'Подложка недоступна. Перепривяжите изображение.' : 'Загрузка изображения…')}</p>}
      </div>
    </div>
    {(error || (document!==basedOnDocument?'Документ изменился. Откройте обработку заново.':'') || invalid || scaleError || placementError || !(scale > 0) || raster.locked || document.layers.find(l => l.id === raster.layerId)?.locked) && <p className="import-error" role="alert">{error || (document!==basedOnDocument?'Документ изменился. Откройте обработку заново.':'') || invalid || scaleError || placementError || (!(scale > 0) ? 'Масштаб должен быть положительным.' : 'Подложка или её слой заблокированы.')}</p>}
    {busy && <p role="status" data-testid="image-progress">{busy}…</p>}
    <div className="import-footer"><span>{step === 4 ? `Будет создано: ${accepted} · один шаг Undo` : 'Настройки не меняют документ до Apply'}</span><button onClick={modalClose}>Отмена</button>{step > 0 && <button disabled={!!busy} onClick={() => setStep(step - 1)}>Назад</button>}{step < 4 && <button className="primary-button" disabled={!!busy || !!invalid || !!scaleError || !!placementError || !(scale > 0) || !source?.image} onClick={() => setStep(step + 1)}>Далее</button>}{step === 4 && <button className="primary-button" disabled={document!==basedOnDocument || !accepted || !!busy || !!invalid || !!scaleError || !!placementError || !(scale > 0) || raster.locked || !!document.layers.find(l => l.id === raster.layerId)?.locked} onClick={apply}>Применить геометрию ({accepted})</button>}</div>
  </div></div>;
}
