import '../semantics/learning.css';
import { useEffect, useMemo, useState } from 'react';
import type { GeoDocument } from '../domain/model';
import { Dialog } from './Dialog';
import { conceptsFor, conceptsNamed } from '../semantics/concepts';
import { describeCondition } from '../semantics/features';
import { learnedMatches, proposeRule, rememberedKnowledge, removeConcept, ruleMatches, type ProposedRule } from '../semantics/learning';
import { emptyKnowledge, featureIdentity, type FeatureCondition, type MatchTier, type SemanticConcept, type SemanticKnowledge, type SemanticRule } from '../semantics/model';
interface Props {document:GeoDocument;selectionIds:readonly string[];mode:'teach'|'manage';onClose:()=>void;onApply:(knowledge:SemanticKnowledge,expectedDocument:GeoDocument)=>void;onPreview:(ids:readonly string[])=>void;onSelect:(ids:readonly string[])=>void;onFit:(ids:readonly string[])=>void}
const tiers:MatchTier[]=['EXACT','STRONG','WEAK'];
export function SemanticLearningDialog({document,selectionIds,mode,onClose,onApply,onPreview,onSelect,onFit}:Props) {
  const [basedOnDocument]=useState(document),[name,setName]=useState('Трубы'),[aliases,setAliases]=useState(''),[parent,setParent]=useState(''),[proposal,setProposal]=useState<ProposedRule|null>(null),[concept,setConcept]=useState<SemanticConcept|null>(null),[rule,setRule]=useState<SemanticRule|null>(null),[factCatalog,setFactCatalog]=useState<FeatureCondition[]>([]),[error,setError]=useState(''),[excluded,setExcluded]=useState<Set<string>>(new Set()),[enabled,setEnabled]=useState<Set<MatchTier>>(new Set(['EXACT','STRONG'])),[activeTier,setActiveTier]=useState<MatchTier|null>(null),[inspecting,setInspecting]=useState(false);
  const all=useMemo(()=>conceptsFor(document),[document]),knowledge=document.semantics??emptyKnowledge();
  const matches=useMemo(()=>rule?ruleMatches(basedOnDocument,{...rule,exclusions:[]}):[],[basedOnDocument,rule]),ids=useMemo(()=>matches.filter(m=>enabled.has(m.tier)&&!excluded.has(m.entityId)).map(m=>m.entityId),[matches,enabled,excluded]);
  useEffect(()=>()=>onPreview([]),[onPreview]);
  useEffect(()=>{onPreview(document===basedOnDocument?ids:[]);},[ids,onPreview,document,basedOnDocument]);
  const apply=(next:SemanticKnowledge)=>{try{if(document!==basedOnDocument)throw new Error('Документ изменился. Откройте обучение заново.');onApply(next,basedOnDocument);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить.');}};
  const generate=()=>{try{if(!name.trim())throw new Error('Введите название категории.');const found=conceptsNamed(document,name);if(found.length>1)throw new Error('Неоднозначное название категории.');const c:SemanticConcept=found[0]??{id:`concept-${crypto.randomUUID()}`,name:name.trim(),aliases:[]};const draft={...c,aliases:aliases.trim()?aliases.split(',').map(a=>a.trim()).filter(Boolean):c.aliases,...(parent?{parentConceptId:parent}:{})};const p=proposeRule(document,selectionIds,c.id,`rule-${crypto.randomUUID()}`);setName(draft.name);setAliases(draft.aliases.join(', '));setParent(draft.parentConceptId??'');setConcept(draft);setFactCatalog(p.shared.map(s=>s.fact));setProposal(p);setRule(p.rule);setExcluded(new Set(knowledge.annotations.filter(a=>a.conceptId===c.id&&a.polarity==='negative').map(a=>a.entityId)));setEnabled(new Set(['EXACT','STRONG']));setError('');setInspecting(true);}catch(e){setError(e instanceof Error?e.message:'Выберите примеры.');}};
  const edit=(c:SemanticConcept,r?:SemanticRule)=>{setConcept(c);setName(c.name);setAliases(c.aliases.join(', '));setParent(c.parentConceptId??'');setRule(r??null);setProposal(null);setFactCatalog(r?[...r.conditions,...r.supporting]:[]);setExcluded(new Set(r?.exclusions??[]));setEnabled(new Set(r?.enabledTiers??['EXACT','STRONG']));setInspecting(true);setError('');};
  const updatedConcept=()=>{if(!concept)throw new Error('Выберите категорию');const {parentConceptId:_old,...rest}=concept;void _old;return {...rest,name:name.trim(),aliases:aliases.split(',').map(a=>a.trim()).filter(Boolean),...(parent?{parentConceptId:parent}:{})};};
  const save=()=>{try{const c=updatedConcept();if(!c.name)throw new Error('Введите название категории');apply(rule?rememberedKnowledge(basedOnDocument,c,rule,excluded,enabled):{...knowledge,concepts:[...knowledge.concepts.filter(x=>x.id!==c.id),c]});}catch(e){setError(e instanceof Error?e.message:'Проверьте категорию');}};
  const changeFact=(fact:FeatureCondition,role:string)=>{if(!rule)return;const key=featureIdentity(fact),conditions=rule.conditions.filter(f=>featureIdentity(f)!==key),supporting=rule.supporting.filter(f=>featureIdentity(f)!==key);if(role==='required')conditions.push(fact);if(role==='supporting')supporting.push(fact);setRule({...rule,conditions,supporting});};
  const facts=factCatalog;
  return <Dialog title={mode==='manage'&&!inspecting?'Смысл / категории':'Научить GeoService'} subtitle="Только этот документ · локально · без отправки в AI" size="lg" className="semantic-learning-dialog" closeLabel="Закрыть обучение" onClose={onClose} footer={<><span>Preview не создаёт Undo · Запомнить — один шаг Undo</span><button onClick={onClose}>Отмена</button></>}>
    {document!==basedOnDocument&&<p role="alert">Документ изменился. Закройте и откройте обучение заново.</p>}{error&&<p role="alert">{error}</p>}
    {mode==='manage'&&!inspecting?<div className="semantic-knowledge">
      <p>Явные метки сохраняются при отключении правила. Удаление категории убирает её метки и правила; геометрия остаётся.</p>
      {all.filter(c=>knowledge.concepts.some(x=>x.id===c.id)||knowledge.rules.some(r=>r.conceptId===c.id)||knowledge.annotations.some(a=>a.conceptId===c.id)).map(c=><section key={c.id}><h3>{c.name}</h3><small>Этот документ · {new Set(learnedMatches(document,c.id).filter(m=>m.tier!=='WEAK').map(m=>m.entityId)).size} объектов</small><button onClick={()=>edit(c)}>Название / синонимы</button><button onClick={()=>{try{apply(removeConcept(document,c.id));}catch(e){setError((e as Error).message);}}}>Удалить категорию {c.name}</button>{knowledge.rules.filter(r=>r.conceptId===c.id).map(r=><div className="semantic-rule" key={r.id}><p>{r.conditions.map(f=>describeCondition(f,document)).join(' + ')}</p><small>{r.enabled?'Включено':'Отключено'} · {r.scope==='document'?'Этот документ':''} · {ruleMatches(document,r).filter(m=>r.enabledTiers.includes(m.tier)).length} совпадений</small><button onClick={()=>edit(c,r)}>Проверить / изменить правило</button><button onClick={()=>apply({...knowledge,rules:knowledge.rules.map(x=>x.id===r.id?{...x,enabled:!x.enabled}:x)})}>{r.enabled?'Отключить правило':'Включить правило'}</button><button onClick={()=>apply({...knowledge,rules:knowledge.rules.filter(x=>x.id!==r.id)})}>Удалить правило</button></div>)}</section>)}
      {!knowledge.rules.length&&!knowledge.annotations.length&&<p>Знаний пока нет. Выберите примеры и нажмите «Научить GeoService».</p>}
    </div>:<div className="semantic-teaching">
      <label>Категория<input aria-label="Название смысловой категории" value={name} maxLength={128} onChange={e=>setName(e.target.value)} list="semantic-concepts"/></label><datalist id="semantic-concepts">{all.map(c=><option key={c.id} value={c.name}/>)}</datalist>
      <label>Синонимы через запятую<input aria-label="Синонимы категории" value={aliases} maxLength={4096} onChange={e=>setAliases(e.target.value)}/></label>
      <label>Родитель<select aria-label="Родитель категории" value={parent} onChange={e=>setParent(e.target.value)}><option value="">Без родителя</option>{all.filter(c=>c.id!==concept?.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      {!inspecting&&<><p>Примеры: {selectionIds.length} · объекты MODEL верхнего уровня</p><button className="primary-button" disabled={!selectionIds.length} onClick={generate}>Предложить правило</button></>}
      {inspecting&&<>{proposal?.warning&&<p role="status">{proposal.warning}</p>}{rule&&<>
        <h3>Предлагаемая логика</h3><p>Обязательные: {rule.conditions.map(f=>describeCondition(f,document)).join(' + ')||'выберите хотя бы один признак'}</p><p>Поддержка: {rule.supporting.map(f=>describeCondition(f,document)).join(' · ')||'нет'}</p>
        <details><summary>Уточнить признаки</summary>{facts.slice(0,32).map(f=><label className="semantic-fact" key={featureIdentity(f)}><span>{describeCondition(f,document)}{proposal&&<small>{proposal.shared.find(s=>featureIdentity(s.fact)===featureIdentity(f))!.documentCount} / {document.entities.length} объектов · {proposal.shared.find(s=>featureIdentity(s.fact)===featureIdentity(f))!.useful?'отличает примеры':'широкий признак'}</small>}</span><select aria-label={`Роль признака ${describeCondition(f,document)}`} value={rule.conditions.some(x=>featureIdentity(x)===featureIdentity(f))?'required':rule.supporting.some(x=>featureIdentity(x)===featureIdentity(f))?'supporting':'off'} onChange={e=>changeFact(f,e.target.value)}><option value="required">Обязательно</option><option value="supporting">Поддержка</option><option value="off">Не учитывать</option></select></label>)}</details>
        <h3>Похожие объекты</h3>{tiers.map(tier=>{const group=matches.filter(m=>m.tier===tier);return <div className="semantic-match-group" key={tier}><label><input aria-label={`Принять ${tier}`} type="checkbox" checked={enabled.has(tier)} onChange={e=>setEnabled(previous=>{const next=new Set(previous);if(e.target.checked)next.add(tier);else next.delete(tier);return next;})}/><strong>{tier} · <span data-testid={`semantic-count-${tier}`}>{group.length}</span></strong></label><button onClick={()=>{setActiveTier(activeTier===tier?null:tier);onPreview(group.filter(m=>!excluded.has(m.entityId)).map(m=>m.entityId));}}>Показать {tier}</button><button disabled={!group.length} onClick={()=>onSelect(group.filter(m=>!excluded.has(m.entityId)).map(m=>m.entityId))}>Выбрать {tier}</button><button disabled={!group.length} onClick={()=>onFit(group.map(m=>m.entityId))}>Fit {tier}</button>{activeTier===tier&&<div>{group.slice(0,100).map(m=><div className="semantic-match" key={m.entityId}><label><input aria-label={`Включить объект ${m.entityId}`} type="checkbox" checked={!excluded.has(m.entityId)} onChange={e=>setExcluded(previous=>{const next=new Set(previous);if(e.target.checked)next.delete(m.entityId);else next.add(m.entityId);return next;})}/>{document.entities.find(e=>e.id===m.entityId)?.name??m.entityId}</label><button aria-label={`Показать объект ${m.entityId}`} onClick={()=>onPreview([m.entityId])}>Показать</button><button aria-label={`Fit объекта ${m.entityId}`} onClick={()=>onFit([m.entityId])}>Fit</button><details><summary>Почему найдено</summary>{m.reasons.map((reason,i)=><p key={i}>{reason}</p>)}</details><button onClick={()=>setExcluded(previous=>new Set([...previous,m.entityId]))}>Это НЕ {name}</button></div>)}{group.length>100&&<small>Первые 100; переключатель группы относится ко всем {group.length} объектам.</small>}</div>}</div>;})}
        <p>Исключения: {excluded.size} · Слабые совпадения выключены по умолчанию. Явно включённые слабые объекты получат подтверждённую метку.</p>{excluded.size>0&&<button onClick={()=>setExcluded(new Set())}>Сбросить исключения</button>}
      </>}
      <button className="primary-button" disabled={document!==basedOnDocument||!!rule&&!rule.conditions.length} onClick={save}>Запомнить</button></>}
    </div>}
  </Dialog>;
}
