import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Dialog } from './Dialog';
import { createAiIntentProvider, browserAiTransport } from '../ai/provider';
import { adoptServerAiDefaults, getApiKey, getPreferenceStorageError, preferencesSchema, setApiKey, updatePreferences, usePreferences, type Preferences } from '../preferences/store';
import './settings.css';
import type { AiState } from '../ai/workflow';
import { readAiDiagnostic } from '../ai/diagnosticStore';
const AiDiagnostics=import.meta.env.DEV?lazy(()=>import('./AiDiagnostics')):null;
export type SettingsSection='general'|'editor'|'ai'|'privacy'|'diagnostics';
const sections:readonly [SettingsSection,string][]=[['general','Общие'],['editor','Редактор'],['ai','AI'],['privacy','Приватность'],['diagnostics','Диагностика']];
export function SettingsCenter({section='general',onClose,ai}:{section?:SettingsSection;onClose:()=>void;ai?:AiState}){
 const prefs=usePreferences(),[tab,setTab]=useState(section),[key,setKey]=useState(getApiKey),[serverKey,setServerKey]=useState(false),[status,setStatus]=useState(''),[testing,setTesting]=useState(false),[draft,setDraft]=useState(prefs.ai);
 const connection=useRef<AbortController|null>(null);
 useEffect(()=>{if(browserAiTransport)return;const controller=new AbortController();void fetch('/api/ai/settings',{signal:controller.signal}).then(async r=>{if(!r.ok)return;const data=await r.json() as {primaryModel?:string;fallbackModel?:string;provider?:string;hasApiKey?:boolean};if(controller.signal.aborted)return;adoptServerAiDefaults(data);setServerKey(!!data.hasApiKey);}).catch(()=>{});return()=>{controller.abort();connection.current?.abort();};},[]);
 useEffect(()=>setDraft(prefs.ai),[prefs.ai]);
 const invalidateConnection=()=>{connection.current?.abort();connection.current=null;setTesting(false);setStatus('');};
 const aiUpdate=(patch:Partial<Preferences['ai']>)=>{invalidateConnection();const next={...draft,...patch};setDraft(next);if(preferencesSchema.safeParse({...prefs,ai:next}).success)updatePreferences({ai:next,aiCustomized:true});else setStatus('Проверьте значения AI: имя модели без пробелов, timeout 1–120 секунд.');};
 const check=async()=>{setTesting(true);setStatus('Проверка…');const controller=new AbortController();connection.current=controller;const timer=setTimeout(()=>controller.abort(),prefs.ai.timeoutMs);try{await createAiIntentProvider().parseIntent({text:'Нарисуй прямоугольник 1x1 м',signal:controller.signal});if(!controller.signal.aborted)setStatus('Соединение проверено.');}catch{if(connection.current===controller)setStatus('Не удалось подключиться. Проверьте ключ, модель и соединение с провайдером.');}finally{clearTimeout(timer);if(connection.current===controller){connection.current=null;setTesting(false);}}};
 return <Dialog title="Настройки" subtitle="Настройки этого браузера · сохраняются автоматически, отдельно от чертежа" size="lg" onClose={onClose} footer={<button onClick={onClose}>Готово</button>}><div className="settings-center"><nav role="tablist" aria-label="Разделы настроек">{sections.map(([id,label])=><button role="tab" id={`settings-tab-${id}`} aria-selected={tab===id} aria-controls={`settings-${id}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav><section role="tabpanel" id={`settings-${tab}`} aria-labelledby={`settings-tab-${tab}`}>
 {tab==='general'&&<><h3>Общие</h3><p>Настройки действуют в этом браузере. Чертежи и их автосохранение хранятся отдельно.</p><p>Параметры редактора и AI сохраняются автоматически. Их изменение не меняет чертёж.</p></>}
 {tab==='editor'&&<><h3>Редактор</h3><label><input aria-label="Сетка по умолчанию" type="checkbox" checked={prefs.gridVisible} onChange={e=>updatePreferences({gridVisible:e.target.checked})}/>Сетка</label><label><input aria-label="SNAP по умолчанию" type="checkbox" checked={prefs.snapEnabled} onChange={e=>updatePreferences({snapEnabled:e.target.checked})}/>SNAP</label><label><input aria-label="Привязка к сетке по умолчанию" type="checkbox" checked={prefs.snapGrid} onChange={e=>updatePreferences({snapGrid:e.target.checked})}/>Привязка к сетке</label><label>Шаг сетки, м<input aria-label="Шаг сетки по умолчанию" type="number" min="0.000001" max="1000000" step="any" value={prefs.gridStep} onChange={e=>{if(e.target.valueAsNumber>0&&e.target.valueAsNumber<=1e6)updatePreferences({gridStep:e.target.valueAsNumber});}}/></label><label><input aria-label="ORTHO по умолчанию" type="checkbox" checked={prefs.ortho} onChange={e=>updatePreferences({ortho:e.target.checked})}/>ORTHO</label><p>Текущие настройки вида применяются сразу. Операции рисования не сохраняются в preferences.</p></>}
 {tab==='ai'&&<><h3>AI</h3><label><input aria-label="AI включён" type="checkbox" checked={draft.enabled} onChange={e=>aiUpdate({enabled:e.target.checked})}/>AI включён</label><label>Provider<select aria-label="AI provider" value={draft.provider} onChange={e=>aiUpdate({provider:e.target.value as Preferences['ai']['provider']})}><option value="openrouter">OpenRouter</option>{!browserAiTransport&&<><option value="openai">OpenAI</option><option value="mock">Демонстрационный mock</option></>}</select></label><label>Основная модель<input aria-label="Основная AI модель" value={draft.primaryModel} onChange={e=>aiUpdate({primaryModel:e.target.value})} spellCheck={false}/></label><label>Резервная модель<input aria-label="Резервная AI модель" value={draft.fallbackModel} onChange={e=>aiUpdate({fallbackModel:e.target.value})} spellCheck={false}/></label><label>Timeout запроса, секунды<input aria-label="AI timeout" type="number" min="1" max="120" value={draft.timeoutMs/1000} onChange={e=>aiUpdate({timeoutMs:e.target.valueAsNumber*1000})}/></label><label>Повтор при сетевой ошибке<select aria-label="Повторы AI" value={draft.retryCount} onChange={e=>aiUpdate({retryCount:Number(e.target.value)})}><option value="0">Без дополнительного повтора</option><option value="1">Один повтор</option></select></label><small>{browserAiTransport?"Статический сайт обращается к OpenRouter напрямую с вашим ключом. Отправляется только запрос и статическая схема; создание геометрии выполняется локально.":"Timeout ограничивает ожидание в браузере. Локальный сервер дополнительно ограничивает upstream запрос."}</small><label>API key<input aria-label="AI API key" type="password" autoComplete="off" spellCheck={false} value={key} placeholder={browserAiTransport?"Ваш OpenRouter API key":"Пусто — ключ локального сервера"} onChange={e=>{invalidateConnection();setKey(e.target.value);try{setApiKey(e.target.value);setStatus('');}catch{setStatus('Ключ должен содержать только печатные символы без пробелов.');}}}/></label><label><input aria-label="Запомнить ключ на этом устройстве" type="checkbox" checked={prefs.rememberApiKey} onChange={e=>{invalidateConnection();try{setApiKey(key,e.target.checked);}catch{setStatus('Ключ должен содержать только печатные символы без пробелов.');}}}/>Запомнить на этом устройстве</label><p>{prefs.rememberApiKey?'Ключ будет сохранён в этом браузере. Не используйте эту опцию на общем компьютере. Это не защищённое хранилище ОС.':'Ключ хранится только в памяти вкладки до перезагрузки.'}</p><p>{key?'Используется введённый ключ':serverKey?'Настроено локальным сервером':'Ключ не задан в браузере'}</p><button disabled={testing||(browserAiTransport&&!key)||!prefs.ai.enabled||!preferencesSchema.safeParse({...prefs,ai:draft}).success||key.length>512||!/^[\x21-\x7e]*$/.test(key)} onClick={()=>void check()}>Проверить подключение</button><p role="status">{status}</p></>}
 {tab==='privacy'&&<><h3>Приватность</h3><p>AI получает только текст вашего запроса и статические инструкции/schema. PDF, изображения, OCR, геометрия, слои, блоки, entity IDs и preferences автоматически не отправляются.</p><p>Удалённый Vision/OCR: отключён. Передача semantic metadata: отключена. Анализ изображений и PDF выполняется локально.</p></>}
 {tab==='diagnostics'&&<><h3>Диагностика</h3><label>DXF renderer<select aria-label="DXF renderer" value={prefs.renderer} onChange={e=>updatePreferences({renderer:e.target.value as 'svg'|'canvas'})}><option value="canvas">Canvas / SVG hybrid</option><option value="svg">SVG</option></select></label><label><input aria-label="Диагностика редактора" type="checkbox" checked={prefs.diagnostics} onChange={e=>updatePreferences({diagnostics:e.target.checked})}/>Показывать локальную диагностику анализа / AI</label><p>Метрики реконструкции, исходная трасса и AI diagnostics доступны только при включении. Ключи не входят в diagnostics или JSON чертежа.</p><p>OCR: ограниченные crops, кеш до четырёх запусков; PDF: одна выбранная страница. Кеш распознавания временный.</p>{prefs.diagnostics&&AiDiagnostics&&ai&&<Suspense fallback={<p>Загрузка диагностики…</p>}><AiDiagnostics record={readAiDiagnostic()} ai={ai}/></Suspense>}</>}
 {getPreferenceStorageError()&&<p role="alert">{getPreferenceStorageError()}</p>}
 </section></div></Dialog>;
}
