import { useEffect, useMemo, useRef, useState } from 'react';
import type { DocumentCommand } from '../domain/commands';
import type { GeoDocument } from '../domain/model';
import { bounds } from '../geometry';
import { conceptsFor } from '../semantics/concepts';
import { portKey } from '../connectors/model';
import { reconstructTopology } from '../topology/client';
import { resolvedRoute, topologyCommands } from '../topology/apply';
import type { GraphDecisions, Point, RouteReview, Scope, TopologyGraph } from '../topology/types';
import type { TopologyPreview } from '../renderer/TopologyOverlay';
import { Dialog } from './Dialog';
import '../topology/topology.css';
export function TopologyDialog({document,selectionIds,layerId,onClose,onApply,onPreview,onFit}:{document:GeoDocument;selectionIds:readonly string[];layerId:string;onClose:()=>void;onApply:(commands:DocumentCommand[],expected:GeoDocument)=>void;onPreview:(preview:TopologyPreview|null)=>void;onFit:(points:Point[])=>void}){
 const [basedOn]=useState(document),[scopeKind,setScopeKind]=useState<Scope['kind']>('selection'),[layer,setLayer]=useState(layerId),[concept,setConcept]=useState('pipe'),[run,setRun]=useState(''),[area,setArea]=useState({minX:document.viewport.center.x-10,minY:document.viewport.center.y-10,maxX:document.viewport.center.x+10,maxY:document.viewport.center.y+10}),[graph,setGraph]=useState<TopologyGraph|null>(null),[decisions,setDecisions]=useState<GraphDecisions>({}),[reviews,setReviews]=useState<Record<string,RouteReview>>({}),[picked,setPicked]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const job=useRef<AbortController|null>(null);useEffect(()=>()=>job.current?.abort(),[]);useEffect(()=>()=>onPreview(null),[onPreview]);
 const runs=[...new Set(document.entities.flatMap(e=>e.imageSource?[e.imageSource.vectorizationRunId]:[]))];
 const scope:Scope=scopeKind==='selection'?{kind:'selection',ids:[...selectionIds]}:scopeKind==='layer'?{kind:'layer',layerId:layer}:scopeKind==='concept'?{kind:'concept',conceptId:concept}:scopeKind==='image-group'?{kind:'image-group',runId:run||runs[0]||''}:{kind:'area',bounds:area};
 const invalidate=()=>{setGraph(null);setReviews({});setDecisions({});setPicked(null);onPreview(null);};
 const analyze=async(next:GraphDecisions={})=>{job.current?.abort();const controller=new AbortController();job.current=controller;setBusy(true);setError('');setGraph(null);setPicked(null);setReviews({});onPreview(null);try{if(scope.kind==='area'&&(!Object.values(area).every(Number.isFinite)||area.minX>=area.maxX||area.minY>=area.maxY))throw new Error('Задайте корректную прямоугольную область MODEL.');const result=await reconstructTopology(basedOn,scope,next,controller.signal);if(!controller.signal.aborted){setGraph(result);setDecisions(next);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Не удалось восстановить связи.');}finally{if(job.current===controller){job.current=null;setBusy(false);}}};
 useEffect(()=>{const route=graph?.routes.find(r=>r.id===picked);if(route){const review=reviews[route.id];onPreview({points:route.points,ports:[...route.startOptions,...route.endOptions],classification:review?.status==='rejected'?'REJECTED':route.classification,confirmed:review?.status==='confirmed'});}},[graph,picked,reviews,onPreview]);
 const ready=useMemo(()=>graph?.routes.filter(r=>resolvedRoute(basedOn,graph,r,reviews[r.id]??{status:'unresolved'}).entity)??[],[basedOn,graph,reviews]);
 const patch=(id:string,changes:Partial<RouteReview>)=>setReviews(previous=>({...previous,[id]:{status:'unresolved',...previous[id],...changes}}));
 const show=(id:string,preview:TopologyPreview)=>{setPicked(id);onPreview(preview);};
 const cancel=()=>{job.current?.abort();onClose();};
 const apply=()=>{try{if(!graph||document!==basedOn)throw new Error('Документ изменился. Откройте восстановление заново.');const commands=topologyCommands(basedOn,graph,reviews);onApply(commands,basedOn);}catch(e){setError(e instanceof Error?e.message:'Изменения не применены.');}};
 return <Dialog title="Восстановить связи" subtitle="Локальный анализ 2D MODEL · геометрическая связь не определяет инженерный смысл" size="xl" onClose={cancel} footer={<><span>До Apply документ не изменяется.</span><button onClick={cancel}>Отмена</button><button className="primary-button" disabled={busy||!ready.length} onClick={apply}>Применить связи ({ready.length})</button></>}>
 <fieldset disabled={busy}><legend>Область анализа</legend><div className="topology-scope"><label>Источник геометрии<select aria-label="Область восстановления" value={scopeKind} onChange={e=>{setScopeKind(e.target.value as Scope['kind']);invalidate();}}><option value="selection">Выбранные Line / Polyline ({selectionIds.length})</option><option value="layer">Указанный слой</option><option value="concept">Подтверждённая смысловая категория</option><option value="area">Прямоугольная область MODEL</option><option value="image-group">Группа импорта изображения / PDF</option></select></label>{scopeKind==='layer'&&<label>Слой<select aria-label="Слой восстановления" value={layer} onChange={e=>{setLayer(e.target.value);invalidate();}}>{document.layers.filter(l=>l.visible).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}{scopeKind==='concept'&&<label>Категория<select aria-label="Категория восстановления" value={concept} onChange={e=>{setConcept(e.target.value);invalidate();}}>{conceptsFor(document).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{scopeKind==='image-group'&&<label>Импорт<select aria-label="Группа восстановления" value={run||runs[0]||''} onChange={e=>{setRun(e.target.value);invalidate();}}>{runs.map((id,i)=><option key={id} value={id}>Импорт {i+1} · {document.entities.filter(e=>e.imageSource?.vectorizationRunId===id).length} объектов</option>)}</select></label>}{scopeKind==='area'&&Object.entries(area).map(([key,value])=><label key={key}>{key}<input aria-label={`Область ${key}`} type="number" step="any" value={value} onChange={e=>{setArea(previous=>({...previous,[key]:e.target.valueAsNumber}));invalidate();}}/></label>)}<button onClick={()=>void analyze()}>Анализировать связи</button></div><small>Только Line / Polyline указанной области. Слабые смысловые подсказки и OCR не устанавливают соединение.</small></fieldset>
 {busy&&<p role="status">Локальный анализ… <button onClick={()=>{job.current?.abort();setBusy(false);}}>Отменить анализ</button></p>}{error&&<p role="alert">{error}</p>}
 {graph&&<><div className="topology-counts" data-testid="topology-counts">Связи: {graph.routes.length} · Узлы: {graph.findings.filter(f=>f.kind==='junction').length} · Пересечения: {graph.findings.filter(f=>f.kind==='crossing').length} · Незавершённые концы: {graph.findings.filter(f=>f.kind==='free').length} · Неоднозначности: {graph.routes.filter(r=>r.classification==='AMBIGUOUS').length+graph.findings.filter(f=>f.kind==='crossing'||f.kind==='gap').length}</div>{picked&&<TopologyMiniPreview graph={graph} picked={picked}/>} {graph.warnings.map(w=><p key={w} role="status">{w}</p>)}<button onClick={()=>setReviews(previous=>{const next={...previous};for(const r of graph.routes)if(r.classification==='STRONG'&&resolvedRoute(basedOn,graph,r,{status:'confirmed'}).entity)next[r.id]={status:'confirmed'};return next;})}>Подтвердить все сильные</button>
 <section><h3>Связи · {graph.routes.length}</h3>{graph.routes.slice(0,100).map(r=>{const review=reviews[r.id]??{status:'unresolved'},result=resolvedRoute(basedOn,graph,r,{...review,status:'confirmed'}),preview:TopologyPreview={points:r.points,ports:[...r.startOptions,...r.endOptions],classification:r.classification,confirmed:review.status==='confirmed'};return <article className={`topology-result${picked===r.id?' active':''}`} data-testid={r.id} key={r.id} onMouseEnter={()=>show(r.id,preview)}><div><button onClick={()=>show(r.id,preview)}>{r.startOptions[0]?.label??'Конец'} → {r.endOptions[0]?.label??'Конец'}</button><strong>{r.classification}</strong><button aria-label={`Fit ${r.id}`} onClick={()=>{show(r.id,preview);onFit(r.points);}}>Fit</button></div><ul>{r.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul>{(['start','end'] as const).map(side=>{const options=side==='start'?r.startOptions:r.endOptions,value=review[side];return <label key={side}>Порт: {side==='start'?'начало':'конец'}<select aria-label={`Порт ${side} ${r.id}`} value={value?portKey(value):options.length===1?portKey(options[0]!.endpoint):''} onChange={e=>{const option=options.find(p=>portKey(p.endpoint)===e.target.value);if(option)patch(r.id,{[side]:option.endpoint,status:'unresolved'});}}><option value="">Выберите порт</option>{options.map(p=><option key={portKey(p.endpoint)} disabled={!p.available} value={portKey(p.endpoint)}>{p.label}{!p.available?' · занят':''}</option>)}</select></label>;})}<p>{result.entity?'Форма сохраняется существующим Connector.':result.reason}</p><div><button disabled={r.classification==='REJECTED'} aria-pressed={review.status==='confirmed'} onClick={()=>patch(r.id,{status:'confirmed'})}>Подтвердить</button><button aria-pressed={review.status==='rejected'} onClick={()=>patch(r.id,{status:'rejected'})}>Отклонить</button><button onClick={()=>patch(r.id,{status:'unresolved'})}>Оставить геометрией</button></div></article>;})}{graph.routes.length>100&&<p>Показаны первые 100 связей. Сузьте область для индивидуальной проверки остальных.</p>}</section>
 {(['junction','crossing','gap','free'] as const).map(kind=><section key={kind}><h3>{{junction:'Узлы',crossing:'Пересечения',gap:'Разрывы',free:'Незавершённые концы'}[kind]} · {graph.findings.filter(f=>f.kind===kind).length}</h3>{graph.findings.filter(f=>f.kind===kind).slice(0,100).map(f=><article className="topology-result" data-testid={`finding-${f.kind}`} key={f.id}><div><button onClick={()=>show(f.id,{points:[f.point],ports:[],classification:f.classification})}>{f.classification}</button><button aria-label={`Fit ${f.id}`} onClick={()=>{show(f.id,{points:[f.point],ports:[],classification:f.classification});onFit([f.point]);}}>Fit</button></div>{f.evidence.map((e,i)=><p key={i}>{e}</p>)}{kind==='crossing'&&f.classification!=='REJECTED'&&<div><button aria-pressed={decisions.crossings?.[f.id]==='connected'} onClick={()=>void analyze({...decisions,crossings:{...decisions.crossings,[f.id]:'connected'}})}>Соединено</button><button aria-pressed={decisions.crossings?.[f.id]==='crossing'} onClick={()=>void analyze({...decisions,crossings:{...decisions.crossings,[f.id]:'crossing'}})}>Просто пересекаются</button></div>}{kind==='junction'&&!f.canonical&&f.degree===3&&<div><button aria-pressed={decisions.junctions?.[f.id]===true} onClick={()=>void analyze({...decisions,junctions:{...decisions.junctions,[f.id]:true}})}>Подтвердить узел</button><button aria-pressed={decisions.junctions?.[f.id]===false} onClick={()=>void analyze({...decisions,junctions:{...decisions.junctions,[f.id]:false}})}>Отклонить узел</button></div>}{kind==='gap'&&<div><button aria-pressed={!!decisions.gaps?.[f.id]} onClick={()=>void analyze({...decisions,gaps:{...decisions.gaps,[f.id]:true}})}>Соединить разрыв</button><button onClick={()=>void analyze({...decisions,gaps:{...decisions.gaps,[f.id]:false}})}>Оставить разрыв</button></div>}</article>)}</section>)}
 <details><summary>Диагностика анализа</summary><pre data-testid="topology-diagnostics">{JSON.stringify(graph.diagnostics,null,2)}</pre></details><p>Apply атомарно заменяет только полные, точные, неразветвлённые пути обычными Connector. Подписи, общие вершины, сложные пути и неподтверждённые решения сохраняются.</p></>}
 </Dialog>;
}
function TopologyMiniPreview({graph,picked}:{graph:TopologyGraph;picked:string}){const route=graph.routes.find(r=>r.id===picked),finding=graph.findings.find(f=>f.id===picked),points=route?.points??(finding?[finding.point]:[]),ports=route?[...route.startOptions,...route.endOptions]:[],b=bounds([...points,...ports.map(p=>p.point)]);if(!b)return null;const pad=Math.max((b.maxX-b.minX)*.1,(b.maxY-b.minY)*.1,.1),w=b.maxX-b.minX+2*pad,h=b.maxY-b.minY+2*pad;return <svg data-testid="topology-mini-preview" aria-label="Выбранный путь и порты" viewBox={`${b.minX-pad} ${-b.maxY-pad} ${w} ${h}`} style={{width:'100%',height:180}}><polyline points={points.map(p=>`${p.x},${-p.y}`).join(' ')} fill="none" stroke="#247dbd" strokeWidth={w/300}/>{ports.map(p=><g key={portKey(p.endpoint)}><circle cx={p.point.x} cy={-p.point.y} r={w/100} fill="#fff" stroke="#16845a" strokeWidth={w/300}/><text x={p.point.x+w/70} y={-p.point.y-w/70} fontSize={w/35}>{p.endpoint.portId}</text></g>)}</svg>;}
