import type { Dispatch } from 'react';
import type { RasterUnderlayEntity } from '../domain/model';
import type { EditorAction } from '../store/editor';
import { assetRegistry } from '../assets/registry';
import { useRasterAsset } from '../assets/useRasterAsset';
export function UnderlayProperties({entity,layerLocked,dispatch}:{entity:RasterUnderlayEntity;layerLocked:boolean;dispatch:Dispatch<EditorAction>}){const asset=useRasterAsset(entity.assetId),disabled=layerLocked||entity.locked;const commit=(patch:Extract<import('../domain/commands').DocumentCommand,{type:'update-underlay'}>['patch'])=>dispatch({type:'execute',command:{type:'update-underlay',entityId:entity.id,patch}});return <div className="property-section" data-testid="underlay-properties"><h3>Подложка</h3><label>Название<input aria-label="Название подложки" key={entity.id} defaultValue={entity.name} disabled={disabled} onBlur={e=>{if(e.target.value.trim()&&e.target.value!==entity.name)dispatch({type:'execute',command:{type:'update-entity',entityId:entity.id,patch:{name:e.target.value}}});}}/></label>
 <label>Непрозрачность · {Math.round(entity.opacity*100)}%<input aria-label="Непрозрачность подложки" type="range" min="0" max="100" value={entity.opacity*100} disabled={disabled} onPointerDown={()=>dispatch({type:'begin-transaction'})} onChange={e=>{dispatch({type:'begin-transaction'});dispatch({type:'transient',command:{type:'update-underlay',entityId:entity.id,patch:{opacity:Number(e.target.value)/100}}});}} onPointerUp={()=>dispatch({type:'commit-transaction'})} onBlur={()=>dispatch({type:'commit-transaction'})} onKeyUp={()=>dispatch({type:'commit-transaction'})}/></label>
 <label>Непрозрачность, %<input aria-label="Непрозрачность, %" type="number" min="0" max="100" value={entity.opacity*100} disabled={disabled} onChange={e=>{if(e.target.value!==''&&Number(e.target.value)>=0&&Number(e.target.value)<=100)commit({opacity:Number(e.target.value)/100});}}/></label>
 {(['x','y','width','height','rotationDeg'] as const).map(key=><label key={key}>{key==='x'?'MODEL X':key==='y'?'MODEL Y':key==='width'?'Ширина, м':key==='height'?'Высота, м':'Поворот, °'}<input aria-label={key==='x'?'Подложка MODEL X':key==='y'?'Подложка MODEL Y':key==='width'?'Ширина подложки':key==='height'?'Высота подложки':'Поворот подложки'} key={`${entity.id}-${key}-${key==='x'||key==='y'?entity.position[key]:entity[key]}`} type="number" step="any" defaultValue={key==='x'||key==='y'?entity.position[key]:entity[key]} disabled={disabled} onBlur={e=>{const value=e.target.valueAsNumber;if(Number.isFinite(value)&&(!['width','height'].includes(key)||value>0))commit(key==='x'||key==='y'?{position:{...entity.position,[key]:value}}:{[key]:value});}}/></label>)}
 <label><input aria-label="Заблокировать подложку" type="checkbox" checked={entity.locked} disabled={layerLocked} onChange={e=>commit({locked:e.target.checked})}/>Заблокирована</label>
 {asset.loaded&&!asset.bitmap&&<p role="status">Подложка недоступна</p>}
 <label className="secondary-action">Перепривязать изображение<input aria-label="Перепривязать изображение" type="file" accept="image/png,image/jpeg,image/webp" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];if(file)void assetRegistry.import(file).then(a=>commit({assetId:a.assetId,assetMetadata:a})).catch(error=>dispatch({type:'report-error',message:String(error)}));e.target.value='';}}/></label>
 <small>JSON не включает файлы подложек. Изображение хранится в этом браузере.</small></div>;}
