// Isolated production browser acceptance: no user browser profile, no saved credential.
import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const url=process.env.PRODUCTION_URL??'http://127.0.0.1:5180/GeoService/',origin=new URL(url).origin;
const real=process.env.PAGES_REAL_AI==='1';
let key='visitor-key-static-test';
if(real){const env=await readFile('.env.local','utf8');key=env.match(/^OPENROUTER_API_KEY\s*=\s*["']?([^\s"']+)/m)?.[1]??'';if(!key)throw Error('Opt-in REAL test needs ignored .env.local OPENROUTER_API_KEY');}
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL??'chrome'}),context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();
page.setDefaultTimeout(30000);const errors=[],missing=[],api=[],external=[],requests=[];
const aiTransportAudit=[];
const report={url,realAi:real,model:process.env.PAGES_AI_MODEL??'qwen/qwen3.5-27b',checks:[]};
const check=(name)=>{report.checks.push(name);console.log('PASS '+name);};
page.on('pageerror',()=>errors.push('pageerror'));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().split(key).join('[REDACTED]'));});page.on('response',r=>{if(real&&new URL(r.url()).hostname==='openrouter.ai')void r.json().then(raw=>console.log(JSON.stringify({openrouterStatus:r.status(),model:raw.model,finish:raw.choices?.[0]?.finish_reason,semantic:JSON.parse((raw.choices?.[0]?.message?.content??'{}').split(key).join('[REDACTED]'))}))).catch(()=>console.log('OpenRouter non-JSON response'));if(r.status()>=400)missing.push({path:new URL(r.url()).pathname,status:r.status()});});
context.on('request',r=>{const u=new URL(r.url());if(u.hostname==='openrouter.ai'&&r.method()==='POST'){const body=r.postDataJSON();aiTransportAudit.push({fields:Object.keys(body).sort(),messageRoles:body.messages?.map(m=>m.role),userMessages:body.messages?.filter(m=>m.role==='user').map(m=>m.content),hasSchema:!!body.response_format,model:body.model});}if(r.url().includes('/api/ai/'))api.push(u.pathname);if(/^https?:/.test(r.url())&&u.origin!==origin&&!u.hostname.endsWith('openrouter.ai'))external.push(u.origin);requests.push(u.pathname);});
page.on('dialog',d=>d.accept());
async function command(name){const b=page.getByRole('button',{name,exact:true,includeHidden:true});const ancestors=await b.evaluate(e=>{const result=[];for(let p=e.parentElement;p;p=p.parentElement)if(p instanceof HTMLDetailsElement&&!p.open)result.unshift(p.querySelector(':scope>summary')?.textContent??'');return result;});for(const text of ancestors)await page.getByText(text,{exact:true}).first().click();await b.click();}
const saved=()=>expect(page.getByTestId('persistence-status')).toHaveText('Сохранено локально');
async function document(){await page.waitForTimeout(80);await saved();return page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('geoservice.autosave',1);r.onerror=()=>reject(Error('IndexedDB unavailable'));r.onsuccess=()=>{const db=r.result,q=db.transaction('documents','readonly').objectStore('documents').get('current');q.onsuccess=()=>{db.close();resolve(q.result.document);};q.onerror=()=>reject(Error('Autosave read failed'));};}));}
async function settings(tab='AI'){await command('Настройки');const d=page.getByRole('dialog',{name:'Настройки',exact:true});await d.getByRole('tab',{name:tab,exact:true}).click();return d;}
async function closeSettings(){await page.getByRole('button',{name:'Готово',exact:true}).click();}
async function canvasClick(x,y){const b=await page.getByTestId('drawing-canvas').boundingBox();await page.mouse.click(b.x+b.width*x,b.y+b.height*y);}
try{
 await page.goto(url);await saved();expect(requests.some(p=>/ocr\/|pdf\.worker|recognition\.worker/.test(p))).toBe(false);check('startup, lazy OCR/PDF');
 await page.getByRole('tablist',{name:'Панели редактора'}).getByRole('tab',{name:'AI',exact:true}).click();await expect(page.locator('.ai-mode')).toHaveText('AI не настроен');await expect(page.getByRole('button',{name:'Generate plan',exact:true})).toBeDisabled();check('friendly no-key AI');
 let d=await settings();const input=page.getByLabel('AI API key',{exact:true});await input.fill(key);if(real&&process.env.PAGES_AI_MODEL){await page.getByLabel('Основная AI модель',{exact:true}).fill(process.env.PAGES_AI_MODEL);await page.getByLabel('Резервная AI модель',{exact:true}).fill('');}
 if(real){await d.getByRole('button',{name:'Проверить подключение',exact:true}).click();await expect(d.getByRole('status')).not.toHaveText('Проверка…',{timeout:120000});await expect(d.getByRole('status')).toHaveText('Соединение проверено.');check('REAL Test connection');}
 else await page.route('https://openrouter.ai/api/v1/chat/completions',r=>r.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({intent:{actions:[{type:'create_boundary_from_named_points',pointNames:['P1','P2','P3','P4']}]},unsupported:false})}}]}}));
 await closeSettings();if(real){await command('Новый документ');await saved();}await page.getByLabel('Запрос',{exact:true}).fill(real?'Нарисуй прямоугольник 2x3 м':'Создай границу по точкам P1, P2, P3 и P4');await page.getByRole('button',{name:'Generate plan',exact:true}).click();await expect(page.getByTestId('ai-plan')).toBeVisible({timeout:120000});await expect(page.getByTestId('ai-plan')).toHaveAttribute('data-status','preview');await expect(page.getByRole('button',{name:'Apply',exact:true})).toBeEnabled();check(real?'REAL structured plan (no backend)':'deterministic browser transport');
 expect(await page.evaluate(k=>Object.values(localStorage).some(v=>v.includes(k)),key)).toBe(false);
 await page.reload();await saved();d=await settings();await expect(input).toHaveValue('');check('Remember OFF reload');
 await input.fill(key);await page.getByLabel('Запомнить ключ на этом устройстве',{exact:true}).check();await closeSettings();await page.reload();await saved();d=await settings();expect(await input.inputValue()===key).toBe(true);check('Remember ON reload');
 await page.getByLabel('Запомнить ключ на этом устройстве',{exact:true}).uncheck();expect(await page.evaluate(()=>localStorage.getItem('geoservice.ai-device-key.v1'))).toBeNull();await input.fill('');await closeSettings();check('disable Remember removes stored key');
 d=await settings('Редактор');await page.getByLabel('Сетка по умолчанию',{exact:true}).uncheck();await closeSettings();await page.reload();await saved();d=await settings('Редактор');await expect(page.getByLabel('Сетка по умолчанию',{exact:true})).not.toBeChecked();await closeSettings();check('Preferences reload');
 await command('Новый документ');await saved();await page.getByRole('tablist',{name:'Панели редактора'}).getByRole('tab',{name:'Свойства',exact:true}).click();
 await command('Инструмент: Точка');await canvasClick(.3,.3);let doc=await document();expect(doc.entities.filter(e=>e.type==='point').length).toBe(1);
 await command('Инструмент: Выбор');const id=doc.entities.find(e=>e.type==='point').id;const box=await page.locator(`[data-entity-id="${id}"] circle[r="14"]`).boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+45,box.y+box.height/2+30,{steps:6});await page.mouse.up();await page.waitForTimeout(600);const moved=await document();expect(moved.vertices).not.toEqual(doc.vertices);
 await command('Отменить');expect((await document()).vertices).toEqual(doc.vertices);await command('Повторить');expect((await document()).vertices).toEqual(moved.vertices);
 await command('Инструмент: Линия');await canvasClick(.2,.55);await canvasClick(.45,.65);doc=await document();expect(doc.entities.some(e=>e.type==='line')).toBe(true);await page.reload();expect((await document()).entities).toEqual(doc.entities);check('Point/Line, select/move, Undo/Redo, IndexedDB autosave/reload');
 await command('DXF');await page.getByLabel('Файл DXF',{exact:true}).setInputFiles('src/tests/fixtures/dxf/layouts.dxf');await page.getByTestId('dxf-report').waitFor();await page.getByRole('button',{name:'Открыть как новый документ',exact:true}).click();await saved();check('synthetic DXF import');
 await command('Новый документ');await saved();await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles('e2e/fixtures/pdf/vector.pdf');await expect(page.getByTestId('pdf-route')).toContainText('Векторный PDF',{timeout:60000});await page.getByLabel('Страница PDF',{exact:true}).selectOption('2');await expect(page.locator('.pdf-candidate-list input:not([type=checkbox])')).toHaveValue('SECOND PAGE');await page.getByRole('button',{name:'Отмена',exact:true}).click();check('native PDF Worker + page selection');
 await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles('e2e/fixtures/pdf/scan.pdf');await expect(page.getByTestId('pdf-route')).toContainText('PDF-скан',{timeout:60000});await page.getByRole('button',{name:'Добавить скан и открыть анализ',exact:true}).click();await page.getByRole('button',{name:'4. Извлечение',exact:true}).click();await page.getByRole('button',{name:'Извлечь геометрию',exact:true}).click();await page.getByRole('button',{name:'Распознать текст и символы',exact:true}).waitFor();await page.getByRole('button',{name:'Отмена',exact:true}).click();check('scan PDF rendering + image geometry Worker');
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=960;c.height=640;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,960,640);ctx.fillStyle='#222';ctx.font='30px Arial';['ГАЗ','ВОДА','ТК-3','H=28.40','V-101','Ø57'].forEach((text,i)=>ctx.fillText(text,70+i%3*280,65+Math.floor(i/3)*100));return c.toDataURL().split(',')[1];});
 await page.getByLabel('Импорт подложки',{exact:true}).setInputFiles({name:'synthetic-labels.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByTestId('underlay-properties').waitFor();await command('Векторизация изображения');await page.getByRole('button',{name:'4. Извлечение',exact:true}).click();await page.getByRole('button',{name:'Извлечь геометрию',exact:true}).click();await page.getByRole('button',{name:'Распознать текст и символы',exact:true}).click();await expect(page.getByRole('button',{name:'Распознать текст и символы',exact:true})).toBeEnabled({timeout:120000});const labels=await page.locator('.recognition-row input:not([type=checkbox])').evaluateAll(es=>es.map(e=>e.value));expect(labels).toContain('ГАЗ');expect(labels).toContain('ВОДА');expect(labels.some(t=>t.includes('V-101'))).toBe(true);await page.getByRole('button',{name:'Отмена',exact:true}).click();check('synthetic image + real RU/EN OCR runtime/core/languages');
 await page.getByLabel('Файл GeoDocument',{exact:true}).setInputFiles('public/examples/process-scheme.json');await saved();await command('Вписать схему в вид');await command('Восстановить связи');await page.getByLabel('Область восстановления',{exact:true}).selectOption('layer');await page.getByLabel('Слой восстановления',{exact:true}).selectOption('buildings');await page.getByRole('button',{name:'Анализировать связи',exact:true}).click();await expect(page.getByTestId('topology-counts')).toContainText('Связи: 4');
 if(process.env.PAGES_SCREENSHOTS==='1'){await mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/topology.png'});}
 await page.getByRole('button',{name:'Подтвердить все сильные',exact:true}).click();await page.getByRole('button',{name:'Применить связи (4)',exact:true}).click();await saved();expect((await document()).entities.filter(e=>e.type==='connector').length).toBe(4);if(process.env.PAGES_SCREENSHOTS==='1')await page.screenshot({path:'docs/screenshots/process.png'});check('topology Worker, Symbol/Connector Apply');
 expect(errors).toEqual([]);expect(missing).toEqual([]);expect(api).toEqual([]);expect(external).toEqual([]);
 Object.assign(report,{aiTransportAudit,pageErrors:errors,missingAssets:missing,backendCalls:api,unexpectedExternal:external,runtimeResources:[...new Set(requests.filter(p=>/worker|ocr\/|\.wasm/.test(p)))],pass:true});
 await writeFile(process.env.PAGES_REPORT??resolve('docs/audit-results/pages-static-smoke.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({url,checks:report.checks,pass:true}));
}catch(error){console.error(JSON.stringify({missing,api,external,errors}));console.error('Pages smoke failed at check '+report.checks.length+': '+String(error).split(key).join('[REDACTED]'));throw Error('Pages smoke failed; credential omitted');}finally{await context.clearCookies();await browser.close();key='';}
