import type { GeoDocument } from '../domain/model';
export const IMAGE_LIMITS={bytes:40*1024*1024,dimension:16384,pixels:70_000_000};
export interface AssetMetadata {assetId:string;mimeType:'image/png'|'image/jpeg'|'image/webp';originalName:string;byteSize:number;widthPx:number;heightPx:number}
export interface RasterAsset extends AssetMetadata {blob:Blob}
export function imageHeader(bytes:Uint8Array):{mimeType:AssetMetadata['mimeType'];width:number;height:number}{const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),ascii=(n:number,l:number)=>String.fromCharCode(...bytes.subarray(n,n+l));let width=0,height=0,mimeType:AssetMetadata['mimeType'];
 if(bytes.length>=24&&ascii(1,3)==='PNG'&&bytes[0]===137&&ascii(12,4)==='IHDR'){mimeType='image/png';width=v.getUint32(16);height=v.getUint32(20);}
 else if(bytes[0]===255&&bytes[1]===216){mimeType='image/jpeg';let i=2;while(i+4<bytes.length){if(bytes[i++]!==255)continue;const m=bytes[i++]!;if(m===217||m===218)break;if(m===0||m===216||m>=208&&m<=215)continue;const size=v.getUint16(i);if(size<2||i+size>bytes.length)break;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m)&&size>=7){height=v.getUint16(i+3);width=v.getUint16(i+5);break;}i+=size;}}
 else if(bytes.length>=30&&ascii(0,4)==='RIFF'&&ascii(8,4)==='WEBP'){mimeType='image/webp';let i=12;while(i+8<=bytes.length){const kind=ascii(i,4),len=v.getUint32(i+4,true),p=i+8;if(p+len>bytes.length)break;if(kind==='VP8X'&&len>=10){if(bytes[p]!&2)throw new Error('Анимированный WebP не поддерживается');width=1+bytes[p+4]!+(bytes[p+5]!<<8)+(bytes[p+6]!<<16);height=1+bytes[p+7]!+(bytes[p+8]!<<8)+(bytes[p+9]!<<16);break;}if(kind==='VP8 '&&len>=10&&bytes[p+3]===157&&bytes[p+4]===1&&bytes[p+5]===42){width=v.getUint16(p+6,true)&16383;height=v.getUint16(p+8,true)&16383;break;}if(kind==='VP8L'&&len>=5&&bytes[p]===47){const bits=v.getUint32(p+1,true);width=(bits&16383)+1;height=((bits>>>14)&16383)+1;break;}i=p+len+(len%2);}}
 else throw new Error('Ожидается PNG, JPEG или WebP');
 if(!width||!height||width>IMAGE_LIMITS.dimension||height>IMAGE_LIMITS.dimension||width*height>IMAGE_LIMITS.pixels)throw new Error('Изображение превышает лимит: 16384 по стороне, 70 млн пикселей');return {mimeType,width,height};
}
const sameDimensions=(w:number,h:number,a:number,b:number)=>w===a&&h===b||w===b&&h===a;
let database:Promise<IDBDatabase>|null=null;
function db(){return database??=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('geoservice-assets',1);r.onupgradeneeded=()=>r.result.createObjectStore('rasters',{keyPath:'assetId'});r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();database=null;};resolve(r.result);};r.onerror=()=>{database=null;reject(new Error('Не удалось открыть хранилище подложек'));};});}
async function request<T>(mode:IDBTransactionMode,operation:(s:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('rasters',mode),r=operation(t.objectStore('rasters'));let result:T;r.onsuccess=()=>{result=r.result;};t.oncomplete=()=>resolve(result);t.onerror=t.onabort=()=>reject(t.error??new Error('Ошибка хранилища изображений'));});}
const decoded=new Map<string,Promise<ImageBitmap|null>>(),users=new Map<string,number>();
export const assetRegistry={
 async import(file:File):Promise<AssetMetadata>{if(!file.size||file.size>IMAGE_LIMITS.bytes)throw new Error('Максимальный размер изображения — 40 MiB');const bytes=new Uint8Array(await file.arrayBuffer()),h=imageHeader(bytes),bitmap=await createImageBitmap(new Blob([bytes],{type:h.mimeType}));if(!sameDimensions(bitmap.width,bitmap.height,h.width,h.height)){bitmap.close();throw new Error('Некорректные размеры изображения');}const asset:RasterAsset={assetId:`asset-${crypto.randomUUID()}`,mimeType:h.mimeType,originalName:file.name.slice(0,1000),byteSize:file.size,widthPx:bitmap.width,heightPx:bitmap.height,blob:new Blob([bytes],{type:h.mimeType})};try{await request('readwrite',s=>s.put(asset));}catch(e){bitmap.close();throw e;}decoded.set(asset.assetId,Promise.resolve(bitmap));const {blob:_,...metadata}=asset;void _;return metadata;},
 retain(id:string){users.set(id,(users.get(id)??0)+1);},
 releaseBitmap(id:string){const count=(users.get(id)??0)-1;if(count>0){users.set(id,count);return;}users.delete(id);const pending=decoded.get(id);decoded.delete(id);void pending?.then(b=>b?.close());},
 get(id:string){return request<RasterAsset|undefined>('readonly',s=>s.get(id));},
 bitmap(id:string){let result=decoded.get(id);if(!result){result=this.get(id).then(async a=>{if(!a||!a.blob?.size||a.blob.size>IMAGE_LIMITS.bytes)return null;const h=imageHeader(new Uint8Array(await a.blob.arrayBuffer()));if(!sameDimensions(h.width,h.height,a.widthPx,a.heightPx)||h.mimeType!==a.mimeType)return null;const bitmap=await createImageBitmap(a.blob);if(bitmap.width!==a.widthPx||bitmap.height!==a.heightPx){bitmap.close();return null;}return bitmap;}).catch(()=>null);decoded.set(id,result);}return result;},
 async remove(id:string){await request('readwrite',s=>s.delete(id));const value=decoded.get(id);decoded.delete(id);(await value)?.close();},
 /** Explicit GC must include current, undo, redo and externally retained documents. Never run on delete. */
 async collect(retained:readonly GeoDocument[]){const refs=new Set(retained.flatMap(d=>d.entities.flatMap(e=>e.type==='raster_underlay'?[e.assetId]:[]))),ids=await request<IDBValidKey[]>('readonly',s=>s.getAllKeys());for(const id of ids)if(!refs.has(String(id)))await this.remove(String(id));},
 release(){for(const promise of decoded.values())void promise.then(b=>b?.close());decoded.clear();}
};
if(typeof window!=='undefined')window.addEventListener('pagehide',event=>{if(!event.persisted)assetRegistry.release();});
