import { ownerBounds } from '../renderer/hybridScene';
import type { GeoDocument } from '../domain/model';
import type { EditorState } from '../store/editor';
import { renderItems } from '../renderer/selectors';
const freezes=new WeakMap<GeoDocument,ReadonlySet<string>>();
export const frozenPresentationLayers=(document:GeoDocument)=>freezes.get(document);
const views=new WeakMap<GeoDocument,WeakMap<object,GeoDocument>>();
export function viewportDocument(document:GeoDocument,viewport:NonNullable<GeoDocument['dxfLayouts']>[number]['viewports'][number]):GeoDocument{let cache=views.get(document);if(!cache){cache=new WeakMap();views.set(document,cache);}const hit=cache.get(viewport);if(hit)return hit;const names=new Set(viewport.frozenSourceLayerNames),frozen=new Set(document.layers.filter(l=>names.has(l.source?.originalLayer??l.name)).map(l=>l.id));const result={...document,layers:document.layers.map(l=>frozen.has(l.id)&&l.visible?{...l,visible:false}:l)};freezes.set(result,frozen);cache.set(viewport,result);return result;}
export function activeLayout(state:Pick<EditorState,'document'|'layoutId'>){return state.document.dxfLayouts?.find(l=>l.id===state.layoutId);}
export function activeDxfViewport(state:Pick<EditorState,'document'|'layoutId'|'dxfViewportId'>){const layout=activeLayout(state);return layout?.viewports.find(v=>v.id===state.dxfViewportId)??layout?.viewports[0];}
export function currentViewEntityIds(state:Pick<EditorState,'document'|'layoutId'|'dxfViewportId'>,document:GeoDocument){const vp=activeDxfViewport(state),view=vp?viewportDocument(document,vp):document;return new Set(renderItems(view).filter(({entity})=>{if(!vp)return true;if(vp.unsupportedReason)return false;const box=ownerBounds(view,entity);if(!box)return false;const a=vp.twist*Math.PI/180,c=Math.cos(a),s=Math.sin(a),points=[{x:box.minX,y:box.minY},{x:box.minX,y:box.maxY},{x:box.maxX,y:box.minY},{x:box.maxX,y:box.maxY}].map(p=>({x:(p.x-vp.modelCenter.x)*c-(p.y-vp.modelCenter.y)*s,y:(p.x-vp.modelCenter.x)*s+(p.y-vp.modelCenter.y)*c})),w=vp.viewHeight*vp.sizePaper.width/vp.sizePaper.height/2,h=vp.viewHeight/2;return Math.min(...points.map(p=>p.x))<=w&&Math.max(...points.map(p=>p.x))>=-w&&Math.min(...points.map(p=>p.y))<=h&&Math.max(...points.map(p=>p.y))>=-h;}).map(i=>i.entity.id));}
export const viewContextKey=(state:EditorState)=>JSON.stringify([state.layoutId,state.dxfViewportId,state.isolation]);
