import { number, value, type RawRecord } from '../dxf/raw';
import type { DxfLayout, DxfViewport } from './types';
import type { VectorPrimitive } from '../vectors/types';
export function entityOwner(r:RawRecord){const end=r.groups.findIndex(g=>g.code===100&&g.value==='AcDbEntity');return (end<0?r.groups:r.groups.slice(0,end)).filter(g=>g.code===330).at(-1)?.value;}
export function importLayouts(records:RawRecord[],sourceId:string,factor:number,paperGeometry:(r:RawRecord)=>VectorPrimitive[]):DxfLayout[]{const layerHandles=new Map(records.filter(r=>r.type==='LAYER').map(r=>[value(r,5),value(r,2)!]));const objects=records.filter(r=>r.type==='LAYOUT'),owners=records.filter(r=>r.type==='BLOCK_RECORD'&&/^\*PAPER_SPACE/i.test(value(r,2)??''));
 return owners.slice(0,100).map(owner=>{const handle=value(owner,5)!,object=objects.find(r=>r.groups.some(g=>g.code===100&&g.value==='AcDbLayout')&&r.groups.filter(g=>g.code===330).at(-1)?.value===handle);const layoutGroups=object?.groups.slice(object.groups.findIndex(g=>g.code===100&&g.value==='AcDbLayout')+1),layoutRecord=object?{...object,groups:layoutGroups!}:undefined;const name=layoutRecord?value(layoutRecord,1):undefined,blockName=value(owner,2)!;
 const members=records.filter(r=>r.type!=='BLOCK'&&r.type!=='ENDBLK'&&(r.section==='BLOCKS'&&r.block===blockName||r.section==='ENTITIES'&&entityOwner(r)===handle));const viewports:DxfViewport[]=members.filter(r=>r.type==='VIEWPORT'&&number(r,69)>1).slice(0,100).flatMap(r=>{const w=number(r,40)*factor,h=number(r,41)*factor,vh=number(r,45)*factor;if(w<=0||h<=0||vh<=0)return [];const flags=number(r,90),twist=number(r,51),a=twist*Math.PI/180,x=number(r,12),y=number(r,22),direction=[number(r,16),number(r,26),number(r,36,1)],clip=flags&65536?{kind:'unsupported' as const,...(value(r,340)?{handle:value(r,340)!}:{})}:{kind:'rectangle' as const};const unsupportedReason=flags&1?'Перспективный viewport не поддерживается':direction[0]!==0||direction[1]!==0||direction[2]!<=0?'Наклонный viewport не поддерживается':clip.kind==='unsupported'?'Непрямоугольное отсечение не поддерживается':flags&131072||value(r,68)==='0'?'Viewport выключен в исходном DXF':undefined;
 return [{id:`${sourceId}-viewport-${value(r,5)??number(r,69)}`,number:number(r,69),centerPaper:{x:number(r,10)*factor,y:number(r,20)*factor},sizePaper:{width:w,height:h},modelCenter:{x:(number(r,17)+x*Math.cos(a)+y*Math.sin(a))*factor,y:(number(r,27)+-x*Math.sin(a)+y*Math.cos(a))*factor},viewHeight:vh,scale:h/vh,twist,frozenSourceLayerNames:r.groups.filter(g=>g.code===331).flatMap(g=>layerHandles.has(g.value)?[layerHandles.get(g.value)!]:[]),clip,...(unsupportedReason?{unsupportedReason}:{})}];});
 let paper:DxfLayout['paper'];if(object){const i=object.groups.findIndex(g=>g.code===100&&g.value==='AcDbPlotSettings'),j=object.groups.findIndex(g=>g.code===100&&g.value==='AcDbLayout'),plot={...object,groups:object.groups.slice(i+1,j)};const width=number(plot,44)*factor,height=number(plot,45)*factor,units=number(plot,72,1);if(i>=0&&width>0&&height>0&&[0,1,2].includes(units))paper={width,height,units:units===0?'inches':units===1?'mm':'pixels'};}
 return {id:`${sourceId}-layout-${handle}`,sourceDocumentId:sourceId,name:name??blockName,nameAvailable:!!name,paperSpaceOwner:handle,...(paper?{paper}:{}),paperPrimitives:members.filter(r=>!['VIEWPORT','VERTEX','SEQEND','ATTRIB'].includes(r.type)).flatMap(r=>{try{return paperGeometry(r);}catch{return [];}}),viewports};});
}
