import { useEffect, useMemo, useRef, type Dispatch } from 'react';
import type { GeoDocument, ImportedGraphicEntity } from '../domain/model';
import type { EditorState, EditorAction } from '../store/editor';
import { editorViewDocument } from '../store/editor';
import { activeLayout, viewportDocument } from './context';
import { bounds, fitToBounds, worldToScreen, panViewport, zoomAt, type ViewSize } from '../geometry';
import { primitiveBounds } from '../vectors/geometry';
import { renderItems } from '../renderer/selectors';
import { canvasEntity } from '../renderer/hybridScene';
import { CanvasStratum } from '../renderer/CanvasStratum';
import { EntityView } from '../renderer/EntityView';
import { SelectionContours } from '../renderer/SelectionContours';
import { RasterUnderlays } from '../renderer/RasterUnderlays';
import { hitOwners } from '../editor/deepSelection';
import type { DxfViewport } from './types';
function ModelViewport({document,vp,paperCamera,size,active,selected,panEnabled,dispatch}:{document:GeoDocument;vp:DxfViewport;paperCamera:GeoDocument['viewport'];size:ViewSize;active:boolean;selected:readonly string[];panEnabled:boolean;dispatch:Dispatch<EditorAction>}){const view=useMemo(()=>viewportDocument(document,vp),[document,vp]),items=useMemo(()=>renderItems(view),[view]);const top=worldToScreen({x:vp.centerPaper.x-vp.sizePaper.width/2,y:vp.centerPaper.y+vp.sizePaper.height/2},paperCamera,size),width=vp.sizePaper.width*paperCamera.pixelsPerUnit,height=vp.sizePaper.height*paperCamera.pixelsPerUnit,visible=top.x+width>0&&top.y+height>0&&top.x<size.width&&top.y<size.height,side=Math.ceil(Math.min(Math.hypot(width,height),Math.hypot(size.width,size.height)+4)),renderX=(Math.max(0,top.x)+Math.min(size.width,top.x+width))/2-top.x,renderY=(Math.max(0,top.y)+Math.min(size.height,top.y+height))/2-top.y,a=vp.twist*Math.PI/180,dx=renderX-width/2,dy=renderY-height/2,pixelsPerUnit=height/vp.viewHeight,inner=useMemo(()=>({width:side,height:side}),[side]),camera=useMemo(()=>({center:{x:vp.modelCenter.x+(dx*Math.cos(a)-dy*Math.sin(a))/pixelsPerUnit,y:vp.modelCenter.y-(dx*Math.sin(a)+dy*Math.cos(a))/pixelsPerUnit},pixelsPerUnit}),[vp,dx,dy,a,pixelsPerUnit]);
 return <g data-testid="layout-viewport" data-viewport-id={vp.id} data-active={active}><svg x={top.x} y={top.y} width={width} height={height} overflow="hidden" onPointerDown={event=>{if(event.button!==0||panEnabled)return;event.stopPropagation();dispatch({type:'dxf-viewport',viewportId:vp.id});if(vp.unsupportedReason)return;const rect=event.currentTarget.getBoundingClientRect(),sx=(event.clientX-rect.left)*width/rect.width-width/2,sy=(event.clientY-rect.top)*height/rect.height-height/2,a=vp.twist*Math.PI/180,x=sx*Math.cos(a)-sy*Math.sin(a),y=sx*Math.sin(a)+sy*Math.cos(a),world={x:vp.modelCenter.x+x/camera.pixelsPerUnit,y:vp.modelCenter.y-y/camera.pixelsPerUnit};dispatch({type:'select',entityId:hitOwners(view,world,7/camera.pixelsPerUnit,camera.pixelsPerUnit)[0]??null,toggle:event.shiftKey});}}>
 {vp.unsupportedReason?<><rect width={width} height={height} fill="#eee"/><text x={8} y={20}>{vp.unsupportedReason}</text></>:visible?<g transform={`translate(${renderX} ${renderY}) rotate(${-vp.twist}) translate(${-side/2} ${-side/2})`}><RasterUnderlays document={view} viewport={camera} size={inner}/><CanvasStratum document={view} items={items.filter(i=>canvasEntity(i.entity))} viewport={camera} size={inner}/>{items.filter(i=>!canvasEntity(i.entity)&&i.entity.type!=='raster_underlay').map(item=><EntityView key={item.entity.id} item={item} document={view} viewport={camera} size={inner} selected={selected.includes(item.entity.id)}/>)}<SelectionContours document={view} items={items.filter(i=>selected.includes(i.entity.id)&&(canvasEntity(i.entity)||['arc','circle','block_instance','imported_graphic'].includes(i.entity.type)))} markerIds={items.filter(i=>canvasEntity(i.entity)).map(i=>i.entity.id)} viewport={camera} size={inner}/></g>:null}
 </svg><rect x={top.x} y={top.y} width={width} height={height} fill="none" stroke={active?'#277ec1':'#aaa'} strokeWidth={active?2:1} pointerEvents="none"/></g>;
}
export function LayoutView({state,dispatch,size,onResize}:{state:EditorState;dispatch:Dispatch<EditorAction>;size:ViewSize;onResize:(size:ViewSize)=>void}){const layout=activeLayout(state)!,ref=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number}|null>(null);const box=useMemo(()=>bounds([...primitiveBounds(state.document,layout.paperPrimitives),...layout.viewports.flatMap(v=>[{x:v.centerPaper.x-v.sizePaper.width/2,y:v.centerPaper.y-v.sizePaper.height/2},{x:v.centerPaper.x+v.sizePaper.width/2,y:v.centerPaper.y+v.sizePaper.height/2}]),...(layout.paper?[{x:0,y:0},{x:layout.paper.width,y:layout.paper.height}]:[])]),[layout,state.document]);const fitted=useMemo(()=>fitToBounds(box,size,50)??{center:{x:0,y:0},pixelsPerUnit:1},[box,size]);const paperCamera=state.layoutViewport??fitted;
 useEffect(()=>{if(!state.layoutViewport)dispatch({type:'layout-camera',viewport:fitted});},[state.layoutViewport,fitted,dispatch]);
 useEffect(()=>{const element=ref.current;if(!element)return;const wheel=(event:WheelEvent)=>{event.preventDefault();const rect=element.getBoundingClientRect(),delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?size.height:1);dispatch({type:'layout-camera',viewport:zoomAt(paperCamera,size,{x:event.clientX-rect.left,y:event.clientY-rect.top},Math.exp(-delta*.001))});};element.addEventListener('wheel',wheel,{passive:false});return()=>element.removeEventListener('wheel',wheel);},[paperCamera,size,dispatch]);
 useEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(([entry])=>{if(entry)onResize({width:entry.contentRect.width,height:entry.contentRect.height});});observer.observe(ref.current);return()=>observer.disconnect();},[onResize]);
 const document=useMemo(()=>editorViewDocument({document:state.document,isolation:state.isolation},state.document,true),[state.document,state.isolation]);
 const paper=useMemo(()=>({...state.document,entities:layout.paperPrimitives.map((primitive,i):ImportedGraphicEntity=>({id:`${layout.id}-paper-${i}`,type:'imported_graphic',name:'Paper Space',layerId:primitive.layerId,position:{x:0,y:0},primitives:[primitive],source:{kind:'dxf',sourceDocumentId:layout.sourceDocumentId,originalLayer:primitive.source?.originalLayer??'0',originalType:primitive.source?.originalType??'PAPER'}}))}),[state.document,layout]);const paperItems=useMemo(()=>renderItems(paper),[paper]);const origin=worldToScreen({x:box?.minX??0,y:box?.maxY??0},paperCamera,size);
 return <div className="canvas-container layout-container" ref={ref}><svg data-testid="layout-canvas" data-zoom={paperCamera.pixelsPerUnit} data-center-x={paperCamera.center.x} data-center-y={paperCamera.center.y} aria-label="Лист DXF" width={size.width} height={size.height} onPointerDown={e=>{if(e.button!==0||state.tool==='pan'){drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(drag.current){const delta={x:e.clientX-drag.current.x,y:e.clientY-drag.current.y};drag.current={x:e.clientX,y:e.clientY};dispatch({type:'layout-camera',viewport:panViewport(paperCamera,delta)});}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><rect width="100%" height="100%" fill="#dce1e5"/><rect x={origin.x} y={origin.y} width={Math.max(1,(box?box.maxX-box.minX:1)*paperCamera.pixelsPerUnit)} height={Math.max(1,(box?box.maxY-box.minY:1)*paperCamera.pixelsPerUnit)} fill="white"/>{layout.viewports.map(vp=><ModelViewport key={vp.id} document={document} vp={vp} paperCamera={paperCamera} size={size} active={state.dxfViewportId===vp.id} selected={state.selectedEntityIds} panEnabled={state.tool==='pan'} dispatch={dispatch}/>)}<CanvasStratum document={paper} items={paperItems} viewport={paperCamera} size={size}/></svg><div className="layout-note">{layout.name} · Paper Space / План{!layout.nameAvailable?' · исходное имя листа недоступно':''}{!layout.paper?' · размер бумаги отсутствует, показаны границы содержимого':''}</div></div>;
}
