import { memo, useEffect, useRef } from 'react';
import type { GeoDocument, RasterUnderlayEntity } from '../domain/model';
import { worldToScreen, type ViewSize } from '../geometry';
import type { RenderCamera } from '../view/projection';
import { underlayCorners } from '../assets/underlay';
import { useRasterAsset } from '../assets/useRasterAsset';
const RasterImage=memo(function RasterImage({entity,viewport,size}:{entity:RasterUnderlayEntity;viewport:RenderCamera;size:ViewSize}){const asset=useRasterAsset(entity.assetId),ref=useRef<HTMLCanvasElement>(null);const corners=underlayCorners(entity).map(p=>worldToScreen({...p,z:0},viewport,size));useEffect(()=>{const canvas=ref.current;if(!canvas||!asset.bitmap)return;const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(size.width*dpr);canvas.height=Math.round(size.height*dpr);const ctx=canvas.getContext('2d');if(!ctx)return;const [a,b,,d]=corners;ctx.setTransform((b!.x-a!.x)/asset.bitmap.width*dpr,(b!.y-a!.y)/asset.bitmap.width*dpr,(d!.x-a!.x)/asset.bitmap.height*dpr,(d!.y-a!.y)/asset.bitmap.height*dpr,a!.x*dpr,a!.y*dpr);ctx.globalAlpha=entity.opacity;ctx.drawImage(asset.bitmap,0,0);},[asset.bitmap,entity,viewport,size,corners]);return <g data-testid="raster-underlay" data-asset-id={entity.assetId} pointerEvents="none">{asset.bitmap?<foreignObject x={0} y={0} width={size.width} height={size.height}><canvas ref={ref} style={{width:size.width,height:size.height,display:'block'}}/></foreignObject>:<g data-testid="missing-raster"><polygon points={corners.map(p=>`${p.x},${p.y}`).join(' ')} fill="#eeeeee80" stroke="#a76e30" strokeDasharray="5 4"/><text x={corners[0]!.x+8} y={corners[0]!.y+18} fill="#a76e30">{asset.loaded?'Подложка недоступна':'Загрузка подложки…'}</text></g>}</g>;});
export function RasterUnderlays({document,viewport,size}:{document:GeoDocument;viewport:RenderCamera;size:ViewSize}){return <g data-testid="raster-background">{[...document.layers].sort((a,b)=>a.order-b.order).filter(l=>l.visible).flatMap(l=>document.entities.filter((e):e is RasterUnderlayEntity=>e.type==='raster_underlay'&&e.layerId===l.id&&e.visible!==false)).map(e=><RasterImage key={e.id+e.assetId} entity={e} viewport={viewport} size={size}/>)}</g>;}
export function UnderlaySelection({entity,viewport,size}:{entity:RasterUnderlayEntity;viewport:RenderCamera;size:ViewSize}){
 const corners=underlayCorners(entity).map(p=>worldToScreen({...p,z:0},viewport,size));
 const editable=!entity.locked&&!viewport.projection;
 return <g data-entity-id={entity.id} data-entity-type="raster_underlay" data-selected="true" data-testid="underlay-selection"><polygon points={corners.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#277ec1" strokeWidth={2} pointerEvents="none"/>{editable&&<>{corners.map((p,i)=><rect key={i} data-underlay-corner={i} x={p.x-5} y={p.y-5} width={10} height={10} fill="white" stroke="#277ec1"/>)}</>}</g>;
}
