import { portKey } from '../connectors/model';
import type { GeoDocument } from '../domain/model';
import { scopedPaths, type SourcePath } from './scope';
import { box, distance, SpatialIndex } from './spatial';
import type { Finding, GraphDecisions, Point, RouteCandidate, Scope, TopologyEdge, TopologyGraph, TopologyNode } from './types';
interface Segment {id:string;source:SourcePath;a:Point;b:Point;av:string;bv:string;cuts:{t:number;point:Point;separate?:string}[]}
const cross=(a:Point,b:Point)=>a.x*b.y-a.y*b.x;
const delta=(a:Point,b:Point)=>({x:a.x-b.x,y:a.y-b.y});
const compatible=(a:SourcePath,b:SourcePath)=>!a.concepts.length||!b.concepts.length||a.concepts.some(c=>b.concepts.includes(c)||b.ancestors.includes(c))||b.concepts.some(c=>a.ancestors.includes(c));
/** Local deterministic geometry only. No provider, fetch, engineering interpretation or mutation. */
export function analyzeTopology(document:GeoDocument,scope:Scope,decisions:GraphDecisions={}):TopologyGraph {
 const start=performance.now(),{paths,suppressed,ports,scale,pixel,stroke}=scopedPaths(document,scope);
 if(!paths.length)throw new Error('Не найдено линий, подходящих для восстановления связей. Выберите Line / Polyline в MODEL.');
 const maxCoordinate=Math.max(1,...paths.flatMap(p=>p.points.map(q=>Math.max(Math.abs(q.x),Math.abs(q.y)))));
 const exact=Math.max(scale*1e-7,maxCoordinate*Number.EPSILON*16),port=Math.max(exact,Math.min(scale*.08,Math.max(scale*.005,pixel*6,stroke*1.5))),gap=Math.max(port,Math.min(scale*.1,Math.max(scale*.035,pixel*3,stroke*2))),angleDeg=8;
 const segments:Segment[]=paths.flatMap(path=>path.points.slice(1).flatMap((b,i)=>{const a=path.points[i]!;return distance(a,b)>exact?[{id:`${path.id}:${i}`,source:path,a,b,av:path.vertexIds[i]!,bv:path.vertexIds[i+1]!,cuts:[{t:0,point:a},{t:1,point:b}]}]:[];}));
 if(segments.length>6000)throw new Error('Слишком много сегментов. Сузьте область анализа до 6000 сегментов.');
 const sourceById=new Map(paths.map(p=>[p.id,p]));
 const index=new SpatialIndex(segments.map((s,i)=>({bounds:box(s.a,s.b,exact),value:i}))),findings:Finding[]=[];
 let pairChecks=0;let graphTime=performance.now()-start;const intersectionStart=performance.now();
 for(const [i,a] of segments.entries())for(const j of index.query(box(a.a,a.b,exact))){if(j<=i)continue;if(findings.length>2000)throw new Error('Слишком много неоднозначных пересечений. Уменьшите область анализа.');if(++pairChecks>100000)throw new Error('Слишком плотная область: более 100 000 соседних пар. Уменьшите область анализа.');const b=segments[j]!,r=delta(a.b,a.a),s=delta(b.b,b.a),den=cross(r,s);
 if(Math.abs(den)<=exact*Math.max(distance(a.a,a.b),distance(b.a,b.b))){const l=distance(a.a,a.b),collinear=Math.abs(cross(delta(b.a,a.a),r))/l<=exact,project=(p:Point)=>((p.x-a.a.x)*r.x+(p.y-a.a.y)*r.y)/(l*l),p0=project(b.a),p1=project(b.b);if(collinear&&Math.min(1,Math.max(p0,p1))-Math.max(0,Math.min(p0,p1))>exact/l)findings.push({id:`overlap:${a.id}:${b.id}`,kind:'crossing',point:a.a,classification:'REJECTED',sourceGeometryIds:[a.source.id,b.source.id],evidence:['Наложенные участки пути. Геометрия сохранена; устраните дубли или сузьте выбор.']});continue;}
 const q=delta(b.a,a.a),t=cross(q,s)/den,u=cross(q,r)/den,at=exact/distance(a.a,a.b),bt=exact/distance(b.a,b.b);
 if(t<-at||t>1+at||u<-bt||u>1+bt)continue;
 const point={x:a.a.x+r.x*Math.max(0,Math.min(1,t)),y:a.a.y+r.y*Math.max(0,Math.min(1,t))},aInterior=t>at&&t<1-at,bInterior=u>bt&&u<1-bt;
 if(!compatible(a.source,b.source)){findings.push({id:`incompatible:${a.id}:${b.id}`,kind:'crossing',point,classification:'REJECTED',sourceGeometryIds:[a.source.id,b.source.id],evidence:['Явные категории геометрии различаются. Соединение не предлагается.']});continue;}
 const id=`crossing:${a.id}:${b.id}`,isX=aInterior&&bInterior;
 if(isX){const connected=decisions.crossings?.[id]==='connected';findings.push({id,kind:'crossing',point,classification:'AMBIGUOUS',reviewed:!!decisions.crossings?.[id],sourceGeometryIds:[a.source.id,b.source.id],evidence:[connected?'Пользователь подтвердил геометрический узел.':'Два пути пересекаются. Это не доказывает соединение.']});
 a.cuts.push({t,point,...(connected?{}:{separate:a.id})});b.cuts.push({t:u,point,...(connected?{}:{separate:b.id})});
 }else {a.cuts.push({t:Math.max(0,Math.min(1,t)),point});b.cuts.push({t:Math.max(0,Math.min(1,u)),point});}
 }
 if(findings.length>2000)throw new Error('Слишком много неоднозначных пересечений. Уменьшите область анализа.');
 const intersectionTime=performance.now()-intersectionStart,nodeBuildStart=performance.now(),nodes:TopologyNode[]=[],edges:TopologyEdge[]=[],adj=new Map<string,TopologyEdge[]>(),nodeMap=new Map<string,TopologyNode>(),cellMap=new Map<string,TopologyNode[]>(),separateMap=new Map<string,TopologyNode>(),nodeSources=new Map<string,SourcePath[]>();
 const nodeFor=(point:Point,source:SourcePath,separate?:string)=>{const x=Math.floor(point.x/exact),y=Math.floor(point.y/exact),separateKey=`${separate}:${x}:${y}`;if(separate&&separateMap.has(separateKey))return separateMap.get(separateKey)!;if(!separate)for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++)for(const n of cellMap.get(`${x+dx}:${y+dy}`)??[])if(distance(n.point,point)<=exact&&(nodeSources.get(n.id)??[]).every(p=>compatible(p,source))){nodeSources.get(n.id)!.push(source);return n;}
 const n:TopologyNode={id:`node-${nodes.length}`,point,kind:'line_endpoint',ports:[],degree:0};nodes.push(n);nodeMap.set(n.id,n);nodeSources.set(n.id,[source]);if(separate)separateMap.set(separateKey,n);else{const key=`${x}:${y}`,ns=cellMap.get(key)??[];ns.push(n);cellMap.set(key,ns);}return n;};
 const addEdge=(edge:TopologyEdge)=>{if(edge.from===edge.to)return;edges.push(edge);for(const id of [edge.from,edge.to]){const list=adj.get(id)??[];list.push(edge);adj.set(id,list);nodeMap.get(id)!.degree++;}};
 for(const segment of segments){const cuts=segment.cuts.sort((a,b)=>a.t-b.t).filter((c,i,list)=>i===0||distance(c.point,list[i-1]!.point)>exact);for(let i=1;i<cuts.length;i++){const a=cuts[i-1]!,b=cuts[i]!;addEdge({id:`edge-${edges.length}`,from:nodeFor(a.point,segment.source,a.separate).id,to:nodeFor(b.point,segment.source,b.separate).id,kind:'traced_route',sourceGeometryIds:[segment.source.id]});}}
 // Four coincident but unshared polyline vertices are still an ambiguous X.
 for(const node of [...nodes])if(node.degree>=3){const incident=adj.get(node.id)!,sourceIds=[...new Set(incident.flatMap(e=>e.sourceGeometryIds))],shared=sourceIds.flatMap(id=>sourceById.get(id)!.vertexIds.filter(id=>distance(document.vertices[id]!,node.point)<=exact)),canonical=new Set(shared).size<shared.length;
 if(node.degree===4&&!canonical&&!findings.some(f=>f.kind==='crossing'&&distance(f.point,node.point)<=exact)){
 const id=`vertex-crossing:${sourceIds.sort().join(':')}:${node.point.x}:${node.point.y}`,connected=decisions.crossings?.[id]==='connected';findings.push({id,kind:'crossing',point:node.point,classification:'AMBIGUOUS',reviewed:!!decisions.crossings?.[id],sourceGeometryIds:sourceIds,evidence:['Четыре сегмента встречаются без общей канонической вершины. Требуется выбор соединения.']});
 if(!connected){const vector=(edge:TopologyEdge)=>delta(nodeMap.get(edge.from===node.id?edge.to:edge.from)!.point,node.point),v=vector(incident[0]!),opposite=incident.slice(1).map(e=>({e,d:(v.x*vector(e).x+v.y*vector(e).y)/(Math.hypot(v.x,v.y)*Math.hypot(vector(e).x,vector(e).y)||1)})).sort((a,b)=>a.d-b.d)[0]!;
 const first=[incident[0]!,opposite.e],second=incident.filter(e=>!first.includes(e)),clone:TopologyNode={...node,id:`node-${nodes.length}`,degree:2,ports:[]};nodes.push(clone);nodeMap.set(clone.id,clone);adj.set(node.id,first);node.degree=2;adj.set(clone.id,second);for(const edge of second){if(edge.from===node.id)edge.from=clone.id;else edge.to=clone.id;}continue;
 }}
 const junctionId=`junction:${sourceIds.sort().join('|')}:${node.point.x}:${node.point.y}`;
 if(node.degree===3&&!canonical&&decisions.junctions?.[junctionId]===false){const vector=(edge:TopologyEdge)=>delta(nodeMap.get(edge.from===node.id?edge.to:edge.from)!.point,node.point),pairs=incident.flatMap((a,i)=>incident.slice(i+1).map(b=>({a,b,d:(vector(a).x*vector(b).x+vector(a).y*vector(b).y)/(Math.hypot(vector(a).x,vector(a).y)*Math.hypot(vector(b).x,vector(b).y)||1)}))).sort((a,b)=>a.d-b.d),straight=pairs[0]!;
 if(straight.d<=-Math.cos(angleDeg*Math.PI/180)){const branch=incident.find(e=>e!==straight.a&&e!==straight.b)!,clone:TopologyNode={...node,id:`node-${nodes.length}`,degree:1,ports:[]};nodes.push(clone);nodeMap.set(clone.id,clone);node.degree=2;adj.set(node.id,[straight.a,straight.b]);adj.set(clone.id,[branch]);if(branch.from===node.id)branch.from=clone.id;else branch.to=clone.id;findings.push({id:junctionId,kind:'junction',point:node.point,classification:'REJECTED',degree:3,reviewed:true,sourceGeometryIds:sourceIds,evidence:['Узел отклонён. Прямой путь и ветвь анализируются отдельно; ветвь остаётся геометрией.']});continue;}}
 node.kind='geometric_junction';findings.push({id:junctionId,kind:'junction',point:node.point,degree:node.degree,canonical,reviewed:canonical||decisions.junctions?.[junctionId]===true,classification:canonical||decisions.junctions?.[junctionId]===true?'CONFIRMED':'STRONG',sourceGeometryIds:sourceIds,evidence:[`${node.degree===3?'Три':node.degree} сегмента сходятся в одной точке.`, 'Геометрический узел; физический тройник не определяется.']});}
 graphTime+=performance.now()-nodeBuildStart;const portStart=performance.now(),portIndex=new SpatialIndex(ports.map(p=>({bounds:box(p.point,undefined,port),value:p})));
 for(const node of nodes)if(node.degree===1){const neighbor=adj.get(node.id)![0]!,other=nodeMap.get(neighbor.from===node.id?neighbor.to:neighbor.from)!,v=delta(other.point,node.point);node.ports=portIndex.query(box(node.point)).filter(p=>distance(p.point,node.point)<=port).map(p=>{const angle=p.directionDeg*Math.PI/180,alignment=(v.x*Math.cos(angle)+v.y*Math.sin(angle))/(Math.hypot(v.x,v.y)||1);return {...p,distance:distance(p.point,node.point),...(alignment<Math.cos(Math.PI/4)&&!p.reason?{reason:'Линия подходит с другой стороны направления порта; требуется проверка.'}:{})};}).sort((a,b)=>a.distance-b.distance);if(node.ports.length)node.kind='symbol_port';}

 const portUse=new Map<string,number>();for(const n of nodes)for(const p of n.ports)portUse.set(portKey(p.endpoint),(portUse.get(portKey(p.endpoint))??0)+1);for(const n of nodes)n.ports=n.ports.map(p=>(portUse.get(portKey(p.endpoint))??0)>1?{...p,reason:p.reason??'Несколько независимых концов претендуют на этот порт; требуется выбор связи.'}:p);
 const endpoints=nodes.filter(n=>n.degree===1&&!n.ports.length),endpointIndex=new SpatialIndex(endpoints.map(n=>({bounds:box(n.point,undefined,gap),value:n}))),pathById=new Map(paths.map(p=>[p.id,p]));
 for(const a of endpoints)for(const b of endpointIndex.query(box(a.point))){if(a.id>=b.id)continue;const d=distance(a.point,b.point);if(d<=exact||d>gap)continue;const ae=adj.get(a.id)![0]!,be=adj.get(b.id)![0]!;if(ae===be)continue;
 const an=nodeMap.get(ae.from===a.id?ae.to:ae.from)!,bn=nodeMap.get(be.from===b.id?be.to:be.from)!,av=delta(a.point,an.point),bv=delta(bn.point,b.point),bridge=delta(b.point,a.point),norm=(v:Point,w:Point)=>(v.x*w.x+v.y*w.y)/(Math.hypot(v.x,v.y)*Math.hypot(w.x,w.y)||1),angle=Math.acos(Math.max(-1,Math.min(1,Math.min(norm(av,bridge),norm(bridge,bv)))))*180/Math.PI;
 if(angle>angleDeg||!compatible(pathById.get(ae.sourceGeometryIds[0]!)!,pathById.get(be.sourceGeometryIds[0]!)!))continue;
 const ends=[`${ae.sourceGeometryIds.join('|')}:${a.point.x}:${a.point.y}`,`${be.sourceGeometryIds.join('|')}:${b.point.x}:${b.point.y}`].sort();const id=`gap:${ends.join('→')}`;findings.push({id,kind:'gap',point:{x:(a.point.x+b.point.x)/2,y:(a.point.y+b.point.y)/2},classification:'AMBIGUOUS',distance:d,angleDeg:angle,sourceGeometryIds:[...ae.sourceGeometryIds,...be.sourceGeometryIds],evidence:[`Разрыв ${d.toPrecision(3)} м; угол ${angle.toFixed(1)}°.`, 'Продолжения коллинеарны, категории совместимы. Требуется явное подтверждение.']});
 if(decisions.gaps?.[id])addEdge({id:`edge-${edges.length}`,from:a.id,to:b.id,kind:'candidate_connection',sourceGeometryIds:[],gapId:id});
 }
 for(const n of nodes)if(n.degree===1&&!n.ports.length){n.kind='free_endpoint';const near=portIndex.query(box(n.point,undefined,gap*3)).map(p=>({...p,d:distance(p.point,n.point)})).filter(p=>p.d<=gap*3).sort((a,b)=>a.d-b.d)[0];findings.push({id:`free:${n.id}`,kind:'free',point:n.point,classification:'AMBIGUOUS',sourceGeometryIds:(adj.get(n.id)??[]).flatMap(e=>e.sourceGeometryIds),evidence:[near?`Возможно продолжение к ${near.label}, расстояние ${near.d.toPrecision(3)} м. За пределами допуска; не подключено.`:'Конец пути без порта или продолжения. Это может быть намеренно.']});}
 const portTime=performance.now()-portStart,tracingStart=performance.now(),routes:RouteCandidate[]=[],seen=new Set<string>();let traceSteps=0;
 for(const source of nodes.filter(n=>n.ports.length)){
 const stack=[{node:source,nodeIds:[source.id],edgeIds:[] as string[],gapIds:[] as string[],sourceIds:[] as string[],branched:false}];
 while(stack.length){const route=stack.pop()!;if(++traceSteps>100000)throw new Error('Слишком много вариантов маршрута. Сузьте область или оставьте пересечения неподключёнными.');if(route.node!==source&&route.node.ports.length){const reverse=[...route.edgeIds].reverse().join('|'),key=route.edgeIds.join('|'),identity=key<reverse?key:reverse;if(seen.has(identity))continue;seen.add(identity);const startOptions=source.ports,endOptions=route.node.ports,availableA=startOptions.filter(p=>p.available),availableB=endOptions.filter(p=>p.available),compatiblePairs=availableA.flatMap(a=>availableB.filter(b=>a.kind===b.kind&&a.endpoint.symbolEntityId!==b.endpoint.symbolEntityId).map(b=>[a,b]));const classification=!compatiblePairs.length?'REJECTED':startOptions.length===1&&endOptions.length===1&&!route.branched&&!route.gapIds.length&&!startOptions[0]!.reason&&!endOptions[0]!.reason&&!findings.some(f=>f.kind==='crossing'&&!f.reviewed&&f.sourceGeometryIds.some(id=>route.sourceIds.includes(id)))?'STRONG':'AMBIGUOUS';routes.push({id:`route-${routes.length}`,nodeIds:route.nodeIds,edgeIds:route.edgeIds,points:route.nodeIds.map(id=>nodeMap.get(id)!.point),sourceGeometryIds:[...new Set(route.sourceIds)],startOptions,endOptions,gapIds:route.gapIds,branched:route.branched,classification,evidence:[`Путь прослежен через ${route.edgeIds.length} сегментов.`,...(compatiblePairs.length?['Есть совместимые порты существующей библиотеки.']:['Нет совместимой свободной пары портов.']),...(route.branched?['Путь проходит через ветвление. Геометрия будет сохранена.']:[]),...startOptions.map(p=>`${p.label}: ${p.distance.toPrecision(3)} м${p.reason?` · ${p.reason}`:''}`),...endOptions.map(p=>`${p.label}: ${p.distance.toPrecision(3)} м${p.reason?` · ${p.reason}`:''}`)]});if(routes.length>1000)throw new Error('Более 1000 маршрутов. Уменьшите область анализа.');continue;}
 if(route.edgeIds.length>=500)continue;
 for(const edge of adj.get(route.node.id)??[]){if(route.edgeIds.includes(edge.id))continue;const next=nodeMap.get(edge.from===route.node.id?edge.to:edge.from)!;if(route.nodeIds.includes(next.id))continue;stack.push({node:next,nodeIds:[...route.nodeIds,next.id],edgeIds:[...route.edgeIds,edge.id],gapIds:[...route.gapIds,...(edge.gapId?[edge.gapId]:[])],sourceIds:[...route.sourceIds,...edge.sourceGeometryIds],branched:route.branched||route.node.degree>2||next.degree>2});}
 }}
 const tracingTime=performance.now()-tracingStart,previewStart=performance.now(),warnings=[...(!document.entities.some(e=>e.type==='symbol')?['Нет подтверждённых символов. Доступны только геометрические узлы и свободные концы.']:!ports.length?['У подтверждённых символов нет видимых портов.']:[]),...(suppressed?[`Исключены внутренние штрихи подтверждённых символов: ${suppressed}.`]:[]),...(!routes.length?['Пути между двумя известными портами не найдены. Геометрия остаётся обычной.']:[])];
 return {nodes,edges,routes,findings,warnings,diagnostics:{geometryCount:paths.length,segments:segments.length,suppressed,pairChecks,tolerances:{exact,port,gap,angleDeg},timings:{graph:graphTime,intersections:intersectionTime,ports:portTime,tracing:tracingTime,preview:performance.now()-previewStart,total:performance.now()-start}}};
}
